### ISSUE TITLE
Screenmarkers can create a null marker

### ISSUE THREAD

**Issue by abextm** [runelite/runelite#10317]
<details><summary> stack traces </summary>

```
java.lang.NullPointerException: null
	at net.runelite.client.plugins.screenmarkers.ScreenMarkerOverlay.getName(ScreenMarkerOverlay.java:55)
	at net.runelite.client.ui.overlay.OverlayManager.saveOverlayPosition(OverlayManager.java:345)
	at net.runelite.client.ui.overlay.OverlayManager.saveOverlay(OverlayManager.java:247)
	at net.runelite.client.plugins.screenmarkers.ScreenMarkerPlugin.finishCreation(ScreenMarkerPlugin.java:194)
	at net.runelite.client.plugins.screenmarkers.ui.ScreenMarkerCreationPanel$1.mousePressed(ScreenMarkerCreationPanel.java:88)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
	at java.awt.Component.processMouseEvent(Component.java:6536)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4532)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

```
java.lang.NullPointerException: null
	at net.runelite.client.plugins.screenmarkers.ui.ScreenMarkerPanel.<init>(ScreenMarkerPanel.java:151)
	at net.runelite.client.plugins.screenmarkers.ui.ScreenMarkerPluginPanel.rebuild(ScreenMarkerPluginPanel.java:164)
	at net.runelite.client.plugins.screenmarkers.ScreenMarkerPlugin.finishCreation(ScreenMarkerPlugin.java:196)
	at net.runelite.client.plugins.screenmarkers.ui.ScreenMarkerCreationPanel$1.mousePressed(ScreenMarkerCreationPanel.java:88)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
	at java.awt.Component.processMouseEvent(Component.java:6536)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4532)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

```
2019-11-24 05:19:41 [RuneLite] WARN  n.r.client.plugins.PluginManager - Unable to start plugin ScreenMarkerPlugin
net.runelite.client.plugins.PluginInstantiationException: java.lang.reflect.InvocationTargetException
	at net.runelite.client.plugins.PluginManager.startPlugin(PluginManager.java:350)
	at net.runelite.client.plugins.PluginManager.startCorePlugins(PluginManager.java:209)
	at net.runelite.client.RuneLite.start(RuneLite.java:340)
	at net.runelite.client.RuneLite.main(RuneLite.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.runelite.launcher.ReflectionLauncher$1.run(ReflectionLauncher.java:64)
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1349)
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1324)
	at javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1353)
	at net.runelite.client.plugins.PluginManager.startPlugin(PluginManager.java:322)
	... 8 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at net.runelite.client.plugins.PluginManager.lambda$startPlugin$3(PluginManager.java:330)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException: null
	at net.runelite.client.plugins.screenmarkers.ScreenMarkerOverlay.getName(ScreenMarkerOverlay.java:55)
	at net.runelite.client.ui.overlay.OverlayManager.loadOverlayLocation(OverlayManager.java:363)
	at net.runelite.client.ui.overlay.OverlayManager.loadOverlay(OverlayManager.java:299)
	at net.runelite.client.ui.overlay.OverlayManager.add(OverlayManager.java:173)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at net.runelite.client.plugins.screenmarkers.ScreenMarkerPlugin.startUp(ScreenMarkerPlugin.java:109)
	at net.runelite.client.plugins.PluginManager.lambda$startPlugin$3(PluginManager.java:326)
	... 14 common frames omitted
```

```
2019-11-24 05:19:41 [RuneLite] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at net.runelite.client.plugins.screenmarkers.ScreenMarkerOverlay.getName(ScreenMarkerOverlay.java:55)
	at net.runelite.client.ui.overlay.OverlayManager.loadOverlayLocation(OverlayManager.java:363)
	at net.runelite.client.ui.overlay.OverlayManager.loadOverlay(OverlayManager.java:299)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at net.runelite.client.ui.overlay.OverlayManager.onPluginChanged(OverlayManager.java:118)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:74)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.plugins.PluginManager.startPlugin(PluginManager.java:346)
	at net.runelite.client.plugins.PluginManager.startCorePlugins(PluginManager.java:209)
	at net.runelite.client.RuneLite.start(RuneLite.java:340)
	at net.runelite.client.RuneLite.main(RuneLite.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.runelite.launcher.ReflectionLauncher$1.run(ReflectionLauncher.java:64)
```
</details>

The actual config looks like
`screenmarkers.markers=[{"id"\:1.57457268275E12,"name"\:"Marker 1","borderThickness"\:3.0,"color"\:{"value"\:-1.4221312E7,"falpha"\:0.0},"fill"\:{"value"\:65280.0,"falpha"\:0.0},"visible"\:true},null]`

I guess what is happening is there are 2 inflight mouse events that fire `finishCreation` at the same time?

This should probably get
 - a null check in `finishCreation`
 - a null check in `loadConfig`'s stream

**Comment by Adam-** [comment]
This also breaks plugin startup
```
2020-01-19 20:51:10 [RuneLite] WARN  n.r.client.plugins.PluginManager - Unable to start plugin ScreenMarkerPlugin
net.runelite.client.plugins.PluginInstantiationException: java.lang.reflect.InvocationTargetException
    at net.runelite.client.plugins.PluginManager.startPlugin(PluginManager.java:362)
    at net.runelite.client.plugins.PluginManager.startPlugins(PluginManager.java:212)
    at net.runelite.client.RuneLite.start(RuneLite.java:347)
    at net.runelite.client.RuneLite.main(RuneLite.java:251)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.runelite.launcher.ReflectionLauncher$1.run(ReflectionLauncher.java:64)
Caused by: java.lang.reflect.InvocationTargetException: null
    at java.awt.EventQueue.invokeAndWait(EventQueue.java:1349)
    at java.awt.EventQueue.invokeAndWait(EventQueue.java:1324)
    at javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1353)
    at net.runelite.client.plugins.PluginManager.startPlugin(PluginManager.java:334)
    ... 8 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
    at net.runelite.client.plugins.PluginManager.lambda$startPlugin$4(PluginManager.java:342)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException: null
    at net.runelite.client.plugins.screenmarkers.ScreenMarkerOverlay.getName(ScreenMarkerOverlay.java:55)
    at net.runelite.client.ui.overlay.OverlayManager.loadOverlayLocation(OverlayManager.java:363)
    at net.runelite.client.ui.overlay.OverlayManager.loadOverlay(OverlayManager.java:299)
    at net.runelite.client.ui.overlay.OverlayManager.add(OverlayManager.java:173)
    at java.util.ArrayList.forEach(ArrayList.java:1257)
    at net.runelite.client.plugins.screenmarkers.ScreenMarkerPlugin.startUp(ScreenMarkerPlugin.java:109)
    at net.runelite.client.plugins.PluginManager.lambda$startPlugin$4(PluginManager.java:338)
    ... 14 common frames omitted
```

**Comment by Felanbird** [comment]
issue prevention was added in 5216b03090595a568debc735ae1f58ecc1491541
