### ISSUE TITLE
Cache module issues

### ISSUE THREAD

**Issue by aurimasniekis** [runelite/runelite#10329]
I am trying to run `net.runelite.cache.Cache` tool to dump stuff from caches but I am running into exceptions.

First I had issues that index 16 in reference table which is empty:

![image](https://user-images.githubusercontent.com/15481/69642217-599fcc80-1059-11ea-883c-afa2f21f8a1f.png)
which caused `net.runelite.cache.fs.jagex.DiskStorage.readIndex` to fail read index. I added some logic to ignore broken index but then I ran into archives not being able to readIndex too so I think something has changed with OSRS caches

```sh
$ java -Dorg.slf4j.simpleLogger.defaultLogLevel=trace -classpath cache-1.5.42-SNAPSHOT-jar-with-dependencies.jar net.runelite.cache.Cache -cache ~/jagexcache/oldschool/LIVE
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 0
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 1
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 2
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 3
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 4
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 5
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 6
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 7
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 8
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 9
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 10
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 11
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 12
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 13
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 14
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 15
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 16
[main] DEBUG net.runelite.cache.fs.jagex.IndexFile - invalid length or sector 0/0
Entry is null for indexId: 16
Exception in thread "main" java.lang.NullPointerException
	at net.runelite.cache.fs.jagex.DiskStorage.readIndex(DiskStorage.java:120)
	at net.runelite.cache.fs.jagex.DiskStorage.loadIndex(DiskStorage.java:128)
	at net.runelite.cache.fs.jagex.DiskStorage.load(DiskStorage.java:108)
	at net.runelite.cache.fs.Store.load(Store.java:121)
	at net.runelite.cache.Cache.loadStore(Cache.java:127)
	at net.runelite.cache.Cache.main(Cache.java:64)
```

```sh
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 0
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 1
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 2
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 3
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 4
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 5
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 6
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 7
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 8
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 9
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 10
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 11
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 12
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 13
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 14
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 15
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 16
[main] DEBUG net.runelite.cache.fs.jagex.IndexFile - invalid length or sector 0/0 for index 16
Entry is null for indexId: 16
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 17
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 18
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 19
[main] TRACE net.runelite.cache.fs.jagex.DiskStorage - Loading index 20
Dumping sprites to /home/Projects/OSRS/dump
[main] DEBUG net.runelite.cache.fs.jagex.IndexFile - invalid length or sector 16711680/0 for index 0
[main] DEBUG net.runelite.cache.fs.jagex.DiskStorage - can't read archive 0 from index 8
Exception in thread "main" java.lang.NullPointerException
	at java.base/java.nio.ByteBuffer.wrap(ByteBuffer.java:422)
	at net.runelite.cache.io.InputStream.<init>(InputStream.java:46)
	at net.runelite.cache.definitions.loaders.SpriteLoader.load(SpriteLoader.java:38)
	at net.runelite.cache.SpriteManager.load(SpriteManager.java:63)
	at net.runelite.cache.Cache.dumpSprites(Cache.java:158)
	at net.runelite.cache.Cache.main(Cache.java:116)
```

**Comment by Adam-** [comment]
Are you sure your cache isn't broken? We use the cache lib fairly often without issues.

**Comment by aurimasniekis** [comment]
I deleted ran several different clients even original one and same problem. Is there a way to download cache without a game?

**Comment by tghartland** [comment]
@aurimasniekis did you fix this?
