### ISSUE TITLE
A JNI Error has occured. Won't Open.

### ISSUE THREAD

**Issue by killall4u** [runelite/runelite#10399]
**Describe the bug**
The jar file won't open on my computer. When I try to open it, It prompts me with a message saying: "Error: A JNI error has occurred, please check your installation and try again". Then when I press OK, it prompts me again with "A java Exception has occurred.".

**To Reproduce**
Try to open jar file with 32-bit java installed.

**Expected behavior**
The launcher to start up and open the client.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Latest Runelite jar file.

**Additional context**
When launching it from cmd to get the console reading:

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/runelite/launcher/Launcher has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

I believe this jar was compiled improperly for the current java version?? I am no expert though.

**Comment by 00-matt** [comment]
RuneLite launcher requires Java 11. You have Java 8 installed and need to update.

**Comment by sangoku116** [comment]
I am getting the same issue on Linux. I have both java 8 and 13 installed. 

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/runelite/launcher/Launcher has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```

**Comment by 00-matt** [comment]
@sangoku116 Which version of Java is your system default? (Hint: run `java -version` on the command line)

On Debian-based systems, you can change the default Java version with `sudo update-alternatives --config java`

**Comment by sangoku116** [comment]
I fixed this issue by looking at which java version were installed with:
```
archlinux-java status
```
and changed the default version with: 
```
sudo archlinux-java set java-13-openjdk
```

**Comment by Nightfirecat** [comment]
The comments have already described the issue--that is, you're trying to open the launcher with Java 8, [when it now requires Java 11 since the Launcher 2.0 release](https://runelite.net/blog/show/2019-08-16-Launcher-Release-2.0.0).
