### ISSUE TITLE
Fatal error starting Runelite

### ISSUE THREAD

**Issue by Vitazu** [runelite/runelite#10454]
This is the log of the problem:
2019-12-16 16:56:11 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2019-12-16 16:56:11 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Client is outdated!
2019-12-16 16:56:12 [RuneLite] WARN  net.runelite.client.RuneLite - Failure during startup
java.lang.NullPointerException: null
	at com.google.inject.internal.InjectorImpl.injectMembers(InjectorImpl.java:986)
	at net.runelite.client.RuneLite.start(RuneLite.java:274)
	at net.runelite.client.RuneLite.main(RuneLite.java:246)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.runelite.launcher.ReflectionLauncher$1.run(ReflectionLauncher.java:64)

I'd really appreciate every help and advice you can give me to solve this.
I already unistalled Runelite and reinstaled, clear cache, reset router and all that stuff.

**Comment by Nightfirecat** [comment]
Please make sure you are only using the RuneLite download from the website: https://runelite.net
