### ISSUE TITLE
Game crashes when seed vault is open

### ISSUE THREAD

**Issue by ckazenske1** [runelite/runelite#10512]
I have been having the same issue for months where the game will sometimes crash while putting seeds in the seed vault. It just happened again and I decided to check my logs (see below). Looks like there is a divide by zero error. 

2019-12-28 10:47:39 [Client] ERROR net.runelite.client.RuneLite - Game crash: 2820 2819 4003
java.lang.ArithmeticException: / by zero
	at e.aq(e.java:2437)
	at eq.y(eq.java:421)
	at e.i(e.java:355)
	at client.f(client.java:97)
	at client.gt(client.java:3171)
	at client.aj(client.java:1233)
	at bj.z(bj.java:337)
	at bj.run(bj.java:316)
	at java.lang.Thread.run(Thread.java:748)

**Comment by abextm** [comment]
Please post your entire log

**Comment by ckazenske1** [comment]
Sorry for the late reply. It just happened again. Here is the full log.

2020-01-24 10:56:40 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2020-01-24 10:56:40 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2020-01-24 10:56:41 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 412848200.23
2020-01-24 10:56:42 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2020-01-24 10:56:43 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2020-01-24 10:56:45 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 5422ms. Uptime: 7360ms
2020-01-24 10:56:45 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1920x1040,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@199041e2,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2020-01-24 11:06:25 [pool-3-thread-1] WARN  n.r.c.plugins.hiscore.HiscorePanel - Error fetching Hiscore data timeout
2020-01-24 11:06:46 [pool-3-thread-1] WARN  n.r.c.plugins.hiscore.HiscorePanel - Error fetching Hiscore data timeout
2020-01-24 11:15:19 [Client] ERROR net.runelite.client.RuneLite - Game crash: 2820 2819 4003
java.lang.ArithmeticException: / by zero
	at e.aq(e.java:2437)
	at eq.y(eq.java:421)
	at e.i(e.java:355)
	at client.f(client.java:97)
	at client.wo(client.java:3171)
	at client.bj(client.java:1233)
	at bj.z(bj.java:337)
	at bj.run(bj.java:316)
	at java.lang.Thread.run(Thread.java:748)
2020-01-24 11:15:26 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2020-01-24 11:15:26 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2020-01-24 11:15:27 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 412848200.23
2020-01-24 11:15:28 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2020-01-24 11:15:29 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2020-01-24 11:15:31 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 5946ms. Uptime: 8057ms
2020-01-24 11:15:32 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1920x1040,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@7667c184,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]

**Comment by abextm** [comment]
The only way I can find to get this to remotely happen is by setting 631.11's' width to 1 (2 should also work). Notably 0 prevents the script from being ran at all, because its not being ticked. Regardless this value can only ever be 0 or 329. All the other divisions are with non-zero constants, so they can be ruled out as well. Even in these manufactured cases, it still doesn't actually crash the client on the current clientpatch, and when I manually crashed it on the clientpatch you listed it is caught and the client continues normally.
