### ISSUE TITLE
Runelite crashing after pest control game

### ISSUE THREAD

**Issue by WeberMen** [runelite/runelite#10549]
[client.log](https://github.com/runelite/runelite/files/4021481/client.log)
[jvm_crash_pid_10724.log](https://github.com/runelite/runelite/files/4021483/jvm_crash_pid_10724.log)
[jvm_crash_pid_8428.log](https://github.com/runelite/runelite/files/4021485/jvm_crash_pid_8428.log)
~10% I crash right after a pest control game ends. Super annoying

**Comment by bytemunch** [comment]
Have you tried reinstalling RuneLite and making sure your graphics drivers are up to date? Try turning GPU plugin off for now?

**Comment by MESLewis** [comment]
Does this happen on the latest release of RuneLite?

**Comment by danceswitheagle** [comment]
I've been getting this issue too. Turning off gpu and skyboxes didn't help. Log attached.

`java.lang.ArrayIndexOutOfBoundsException: Index 13 out of bounds for length 13
	at com.larsvansoest.runelite.clueitems.progress.EmoteClueItemsTracker.writeDeltas(EmoteClueItemsTracker.java:58)
	at com.larsvansoest.runelite.clueitems.progress.EmoteClueItemsMonitor.fetchEmoteClueItemChanges(EmoteClueItemsMonitor.java:72)
	at com.larsvansoest.runelite.clueitems.progress.RequirementStatusManager.handleEmoteClueItemChanges(RequirementStatusManager.java:107)
	at com.larsvansoest.runelite.clueitems.EmoteClueItemsPlugin.onItemContainerChanged(EmoteClueItemsPlugin.java:115)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:66)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:219)
	at net.runelite.client.util.DeferredEventBus.replay(DeferredEventBus.java:69)
	at net.runelite.client.callback.Hooks.updateNpcs(Hooks.java:487)
	at client.nt(client.java:29344)
	at x.hs(x.java)
	at client.ce(client.java:6478)
	at client.ef(client.java:3199)
	at client.a(client.java:1295)
	at aa.g(aa.java:336)
	at aa.run(aa.java:315)
	at java.base/java.lang.Thread.run(Unknown Source)
`

**Comment by zednine420** [comment]
i am still getting same issue after pest control game. crashes often and makes this grind even more a pain. any fixes?

**Comment by Kinomora** [comment]
What is the status on this issue? No info since it was posted, but my bug report was closed about it. What am I supposed to do to fix it.

**Comment by Nightfirecat** [comment]
There's no resolution for it presently. The only workaround is to disable the skybox plugin, as the crashes you're experiencing are caused by code run by that plugin.
