### ISSUE TITLE
NPE in ObjectIndicators when logging in

### ISSUE THREAD

**Issue by raiyni** [runelite/runelite#10576]
1. Mark Culimancer's Chest
2. Logout
3. Login

```
java.lang.NullPointerException: null
	at net.runelite.client.plugins.objectindicators.ObjectIndicatorsPlugin.checkObjectPoints(ObjectIndicatorsPlugin.java:333)
	at net.runelite.client.plugins.objectindicators.ObjectIndicatorsPlugin.onGameObjectSpawned(ObjectIndicatorsPlugin.java:195)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:73)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:222)
	at net.runelite.client.callback.Hooks.post(Hooks.java:167)
	at dy.du(dy.java:43062)
	at ej.cy(ej.java:326)
	at ej.ch(ej.java:269)
	at iq.e(iq.java:373)
	at client.bj(client.java:1108)
	at bj.z(bj.java:337)
	at bj.run(bj.java:316)
	at java.lang.Thread.run(Thread.java:748)```

**Comment by ypperlig** [comment]
I got the same issue yesterday. The only difference I could see is that the object being marked had an id of 12308 but examine showed it had an id of 12309.
