### ISSUE TITLE
Runelite doesn't launch

### ISSUE THREAD

**Issue by adamlambe** [runelite/runelite#10825]
**Describe the bug**
Runelite crashes before seeing the splash/loading screen.

**To Reproduce**
1. Run Runelite

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: Latest

**Additional context**
Log file contents:
`2020-02-18 13:32:48 [main] ERROR net.runelite.launcher.Launcher - Failure during startup
java.lang.UnsatisfiedLinkError: C:\Users\adam\AppData\Local\RuneLite\jre\bin\javaaccessbridge.dll: Can't find dependent libraries
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(Unknown Source)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.base/java.lang.System.loadLibrary(Unknown Source)
	at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge$3.run(Unknown Source)
	at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge$3.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge.<clinit>(Unknown Source)
	at jdk.accessibility/com.sun.java.accessibility.internal.ProviderImpl.activate(Unknown Source)
	at java.desktop/java.awt.Toolkit.lambda$loadAssistiveTechnologies$0(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.Toolkit.loadAssistiveTechnologies(Unknown Source)
	at java.desktop/java.awt.Toolkit.getDefaultToolkit(Unknown Source)
	at java.desktop/java.awt.EventQueue.invokeAndWait(Unknown Source)
	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(Unknown Source)
	at net.runelite.launcher.SplashScreen.init(SplashScreen.java:161)
	at net.runelite.launcher.Launcher.main(Launcher.java:143)`

Note: I looked at issue #9798, and I have the redistributables installed (2013, 2015-2019 both x86/x64). Also tried reinstalling Runelite, and the official client won't load either (presumably the same issue).

**Comment by Hydrox6** [comment]
Please join the [Discord](https://discord.gg/mePCs8U). Everyone's issues are subtly different and usually dependant on the system running it, and the Issue Tracker is not a support forum.
