### ISSUE TITLE
Changing slayer plugin infobox config causes client crash

### ISSUE THREAD

**Issue by ChaoticConundrum** [runelite/runelite#1090]
Changing the config for the infobox on the slayer plugin causes a crash with the trace:
```
java.lang.ArrayIndexOutOfBoundsException: -104
	at eu.c(eu.java:600)
	at eu.o(eu.java:242)
	at ew.ac(ew.java:1208)
	at ew.ab(ew.java:917)
	at ew.copy$drawRegion(ew.java:766)
	at ew.ak(ew.java:54)
	at e.gd(e.java:3878)
	at jk.iq(jk.java:9470)
	at kq.ix(kq.java:9321)
	at client.gu(client.java:3533)
	at client.ah(client.java:922)
	at bh.h(bh.java:369)
	at bh.run(bh.java:323)
	at java.lang.Thread.run(Thread.java:748)
```
This is almost certainly caused by SlayerPlugin.onConfigChanged -> addCounter -> ItemManager.getImage(). ItemManager.getImage is unsafe to call off of the client thread.

**Comment by deathbeam** [comment]
Fixed with changes that moved call of the getImage method to client thread.
