### ISSUE TITLE
random crash | elite clue issue?

### ISSUE THREAD

**Issue by Victor-Huynh** [runelite/runelite#11295]
**Clue scroll error:** 
2020-04-16 15:44:26 [Client] WARN  n.r.c.p.cluescrolls.ClueScrollPlugin - Encountered unhandled clue text: How many items can carry water in Gielinor?

**Relevant error log attached:

CRASH ONE:**
```
2020-04-16 22:29:25 [Client] ERROR net.runelite.client.RuneLite - Game crash: null
java.lang.NullPointerException: null
	at ej.fi(ej.java:1155)
	at ej.pf(ej.java)
	at fb.hh(fb.java:38060)
	at hj.gn(hj.java:4337)
	at iv.io(iv.java:9896)
	at hy.ik(hy.java:9785)
	at client.yn(client.java:4086)
	at client.ao(client.java:1182)
	at br.ke(br.java:362)
	at br.run(br.java:316)
	at java.base/java.lang.Thread.run(Unknown Source)
2020-04-16 22:29:45 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2020-04-16 22:29:45 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2020-04-16 22:29:45 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 514150018.107
2020-04-16 22:29:46 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2020-04-16 22:29:46 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2020-04-16 22:29:47 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2020-04-16 22:29:48 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 3191ms. Uptime: 5170ms
2020-04-16 22:29:48 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,1082,258,1310x885,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1310x885,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@38f7e878,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2020-04-16 22:29:49 [pool-3-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user Victor ?.
```

**Comment by Victor-Huynh** [comment]
[client.log](https://github.com/runelite/runelite/files/4490658/client.log)

**Comment by Nightfirecat** [comment]
As this issue is very old, I am closing it. If you still experience these crashes, please post a recent log and we'll look into it.
