### ISSUE TITLE
Spam clicking client close button causes exceptions

### ISSUE THREAD

**Issue by Juuldamen** [runelite/runelite#11354]
**Describe the bug**
Each click on the client close button after the first will throw exceptions.

**To Reproduce**
1. Open the client and wait for it to load.
2. Click on the close button and spam it after the first click.
3. See error

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.6.12
 - Launcher version: Built from master

**Additional context**
Logs of the error:
```
2020-04-23 22:46:38 [pool-2-thread-1] WARN  n.r.c.util.RunnableExceptionLogger - Uncaught exception in runnable net.runelite.client.ClientSessionManager$$Lambda$1069/1208109353@453563c5
java.lang.NullPointerException: null
	at net.runelite.client.SessionClient.delete(SessionClient.java:89)
	at net.runelite.client.ClientSessionManager.lambda$onClientShutdown$0(ClientSessionManager.java:84)
	at net.runelite.client.util.RunnableExceptionLogger.run(RunnableExceptionLogger.java:41)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-04-23 22:46:38 [RuneLite Shutdown] WARN  n.r.client.events.ClientShutdown - Error during shutdown: 
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at net.runelite.client.events.ClientShutdown.waitForAllConsumers(ClientShutdown.java:60)
	at net.runelite.client.ui.ClientUI.lambda$shutdownClient$9(ClientUI.java:581)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at net.runelite.client.SessionClient.delete(SessionClient.java:89)
	at net.runelite.client.ClientSessionManager.lambda$onClientShutdown$0(ClientSessionManager.java:84)
	at net.runelite.client.util.RunnableExceptionLogger.run(RunnableExceptionLogger.java:41)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 common frames omitted
```

**Comment by Adam-** [comment]
@abextm do you have an opinion on the best way to fix this?
