### ISSUE TITLE
Can't open RuneLite

### ISSUE THREAD

**Issue by simon9943** [runelite/runelite#11462]
Tried other troubleshooting guides. Can't open the standard ORSR client either.
Tried uninstalling and reinstalling.
Here are the logs:

2020-05-04 18:41:09 [main] ERROR net.runelite.launcher.Launcher - Failure during startup
java.lang.UnsatisfiedLinkError: C:\Users\username\AppData\Local\RuneLite\jre\bin\javaaccessbridge.dll: Can't find dependent libraries
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(Unknown Source)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.base/java.lang.System.loadLibrary(Unknown Source)
	at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge$3.run(Unknown Source)
	at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge$3.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge.<clinit>(Unknown Source)
	at jdk.accessibility/com.sun.java.accessibility.internal.ProviderImpl.activate(Unknown Source)
	at java.desktop/java.awt.Toolkit.lambda$loadAssistiveTechnologies$0(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.Toolkit.loadAssistiveTechnologies(Unknown Source)
	at java.desktop/java.awt.Toolkit.getDefaultToolkit(Unknown Source)
	at java.desktop/java.awt.EventQueue.invokeAndWait(Unknown Source)
	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(Unknown Source)
	at net.runelite.launcher.SplashScreen.init(SplashScreen.java:161)
	at net.runelite.launcher.Launcher.main(Launcher.java:143)

**Comment by Alexsuperfly** [comment]
Try the [32 bit launcher](https://github.com/runelite/launcher/releases/download/2.1.0/RuneLiteSetup32.exe)

If that doesn't seem to work join us on [discord](https://runelite.net/discord) since this is not a support forum
