### ISSUE TITLE
Crash when refreshing hiscores(?)

### ISSUE THREAD

**Issue by RonnyAL** [runelite/runelite#11572]
As I got thrown off Lunar Isle on my way back to Vorkath, I refreshed the hiscores by highlighting the input field and pressing enter to repeat a previous search. As I spawned in Rellekka, I noticed a significant FPS drop, and the program halted completely (froze). At this point I was only able to exit by using task manager to force close the application. Note that FPS drop occured almost exactly when I pressed enter to refresh the hiscores.

I checked the logs and found this around the time of the crash:

```
2020-05-13 20:54:51 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 9
	at he.getChild(he.java:58351)
	at info.sigterm.plugins.esspouch.EssPouchPlugin.onMenuOptionClicked(EssPouchPlugin.java:279)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:73)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:222)
	at net.runelite.client.callback.Hooks.post(Hooks.java:167)
	at hi.ij(hi.java:17752)
	at client.gc(client.java:8313)
	at client.ey(client.java:3142)
	at client.u(client.java:1113)
	at br.mk(br.java:336)
	at br.run(br.java:315)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Possibly related to the Essence Pouch plugin? I was carrying an essence pouch at the time.

Can provide more details if necessary.

**Comment by Nightfirecat** [comment]
Please open this as an issue on the repository of the essence pouch plugin. Click the support icon of the plugin to get a link to its repository.
