### ISSUE TITLE
Runelite - Client no Launch

### ISSUE THREAD

**Issue by Volcomtony** [runelite/runelite#11633]
Hello, I have this problem, the client does nothing
2020-05-17 04:36:09 [main] ERROR net.runelite.launcher.Launcher - Failure during startup
java.lang.UnsatisfiedLinkError: C:\Users\Rafael\AppData\Local\RuneLite\jre\bin\javaaccessbridge.dll: Can't find dependent libraries
at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
at java.base/java.lang.ClassLoader$NativeLibrary.load(Unknown Source)
at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(Unknown Source)
at java.base/java.lang.ClassLoader.loadLibrary0(Unknown Source)
at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
at java.base/java.lang.System.loadLibrary(Unknown Source)
at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge$3.run(Unknown Source)
at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge$3.run(Unknown Source)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.base/java.security.AccessController.doPrivileged(Unknown Source)
at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge.<clinit>(Unknown Source)
at jdk.accessibility/com.sun.java.accessibility.internal.ProviderImpl.activate(Unknown Source)
at java.desktop/java.awt.Toolkit.lambda$loadAssistiveTechnologies$0(Unknown Source)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.desktop/java.awt.Toolkit.loadAssistiveTechnologies(Unknown Source)
at java.desktop/java.awt.Toolkit.getDefaultToolkit(Unknown Source)
at java.desktop/java.awt.EventQueue.invokeAndWait(Unknown Source)
at java.desktop/javax.swing.SwingUtilities.invokeAndWait(Unknown Source)
at net.runelite.launcher.SplashScreen.init(SplashScreen.java:161)
at net.runelite.launcher.Launcher.main(Launcher.java:143)

**Comment by Nightfirecat** [comment]
This is an issue tracker for software bugs, not a troubleshooting forum. [Please join the `#support` channel on our Discord server](https://runelite.net/discord) for support with this issue.
