### ISSUE TITLE
Logging in causes client to freeze

### ISSUE THREAD

**Issue by SpaIns** [runelite/runelite#11767]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Upon logging in, the client no longer updates and an error is thrown.

The error occurs from commit 1e7299bcc618fcf2441a8f82f70dfc0788252b43 onward, but not for commits previous (including 590c11edb4351e2bf7cb0d7d392724110c049393).  Seems odd, considering the diff between commits is just POM updates of the version.

**To Reproduce**
1. Checkout commit 1e7299bcc618fcf2441a8f82f70dfc0788252b43
2. Launch client
3. Login.
4. Note that the client screen does not update past the "Connecting to server..." login screen.

**Expected behavior**
Client should login as normal.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.6.18-SNAPSHOT
 - Launcher version: Unknown

**Additional context**
The error thrown is this:
2020-05-30 12:05:20 [main] INFO  net.runelite.client.RuneLite - Client initialization took 5754ms. Uptime: 6505ms
2020-05-30 12:05:21 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,1258,600,809x684,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x684,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@2acb2215,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2020-05-30 12:05:32 [Client] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.NoSuchMethodError: 'void net.runelite.api.hooks.Callbacks.drawAfterWidgets()'
	at client.ho(client.java:4088)
	at client.ao(client.java:1182)
	at br.h(br.java:362)
	at br.run(br.java:316)
	at java.base/java.lang.Thread.run(Thread.java:830)

**Comment by ThatGamerBlue** [comment]
Rerun your maven build:

1) Make sure your branch is up to date with master. See !sync
2) Run maven with -U. Typically your arguments will look like clean install -DskipTests -U
3) In IntelliJ: Maven Projects > Reimport all maven projects

**Comment by SpaIns** [comment]
That did appear to be the issue! Thanks for the quick reply and sorry for the false report.
