### ISSUE TITLE
fatal error starting runelite

### ISSUE THREAD

**Issue by shyfxx** [runelite/runelite#11830]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
fatal error during startup on runelite

**Screenshots**
2020-06-06 09:59:53 [AWT-EventQueue-0] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.IllegalStateException: Fatal error during fatal error: RuneLite has encountered an unexpected error during startup.
	at net.runelite.client.ui.FatalErrorDialog.<init>(FatalErrorDialog.java:69)
	at net.runelite.client.RuneLite.lambda$main$3(RuneLite.java:279)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

**Environment (please complete the following information):**
 - OS: windows
 - RuneLite version: newest version
 - Launcher version: newest version

**Additional context**
.

**Comment by Nightfirecat** [comment]
Please upload your client.log and launcher.log files
