### ISSUE TITLE
Runescape client not loading when opening runelite

### ISSUE THREAD

**Issue by vincentfortin** [runelite/runelite#11960]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
When opening the runelite client, the runescape client does not load and the page stays black. This happened randomly, not after any update of the client.

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="804" alt="Screen Shot 2020-06-22 at 6 37 57 PM" src="https://user-images.githubusercontent.com/20601293/85341974-7f8a3400-b4b7-11ea-87df-b449754d8be0.png">

**Environment (please complete the following information):**
 - OS: MacOS
 - RuneLite version: Latest ?
 - Launcher version: 2.1.2

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.
2020-06-22 09:37:36 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.6.20 (launcher version 2.1.2) starting up, args: none
2020-06-22 09:37:43 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2020-06-22 09:37:43 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2020-06-22 09:37:44 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 601021252.170
2020-06-22 09:37:51 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2020-06-22 09:37:54 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "zulrah-helper" version "1.2.1" commit "a10c7242ee25809705985883ad297e89962b9b85"
2020-06-22 09:37:54 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "fight-cave-waves" version "1.0" commit "17ccfb7deaa30f10e4392f60ba264c54b0030bd4"
2020-06-22 09:37:54 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "master-farmer" version "1.0-SNAPSHOT" commit "0836763af9e9786f8b5225c7f576e8a2594084b8"
2020-06-22 09:37:54 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "banked-experience" version "1.5" commit "3f48e17add5653aaf707ac1863e684b769e9666a"
2020-06-22 09:37:54 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "ess-pouch" version "1.3" commit "dd766b0c5cb3f9ef9c24f3ddb5f75c09b2f1318e"
2020-06-22 09:37:55 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2020-06-22 09:37:57 [pool-3-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user vfortin.
2020-06-22 09:38:03 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 26371ms. Uptime: 34604ms
2020-06-22 09:38:03 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,238,23,405x301,invalid,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,405x301,invalid,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@4f8b0dae,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2020-06-22 10:33:43 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.6.20 (launcher version 2.1.2) starting up, args: none
2020-06-22 10:33:44 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2020-06-22 10:33:44 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2020-06-22 10:33:44 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 601021252.170
2020-06-22 10:33:47 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2020-06-22 10:33:48 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "zulrah-helper" version "1.2.1" commit "a10c7242ee25809705985883ad297e89962b9b85"
2020-06-22 10:33:48 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "fight-cave-waves" version "1.0" commit "17ccfb7deaa30f10e4392f60ba264c54b0030bd4"
2020-06-22 10:33:48 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "master-farmer" version "1.0-SNAPSHOT" commit "0836763af9e9786f8b5225c7f576e8a2594084b8"
2020-06-22 10:33:48 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "banked-experience" version "1.5" commit "3f48e17add5653aaf707ac1863e684b769e9666a"
2020-06-22 10:33:48 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "ess-pouch" version "1.3" commit "dd766b0c5cb3f9ef9c24f3ddb5f75c09b2f1318e"
2020-06-22 10:33:49 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2020-06-22 10:33:51 [pool-3-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user vfortin.
2020-06-22 10:33:54 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 10488ms. Uptime: 15174ms
2020-06-22 10:33:54 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,238,23,405x301,invalid,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,405x301,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@7554ad14,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2020-06-22 12:01:25 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.6.20 (launcher version 2.1.2) starting up, args: none
2020-06-22 12:01:27 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2020-06-22 12:01:28 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2020-06-22 12:01:29 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 601021252.170
2020-06-22 12:01:39 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2020-06-22 12:01:43 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "zulrah-helper" version "1.2.1" commit "a10c7242ee25809705985883ad297e89962b9b85"
2020-06-22 12:01:43 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "fight-cave-waves" version "1.0" commit "17ccfb7deaa30f10e4392f60ba264c54b0030bd4"
2020-06-22 12:01:43 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "master-farmer" version "1.0-SNAPSHOT" commit "0836763af9e9786f8b5225c7f576e8a2594084b8"
2020-06-22 12:01:43 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "banked-experience" version "1.5" commit "3f48e17add5653aaf707ac1863e684b769e9666a"
2020-06-22 12:01:43 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "ess-pouch" version "1.3" commit "dd766b0c5cb3f9ef9c24f3ddb5f75c09b2f1318e"
2020-06-22 12:01:46 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2020-06-22 12:01:48 [pool-3-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user vfortin.
2020-06-22 12:01:58 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 33675ms. Uptime: 44775ms
2020-06-22 12:01:59 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,235,23,405x268,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@59a216bf,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2020-06-22 18:02:56 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.6.20 (launcher version 2.1.2) starting up, args: none
2020-06-22 18:02:57 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2020-06-22 18:02:57 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2020-06-22 18:02:57 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 601021252.170
2020-06-22 18:03:03 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2020-06-22 18:03:05 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "zulrah-helper" version "1.2.1" commit "a10c7242ee25809705985883ad297e89962b9b85"
2020-06-22 18:03:05 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "fight-cave-waves" version "1.0" commit "17ccfb7deaa30f10e4392f60ba264c54b0030bd4"
2020-06-22 18:03:05 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "master-farmer" version "1.0-SNAPSHOT" commit "0836763af9e9786f8b5225c7f576e8a2594084b8"
2020-06-22 18:03:05 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "banked-experience" version "1.5" commit "3f48e17add5653aaf707ac1863e684b769e9666a"
2020-06-22 18:03:05 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "ess-pouch" version "1.3" commit "dd766b0c5cb3f9ef9c24f3ddb5f75c09b2f1318e"
2020-06-22 18:03:07 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2020-06-22 18:03:09 [pool-3-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user vfortin.
2020-06-22 18:03:14 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 18544ms. Uptime: 27580ms
2020-06-22 18:03:15 [Client] ERROR client-patch - Game crash: null
java.lang.ArrayIndexOutOfBoundsException: Index 181306 out of bounds for length 181306
	at cw.j(cw.java:209)
	at cw.dq(cw.java:174)
	at cw.q(cw.java:85)
	at ch.z(ch.java:1262)
	at client.am(client.java:961)
	at bn.hk(bn.java:384)
	at bn.run(bn.java:338)
	at java.base/java.lang.Thread.run(Unknown Source)
2020-06-22 18:03:15 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,235,23,405x268,invalid,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,405x268,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@5cbcb28e,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2020-06-22 18:04:00 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.6.20 (launcher version 2.1.2) starting up, args: none
2020-06-22 18:04:01 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2020-06-22 18:04:01 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2020-06-22 18:04:02 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 601021252.170
2020-06-22 18:04:05 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2020-06-22 18:04:06 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "zulrah-helper" version "1.2.1" commit "a10c7242ee25809705985883ad297e89962b9b85"
2020-06-22 18:04:06 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "fight-cave-waves" version "1.0" commit "17ccfb7deaa30f10e4392f60ba264c54b0030bd4"
2020-06-22 18:04:06 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "master-farmer" version "1.0-SNAPSHOT" commit "0836763af9e9786f8b5225c7f576e8a2594084b8"
2020-06-22 18:04:06 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "banked-experience" version "1.5" commit "3f48e17add5653aaf707ac1863e684b769e9666a"
2020-06-22 18:04:06 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "ess-pouch" version "1.3" commit "dd766b0c5cb3f9ef9c24f3ddb5f75c09b2f1318e"
2020-06-22 18:04:07 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2020-06-22 18:04:09 [pool-3-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user vfortin.
2020-06-22 18:04:21 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 21136ms. Uptime: 26430ms
2020-06-22 18:04:22 [Client] ERROR client-patch - Game crash: null
java.lang.ArrayIndexOutOfBoundsException: Index 181306 out of bounds for length 181306
	at cw.j(cw.java:209)
	at cw.dq(cw.java:174)
	at cw.q(cw.java:85)
	at ch.z(ch.java:1262)
	at client.am(client.java:961)
	at bn.hk(bn.java:384)
	at bn.run(bn.java:338)
	at java.base/java.lang.Thread.run(Unknown Source)
2020-06-22 18:04:22 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,235,23,405x268,invalid,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,405x268,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@3ab319c7,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2020-06-22 18:12:17 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.6.20 (launcher version 2.1.2) starting up, args: none
2020-06-22 18:12:20 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2020-06-22 18:12:21 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2020-06-22 18:12:23 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 601021252.170
2020-06-22 18:12:31 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2020-06-22 18:12:34 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "zulrah-helper" version "1.2.1" commit "a10c7242ee25809705985883ad297e89962b9b85"
2020-06-22 18:12:34 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "fight-cave-waves" version "1.0" commit "17ccfb7deaa30f10e4392f60ba264c54b0030bd4"
2020-06-22 18:12:34 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "master-farmer" version "1.0-SNAPSHOT" commit "0836763af9e9786f8b5225c7f576e8a2594084b8"
2020-06-22 18:12:34 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "banked-experience" version "1.5" commit "3f48e17add5653aaf707ac1863e684b769e9666a"
2020-06-22 18:12:34 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "ess-pouch" version "1.3" commit "dd766b0c5cb3f9ef9c24f3ddb5f75c09b2f1318e"
2020-06-22 18:12:36 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2020-06-22 18:12:38 [pool-3-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user vfortin.
2020-06-22 18:12:52 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 35412ms. Uptime: 60510ms
2020-06-22 18:12:54 [Client] ERROR client-patch - Game crash: null
java.lang.ArrayIndexOutOfBoundsException: Index 181306 out of bounds for length 181306
	at cw.j(cw.java:209)
	at cw.dq(cw.java:174)
	at cw.q(cw.java:85)
	at ch.z(ch.java:1262)
	at client.am(client.java:961)
	at bn.hk(bn.java:384)
	at bn.run(bn.java:338)
	at java.base/java.lang.Thread.run(Unknown Source)
2020-06-22 18:12:53 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,235,23,405x268,invalid,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,405x268,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@29f42067,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2020-06-22 18:16:25 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.6.20 (launcher version 2.1.2) starting up, args: none
2020-06-22 18:16:26 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2020-06-22 18:16:27 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2020-06-22 18:16:27 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 601021252.170
2020-06-22 18:16:30 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2020-06-22 18:16:31 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "zulrah-helper" version "1.2.1" commit "a10c7242ee25809705985883ad297e89962b9b85"
2020-06-22 18:16:31 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "fight-cave-waves" version "1.0" commit "17ccfb7deaa30f10e4392f60ba264c54b0030bd4"
2020-06-22 18:16:31 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "master-farmer" version "1.0-SNAPSHOT" commit "0836763af9e9786f8b5225c7f576e8a2594084b8"
2020-06-22 18:16:31 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "banked-experience" version "1.5" commit "3f48e17add5653aaf707ac1863e684b769e9666a"
2020-06-22 18:16:31 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "ess-pouch" version "1.3" commit "dd766b0c5cb3f9ef9c24f3ddb5f75c09b2f1318e"
2020-06-22 18:16:33 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2020-06-22 18:16:35 [pool-3-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user vfortin.
2020-06-22 18:16:40 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 14913ms. Uptime: 23502ms
2020-06-22 18:16:41 [Client] ERROR client-patch - Game crash: null
java.lang.ArrayIndexOutOfBoundsException: Index 181306 out of bounds for length 181306
	at cw.j(cw.java:209)
	at cw.dq(cw.java:174)
	at cw.q(cw.java:85)
	at ch.z(ch.java:1262)
	at client.am(client.java:961)
	at bn.hk(bn.java:384)
	at bn.run(bn.java:338)
	at java.base/java.lang.Thread.run(Unknown Source)
2020-06-22 18:16:41 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,239,23,405x268,invalid,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,405x268,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@756c435f,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2020-06-22 18:21:48 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.6.20 (launcher version 2.1.2) starting up, args: none
2020-06-22 18:21:51 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2020-06-22 18:21:51 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2020-06-22 18:21:51 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 601021252.170
2020-06-22 18:21:55 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2020-06-22 18:21:56 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "zulrah-helper" version "1.2.1" commit "a10c7242ee25809705985883ad297e89962b9b85"
2020-06-22 18:21:56 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "fight-cave-waves" version "1.0" commit "17ccfb7deaa30f10e4392f60ba264c54b0030bd4"
2020-06-22 18:21:56 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "master-farmer" version "1.0-SNAPSHOT" commit "0836763af9e9786f8b5225c7f576e8a2594084b8"
2020-06-22 18:21:56 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "banked-experience" version "1.5" commit "3f48e17add5653aaf707ac1863e684b769e9666a"
2020-06-22 18:21:56 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "ess-pouch" version "1.3" commit "dd766b0c5cb3f9ef9c24f3ddb5f75c09b2f1318e"
2020-06-22 18:21:57 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2020-06-22 18:21:59 [pool-3-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user vfortin.
2020-06-22 18:22:03 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 14891ms. Uptime: 19936ms
2020-06-22 18:22:03 [Client] ERROR client-patch - Game crash: null
java.lang.ArrayIndexOutOfBoundsException: Index 181306 out of bounds for length 181306
	at cw.j(cw.java:209)
	at cw.dq(cw.java:174)
	at cw.q(cw.java:85)
	at ch.z(ch.java:1262)
	at client.am(client.java:961)
	at bn.hk(bn.java:384)
	at bn.run(bn.java:338)
	at java.base/java.lang.Thread.run(Unknown Source)
2020-06-22 18:22:03 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,119,23,405x268,invalid,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,405x268,invalid,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@487ced0c,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2020-06-22 18:34:46 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.6.20 (launcher version 2.1.2) starting up, args: none
2020-06-22 18:34:49 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2020-06-22 18:34:49 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2020-06-22 18:34:50 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 601021252.170
2020-06-22 18:34:52 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2020-06-22 18:34:53 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "zulrah-helper" version "1.2.1" commit "a10c7242ee25809705985883ad297e89962b9b85"
2020-06-22 18:34:53 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "fight-cave-waves" version "1.0" commit "17ccfb7deaa30f10e4392f60ba264c54b0030bd4"
2020-06-22 18:34:53 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "master-farmer" version "1.0-SNAPSHOT" commit "0836763af9e9786f8b5225c7f576e8a2594084b8"
2020-06-22 18:34:53 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "banked-experience" version "1.5" commit "3f48e17add5653aaf707ac1863e684b769e9666a"
2020-06-22 18:34:53 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "ess-pouch" version "1.3" commit "dd766b0c5cb3f9ef9c24f3ddb5f75c09b2f1318e"
2020-06-22 18:34:54 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2020-06-22 18:34:56 [pool-3-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user vfortin.
2020-06-22 18:35:03 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 16264ms. Uptime: 25264ms
2020-06-22 18:35:03 [Client] ERROR client-patch - Game crash: null
java.lang.ArrayIndexOutOfBoundsException: Index 181306 out of bounds for length 181306
	at cw.j(cw.java:209)
	at cw.dq(cw.java:174)
	at cw.q(cw.java:85)
	at ch.z(ch.java:1262)
	at client.am(client.java:961)
	at bn.hk(bn.java:384)
	at bn.run(bn.java:338)
	at java.base/java.lang.Thread.run(Unknown Source)
2020-06-22 18:35:03 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,236,23,405x268,invalid,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,405x268,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@20ed4953,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]

**Comment by Hydrox6** [comment]
Turn off Flames in the Login Screen plugin

**Comment by vincentfortin** [comment]
This worked, thanks
