### ISSUE TITLE
Exception thrown when widget inspector is open at login interface

### ISSUE THREAD

**Issue by paulocsanz** [runelite/runelite#12115]
**Describe the bug**
I got this stacktrace when opened the widget inspector from the devtools at the login interface. It's probably a (fairly harmless) symptom of a bug that should be fixed.

```
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at net.runelite.client.plugins.devtools.WidgetInspector.addPickerWidget(WidgetInspector.java:458)
	at net.runelite.client.callback.ClientThread.lambda$invokeLater$1(ClientThread.java:79)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:191)
	at bg.sx(bg.java:6064)
	at client.am(client.java)
	at bn.iq(bn.java:384)
	at bn.run(bn.java:338)
	at java.lang.Thread.run(Thread.java:748)
```
**Environment (please complete the following information):**
 - OS: Ubuntu
 - RuneLite version: 1.6.22

**Comment by paulocsanz** [comment]
The problem is this line: https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/devtools/WidgetInspector.java#L458

Because it calls `findFirst().get()`, the question is, should we just bail out of the function if `findFirst()` returns `Optional.empty()`. Or what?

**Comment by Adam-** [comment]
Personally I don't see anything wrong with developer tools throwing/logging exceptions since the target user is *developers*. If anything it could be more useful than a normal log message.

**Comment by paulocsanz** [comment]
It's just a message that there are no loaded widgets, which happens at login. It's not something needed to crash on.
