### ISSUE TITLE
Game Freezes 

### ISSUE THREAD

**Issue by AndrewR0R** [runelite/runelite#12383]
Game randomly freezes, client continues to function. Has happened a few times recently in different spots

[clienterror.txt](https://github.com/runelite/runelite/files/5116226/clienterror.txt)

 - OS: Windows 10
 - RuneLite version: 1.6.24.1
 - Launcher version: 2.1.3

Relevant error:

```
2020-08-24 16:03:43 [Client] ERROR client-patch - Game crash: null
java.lang.ArrayIndexOutOfBoundsException: Index 1031274578 out of bounds for length 105
	at cr.a(cr.java:80)
	at el.ob(el.java)
	at el.getModel(el.java:58358)
	at net.runelite.client.plugins.gpu.GpuPlugin.draw(GpuPlugin.java:1494)
	at client.hp(client.java:52494)
	at em.ft(em.java:998)
	at em.om(em.java)
	at em.fd(em.java:53233)
	at bg.fz(bg.java:4090)
	at bo.ib(bo.java:9448)
	at iq.ij(iq.java:9337)
	at client.ft(client.java:3828)
	at client.am(client.java:976)
	at bn.pe(bn.java:384)
	at bn.run(bn.java:338)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by MESLewis** [comment]
Reopen this issue if the problem persists in the latest RuneLite release.
