### ISSUE TITLE
Repeated crashing when using GE after 3-5 hours of play

### ISSUE THREAD

**Issue by 8ytan** [runelite/runelite#12639]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
After playing for a while, RuneLite has a tendency to freeze. When I check in the task manager, the CPU usage is showing as 100%, and drops when I focus out of the application. Focusing back in causes the CPU stat to instantly spike again. While this is happening, the screen is frozen and the app cannot be closed without ending the task using task manager. I've noticed this happens most often when I'm in the GE, and it's quite annoying as force closing the app causes it to forget my session (loot tracker, GE plugin etc. all wiped)

**To Reproduce**
1. Use RuneLite
2. Go to GE
3. Play the game for a few hours
4. Client crashes

**Expected behavior**
It shouldn't be using that much CPU. It also seems to use about 10% just having the GE interface open, which seems quite high.

**Environment (please complete the following information):**
 - OS: Windows 10 Pro
 - RuneLite version: 1.6.28
 - Launcher version: 2.1.3 (64-bit)
 - Plugins: Flipping Utilities

**Additional context**
I found the following exception in the log:

> 2020-10-13 16:46:05 [Client] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.OutOfMemoryError: Java heap space
	at java.desktop/sun.java2d.marlin.IntArrayCache.createArray(Unknown Source)
	at java.desktop/sun.java2d.marlin.IntArrayCache$Reference.<init>(Unknown Source)
	at java.desktop/sun.java2d.marlin.IntArrayCache.createRef(Unknown Source)
	at java.desktop/sun.java2d.marlin.DRendererContext.newCleanIntArrayRef(Unknown Source)
	at java.desktop/sun.java2d.marlin.DRenderer.<init>(Unknown Source)
	at java.desktop/sun.java2d.marlin.DRendererContext.<init>(Unknown Source)
	at java.desktop/sun.java2d.marlin.DRendererContext.createContext(Unknown Source)
	at java.desktop/sun.java2d.marlin.DMarlinRenderingEngine$1.newContext(Unknown Source)
	at java.desktop/sun.java2d.marlin.DMarlinRenderingEngine$1.newContext(Unknown Source)
	at java.desktop/sun.java2d.ReentrantContextProviderTL.acquire(Unknown Source)
	at java.desktop/sun.java2d.marlin.DMarlinRenderingEngine.getRendererContext(Unknown Source)
	at java.desktop/sun.java2d.marlin.DMarlinRenderingEngine.getAATileGenerator(Unknown Source)
	at java.desktop/sun.java2d.pipe.AAShapePipe.renderPath(Unknown Source)
	at java.desktop/sun.java2d.pipe.AAShapePipe.draw(Unknown Source)
	at java.desktop/sun.java2d.pipe.PixelToParallelogramConverter.draw(Unknown Source)
	at java.desktop/sun.java2d.pipe.ValidatePipe.draw(Unknown Source)
	at java.desktop/sun.java2d.SunGraphics2D.draw(Unknown Source)
	at net.runelite.client.plugins.regenmeter.RegenMeterOverlay.renderRegen(RegenMeterOverlay.java:119)
	at net.runelite.client.plugins.regenmeter.RegenMeterOverlay.render(RegenMeterOverlay.java:80)
	at net.runelite.client.ui.overlay.OverlayRenderer.safeRender(OverlayRenderer.java:708)
	at net.runelite.client.ui.overlay.OverlayRenderer.render(OverlayRenderer.java:238)
	at net.runelite.client.callback.Hooks.drawAfterWidgets(Hooks.java:459)
	at client.to(client.java:43104)
	at client.vb(client.java:3921)
	at client.aq(client.java:1225)
	at bw.bq(bw.java:360)
	at bw.run(bw.java:314)
	at java.base/java.lang.Thread.run(Unknown Source)
2020-10-13 16:46:19 [AWT-EventQueue-0] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.OutOfMemoryError: Java heap space
	at java.desktop/java.awt.image.DataBufferInt.<init>(Unknown Source)
	at java.desktop/java.awt.image.SinglePixelPackedSampleModel.createDataBuffer(Unknown Source)
	at java.desktop/sun.awt.image.IntegerInterleavedRaster.<init>(Unknown Source)
	at java.desktop/sun.awt.image.IntegerInterleavedRaster.createCompatibleWritableRaster(Unknown Source)
	at java.desktop/java.awt.image.ConvolveOp.createCompatibleDestImage(Unknown Source)
	at java.desktop/java.awt.image.ConvolveOp.filter(Unknown Source)
	at org.pushingpixels.substance.internal.utils.SubstanceTextUtilities.paintTextWithDropShadow(SubstanceTextUtilities.java:116)
	at org.pushingpixels.substance.internal.utils.SubstanceTitlePane.paintComponent(SubstanceTitlePane.java:1154)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JLayeredPane.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent._paintImmediately(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintImmediately(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$4.run(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
2020-10-13 16:46:35 [AWT-EventQueue-0] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.OutOfMemoryError: Java heap space

**Comment by Adam-** [comment]
This is likely due to third party plugins such as flipping utilities. If you can reproduce this with no plugin hub plugins installed then I will look into it.

**Comment by deathbeam** [comment]
https://github.com/Belieal/flipping-utilities/issues/110 it looks like this exact same issue (at least the last part)

**Comment by MESLewis** [comment]
Reopen this issue if the problem persists in the latest RuneLite release.
