### ISSUE TITLE
GPU Plugin Not Working in Virtual Machine

### ISSUE THREAD

**Issue by CalebBuxton** [runelite/runelite#12675]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
I use a Virtual Machine for almost everything and I have no problem with the client but now that I want to use the GPU plugin for Runecrafting it will temporarily freeze the graphics, then the GPU plugin will turn itself back off.

I have tried the `--mode:OFF` and the .bat file fix, neither have worked.

**To Reproduce**
Toggle GPU on

**Expected behavior**
I expect the GPU function to work

**Environment (please complete the following information):**
- VM: VirtualBox - 3D Acceleration on, VBoxSVGA Controller, 256mb Video Memory 
- OS: Windows 10 Pro
 - RuneLite version: 1.6.28
 - Launcher version: 2.1.3

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.
2020-10-20 08:48:55 [main] INFO  net.runelite.client.RuneLite - RuneLite 1.6.28 (launcher version 2.1.3) starting up, args: none
2020-10-20 08:48:57 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2020-10-20 08:48:57 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2020-10-20 08:48:58 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 777841281.281
2020-10-20 08:48:58 [main] INFO  n.r.client.account.SessionManager - No session file exists
2020-10-20 08:49:00 [main] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2020-10-20 08:49:00 [main] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "zom-dense-essence" version "1.0" commit "95722a465c3b3a9cb1926f03b768329a3547aad9"
2020-10-20 08:49:00 [main] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "gpu-experimental" version "1.1" commit "a07807cea3922591ab8cd23d1a87d04b267ddf9e"
2020-10-20 08:49:00 [main] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "skills-tab-progress-bars" version "0.7" commit "ab58a7463762e2707e2e51d5a0f1f15704b211a8"
2020-10-20 08:49:01 [main] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2020-10-20 08:49:04 [main] INFO  net.runelite.client.RuneLite - Client initialization took 8561ms. Uptime: 10713ms
2020-10-20 08:49:04 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1920x1040,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1920x1040,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@2ea5b930,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2020-10-20 08:49:39 [Client] ERROR n.r.client.plugins.gpu.GpuPlugin - Error starting GPU plugin
com.jogamp.opengl.GLException: Profile GL4 is not available on WindowsGraphicsDevice[type .windows, connection decon, unitID 0, handle 0x0, owner false, NullToolkitLock[obj 0x26062e7a]], but: [GLProfile[GL2ES1/GL2.hw], GLProfile[GL2ES2/GL2.hw], GLProfile[GL2/GL2.hw], GLProfile[GL2/GL2.hw], GLProfile[GL2GL3/GL2.hw]]
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:1012)
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:1025)
	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$startUp$0(GpuPlugin.java:314)
	at net.runelite.client.plugins.gpu.GpuPlugin.invokeOnMainThread(GpuPlugin.java:1625)
	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$startUp$2(GpuPlugin.java:312)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:191)
	at client.vy(client.java:42045)
	at client.aq(client.java)
	at bw.bq(bw.java:360)
	at bw.run(bw.java:314)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Bram91** [comment]
You drivers don't support the GPU plugin, also the issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.
