### ISSUE TITLE
Game Crash: Null array out of bounds

### ISSUE THREAD

**Issue by sketchyfresh** [runelite/runelite#12762]
[client.log](https://github.com/runelite/runelite/files/5507825/client.log)
Hey guys I have been having problems with Runelite client crashing due to a java error I suppose. 
My client will freeze, or crash (client will close) randomly throughout playing. 

These instances happen at random, nothing specific to my gameplay or area location. 
Perhaps its an on-screen problem?
I was hoping someone may be able to help me out. I do not have any third party or extra downloadable plugins installed. I play my client basically as its 'vanilla' form. I have a FPS and ping counter on screen, and of course boosts and other helpful info boxes that are on the sides of the game. But nothing special added to runelite. 
Please let me know if you'd like anymore logs or extra information!
Thanks so much!
Here are a few examples of some crashes from my logs, and I have attached 2 client .txt files that have crashes inside them. 
2020-11-08 21:42:49 [Client] ERROR client-patch - Game crash: null

---java.lang.ArrayIndexOutOfBoundsException: Index 16777268 out of bounds for length 104
	at hz.ql(hz.java:902)
	at ef.cg(ef.java)
	at fu.xi(fu.java:28163)
	at bv.gs(bv.java:4616)
	at ax.ik(ax.java:9441)
	at kv.io(kv.java:9330)
	at client.zv(client.java:4263)
	at client.ak(client.java:1621)
	at ba.d(ba.java:361)
	at ba.run(ba.java:315)
at java.base/java.lang.Thread.run(Unknown Source)

--- java.lang.NullPointerException: null
	at net.runelite.client.plugins.slayer.SlayerPlugin.taskLookup(SlayerPlugin.java:831)
	at net.runelite.client.chat.ChatCommandManager.lambda$onChatMessage$0(ChatCommandManager.java:122)
	at net.runelite.client.util.RunnableExceptionLogger.run(RunnableExceptionLogger.java:41)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2020-11-07 08:14:25 [Client] WARN  client-patch - error during tile underlay rendering
java.lang.ArrayIndexOutOfBoundsException: null
2020-11-07 08:22:11 [Client] WARN  client-patch - error during tile underlay rendering
java.lang.ArrayIndexOutOfBoundsException: null
2020-11-07 08:27:17 [Client] WARN  client-patch - error during tile underlay rendering
java.lang.ArrayIndexOutOfBoundsException: null
2020-11-07 08:36:37 [Client] WARN  client-patch - error during tile underlay rendering
java.lang.ArrayIndexOutOfBoundsException: null
2020-11-07 08:39:15 [Client] WARN  client-patch - error during tile underlay rendering
java.lang.ArrayIndexOutOfBoundsException: null
2020-11-07 08:40:40 [Client] WARN  client-patch - error during tile underlay rendering
java.lang.ArrayIndexOutOfBoundsException: null
2020-11-07 08:47:54 [Client] WARN  client-patch - error during tile underlay rendering

[client_2020-11-07.0.log](https://github.com/runelite/runelite/files/5507833/client_2020-11-07.0.log)

**Comment by sketchyfresh** [comment]
Any suggestions anyone?

**Comment by MESLewis** [comment]
Reopen this issue if the problem persists in the current version of RuneLite.
