### ISSUE TITLE
Unable to use GPU plugin compute shaders on Ubuntu 20.10

### ISSUE THREAD

**Issue by amarucci** [runelite/runelite#12922]
other similar bugs exist, however none of the solutions worked: 
https://github.com/runelite/runelite/issues/11848

**Describe the bug**
When turning on the GPU plugin, it quickly turns off. When using `MESA_GL_VERSION_OVERRIDE=4.3` and logging in, I can turn the plugin on, but enabling computer shaders causes a crash.

**To Reproduce**
1. Load runelite
2. enable GPU plugin
3. does not turn on

alternatively

1. Load runelite with setting `MESA_GL_VERSION_OVERRIDE=4.3` 
2. Enable GPU plugin (success)
3. Log in
4. Graphics driver crash

When on Windows, I am able to enable both GPU and computer shaders on this computer.

**Error Output**
This is the error when running WITHOUT `MESA_GL_VERSION_OVERRIDE=4.3` 
```
2020-12-11 23:24:09 [Client] ERROR n.r.client.plugins.gpu.GpuPlugin - Error starting GPU plugin
java.lang.InternalError: XXX0 profile[2]: GL2 -> profileImpl GL3bc !!! not mapped 
        at com.jogamp.opengl.GLProfile.computeProfileMap(GLProfile.java:2098)
        at com.jogamp.opengl.GLProfile.initProfilesForDeviceCritical(GLProfile.java:1976)
        at com.jogamp.opengl.GLProfile.initProfilesForDevice(GLProfile.java:1895)
        at com.jogamp.opengl.GLProfile.initProfilesForDefaultDevices(GLProfile.java:1861)
        at com.jogamp.opengl.GLProfile.access$000(GLProfile.java:80)
        at com.jogamp.opengl.GLProfile$1.run(GLProfile.java:239)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at com.jogamp.opengl.GLProfile.initSingleton(GLProfile.java:225)
        at net.runelite.client.plugins.gpu.GpuPlugin.lambda$startUp$2(GpuPlugin.java:310)
        at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
        at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:191)
        at client.bl(client.java:3831)
        at client.av(client.java)
        at bd.r(bd.java:377)
        at bd.run(bd.java:331)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

When running WITH `MESA_GL_VERSION_OVERRIDE=4.3` not error message is reported (in the client log) but my graphics driver seems to be crashing.

**Expected behavior**
GPU plugin turns on and works as expected, specifically allowing me to use computer shaders and change render distance.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.20
 - RuneLite version: 1.6.35
 - Launcher version: 1.6.2
```
➜  ~ java --version
openjdk 11.0.9.1 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.10)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.10, mixed mode, sharing)
➜  ~ glxinfo | grep "OpenGL version"
OpenGL version string: 3.1 Mesa 20.2.1
➜  ~ lspci | grep VGA
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Cayman PRO [Radeon HD 6950]
06:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Cayman PRO [Radeon HD 6950]
```
(this graphics card indeed supports opengl 4.3 https://www.techpowerup.com/gpu-specs/radeon-hd-6950.c405)

**Comment by abextm** [comment]
Last I checked amdgpu and amdgpu pro doesn't support compute shaders on this card, and I doubt anything has changed recently.

**Comment by amarucci** [comment]
I'm using the radeon driver, do you know if that or catalyst/ati supports this? According to the arch wiki, looks like the best driver for my card might be ATI: https://wiki.archlinux.org/index.php/Xorg#AMD

**Comment by abextm** [comment]
You could try. I used to have this card and I couldn't get anything to work.

**Comment by amarucci** [comment]
iirc the radeon driver is what the ati driver is now called, so it sounds like no dice. Unfortunate, it works on windows. What steps did you try?

**Comment by abextm** [comment]
Its been a while since then so I really don't remember what I tried unfortunately. I generally had a bad experience with stability of that card under linux, though that might be related to the noticeable bend in mine.

**Comment by amarucci** [comment]
yeah its a bit older as well, which doesn't have good signs for any future support.... I'll poke around and see if I can figure anything out but thanks for looking into this!
