### ISSUE TITLE
Client stalls on world switch - UncheckedExecutionException

### ISSUE THREAD

**Issue by TechMaz** [runelite/runelite#12967]
**Describe the bug**
I repeatedly see that every 10 or so times I switch worlds, the moment I appear in the new world, the client is frozen and I can't do anything. If I move anything over the Runescape game window, whatever gets moved on top of it either stays on the screen or the window goes completely black. I am forced to close the application and start it again to be able to log in once more.

**To Reproduce**
1. World hop 5-20 times and at a random point, it will freeze.

**Expected behavior**
* I tested doing the same world hops on the official OSRS client and there are no issues, so it seems to be something to do with Runelite. I tried uninstalling Runelite and re-installing it, but that did not fix the issue.

**Screenshots**
![runelite_stalling](https://user-images.githubusercontent.com/2186709/102975841-8a00a700-44b5-11eb-9800-5a9b649d4dc6.PNG)

**Environment (please complete the following information):**
 - OS: Windows - Windows 10 Home 64-bit
 - RuneLite version: 1.6.35
 - Launcher version: 2.1.6

**Additional context**
client logs:
```
2020-12-23 00:08:05 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.6.35 (launcher version 2.1.6) starting up, args: none
2020-12-23 00:08:06 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2020-12-23 00:08:06 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2020-12-23 00:08:06 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 899601965.344
2020-12-23 00:08:07 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2020-12-23 00:08:07 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "equipment-inspector" version "1.1" commit "09fed5837d1d60e173704a9ff110d72577306ba1"
2020-12-23 00:08:07 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "ham-store-rooms" version "1.0" commit "9deefcc01ca6a026eb9044c55a818a79d1c5ed4d"
2020-12-23 00:08:07 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "fire-beats" version "1.1.2" commit "4935be53b9cf344f19b472803ae2a23a398e946f"
2020-12-23 00:08:07 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "profit-tracker" version "1.0-SNAPSHOT" commit "ecd536275f92a86a91ef8bfa5b71a6208447c359"
2020-12-23 00:08:07 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "resource-packs" version "1.3.1" commit "003799ef17617b6b419e8e49808f593269595ed4"
2020-12-23 00:08:07 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "skills-tab-progress-bars" version "0.7" commit "ab58a7463762e2707e2e51d5a0f1f15704b211a8"
2020-12-23 00:08:07 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "ess-pouch" version "1.3" commit "dd766b0c5cb3f9ef9c24f3ddb5f75c09b2f1318e"
2020-12-23 00:08:07 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "inventory-value-overlay" version "1.0" commit "a64940d73f5a42f625c4f8ae13ec75d7a3e87aab"
2020-12-23 00:08:07 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2020-12-23 00:08:08 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 3630ms. Uptime: 5255ms
2020-12-23 00:08:08 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,2560x1050,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,2560x1050,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@7ce00a47,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2020-12-23 00:14:16 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: mg
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.LongPipeline.reduce(Unknown Source)
	at java.base/java.util.stream.LongPipeline.sum(Unknown Source)
	at com.wikiworm.inventoryvalue.InventoryValuePlugin.onItemContainerChanged(InventoryValuePlugin.java:101)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:73)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:222)
	at net.runelite.client.util.DeferredEventBus.replay(DeferredEventBus.java:69)
	at net.runelite.client.callback.Hooks.updateNpcs(Hooks.java:504)
	at client.xu(client.java:29047)
	at k.hw(k.java)
	at client.ta(client.java:5706)
	at client.su(client.java:2997)
	at client.y(client.java:1256)
	at bd.nw(bd.java:351)
	at bd.run(bd.java:330)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: mg
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2218)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4147)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5140)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5146)
	at net.runelite.client.game.ItemManager.getItemComposition(ItemManager.java:393)
	at com.wikiworm.inventoryvalue.InventoryValuePlugin.calculateItemValue(InventoryValuePlugin.java:110)
	at com.wikiworm.inventoryvalue.InventoryValuePlugin.lambda$onItemContainerChanged$0(InventoryValuePlugin.java:100)
	at java.base/java.util.stream.ReferencePipeline$10$1.accept(Unknown Source)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source)
	at java.base/java.util.stream.AbstractTask.compute(Unknown Source)
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: mg: null
	at fj.v(fj.java:103)
	at bw.v(bw.java:109)
	at client.kl(client.java:52493)
	at client.getItemDefinition(client.java:12009)
	at net.runelite.client.game.ItemManager$2.load(ItemManager.java:195)
	at net.runelite.client.game.ItemManager$2.load(ItemManager.java:191)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212)
	... 20 common frames omitted
Caused by: java.lang.NullPointerException: null
	at bo.jq(bo.java:11)
	at jf.vs(jf.java:40)
	at ez.cc(ez.java:42)
	at bw.v(bw.java:119)
	... 28 common frames omitted
2020-12-23 00:15:08 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: mg
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.LongPipeline.reduce(Unknown Source)
	at java.base/java.util.stream.LongPipeline.sum(Unknown Source)
	at com.wikiworm.inventoryvalue.InventoryValuePlugin.onItemContainerChanged(InventoryValuePlugin.java:101)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:73)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:222)
	at net.runelite.client.util.DeferredEventBus.replay(DeferredEventBus.java:69)
	at net.runelite.client.callback.Hooks.updateNpcs(Hooks.java:504)
	at client.xu(client.java:29047)
	at k.hw(k.java)
	at client.ta(client.java:5706)
	at client.su(client.java:2997)
	at client.y(client.java:1256)
	at bd.nw(bd.java:351)
	at bd.run(bd.java:330)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: mg
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2218)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4147)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5140)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5146)
	at net.runelite.client.game.ItemManager.getItemComposition(ItemManager.java:393)
	at com.wikiworm.inventoryvalue.InventoryValuePlugin.calculateItemValue(InventoryValuePlugin.java:110)
	at com.wikiworm.inventoryvalue.InventoryValuePlugin.lambda$onItemContainerChanged$0(InventoryValuePlugin.java:100)
	at java.base/java.util.stream.ReferencePipeline$10$1.accept(Unknown Source)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source)
	at java.base/java.util.stream.AbstractTask.compute(Unknown Source)
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: mg: null
	at fj.v(fj.java:103)
	at bw.v(bw.java:109)
	at client.kl(client.java:52493)
	at client.getItemDefinition(client.java:12009)
	at net.runelite.client.game.ItemManager$2.load(ItemManager.java:195)
	at net.runelite.client.game.ItemManager$2.load(ItemManager.java:191)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212)
	... 20 common frames omitted
Caused by: java.lang.NullPointerException: null
	at bx.jz(bx.java:11)
	at ez.cc(ez.java:43)
	at bw.v(bw.java:119)
	... 28 common frames omitted
2020-12-23 00:16:06 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: mg
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.LongPipeline.reduce(Unknown Source)
	at java.base/java.util.stream.LongPipeline.sum(Unknown Source)
	at com.wikiworm.inventoryvalue.InventoryValuePlugin.onItemContainerChanged(InventoryValuePlugin.java:101)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:73)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:222)
	at net.runelite.client.util.DeferredEventBus.replay(DeferredEventBus.java:69)
	at net.runelite.client.callback.Hooks.updateNpcs(Hooks.java:504)
	at client.xu(client.java:29047)
	at k.hw(k.java)
	at client.ta(client.java:5706)
	at client.su(client.java:2997)
	at client.y(client.java:1256)
	at bd.nw(bd.java:351)
	at bd.run(bd.java:330)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: mg
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2218)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4147)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5140)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5146)
	at net.runelite.client.game.ItemManager.getItemComposition(ItemManager.java:393)
	at com.wikiworm.inventoryvalue.InventoryValuePlugin.calculateItemValue(InventoryValuePlugin.java:110)
	at com.wikiworm.inventoryvalue.InventoryValuePlugin.lambda$onItemContainerChanged$0(InventoryValuePlugin.java:100)
	at java.base/java.util.stream.ReferencePipeline$10$1.accept(Unknown Source)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source)
	at java.base/java.util.stream.AbstractTask.compute(Unknown Source)
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: mg: null
	at fj.v(fj.java:103)
	at bw.v(bw.java:109)
	at client.kl(client.java:52493)
	at client.getItemDefinition(client.java:12009)
	at net.runelite.client.game.ItemManager$2.load(ItemManager.java:195)
	at net.runelite.client.game.ItemManager$2.load(ItemManager.java:191)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212)
	... 20 common frames omitted
Caused by: java.lang.NullPointerException: null
	at la.p(la.java:27)
	at ew.ek(ew.java:23)
	at bw.v(bw.java:92)
	... 28 common frames omitted
```

[client_2020-12-22.0.log](https://github.com/runelite/runelite/files/5734093/client_2020-12-22.0.log)

**Comment by Hydrox6** [comment]
This looks to be an issue with the Inventory Value plugin, given that stack trace.

Issues and suggestions for hub plugins must be made on that plugin's repository; they are not maintained by us. The repo is usually accessible from the Support link on the plugin.

**Comment by TechMaz** [comment]
@Hydrox6 thanks for helping pinpoint the issue, I will check to see if removing that plugin stops the problem.
