### ISSUE TITLE
RuneLite crashing with brand new 3070 

### ISSUE THREAD

**Issue by KingJafar** [runelite/runelite#12961]
**Describe the bug**
Seems to happen randomly, but at times my monitors hang, turn black, come back on and RuneLite has completely closed. I saw one other user with this issue in the #support channel on discord.

**To Reproduce**
Happens randomly

**Expected behavior**
Not crashing :)

**Screenshots**
Can't take sadly.

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.6.35
 - Launcher version: 2.1.5

**Comment by Nightfirecat** [comment]
Based on logs from the support channel, this appears to be caused by the plugin-hub's BA plugin. Please open an issue [on that plugin's repository](https://github.com/BegOsrs/Ba-minigame) and give them the following logs:

```
2020-12-21 02:53:52 [Client] WARN  n.r.client.callback.ClientThread - Exception in invoke
java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
	at begosrs.barbarianassault.BaMinigamePlugin.restoreAttackStyleText(BaMinigamePlugin.java:776)
	at begosrs.barbarianassault.BaMinigamePlugin.updateAttackStyleText(BaMinigamePlugin.java:637)
	at begosrs.barbarianassault.BaMinigamePlugin.lambda$onScriptPostFired$2(BaMinigamePlugin.java:540)
	at net.runelite.client.callback.ClientThread.lambda$invokeLater$1(ClientThread.java:79)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:191)
	at client.bl(client.java:3831)
	at client.av(client.java)
	at bd.r(bd.java:377)
	at bd.run(bd.java:331)
	at java.base/java.lang.Thread.run(Unknown Source)
```
