### ISSUE TITLE
Cache lib fails to create/modify file data

### ISSUE THREAD

**Issue by Jonatino** [runelite/runelite#13042]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
When trying to create a new file in an archive or modify existing file data, runelite when fail with an `ArrayIndexOutOfBoundsException` when trying to update the CRC hash of the file.

**To Reproduce**
```kotlin

import net.runelite.cache.fs.Store
import net.runelite.cache.index.FileData
import java.io.File


object RuneliteCache {
	
	@JvmStatic
	fun main(args: Array<String>) {
		val cacheFolder = File("test-cache")
		cacheFolder.deleteRecursively()
		cacheFolder.mkdir()
		
		// Create index/archive
		val store = Store(cacheFolder)
		store.load()
		
		val index = store.addIndex(0)
		val archive = index.addArchive(0)
		archive.nameHash = 10000
		archive.fileData = arrayOfNulls<FileData>(1)
		
		// Create file entry
		val fileData = archive.fileData
		fileData[0] = FileData()
		val file = fileData[0]
		file.id = 0
		file.nameHash = 20000
		
		// Create file data using sample npc definition data from abyssal sire (npc id 5886)
		val abyssalSireDef = byteArrayOf(95, 1, 94, 12, 6, 13, 17, -81, 14, 17, -81, 103, 0, 0, 31, 65, 116, 116, 97, 99, 107, 0, 99, 2, 65, 98, 121, 115, 115, 97, 108, 32, 83, 105, 114, 101, 0, 1, 1, 115, 37, 0)
		val archiveFiles = archive.getFiles(store.storage.loadArchive(archive))
		val currentFile = archiveFiles.findFile(0)!!
		currentFile.contents = abyssalSireDef
		
		// Save data
		val content = archiveFiles.saveContents()
		store.storage.saveArchive(archive, content) // Fails here
		store.save()
		
	}
	
}
```

Output: 
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
	at java.base/java.util.zip.CRC32.update(CRC32.java:76)
	at net.runelite.cache.util.Crc32.update(Crc32.java:36)
	at net.runelite.cache.fs.jagex.DiskStorage.saveArchive(DiskStorage.java:223)
	at RuneliteCache.main(RuneliteCache.kt:39)

Process finished with exit code 1
```

**Expected behavior**
File data should be able to be modified and saved without error.

**Comment by Jonatino** [comment]
Not too familiar with the rs cache structure but the bug could possibly be coming from the `ArchiveFiles.saveContents()`.

```java
	public byte[] saveContents()
	{
		OutputStream stream = new OutputStream();

		int filesCount = this.getFiles().size();

		if (filesCount == 1)
		{
			FSFile file = this.getFiles().get(0);
			stream.writeBytes(file.getContents());
		}
		else
		{
			for (FSFile file : this.getFiles())
			{
				byte[] contents = file.getContents();
				stream.writeBytes(contents);
			}

			int offset = 0;

			for (FSFile file : this.getFiles())
			{
				int chunkSize = file.getSize();

				int sz = chunkSize - offset;
				offset = chunkSize;
				stream.writeInt(sz);
			}

			stream.writeByte(1); // chunks
		}

		byte[] fileData = stream.flip();

		logger.trace("Saved contents of archive ({} files), {} bytes", files.size(), fileData.length);
		return fileData;
	}
```

Is it always supposed to write only 1 chunk?

 `stream.writeByte(1); // chunks`

**Comment by Adam-** [comment]
![image](https://user-images.githubusercontent.com/309739/104331968-b2c8fa80-54bd-11eb-994a-2ffb3a96d271.png)

Your stack trace seems to not line up with master

**Comment by Adam-** [comment]
Here is an example with master that works

```java
			Index index = store.addIndex(0);
			Archive archive = index.addArchive(0);
			archive.setFileData(new FileData[1]);
			FileData fileData = archive.getFileData()[0] = new FileData();
			fileData.setId(42);
			fileData.setNameHash(7);

			Storage storage = store.getStorage();
			Container container = new Container(archive.getCompression(), -1);
			container.compress("moo".getBytes(), null);
			storage.saveArchive(archive, container.data);

			store.save();
```

**Comment by Jonatino** [comment]
@Adam- worked. Thank you.
