### ISSUE TITLE
FlatStorage does not update archive CRC when saving

### ISSUE THREAD

**Issue by Jonatino** [runelite/runelite#13044]
**Describe the bug**
Related to #13042 but this time with `FlatStorage` type. When saving archive/file data with a `FlatStorage` store, the archive's CRC never gets updated and causes an exception to be thrown when you try to load the cache after packing it.

**To Reproduce**
```java
package net.runelite.cache;

import net.runelite.cache.fs.Archive;
import net.runelite.cache.fs.Container;
import net.runelite.cache.fs.FSFile;
import net.runelite.cache.fs.Index;
import net.runelite.cache.fs.Storage;
import net.runelite.cache.fs.Store;
import net.runelite.cache.fs.flat.FlatStorage;
import net.runelite.cache.index.FileData;

import java.io.File;
import java.io.IOException;
import java.util.List;

public class FlatStoragePackTest {
	
	public static void main(String[] args) throws IOException {
		File cacheDir = new File("C:\\Users\\Desktop\\Desktop\\test-cache");
		Store store = new Store(new FlatStorage(cacheDir));
		
		if (cacheDir.exists()) {
			store.load();
			Archive archive = store.findIndex(0).getArchive(0);
			List<FSFile> files = archive.getFiles(store.getStorage().loadArchive(archive)).getFiles();
			System.out.println(files);
		} else {
			createAndPack(store);
		}
	}
	
	public static void createAndPack(Store store) throws IOException {
		Index index = store.addIndex(0);
		Archive archive = index.addArchive(0);
		archive.setFileData(new FileData[1]);
		FileData fileData = archive.getFileData()[0] = new FileData();
		//fileData.setId(42);
		//fileData.setNameHash(7);
		
		Storage storage = store.getStorage();
		Container container = new Container(archive.getCompression(), -1);
		container.compress("moo".getBytes(), null);
		storage.saveArchive(archive, container.data);
		
		store.save();
	}
	
}
```

You will need to run it twice to see the error. The first time it will create the cache and save it, the second time it will try to load it and the exception will be thrown.

Output:
```
Exception in thread "main" java.io.IOException: CRC mismatch for 0/0
	at net.runelite.cache.fs.Archive.decompress(Archive.java:120)
	at net.runelite.cache.fs.Archive.getFiles(Archive.java:147)
	at net.runelite.cache.fs.Archive.getFiles(Archive.java:142)
	at net.runelite.cache.FlatStoragePackTest.main(FlatStoragePackTest.java:25)

Process finished with exit code 1
```

**Expected behavior**
`FlatStorage` behavior should match the behavior of `DiskStorage` type and update the archives crc value before saving it.

**Comment by abextm** [comment]
FlatStorage should be fully transparent, including crc errors, so this it working correctly.

**Comment by Jonatino** [comment]
Gotcha. In case anyone wants to use `FlatStorage` for an editable cache here's the fix. 

FileStorage -> saveArchive
```java
        @Override
	public void saveArchive(Archive archive, byte[] bytes) throws IOException
	{
		byte compression = bytes[0];
		int compressedSize = Ints.fromBytes(bytes[1], bytes[2],
				bytes[3], bytes[4]);
		
		// don't crc the appended revision, if it is there
		int length = 1 // compression type
				+ 4 // compressed size
				+ compressedSize
				+ (compression != CompressionType.NONE ? 4 : 0);
		
		Crc32 crc = new Crc32();
		crc.update(bytes, 0, length);
		archive.setCrc(crc.getHash());
		
		data.put((long) archive.getIndex().getId() << 32 | archive.getArchiveId(), bytes);
	}
```
