### ISSUE TITLE
Can't enable GPU plugin - Linux (Fedora)

### ISSUE THREAD

**Issue by Sorgrum** [runelite/runelite#13098]
**Describe the bug**
The GPU plugin isn't able to be enabled. Trying to enable the plugin by clicking immediately turns it off.

**To Reproduce**
1. Download RuneLite through Flatpak
2. Launch Runelite
3. Try to enable the GPU plugin in the plugin panel

**Expected behavior**
The GPU plugin should be enabled

**Environment (please complete the following information):**
 - OS: Fedora 33
 - RuneLite version: 1.6.37
 - Launcher version: 2.1.3

**Additional context**
`client.log`
```
2021-01-22 23:57:13 [Client] ERROR n.r.client.plugins.gpu.GpuPlugin - Error starting GPU plugin
com.jogamp.opengl.GLException: Profile GL4 is not available on X11GraphicsDevice[type .x11, connection :99.0, unitID 0, handle 0x0, owner false, ResourceToolkitLock[obj 0x76c7af1f, isOwner false, <78004fb7, 7c3fc46f>[count 0, qsz 0, owner <NULL>]]], but: [GLProfile[GLES1/GLES1.sw], GLProfile[GLES2/GLES3.sw], GLProfile[GL3bc/GL3bc.sw], GLProfile[GL2ES1/GL3bc.sw], GLProfile[GL4ES3/GLES3.sw], GLProfile[GL2ES2/GL3.sw], GLProfile[GL3bc/GL3bc.sw], GLProfile[GL2/GL3bc.sw], GLProfile[GLES3/GLES3.sw], GLProfile[GL3/GL3.sw], GLProfile[GL2GL3/GL3bc.sw]]
        at com.jogamp.opengl.GLProfile.get(GLProfile.java:1012)
        at com.jogamp.opengl.GLProfile.get(GLProfile.java:1025)
        at net.runelite.client.plugins.gpu.GpuPlugin.lambda$startUp$0(GpuPlugin.java:314)
        at net.runelite.client.plugins.gpu.GpuPlugin.invokeOnMainThread(GpuPlugin.java:1688)
        at net.runelite.client.plugins.gpu.GpuPlugin.lambda$startUp$2(GpuPlugin.java:312)
        at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
        at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:187)
        at jf.al(jf.java:3071)
        at client.av(client.java)
        at bd.sl(bd.java:377)
        at bd.run(bd.java:331)
        at java.base/java.lang.Thread.run(Thread.java:834)

```

`glxinfo`
```
name of display: :1
display: :1  screen: 0
direct rendering: Yes
server glx vendor string: NVIDIA Corporation
server glx version string: 1.4
...
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 8192 MB
    Total available memory: 8192 MB
    Currently available dedicated video memory: 7507 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce RTX 2080 SUPER/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 460.32.03
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
...
OpenGL version string: 4.6.0 NVIDIA 460.32.03
OpenGL shading language version string: 4.60 NVIDIA
```

**Comment by Sorgrum** [comment]
Honestly not sure how this was resolved. Built runelite from source in IntelliJ and GPU plugin started working from that point onward.

**Comment by Baardi** [comment]
I'm on Fedora as well. RuneLite worked fine with default drivers. After installing NVIDIA drivers, the GPU plugin wouldn't work, though. The default drivers are terrible, and not a viable option.
I had it working on both PopOS and Windows with NVIDIA drivers, it's just Fedora that is having issues

**Comment by Baardi** [comment]
... however it seems to have fixed itself after reinstalling RuneLite
