### ISSUE TITLE
Unable to copy paste from keepass2

### ISSUE THREAD

**Issue by FelixAbrahamsson** [runelite/runelite#13135]
I'm unable to copy paste email/password from keepass2 into the login fields. If I paste the password from keepass to somewhere else and copy from there I'm able to paste it successfully into the Runelite client.

**Environment**
 - OS: Ubuntu 18.04
 - RuneLite version: 1.6.38
 - Launcher version: 2.1.0

This is the console output when I try to paste:
```
2021-02-01 08:21:06 [AWT-EventQueue-0] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.NullPointerException: Failed to retrieve atom name.
	at java.desktop/sun.awt.X11.XlibWrapper.XGetAtomName(Native Method)
	at java.desktop/sun.awt.X11.XAtom.getName(Unknown Source)
	at java.desktop/sun.awt.X11.XDataTransferer.getTargetNameForAtom(Unknown Source)
	at java.desktop/sun.awt.X11.XDataTransferer.getNativeForFormat(Unknown Source)
	at java.desktop/sun.awt.datatransfer.DataTransferer.getFlavorsForFormats(Unknown Source)
	at java.desktop/sun.awt.datatransfer.SunClipboard.getData(Unknown Source)
	at net.runelite.client.plugins.loginscreen.LoginScreenPlugin.keyPressed(LoginScreenPlugin.java:217)
	at net.runelite.client.input.KeyManager.processKeyPressed(KeyManager.java:85)
	at net.runelite.client.callback.Hooks.keyPressed(Hooks.java:300)
	at bs.keyPressed(bs.java:46413)
	at java.desktop/java.awt.Component.processKeyEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(Unknown Source)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(Unknown Source)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by FelixAbrahamsson** [comment]
Should be note that this doesn't seem to happen on Windows.
