### ISSUE TITLE
Chat commands plugin NPE

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#13160]
```
2021-02-05 22:13:17 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at net.runelite.client.plugins.chatcommands.ChatCommandsPlugin.onGameTick(ChatCommandsPlugin.java:484)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:73)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:222)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:179)
	at client.qb(client.java:47834)
	at client.av(client.java)
	at bd.zq(bd.java:377)
	at bd.run(bd.java:331)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Adam-** [comment]
fixed in #13227
