### ISSUE TITLE
NullPointerException in Client.getItemDefinition()

### ISSUE THREAD

**Issue by wikiworm** [runelite/runelite#13296]
I'm seeing a `NullPointerException` in `Client.getItemDefinition()` when world hopping using a plugin that uses the `ItemManager` to respond to `onItemContainerChanged` events. I'm not sure if it's a bug in the `ItemManager` class or usage of the `ItemManager` in the plugin. 

Here is background on the issue. I developed a plugin called InventoryValue. This plugin calculates the value of a RuneLite users's inventory and displays the value on an overlay in the RuneLite UI. 

The plugin calculates the value of the users inventory by responding to subscribed events using `onItemContainerChanged` and then calculating each item in the user's inventory by using the `ItemManager`. Then, the plugin updates an overlay on the user's UI. 

This works as expected until world hopping. Here are details of the problem. As far as I understand the `ItemManager` class, it appears to be a race condition.

The `ItemManager` responds to `onGameStateChanged` by invalidating all entries in the `ItemManager.itemCompositions` cache. This causes subsequent calls to `ItemManager.getItemComposition()` to use the `ItemManager.itemCompositions.CacheLoader` which in turn calls `Client.getItemDefinition()`. Inside `Client.getItemDefinition()` a `NullPointerException` is thrown. Below is a StackTrace of the issue: 

```
2021-02-26 20:57:09 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: mr
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.LongPipeline.reduce(Unknown Source)
	at java.base/java.util.stream.LongPipeline.sum(Unknown Source)
	at com.wikiworm.inventoryvalue.InventoryValuePlugin.onItemContainerChanged(InventoryValuePlugin.java:101)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:73)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:222)
	at net.runelite.client.util.DeferredEventBus.replay(DeferredEventBus.java:69)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:185)
	at client.oo(client.java:11183)
	at client.ak(client.java)
	at bt.sj(bt.java:404)
	at bt.run(bt.java:358)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: mr
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2218)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4147)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5140)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5146)
	at net.runelite.client.game.ItemManager.getItemComposition(ItemManager.java:402)
	at net.runelite.client.game.ItemManager.getItemPrice(ItemManager.java:316)
	at net.runelite.client.game.ItemManager.getItemPrice(ItemManager.java:345)
	at net.runelite.client.game.ItemManager.getItemPrice(ItemManager.java:295)
	at com.wikiworm.inventoryvalue.InventoryValuePlugin.calculateItemValue(InventoryValuePlugin.java:127)
	at com.wikiworm.inventoryvalue.InventoryValuePlugin.lambda$onItemContainerChanged$0(InventoryValuePlugin.java:101)
	at java.base/java.util.stream.ReferencePipeline$10$1.accept(Unknown Source)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source)
	at java.base/java.util.stream.AbstractTask.compute(Unknown Source)
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: mr: null
	at kb.v(kb.java:61)
	at jq.n(jq.java:112)
	at client.mw(client.java:39096)
	at client.getItemDefinition(client.java:14129)
	at net.runelite.client.game.ItemManager$2.load(ItemManager.java:202)
	at net.runelite.client.game.ItemManager$2.load(ItemManager.java:198)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212)
	... 23 common frames omitted
Caused by: java.lang.NullPointerException: null
	at lg.z(lg.java:27)
	at ex.me(ex.java:23)
	at jq.n(jq.java:84)
	... 31 common frames omitted
```

**To Reproduce**
1) Run any plugin which uses the `ItemManager.getItemComposition` in an `onItemContainerChanged` event. 
2) World hop repeatedly.

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.7.1
 - Launcher version: 2.1.0

If this is not a bug inside the `Client.getItemDefinition()` function and rather an issue with usage of the `ItemManager` class in the plugin, please point me in the right direction and I can make the appropriate fix.

**Comment by Adam-** [comment]
It looks like you are calling getItemComposition off of the client thread. It need to be called on the client thread. If you run the client with `-ea` you would get a nicer error message telling you this.

**Comment by wikiworm** [comment]
Easy fix. Thank you.
