### ISSUE TITLE
Slayer task infobox does not update after end of task, gets "stuck" until restarting client

### ISSUE THREAD

**Issue by RSNKitt3n** [runelite/runelite#13307]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues) ✔️ 

**Describe the bug**
Slayer task infobox fails to update after the last kill of slayer task - it remains with a single kill left on task, even when checking the slayer helm or getting a new task from a slayer master. Should also note that after the infobox expiry time limit passes, when checking your task the infobox fails to show up at all. This only just recently started happening for me (last day or so).

**To Reproduce**
1. Get slayer task
2. Finish the task
3. Task counter stays at 1 for the previous task

**Expected behavior**
Task infobox should update to no longer be present when task is complete, and update to new task when a new task is obtained

**Screenshots**
![RuneLite_jiT6r7lpVz](https://user-images.githubusercontent.com/54251743/109958382-6622c400-7ca3-11eb-97dc-58207d867493.png)
![RuneLite_rTrFfW740w](https://user-images.githubusercontent.com/54251743/109958394-68851e00-7ca3-11eb-89a3-6e5a0cf8d50e.png)
![RuneLite_EajGc8p9ha](https://user-images.githubusercontent.com/54251743/109958366-628f3d00-7ca3-11eb-819d-a41d56e7b91a.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.7.2.1
 - Launcher version: 2.1.3

**Additional context**
None but please let me know if you have questions, and thanks!

**Comment by honeyhoney** [comment]
I was able to replicate this as described.

![image](https://user-images.githubusercontent.com/11140337/109961144-82455600-7ce1-11eb-9f67-deecd931de1f.png)

**Comment by Hydrox6** [comment]
I think this is a bug relating to setting an RSProfile config to null, which the slayer plugin does. If you check your logs, you might be able to see this happening.

If it is that, it should be fixed in 60b8d3370f4b50709ca931395c7531310fd2bc4f. If someone could run the master branch and confirm that, that would be great (my current task is Kree and I can't do that in a reasonable time)

**Comment by RSNKitt3n** [comment]
looks like it (?)
```
2021-03-04 04:01:44 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(Unknown Source)
	at java.base/java.util.concurrent.ConcurrentHashMap.put(Unknown Source)
	at java.base/java.util.Properties.put(Unknown Source)
	at java.base/java.util.Properties.setProperty(Unknown Source)
	at net.runelite.client.config.ConfigManager.setConfiguration(ConfigManager.java:497)
	at net.runelite.client.config.ConfigManager.setConfiguration(ConfigManager.java:525)
	at net.runelite.client.config.ConfigManager.setRSProfileConfiguration(ConfigManager.java:566)
	at net.runelite.client.plugins.slayer.SlayerPlugin.setProfileConfig(SlayerPlugin.java:319)
	at net.runelite.client.plugins.slayer.SlayerPlugin.save(SlayerPlugin.java:327)
	at net.runelite.client.plugins.slayer.SlayerPlugin.setTask(SlayerPlugin.java:758)
	at net.runelite.client.plugins.slayer.SlayerPlugin.setTask(SlayerPlugin.java:749)
	at net.runelite.client.plugins.slayer.SlayerPlugin.setTask(SlayerPlugin.java:744)
	at net.runelite.client.plugins.slayer.SlayerPlugin.onChatMessage(SlayerPlugin.java:522)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:67)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:238)
	at net.runelite.client.callback.Hooks.post(Hooks.java:169)
	at mn.v(mn.java:23765)
	at ac.n(ac.java:19)
	at client.hs(client.java:6175)
	at client.jw(client.java:2677)
	at client.ap(client.java:905)
	at bt.rq(bt.java:378)
	at bt.run(bt.java:357)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by honeyhoney** [comment]
I believe you are correct.

```2021-03-04 11:32:14 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(Unknown Source)
	at java.base/java.util.concurrent.ConcurrentHashMap.put(Unknown Source)
	at java.base/java.util.Properties.put(Unknown Source)
	at java.base/java.util.Properties.setProperty(Unknown Source)
	at net.runelite.client.config.ConfigManager.setConfiguration(ConfigManager.java:497)
	at net.runelite.client.config.ConfigManager.setConfiguration(ConfigManager.java:525)
	at net.runelite.client.config.ConfigManager.setRSProfileConfiguration(ConfigManager.java:566)
	at net.runelite.client.plugins.slayer.SlayerPlugin.setProfileConfig(SlayerPlugin.java:319)
	at net.runelite.client.plugins.slayer.SlayerPlugin.save(SlayerPlugin.java:327)
	at net.runelite.client.plugins.slayer.SlayerPlugin.setTask(SlayerPlugin.java:758)
	at net.runelite.client.plugins.slayer.SlayerPlugin.setTask(SlayerPlugin.java:749)
	at net.runelite.client.plugins.slayer.SlayerPlugin.onChatMessage(SlayerPlugin.java:545)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:67)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:238)
	at net.runelite.client.callback.Hooks.post(Hooks.java:169)
	at mn.v(mn.java:23765)
	at ac.n(ac.java:19)
	at client.hs(client.java:6175)
	at client.jw(client.java:2677)
	at client.ap(client.java:905)
	at bt.rq(bt.java:378)
	at bt.run(bt.java:357)
	at java.base/java.lang.Thread.run(Unknown Source)
```

I'll be running the master branch and update you if https://github.com/runelite/runelite/commit/60b8d3370f4b50709ca931395c7531310fd2bc4f resolves the issue.

**Comment by honeyhoney** [comment]
https://github.com/runelite/runelite/commit/60b8d3370f4b50709ca931395c7531310fd2bc4f appears to have resolved the issue.

![image](https://user-images.githubusercontent.com/11140337/109970034-80cd5b00-7cec-11eb-8611-3f6027531f0d.png)

**Comment by Hydrox6** [comment]
Brilliant. So, it will be fixed whenever the client next updates, which should be at the very least next Wednesday, though I imagine we might do a release earlier to fix this since it's so big

**Comment by RSNKitt3n** [comment]
thanks dudes :)
