### ISSUE TITLE
Runelite 64bit does not launch on Windows 10: UnsatisfiedLinkError related to javaaccessbridge.dll

### ISSUE THREAD

**Issue by AuroraLS3** [runelite/runelite#13520]
**Describe the bug**

Upon installing RuneLite with the 64 bit installer for Windows, with the open runelite tickbox checked, RuneLite crashed silently.

**To Reproduce**
1. Go to https://github.com/runelite/launcher/releases/download/2.1.6/RuneLiteSetup.exe and download 64 bit installer
2. Complete installation with defaults by clicking on Next until the program is installed
3. Tick the Open Runelite box
4. Click Finish
5. Runelite process starts but dies quickly afterwards.

**Expected behavior**

Runelite should open

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10 Home 20H2 build 19042.928
 - RuneLite version: 2.1.6
 - Launcher version: unknown

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

```
2021-04-24 12:48:38 [main] ERROR net.runelite.launcher.Launcher - Failure during startup
java.lang.UnsatisfiedLinkError: S:\Games\Installed\RuneLite\jre\bin\javaaccessbridge.dll: %1 ei ole kelvollinen Win32-sovellus // translated: is not valid Win32-application
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(Unknown Source)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.base/java.lang.System.loadLibrary(Unknown Source)
	at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge$3.run(Unknown Source)
	at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge$3.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge.<clinit>(Unknown Source)
	at jdk.accessibility/com.sun.java.accessibility.internal.ProviderImpl.activate(Unknown Source)
	at java.desktop/java.awt.Toolkit.lambda$loadAssistiveTechnologies$0(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.Toolkit.loadAssistiveTechnologies(Unknown Source)
	at java.desktop/java.awt.Toolkit.getDefaultToolkit(Unknown Source)
	at java.desktop/java.awt.EventQueue.invokeAndWait(Unknown Source)
	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(Unknown Source)
	at net.runelite.launcher.SplashScreen.init(SplashScreen.java:161)
	at net.runelite.launcher.Launcher.main(Launcher.java:163)
```

Upon following instructions here https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client#unsatisfiedlinkerror-javaaccessbridge-32dll-cant-find-dependent-libraries the issue was resolved.

It might be worth it to add an error message for the user.

**Comment by Adam-** [comment]
We've identified this to be an issue with the launcher, and think it is fixed in https://github.com/runelite/launcher/commit/fab648ce1222dad94c1df0cfb99a6f97448db467

This is the same issue as: #12384 #11633 #11462 #10825 #9798
