### ISSUE TITLE
Plugin Hub Plugins not working

### ISSUE THREAD

**Issue by dan-drews** [runelite/runelite#13657]
**Describe the bug**
None of my pre-installed plugin-hub plugins are launching on load of runelite. Additionally, when I attempt to access the plugin hub to install them, or simply browse other plugins, I receive the error "Downloading the plugin manifest failed". I have checked with members of my CC, and none of them are experiencing this issue, so it may be isolated to my setup.

I have rebooted, and reinstalled runelite multiple times and I am still encountering the issue.

**To Reproduce**
1. Go to 'Configuration'
2. Click on 'Plugin Hub'
4. See error, and no plugins load

**Expected behavior**
I would expect this to work as it typically has. When I open runelite, my existing hub plugins are present, and I can access the plugin hub without error and see a list of available plugins to install.

**Screenshots**
![image](https://user-images.githubusercontent.com/2341007/120050087-c0e96480-bfe1-11eb-9172-e6a4a095de5b.png)

**Environment (please complete the following information):**
 - OS: Windows 10 build 19042.928
 - RuneLite version: 1.7.10
 - Launcher version: 2.1.7

**Additional context**
I typically launch runelite via command prompt for GPU mode off with the following command. However, this error happens whether I launch with that or not
`start "" "%localappdata%/runelite/jre/bin/java.exe" -jar "%localappdata%/runelite/runelite.jar" --mode=OFF`

Because the log is returning 404 errors, and again, because it seems to be only happening on my machine, none of my clan-members' machines, I attempted to see if it was a routing issue, so I connected via VPN. The issue persisted, which tells me it's not an issue with my ISP

**LOG**
2021-05-28 18:24:58 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.7.10 (launcher version 2.1.7) starting up, args: none
2021-05-28 18:25:00 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2021-05-28 18:25:00 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2021-05-28 18:25:00 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 1302553862.148
2021-05-28 18:25:01 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2021-05-28 18:25:01 [RuneLite] ERROR n.r.c.e.ExternalPluginManager - Unable to download external plugins
java.io.IOException: Non-OK response code: 404
	at net.runelite.client.externalplugins.ExternalPluginClient.downloadManifest(ExternalPluginClient.java:82)
	at net.runelite.client.externalplugins.ExternalPluginManager.refreshPlugins(ExternalPluginManager.java:178)
	at net.runelite.client.externalplugins.ExternalPluginManager.loadExternalPlugins(ExternalPluginManager.java:115)
	at net.runelite.client.RuneLite.start(RuneLite.java:295)
	at net.runelite.client.RuneLite.main(RuneLite.java:250)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.runelite.launcher.ReflectionLauncher$1.run(ReflectionLauncher.java:63)
2021-05-28 18:25:02 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2021-05-28 18:25:03 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 4516ms. Uptime: 6792ms
2021-05-28 18:25:03 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,538,240,1484x931,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1484x931,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@1d36a11,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2021-05-28 18:25:04 [pool-3-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user ***Redacted***.
2021-05-28 18:25:27 [pool-3-thread-1] ERROR n.r.c.plugins.config.PluginHubPanel - 
java.io.IOException: Non-OK response code: 404
	at net.runelite.client.externalplugins.ExternalPluginClient.downloadManifest(ExternalPluginClient.java:82)
	at net.runelite.client.plugins.config.PluginHubPanel.lambda$reloadPluginList$3(PluginHubPanel.java:508)
	at net.runelite.client.util.RunnableExceptionLogger.run(RunnableExceptionLogger.java:41)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Nightfirecat** [comment]
Delete your `%userprofile%/.runelite/cache/okhttp` folder or run this command in command prompt run as Administrator:
```
rmdir /s "%userprofile%\.runelite\cache\okhttp"
```

**Comment by Equintox** [comment]
I have the same issue and for me it does not work by removing the cache directory.

I Built runelite from source and everything seems to be working beside the external plugin hub. Any idea what else could cause the problem?

```
java.io.IOException: Non-OK response code: 404
	at net.runelite.client.externalplugins.ExternalPluginClient.downloadManifest(ExternalPluginClient.java:83)
	at net.runelite.client.plugins.config.PluginHubPanel.lambda$reloadPluginList$3(PluginHubPanel.java:508)
	at net.runelite.client.util.RunnableExceptionLogger.run(RunnableExceptionLogger.java:41)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by zacharyrperales** [comment]
> I have the same issue and for me it does not work by removing the cache directory.
> 
> I Built runelite from source and everything seems to be working beside the external plugin hub. Any idea what else could cause the problem?
> 
> ```
> java.io.IOException: Non-OK response code: 404
> 	at net.runelite.client.externalplugins.ExternalPluginClient.downloadManifest(ExternalPluginClient.java:83)
> 	at net.runelite.client.plugins.config.PluginHubPanel.lambda$reloadPluginList$3(PluginHubPanel.java:508)
> 	at net.runelite.client.util.RunnableExceptionLogger.run(RunnableExceptionLogger.java:41)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
> 	at java.base/java.lang.Thread.run(Thread.java:831)
> ```
> 
> Edit: My bad. After searching again i found in the docs that the pluginhub is only working in the release version.
> 
> ```
> The Plugin Hub only works on the Release versions of RuneLite. If you are running the Release and it's still not working, make sure nothing is blocking RuneLite from accessing
> ```
> 
> Guess I have to find a way to add the specific plugin otherwise for testing purposes.

You can actually manually search for the latest version of a publicly accessible manifest.js file here:
https://repo.runelite.net/plugins/

Currently that would be version 1.8.33.1:
https://repo.runelite.net/plugins/1.8.33.1/manifest.js

The link returning the HTTP 404 error is built here in the "downloadManifest()" method in the "ExternalPluginClient" class ( client/src/main/java/net/runelite/client/externalplugins/ ):

`
HttpUrl manifest = RuneLiteProperties.getPluginHubBase().newBuilder().addPathSegments("manifest.js").build();
`

We need to modify the path segment containing the version in order to create a static link. This can be done by changing
`runelite.pluginhub.version=${project.version}` to `runelite.pluginhub.version=VERSION_NUMBER_YOU_FOUND_EARLIER` in the "runelite.properties" file ( runelite/runelite-client/src/main/resources/net/runelite/client/ ).

![image](https://user-images.githubusercontent.com/60770908/191203832-50f22b13-f054-420f-b23c-b2c045d440ea.png)

Note: I added the logging message that you see above about the link modification in the "downloadManifest()" method.

**Comment by Lyles-kauff** [comment]
> Delete your `%userprofile%/.runelite/cache/okhttp` folder or run this command in command prompt run as Administrator:
> 
> ```
> rmdir /s "%userprofile%\.runelite\cache\okhttp"
> ```

Please can you elaborate? I am plagued with this issue.

I see the following in ~,
/.runelite $ ls -a
.   cache     jagexcache                   logs       random.dat   session
..  icon.png  jagex_cl_oldschool_LIVE.dat  profiles2  screenshots

**Comment by Felanbird** [comment]
![image](https://github.com/runelite/runelite/assets/41973452/48fcd762-af8d-477a-9209-a9ef210f0efd)

Delete the okhttp folder inside the cache folder
