### ISSUE TITLE
Transparent client on RuneLite

### ISSUE THREAD

**Issue by MangeMoiLkraken** [runelite/runelite#13681]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Transparent screen

**To Reproduce**
1. Open RuneLite

**Expected behavior**
Transparent screen.. but i can navigate through the menu option

**Screenshots**
![image](https://user-images.githubusercontent.com/85264441/120570518-54f26c00-c3e6-11eb-934c-123bf07b8816.png)

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.7.10
 - Launcher version: latest 2.1.7

**Additional context**
2021-06-02 20:55:11 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.7.10 (launcher version 2.1.7) starting up, args: none
2021-06-02 20:55:17 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 1302553862.148
2021-06-02 20:55:17 [RuneLite] INFO  n.r.client.config.ConfigManager - creating new salt as there is no existing one WcuksfiapFjJBs0Uo6Nu
2021-06-02 20:55:17 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2021-06-02 20:55:17 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2021-06-02 20:55:18 [AWT-EventQueue-0] ERROR client-patch - Game crash: null
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at nd.my(nd.java:240)
	at ac.v(ac.java:56)
	at client.init(client.java:837)
	at net.runelite.client.ui.ClientPanel.<init>(ClientPanel.java:53)
	at net.runelite.client.ui.ClientUI.lambda$init$5(ClientUI.java:365)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
2021-06-02 20:55:18 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2021-06-02 20:55:18 [Client] ERROR client-patch - Game crash: null
java.lang.NullPointerException: null
	at lh.cg(lh.java:21)
	at jp.p(jp.java:93)
	at client.fz(client.java:1286)
	at client.o(client.java:930)
	at af.xl(af.java:369)
	at af.run(af.java:348)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-06-02 20:55:19 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 7832ms. Uptime: 11705ms
2021-06-02 20:55:19 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,556,253,809x534,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@49afd4fe,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2021-06-02 20:55:20 [pool-3-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user GOK Kraken.
2021-06-02 20:56:52 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.7.10 (launcher version 2.1.7) starting up, args: none
2021-06-02 20:56:54 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2021-06-02 20:56:54 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2021-06-02 20:56:55 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 1302553862.148
2021-06-02 20:56:55 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2021-06-02 20:56:55 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2021-06-02 20:56:56 [AWT-EventQueue-0] ERROR client-patch - Game crash: null
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at nd.my(nd.java:240)
	at ac.v(ac.java:56)
	at client.init(client.java:837)
	at net.runelite.client.ui.ClientPanel.<init>(ClientPanel.java:53)
	at net.runelite.client.ui.ClientUI.lambda$init$5(ClientUI.java:365)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
2021-06-02 20:56:56 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2021-06-02 20:56:57 [Client] ERROR client-patch - Game crash: null
java.lang.NullPointerException: null
	at lh.cg(lh.java:21)
	at jp.p(jp.java:93)
	at client.fz(client.java:1286)
	at client.o(client.java:930)
	at af.xl(af.java:369)
	at af.run(af.java:348)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-06-02 20:56:57 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 4945ms. Uptime: 6607ms
2021-06-02 20:56:58 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,556,253,809x534,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@4fefb9e4,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2021-06-02 20:56:58 [pool-3-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user GOK Kraken.
2021-06-02 21:00:02 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.7.10 (launcher version 2.1.7) starting up, args: none
2021-06-02 21:00:03 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2021-06-02 21:00:04 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2021-06-02 21:00:04 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 1302553862.148
2021-06-02 21:00:04 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2021-06-02 21:00:05 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2021-06-02 21:00:05 [AWT-EventQueue-0] ERROR client-patch - Game crash: null
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at nd.my(nd.java:240)
	at ac.v(ac.java:56)
	at client.init(client.java:837)
	at net.runelite.client.ui.ClientPanel.<init>(ClientPanel.java:53)
	at net.runelite.client.ui.ClientUI.lambda$init$5(ClientUI.java:365)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
2021-06-02 21:00:05 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2021-06-02 21:00:06 [Client] ERROR client-patch - Game crash: null
java.lang.NullPointerException: null
	at lh.cg(lh.java:21)
	at jp.p(jp.java:93)
	at client.fz(client.java:1286)
	at client.o(client.java:930)
	at af.xl(af.java:369)
	at af.run(af.java:348)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-06-02 21:00:06 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 3987ms. Uptime: 5884ms
2021-06-02 21:00:06 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,556,253,809x534,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@13b5365f,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2021-06-02 21:00:07 [pool-3-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user GOK Kraken.
2021-06-02 21:01:41 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.7.10 (launcher version 2.1.7) starting up, args: none
2021-06-02 21:01:42 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2021-06-02 21:01:43 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2021-06-02 21:01:43 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 1302553862.148
2021-06-02 21:01:43 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2021-06-02 21:01:43 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2021-06-02 21:01:44 [AWT-EventQueue-0] ERROR client-patch - Game crash: null
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at nd.my(nd.java:240)
	at ac.v(ac.java:56)
	at client.init(client.java:837)
	at net.runelite.client.ui.ClientPanel.<init>(ClientPanel.java:53)
	at net.runelite.client.ui.ClientUI.lambda$init$5(ClientUI.java:365)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
2021-06-02 21:01:44 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2021-06-02 21:01:45 [Client] ERROR client-patch - Game crash: null
java.lang.NullPointerException: null
	at lh.cg(lh.java:21)
	at jp.p(jp.java:93)
	at client.fz(client.java:1286)
	at client.o(client.java:930)
	at af.xl(af.java:369)
	at af.run(af.java:348)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-06-02 21:01:45 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 4343ms. Uptime: 5993ms
2021-06-02 21:01:46 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,556,253,809x534,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@660798f7,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2021-06-02 21:01:46 [pool-3-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user GOK Kraken.

**Comment by Adam-** [comment]
HDOS corrupts the `jagex_cl_oldschool_LIVE.dat` file in your userhome folder when it is run, which prevents the vanilla client from working. Delete this file and then stop using HDOS.
