### ISSUE TITLE
Force logouts

### ISSUE THREAD

**Issue by lizcos** [runelite/runelite#13714]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Getting force logged out from time to time, most of the times just in beginning of Chambers of xeric.

**Environment (please complete the following information):**
Windows
1.7.11.2 (launcher version 2.1.7)

**Additional context**
Logs attached, latest force logout was around 20:50
[launcher.log](https://github.com/runelite/runelite/files/6626316/launcher.log)

[client.log](https://github.com/runelite/runelite/files/6626312/client.log)

**Comment by LlemonDuck** [comment]
I'll just pick apart the log for whoever is more qualified, since it's a bit spammy. There are two relevant client log errors:

The first is this:
```
2021-06-09 20:52:37 [Client] ERROR client-patch - Game crash: 16,87,26,23,11888,2026,0,0,0,0,0,0,0,2,99,0,0,1,121,-15,3,79,-43,3,0,23,0,-1,0,
java.lang.RuntimeException: 
	at x.jy(x.java:41)
	at client.hh(client.java:6827)
	at client.iq(client.java:2725)
	at client.o(client.java:999)
	at af.ru(af.java:369)
	at af.run(af.java:348)
	at java.base/java.lang.Thread.run(Unknown Source)
```
and the second is this, which happens repeatedly after the above one triggers:
```
2021-06-09 20:55:05 [Client] ERROR client-patch - Game crash: 2103 2101 2100 4018
java.lang.ArithmeticException: / by zero
	at lb.al(lb.java:2903)
	at lo.f(lo.java:452)
	at bg.n(bg.java:32433)
	at ds.v(ds.java:106)
	at bo.jr(bo.java:10688)
	at ct.jm(ct.java:10660)
	at bo.jr(bo.java:10670)
	at ct.jm(ct.java:10660)
	at bo.jr(bo.java:10670)
	at ct.jm(ct.java:10660)
	at ao.kx(ao.java:11089)
	at client.fg(client.java:2403)
	at client.o(client.java:996)
	at af.ru(af.java:369)
	at af.run(af.java:348)
	at java.base/java.lang.Thread.run(Unknown Source)
``` 
at first glance it seems the second is likely caused by the first, but I'm not knowledgeable enough on the client internals to say for certain.

@Blackberry0Pie I'm also gonna ping you on this, not because your plugin is responsible for the crash, but it spams the log a lot with an NPE:
```
2021-06-09 18:33:56 [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
	at bbp.chambers.CoxScouterExternalOverlay.render(CoxScouterExternalOverlay.java:114)
	at net.runelite.client.ui.overlay.OverlayRenderer.safeRender(OverlayRenderer.java:747)
	...
```

**Comment by LlemonDuck** [comment]
@lizcos Can you try running RL in safe mode and report back if you still have these crashes?

Windows: Run "%localappdata%\runelite\runelite.exe" --clientargs --safe-mode in command prompt
Mac: Run /Applications/RuneLite.app/Contents/MacOS/RuneLite --clientargs --safe-mode in terminal

Also feel free to hop in the [RuneLite Discord](https://runelite.net/discord) for more responsive help.

**Comment by lizcos** [comment]
Yeah, havn't kicked me out in safemode. Some of the plugins does it?

**Comment by Nightfirecat** [comment]
If you're not experiencing disconnects/client crashes in safe mode, then yes, one of your installed hub plugins is causing it.
