### ISSUE TITLE
Runelite freezes randomly

### ISSUE THREAD

**Issue by GGeasyL2P** [runelite/runelite#14071]
**Describe the bug**
I have an issue where Runelite freezes. It mostly happens when I have sites open using relatively high resources (Twitch/YouTube). Swapping window focus fixes it most of the time, if I don't do this the game will stay frozen indefinitely. When the game unfreezes, it acts as if I just regained connection with: multiple hitsplats appearing, multiple sounds/animations playing at once. 

Bug sounds similar to https://github.com/runelite/runelite/issues/12669

**To Reproduce**

Reproduction is difficult, it happens roughly every 2-3 hours.

**Expected behavior**
Not freeze

**Screenshots**

https://streamable.com/qcagyx

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.7.21.1
 - Launcher version: 2.1.7

**Additional context**

**Logs**

Freeze happened at roughly 00:28, as far as I can tell nothing is logged in here.

2021-08-26 00:32:06 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at net.runelite.client.plugins.npcunaggroarea.NpcAggroAreaPlugin.isNpcMatch(NpcAggroAreaPlugin.java:269)
	at net.runelite.client.plugins.npcunaggroarea.NpcAggroAreaPlugin.checkAreaNpcs(NpcAggroAreaPlugin.java:297)
	at net.runelite.client.plugins.npcunaggroarea.NpcAggroAreaPlugin.recheckActive(NpcAggroAreaPlugin.java:310)
	at net.runelite.client.plugins.npcunaggroarea.NpcAggroAreaPlugin.onGameStateChanged(NpcAggroAreaPlugin.java:473)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:66)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:219)
	at net.runelite.client.callback.Hooks.post(Hooks.java:169)
	at client.bk(client.java:6105)
	at cc.ed(cc.java:2053)
	at bo.fs(bo.java:3426)
	at client.el(client.java:3270)
	at client.f(client.java:1894)
	at at.dr(at.java:380)
	at at.run(at.java:359)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-08-26 12:02:58 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.7.21.1 (launcher version 2.1.7) starting up, args: none

**Comment by Nightfirecat** [comment]
Since this issue is lacking information and has not been updated in some time, I am closing it.

**Comment by Jarrianm** [comment]
This issue is closed however Im experiencing the same thing all the time now. Just like original post said , its hard to catch it when its happen but its gotten me killed mid raid more than once . I think this should be opened and looked into more I haven't been able to find any video explaining what's been happening to me until I stumbled across this. Has there been any other request made with this issue?

**Comment by Nightfirecat** [comment]
Uploading your `client.log` and/or `jvm_crash_pid` log files from the day(s) where you encountered this issue may help us diagnose it. Otherwise, that is not enough information to be useful.

**Comment by Jarrianm** [comment]
how do I access those files?

**Comment by Jarrianm** [comment]
Issue just happened within the first 60 seconds of logging in

**Comment by Nightfirecat** [comment]
To find the logs, you can do one of the following:
- If your client failed to open, click the Open logs folder button.
- Open the screenshot directory by right-clicking 📷 Camera button, navigate 1 directory up, then open logs folder.
- Navigate to %userprofile%\.runelite\logs on Windows or $HOME/.runelite/logs on Linux and macOS.

**Comment by Jarrianm** [comment]
**Client.log**:

```
2022-11-11 01:34:48 [Client] ERROR client-patch - Client error: null
java.lang.RuntimeException: unable to SwapBuffers (6)
	at net.runelite.rlawt.AWTContext.swapBuffers(Native Method)
	at net.runelite.client.plugins.gpu.GpuPlugin.draw(GpuPlugin.java:1279)
	at ae.r(ae.java:10766)
	at ae.run(ae.java:370)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-11-11 16:46:45 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.9.3 (launcher version 2.5.0) starting up, args: none
2022-11-11 16:46:45 [RuneLite] INFO  net.runelite.client.RuneLite - Java VM arguments: -XX:+DisableAttachMechanism -Drunelite.launcher.nojvm=true -Drunelite.launcher.blacklistedDlls=RTSSHooks.dll,RTSSHooks64.dll,NahimicOSD.dll,NahimicMSIOSD.dll,Nahimic2OSD.dll,Nahimic2DevProps.dll,k_fps32.dll,k_fps64.dll,SS2DevProps.dll,SS2OSD.dll -Xmx512m -Xss2m -XX:CompileThreshold=1500 -XX:ErrorFile=C:\Users\madem\.runelite\logs\jvm_crash_pid_%p.log
2022-11-11 16:46:46 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2022-11-11 16:46:47 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2022-11-11 16:46:47 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 3328007803.299
2022-11-11 16:46:48 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2022-11-11 16:46:48 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "maxhitplugin" version "23d328cb" commit "23d328cb160dd471431fd88fbb8268b8f01f01a2"
2022-11-11 16:46:48 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "runewatch" version "2.2.1" commit "2573e1d9fd6d47c69cf5bf3ef1457d0c9969cbfc"
2022-11-11 16:46:48 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "quest-helper" version "3.1.4" commit "8dd29c3c61a0b8003a19294da11f4bba30269c1c"
2022-11-11 16:46:48 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "117hd" version "1.2.4" commit "d5b2409f0fb46dcd70011c6280993e359a8f874f"
2022-11-11 16:46:48 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "guardians-of-the-rift-helper" version "1.02" commit "448ce9e65384d0135b3dd77dcc57b4149898a435"
2022-11-11 16:46:48 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "twitch-live-loadout" version "1.1.0" commit "586f9f87dd9b55063e8a9899456946912b1558aa"
2022-11-11 16:46:48 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "tombs-of-amascut" version "2.2.3" commit "56534afe0c965f21c4d6a2ceae8f8d5490dc2b76"
2022-11-11 16:46:49 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2022-11-11 16:46:51 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 5840ms. Uptime: 8155ms
2022-11-11 16:46:51 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,1,2563x1390,invalid,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,2563x1390,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@66881b61,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2022-11-11 16:46:51 [Client] INFO  n.r.client.plugins.gpu.GpuPlugin - Using device: NVIDIA GeForce RTX 3080/PCIe/SSE2
2022-11-11 16:46:51 [Client] INFO  n.r.client.plugins.gpu.GpuPlugin - Using driver: 4.6.0 NVIDIA 516.94

```
Launcher LOG:
```
2022-11-11 16:46:43 [main] INFO  net.runelite.launcher.Launcher - RuneLite Launcher version 2.5.0
2022-11-11 16:46:43 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to DIRECTDRAW
2022-11-11 16:46:45 [main] INFO  net.runelite.launcher.Launcher - Verified hash of client-1.9.3.jar
2022-11-11 16:46:45 [main] INFO  net.runelite.launcher.Launcher - Verified hash of slf4j-api-1.7.25.jar
2022-11-11 16:46:45 [main] INFO  net.runelite.launcher.Launcher - Verified hash of logback-classic-1.2.9.jar
2022-11-11 16:46:45 [main] INFO  net.runelite.launcher.Launcher - Verified hash of logback-core-1.2.9.jar
2022-11-11 16:46:45 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jopt-simple-5.0.1.jar
2022-11-11 16:46:45 [main] INFO  net.runelite.launcher.Launcher - Verified hash of guava-23.2-jre.jar
2022-11-11 16:46:45 [main] INFO  net.runelite.launcher.Launcher - Verified hash of guice-4.1.0-no_aop.jar
2022-11-11 16:46:45 [main] INFO  net.runelite.launcher.Launcher - Verified hash of javax.inject-1.jar
2022-11-11 16:46:45 [main] INFO  net.runelite.launcher.Launcher - Verified hash of aopalliance-1.0.jar
2022-11-11 16:46:45 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gson-2.8.5.jar
2022-11-11 16:46:45 [main] INFO  net.runelite.launcher.Launcher - Verified hash of substance-8.0.02.jar
2022-11-11 16:46:45 [main] INFO  net.runelite.launcher.Launcher - Verified hash of trident-1.5.00.jar
2022-11-11 16:46:45 [main] INFO  net.runelite.launcher.Launcher - Verified hash of commons-text-1.2.jar
2022-11-11 16:46:45 [main] INFO  net.runelite.launcher.Launcher - Verified hash of commons-lang3-3.7.jar
2022-11-11 16:46:45 [main] INFO  net.runelite.launcher.Launcher - Verified hash of archive-patcher-applier-1.2.jar
2022-11-11 16:46:45 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jna-5.9.0.jar
2022-11-11 16:46:45 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jna-platform-5.9.0.jar
2022-11-11 16:46:45 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jsr305-3.0.2.jar
2022-11-11 16:46:45 [main] INFO  net.runelite.launcher.Launcher - Verified hash of protobuf-javalite-3.21.1.jar
2022-11-11 16:46:45 [main] INFO  net.runelite.launcher.Launcher - Verified hash of rlawt-1.3.jar
2022-11-11 16:46:45 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jocl-1.0.jar
2022-11-11 16:46:45 [main] INFO  net.runelite.launcher.Launcher - Verified hash of lwjgl-3.3.1.jar
2022-11-11 16:46:45 [main] INFO  net.runelite.launcher.Launcher - Verified hash of lwjgl-3.3.1-natives-windows.jar
2022-11-11 16:46:45 [main] INFO  net.runelite.launcher.Launcher - Verified hash of lwjgl-opengl-3.3.1.jar
2022-11-11 16:46:45 [main] INFO  net.runelite.launcher.Launcher - Verified hash of lwjgl-opengl-3.3.1-natives-windows.jar
2022-11-11 16:46:45 [main] INFO  net.runelite.launcher.Launcher - Verified hash of client-patch-1.9.3.jar
2022-11-11 16:46:45 [main] INFO  net.runelite.launcher.Launcher - Verified hash of http-api-1.1.7.jar
2022-11-11 16:46:45 [main] INFO  net.runelite.launcher.Launcher - Verified hash of okhttp-3.14.9.jar
2022-11-11 16:46:45 [main] INFO  net.runelite.launcher.Launcher - Verified hash of okio-1.17.2.jar
2022-11-11 16:46:45 [main] INFO  net.runelite.launcher.Launcher - Verified hash of discord-1.4.jar
2022-11-11 16:46:45 [main] INFO  net.runelite.launcher.Launcher - Verified hash of runelite-api-1.9.3-runtime.jar
```
These are what i have there for today 11/11/2022

**Comment by Nightfirecat** [comment]
Looks like a GPU crash; this is likely due to your graphics drivers and something we can't fix.

**Comment by Jarrianm** [comment]
Strange I haven't updated to the recent NVIDIA one and Im using a 3080, is there any underlying compatibility issues with anything such as g-sync being on. Thanks for actually trying to help me out this has been frustrating me for months HD client or with GPU mode on I mean this happened after i typed in my bank pin. Any troubleshooting tips ?

**Comment by Nightfirecat** [comment]
I'd strongly recommend checking in [our Discord server's](https://runelite.net/discord) `#support` channel, as we'll be able to help you more directly there.
