### ISSUE TITLE
RuneLite freezing after connecting external HDMI on Mac OS with GPU plugin enabled

### ISSUE THREAD

**Issue by miikaj1** [runelite/runelite#14431]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

Recreating issue from comment on #12153. This seems similar to #12390, but I believe it is a different issue because this issue only occurs with GPU plugin on. #12390 
occurs either way: ["this occurs with the RL GPU turned on and off"](https://github.com/runelite/runelite/issues/12930#issuecomment-760628558). This issue should not be marked as a duplicate because although the trigger (plugging HDMI cable to external monitor) is the same, the cause is likely different. There are other issues of people reporting this problem (for example #12153 but these all have been closed as duplicates). I do not see any error logs in any of these previous issues. Adding below.

I would like to clarify that the game freezes but the rest of the client (settings, etc.) work fine. This issue does not occur when _disconnecting_ external monitor. It also does not make a difference if the client is changing displays or staying on the same display. I think the below error log should be sufficient to not close this issue, but I would also be happy to collect more debugging information as this issue can be reliably reproduced (enable GPU plugin and connect external HDMI display on Mac OS). 

**Describe the bug**
Game freezes on Mac OS when GPU plugin is turned on and external monitor is connected.

**To Reproduce**
1. Open RuneLite on Mac OS
2. Turn on GPU plugin
3. Connect HDMI cable to external monitor

**Expected behavior**
Game should continue to run once external monitor is connected.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: macOS
 - RuneLite version: 1.8.4
 - Launcher version: 2.2.0
 
**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

Log which occurs after connecting external HDMI:
```
2021-11-29 21:12:51 [AppKit Thread] INFO  n.r.client.plugins.gpu.GpuPlugin - Using device: Apple M1 Max
2021-11-29 21:12:51 [AppKit Thread] INFO  n.r.client.plugins.gpu.GpuPlugin - Using driver: 2.1 Metal - 76.1
2021-11-29 21:13:09 [Client] ERROR client-patch - Client error: null
java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "java.nio.ByteBuffer.asIntBuffer()" because the return value of "com.jogamp.opengl.GL4.glMapBuffer(int, int)" is null
	at jogamp.nativewindow.macosx.OSXUtil.RunOnMainThread(OSXUtil.java:324)
	at net.runelite.client.plugins.gpu.GpuPlugin.invokeOnMainThread(GpuPlugin.java:1764)
	at net.runelite.client.plugins.gpu.GpuPlugin.draw(GpuPlugin.java:1077)
	at ai.g(ai.java:64853)
	at ai.run(ai.java:368)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "java.nio.ByteBuffer.asIntBuffer()" because the return value of "com.jogamp.opengl.GL4.glMapBuffer(int, int)" is null
	at net.runelite.client.plugins.gpu.GpuPlugin.prepareInterfaceTexture(GpuPlugin.java:1113)
	at net.runelite.client.plugins.gpu.GpuPlugin.drawFrame(GpuPlugin.java:1134)
	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$draw$8(GpuPlugin.java:1077)
	at com.jogamp.common.util.RunnableTask.run(RunnableTask.java:143)
error_game_crash
```

**Comment by abextm** [comment]
duplicate #12930
