### ISSUE TITLE
Chat Filter plugin NPE

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#14438]
Found in a user's log from `#support`, I don't know where they were or what they were doing ingame to cause this behavior.

```
java.lang.NullPointerException: null
	at net.runelite.client.plugins.chatfilter.ChatFilterPlugin.shouldFilterPlayerMessage(ChatFilterPlugin.java:287)
	at net.runelite.client.plugins.chatfilter.ChatFilterPlugin.onOverheadTextChanged(ChatFilterPlugin.java:250)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:169)
	at ct.zy(ct.java:34619)
	at jk.w(jk.java:223)
	at client.ho(client.java:7122)
	at client.en(client.java:3304)
	at client.h(client.java:1540)
	at ai.q(ai.java:387)
	at ai.run(ai.java:366)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by Nightfirecat** [comment]
I'm confirming I'm still seeing this exception in my logs every now and then. Still not sure what causes it though.

**Comment by iProdigy** [comment]
Local player can be null while loading into the world (before LOGGED_IN), so NPE may reflect (unlucky) timing of text event before completely logged in
