### ISSUE TITLE
My runelite client crashes randomly 

### ISSUE THREAD

**Issue by DanielGlez1994** [runelite/runelite#14446]
Around 2 weeks ago my client started crashing randomly along the day, it doesnt close nor the screen goes black it just stop working like the image just paralyzes, cant click anywhere and I need to close the client in order to reset it but also it seems that my account doesnt keep logged in once this happens because I dont get the message you normally get of "your account hasnt logged off from your last session". I did some research but anything that ive done so far has worked Ill appreciate if someone could help me.

This is the last thing that appears on my client log before the crash happened.

2021-12-06 01:02:07 [Client] INFO  c.f.controller.FlippingPlugin - account is an ironman, not adding it to the cache
2021-12-06 01:04:30 [pool-3-thread-1] WARN  net.runelite.client.task.Scheduler - error during scheduled task
java.util.ConcurrentModificationException: null
	at java.base/java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.base/java.util.HashMap$ValueIterator.next(Unknown Source)
	at java.base/java.util.AbstractCollection.toArray(Unknown Source)
	at java.base/java.util.ArrayList.addAll(Unknown Source)
	at com.twitchliveloadout.Fight.getAllSessions(Fight.java:336)
	at com.twitchliveloadout.Fight.calculateTotalSession(Fight.java:227)
	at com.twitchliveloadout.FightStateManager.getFightStatisticsState(FightStateManager.java:973)
	at com.twitchliveloadout.TwitchLiveLoadoutPlugin.syncFightStatisticsState(TwitchLiveLoadoutPlugin.java:284)
	at net.runelite.client.task.Scheduler.run(Scheduler.java:101)
	at net.runelite.client.task.Scheduler.lambda$tick$0(Scheduler.java:84)
	at net.runelite.client.util.RunnableExceptionLogger.run(RunnableExceptionLogger.java:41)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Screenshots**

This is the last frame I got before the crash and it keeps that way until I close the client.

![image](https://user-images.githubusercontent.com/95609434/144804375-3f4fa4a9-647b-4bfe-8bce-374e2e8f8791.png)

**Comment by wayne-li2** [comment]
It looks like the crash is caused by the Twitch Live Loadout Plugin. This is an external plugin not maintained by Runelite.
```
at com.twitchliveloadout.Fight.getAllSessions(Fight.java:336)
at com.twitchliveloadout.Fight.calculateTotalSession(Fight.java:227)
at com.twitchliveloadout.FightStateManager.getFightStatisticsState(FightStateManager.java:973)
at com.twitchliveloadout.TwitchLiveLoadoutPlugin.syncFightStatisticsState(TwitchLiveLoadoutPlugin.java:284)
```
