### ISSUE TITLE
Computer crashing Ubuntu 21.10 when reopening Runelite

### ISSUE THREAD

**Issue by rilesdun** [runelite/runelite#14466]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Runelite runs fine on Ubuntu 21.10, but after minizing the client, and reopening; entire computer crashes. Spotify continues playing, but mouse is dead and hard reset is required

**To Reproduce**
1. Download 64bit deb appimage
2. Run & play runescape for 5~ minutes
3. Minimze client, and try and reopen

**Expected behavior**
Client to reopen, and log in again; works for the first run, until minimized.

**Environment (please complete the following information):**
 - OS: [Ubuntu 21.04]
- Latest deb release as of dec 10 2021

**Additional context**; Seperated error logs with a few spaces below, also removed some self identifying info
Client logs:
21-12-09 17:30:53 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.8.6 (launcher version 2.2.0) starting up, args: none
2021-12-09 17:30:58 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 1867715507.343
2021-12-09 17:30:58 [RuneLite] INFO  n.r.client.config.ConfigManager - creating new salt as there is no existing one 
2021-12-09 17:30:58 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2021-12-09 17:30:59 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2021-12-09 17:30:59 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2021-12-09 17:31:00 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 7554ms. Uptime: 20007ms
2021-12-09 17:31:00 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,2475,274,811x540,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,5,25,801x503,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2021-12-09 17:31:48 [pool-3-thread-1] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "117hd" version "1.0.9" commit "0882350c301e6b88036a386293d67ff241f31878"
2021-12-09 17:31:48 [pool-3-thread-1] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "crab-stun-timers" version "b0e7ad22" commit "b0e7ad22a6018fed3cdcd105d6a1873a242e75e3"
2021-12-09 17:31:48 [pool-3-thread-1] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "crab-solver" version "1.2" commit "a81701ff28b1c0f0790bd0bd9a927c140d3a3e97"
2021-12-09 17:31:49 [Client] INFO  rs117.hd.HdPlugin - Using device: Radeon RX 580 Series (POLARIS10, DRM 3.41.0, 5.13.0-22-generic, LLVM 12.0.1)

2021-12-09 17:31:49 [Client] INFO  rs117.hd.HdPlugin - Using driver: 4.6 (Compatibility Profile) Mesa 21.2.2
2021-12-09 17:41:02 [AWT-EventQueue-0] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.UnsupportedOperationException: The system tray is not supported on the current platform.
	at java.desktop/java.awt.SystemTray.getSystemTray(Unknown Source)
	at java.desktop/sun.awt.X11.XTrayIconPeer$4$1.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

2021-12-09 18:03:08 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.8.6 (launcher version 2.2.0) starting up, args: none
2021-12-09 18:03:09 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2021-12-09 18:03:10 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2021-12-09 18:03:10 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 1867715507.343
2021-12-09 18:03:10 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2021-12-09 18:03:10 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2021-12-09 18:03:11 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "117hd" version "1.0.9" commit "0882350c301e6b88036a386293d67ff241f31878"
2021-12-09 18:03:11 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "crab-stun-timers" version "b0e7ad22" commit "b0e7ad22a6018fed3cdcd105d6a1873a242e75e3"
2021-12-09 18:03:11 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "crab-solver" version "1.2" commit "a81701ff28b1c0f0790bd0bd9a927c140d3a3e97"
2021-12-09 18:03:11 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2021-12-09 18:03:12 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 4430ms. Uptime: 6763ms
2021-12-09 18:03:12 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,2475,274,811x540,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,5,25,801x503,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2021-12-09 18:03:13 [Client] INFO  rs117.hd.HdPlugin - Using device: Radeon RX 580 Series (POLARIS10, DRM 3.41.0, 5.13.0-22-generic, LLVM 12.0.1)
2021-12-09 18:03:13 [Client] INFO  rs117.hd.HdPlugin - Using driver: 4.6 (Compatibility Profile) Mesa 21.2.2
2021-12-09 18:04:24 [Client] WARN  n.r.client.config.ConfigManager - trying to create profile without display name
2021-12-09 18:05:14 [Client] INFO  rs117.hd.HdPlugin - Using device: Radeon RX 580 Series (POLARIS10, DRM 3.41.0, 5.13.0-22-generic, LLVM 12.0.1)
2021-12-09 18:05:14 [Client] INFO  rs117.hd.HdPlugin - Using driver: 4.6 (Compatibility Profile) Mesa 21.2.2
2021-12-09 18:24:59 [AWT-EventQueue-0] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.UnsupportedOperationException: The system tray is not supported on the current platform.
	at java.desktop/java.awt.SystemTray.getSystemTray(Unknown Source)
	at java.desktop/sun.awt.X11.XTrayIconPeer$4$1.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

**Comment by rilesdun** [comment]
`java.lang.UnsupportedOperationException: The system tray is not supported on the current platform.`

Any advice on why? Or if this works on 20.04 LTS ubuntu?

**Comment by Nightfirecat** [comment]
Apparently Gnome 3.28 removed the system tray, so this behavior is expected: https://stackoverflow.com/a/50574518/540162. We should update this to not crash though

**Comment by wayne-li2** [comment]
```
		if (!SystemTray.isSupported())
		{
			return null;
		}
```

It looks like we already exit early if SystemTray isn't supported. So it's weird that this flag check returns true but then `getSystemTray` fails.

**Comment by abextm** [comment]
this looks like [JDK-8058804](https://bugs.openjdk.java.net/browse/JDK-8058804)

**Comment by rilesdun** [comment]
This is not reproducible on Ubuntu 20.04.3; Which is running Gnome version 3.36.8. I haven't retested this on my 21.10 installed so it doesn't seem to be an issue with system tray unless this was fixed in recent updates.

I'll give this an attempt at later tonight to confirm if its been fixed in a fully updated 21.10 environment

**Comment by rilesdun** [comment]
Update:

This still breaks the system requiring a hard reboot on Ubuntu 21.10, GNOME Version 40.4.0; Wayland

**Comment by Nightfirecat** [comment]
May be related to #7817

**Comment by Ammako** [comment]
If you turn *off* the Ubuntu AppIndicators gnome shell extension, it won't crash, because a tray icon is only created when the system supports appindicators.

I'm tempted to blame Ubuntu non-LTS releases for being D-tier software. For some reason, on Wayland, the dock extension can't handle accessing and displaying the JavaEmbeddedFrame.

The error from that log is a red herring, also. It wouldn't hurt to catch that exception properly, but it's not the cause for this problem.

(Mutter really ought to be ignoring JavaEmbeddedFrames by now, though... this is 2022)

**Comment by pistolpetefl** [comment]
> If you turn _off_ the Ubuntu AppIndicators gnome shell extension, it won't crash, because a tray icon is only created when the system supports appindicators.

Can you explain how one would do this? I'm having the same issue.

**Comment by Ammako** [comment]
Install `gnome-shell-extension-prefs`, toggle off the Ubuntu AppIndicators from the list.

**Comment by Adam-** [comment]
Not sure if this helps, but we recently added a toggle to disable the tray icon completely (`runelite.trayIcon=false`), so maybe disabling it is an effective workaround?

**Comment by Ammako** [comment]
Oh nice, I didn't know that was a thing now. Love it.

That would be the better option, that way you can at least keep appindicators for all your other programs.

**Comment by pistolpetefl** [comment]
> Install `gnome-shell-extension-prefs`, toggle off the Ubuntu AppIndicators from the list.

Wow, fastest help I've ever gotten. Thank you so so much I've been screwing with this for hours. 

> Not sure if this helps, but we recently added a toggle to disable the tray icon completely (`runelite.trayIcon=false`), so maybe disabling it is an effective workaround?

Total noob here, where would I go about toggling that?

**Comment by Ammako** [comment]
You can actually just uncheck it in the settings, under RuneLite

![image](https://user-images.githubusercontent.com/94999823/149686117-3926d8f9-f8de-44c6-8ba1-7814ac3f9d7c.png)

Change takes effect after a restart
