### ISSUE TITLE
Stretched Mode doesn't scale correctly with GPU enabled

### ISSUE THREAD

**Issue by kristmascane** [runelite/runelite#14513]
**Describe the bug**

**macOS ISSUE AS A WHOLE, NOT ONLY M1**

**FIXED MODE ONLY**

When in **Fixed mode**  and enabling stretched mode alongside GPU or 117's plugin, the client doesn't scale linearly, no matter what options you have selected in stretched mode. Must be something fucky with the M1 gpu cores.

**To Reproduce**
1. Set game to Fixed Mode (Resizable functions normally here so no issue with that)
2. Turn on Stretched Mode
3. Turn on some GPU plugin. (GPU or 117's HD)
4. Attempt to resize the client.

**Expected behavior**
Turn on both plugins, resize the client with normal scaling behavior.

**Video**
https://streamable.com/z61nrc

**Environment (please complete the following information):**
 - macOS (M1)
 - RuneLite version: 1.8.7.1       
 - Launcher version: 2.2.0

**Additional context**

2021-12-21 20:47:20 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.8.7.1 (launcher version 2.2.0) starting up, args: none
2021-12-21 20:47:22 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Vanilla cache is the wrong size
2021-12-21 20:47:23 [Preloader] WARN  net.runelite.client.rs.ClientLoader - Cached patch hash mismatches, regenerating patch
2021-12-21 20:47:40 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 1895092647.351
2021-12-21 20:47:41 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2021-12-21 20:47:41 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2021-12-21 20:47:42 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "inventory-setups" version "v1.12.2" commit "a801c482312c09ba6e85e599f97e9b27ace0eb07"
2021-12-21 20:47:42 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "door-kicker" version "1.0" commit "04dfc0e0974b28080599bb1ffdc3f7195df922d6"
2021-12-21 20:47:42 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "cox-special-loot-hider" version "4838f75f" commit "4838f75fb86f32b7b517b94baca94b92b7f2ed0e"
2021-12-21 20:47:42 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "runewatch" version "2.1.1" commit "f8616bcdb31174ae95a628ac8c1cdbd339ba754a"
2021-12-21 20:47:42 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "117hd" version "1.0.11" commit "d99ec13309e0794f403c1960580d447252641270"
2021-12-21 20:47:42 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "loot-logger" version "3.1.4" commit "f02ddd96637911ba3fd783b676ed5199d8facec9"
2021-12-21 20:47:42 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "fixed-mode-hide-chat" version "1.0" commit "ce4bebd044eead4b2b46433e92c96acdd45411ec"
2021-12-21 20:47:42 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "tob-damage-counter" version "1.1" commit "bbfa095fd86b0ca3d80f678d14e1b7595e9556c8"
2021-12-21 20:47:42 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "the-gauntlet" version "4e13d3eb" commit "4e13d3ebdf7da91f96c3a47856b2ac19de1e48c8"
2021-12-21 20:47:42 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "tempoross" version "1.2" commit "af72eacca6df48b132232cb4dd5775b225fa2e5e"
2021-12-21 20:47:42 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "zulrah-helper" version "1.2.1" commit "a10c7242ee25809705985883ad297e89962b9b85"
2021-12-21 20:47:42 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "emojiscape" version "1.6" commit "eebad1d510f80720304c0fa1812d96e5262b6b8d"
2021-12-21 20:47:42 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "raid-points-overlay" version "178e96a5" commit "178e96a5af1ffa883c26c8524b73b038ab15f976"
2021-12-21 20:47:42 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "menu-swapper-extended" version "1.8" commit "9a5a9cc3278fd552b948bfc62c2ee1a461f6fde1"
2021-12-21 20:47:42 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "resource-packs" version "1.4.4" commit "febc83db0fbb19172d9fa4a5d740e490cd8cd428"
2021-12-21 20:47:42 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "quest-helper" version "2.8.0" commit "b045eaa6a5932c229716576516e16705d3bf4928"
2021-12-21 20:47:42 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "bats-locator" version "890cefa0" commit "890cefa0a95a734abc15a6b1f0681276c5c78c4d"
2021-12-21 20:47:42 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "raid-reloader" version "415a4b71" commit "415a4b71a6f94f9f10345f5c825ab1109bc7cb07"
2021-12-21 20:47:42 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "theatre-of-blood-stats" version "1.3" commit "9c4493305fb6e28e283d622c674779a007c19ea3"
2021-12-21 20:47:42 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "banked-experience" version "2.0.9" commit "288bc92bc61e623a7466c31702bdda2488843489"
2021-12-21 20:47:42 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "fight-cave-waves" version "1.2" commit "51790d94159cbb85893de04d90efc5c0c20d819a"
2021-12-21 20:47:42 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "advanced-notifications" version "1.1.2" commit "2ebfa4f2e06218f1f7224b6987e99ea401af9363"
2021-12-21 20:47:42 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "shooting-stars-tracking" version "1.0" commit "f15693fec2050eee9d14e6e590e15c8410c03015"
2021-12-21 20:47:42 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "shortest-path" version "1.2" commit "f6073d99e00e3d06d62d6d41d506181dcee6be04"
2021-12-21 20:47:42 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "crab-stun-timers" version "b0e7ad22" commit "b0e7ad22a6018fed3cdcd105d6a1873a242e75e3"
2021-12-21 20:47:42 [RuneLite] WARN  n.r.client.config.ConfigManager - Unable to unmarshal worldhopper.quickHopRegionFilter 
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
	at com.google.gson.Gson.fromJson(Gson.java:939)
	at com.google.gson.Gson.fromJson(Gson.java:892)
	at com.google.gson.Gson.fromJson(Gson.java:841)
	at net.runelite.client.config.ConfigManager.stringToObject(ConfigManager.java:838)
	at net.runelite.client.config.ConfigManager.getConfiguration(ConfigManager.java:481)
	at net.runelite.client.config.ConfigManager.getConfiguration(ConfigManager.java:460)
	at net.runelite.client.config.ConfigManager.setDefaultConfiguration(ConfigManager.java:723)
	at net.runelite.client.plugins.PluginManager.loadDefaultPluginConfiguration(PluginManager.java:222)
	at net.runelite.client.RuneLite.start(RuneLite.java:302)
	at net.runelite.client.RuneLite.main(RuneLite.java:251)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.runelite.launcher.ReflectionLauncher$1.run(ReflectionLauncher.java:63)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:350)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:80)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	... 14 common frames omitted
2021-12-21 20:47:42 [RuneLite] WARN  n.r.client.config.ConfigManager - Unable to unmarshal worldhopper.regionFilter 
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
	at com.google.gson.Gson.fromJson(Gson.java:939)
	at com.google.gson.Gson.fromJson(Gson.java:892)
	at com.google.gson.Gson.fromJson(Gson.java:841)
	at net.runelite.client.config.ConfigManager.stringToObject(ConfigManager.java:838)
	at net.runelite.client.config.ConfigManager.getConfiguration(ConfigManager.java:481)
	at net.runelite.client.config.ConfigManager.getConfiguration(ConfigManager.java:460)
	at net.runelite.client.config.ConfigManager.setDefaultConfiguration(ConfigManager.java:723)
	at net.runelite.client.plugins.PluginManager.loadDefaultPluginConfiguration(PluginManager.java:222)
	at net.runelite.client.RuneLite.start(RuneLite.java:302)
	at net.runelite.client.RuneLite.main(RuneLite.java:251)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.runelite.launcher.ReflectionLauncher$1.run(ReflectionLauncher.java:63)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:350)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:80)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	... 14 common frames omitted
2021-12-21 20:47:42 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2021-12-21 20:47:43 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 23534ms. Uptime: 26239ms
2021-12-21 20:47:44 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,37,91,1438x775,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1438x775,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@2cd68e82,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2021-12-21 20:49:12 [AppKit Thread] INFO  n.r.client.plugins.gpu.GpuPlugin - Using device: Apple M1 Pro
2021-12-21 20:49:12 [AppKit Thread] INFO  n.r.client.plugins.gpu.GpuPlugin - Using driver: 2.1 Metal - 76.3
2021-12-21 20:51:26 [pool-3-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user Kristmascane.
2021-12-21 20:52:21 [AppKit Thread] INFO  n.r.client.plugins.gpu.GpuPlugin - Using device: Apple M1 Pro
2021-12-21 20:52:21 [AppKit Thread] INFO  n.r.client.plugins.gpu.GpuPlugin - Using driver: 2.1 Metal - 76.3
2021-12-21 20:52:39 [AppKit Thread] INFO  n.r.client.plugins.gpu.GpuPlugin - Using device: Apple M1 Pro
2021-12-21 20:52:39 [AppKit Thread] INFO  n.r.client.plugins.gpu.GpuPlugin - Using driver: 2.1 Metal - 76.3
2021-12-21 20:52:50 [AppKit Thread] INFO  n.r.client.plugins.gpu.GpuPlugin - Using device: Apple M1 Pro
2021-12-21 20:52:50 [AppKit Thread] INFO  n.r.client.plugins.gpu.GpuPlugin - Using driver: 2.1 Metal - 76.3
2021-12-21 20:56:06 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.8.7.1 (launcher version 2.2.0) starting up, args: none
2021-12-21 20:56:08 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2021-12-21 20:56:08 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2021-12-21 20:56:09 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 1895092647.351
2021-12-21 20:56:09 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2021-12-21 20:56:09 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2021-12-21 20:56:10 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "inventory-setups" version "v1.12.2" commit "a801c482312c09ba6e85e599f97e9b27ace0eb07"
2021-12-21 20:56:10 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "door-kicker" version "1.0" commit "04dfc0e0974b28080599bb1ffdc3f7195df922d6"
2021-12-21 20:56:10 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "cox-special-loot-hider" version "4838f75f" commit "4838f75fb86f32b7b517b94baca94b92b7f2ed0e"
2021-12-21 20:56:10 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "runewatch" version "2.1.1" commit "f8616bcdb31174ae95a628ac8c1cdbd339ba754a"
2021-12-21 20:56:10 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "117hd" version "1.0.11" commit "d99ec13309e0794f403c1960580d447252641270"
2021-12-21 20:56:10 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "loot-logger" version "3.1.4" commit "f02ddd96637911ba3fd783b676ed5199d8facec9"
2021-12-21 20:56:10 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "fixed-mode-hide-chat" version "1.0" commit "ce4bebd044eead4b2b46433e92c96acdd45411ec"
2021-12-21 20:56:10 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "tob-damage-counter" version "1.1" commit "bbfa095fd86b0ca3d80f678d14e1b7595e9556c8"
2021-12-21 20:56:10 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "the-gauntlet" version "4e13d3eb" commit "4e13d3ebdf7da91f96c3a47856b2ac19de1e48c8"
2021-12-21 20:56:10 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "tempoross" version "1.2" commit "af72eacca6df48b132232cb4dd5775b225fa2e5e"
2021-12-21 20:56:10 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "zulrah-helper" version "1.2.1" commit "a10c7242ee25809705985883ad297e89962b9b85"
2021-12-21 20:56:10 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "emojiscape" version "1.6" commit "eebad1d510f80720304c0fa1812d96e5262b6b8d"
2021-12-21 20:56:10 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "raid-points-overlay" version "178e96a5" commit "178e96a5af1ffa883c26c8524b73b038ab15f976"
2021-12-21 20:56:10 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "menu-swapper-extended" version "1.8" commit "9a5a9cc3278fd552b948bfc62c2ee1a461f6fde1"
2021-12-21 20:56:10 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "resource-packs" version "1.4.4" commit "febc83db0fbb19172d9fa4a5d740e490cd8cd428"
2021-12-21 20:56:10 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "quest-helper" version "2.8.0" commit "b045eaa6a5932c229716576516e16705d3bf4928"
2021-12-21 20:56:10 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "bats-locator" version "890cefa0" commit "890cefa0a95a734abc15a6b1f0681276c5c78c4d"
2021-12-21 20:56:10 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "raid-reloader" version "415a4b71" commit "415a4b71a6f94f9f10345f5c825ab1109bc7cb07"
2021-12-21 20:56:10 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "theatre-of-blood-stats" version "1.3" commit "9c4493305fb6e28e283d622c674779a007c19ea3"
2021-12-21 20:56:10 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "banked-experience" version "2.0.9" commit "288bc92bc61e623a7466c31702bdda2488843489"
2021-12-21 20:56:10 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "fight-cave-waves" version "1.2" commit "51790d94159cbb85893de04d90efc5c0c20d819a"
2021-12-21 20:56:10 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "advanced-notifications" version "1.1.2" commit "2ebfa4f2e06218f1f7224b6987e99ea401af9363"
2021-12-21 20:56:10 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "shooting-stars-tracking" version "1.0" commit "f15693fec2050eee9d14e6e590e15c8410c03015"
2021-12-21 20:56:10 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "shortest-path" version "1.2" commit "f6073d99e00e3d06d62d6d41d506181dcee6be04"
2021-12-21 20:56:10 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "crab-stun-timers" version "b0e7ad22" commit "b0e7ad22a6018fed3cdcd105d6a1873a242e75e3"
2021-12-21 20:56:10 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2021-12-21 20:56:11 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 4910ms. Uptime: 6306ms
2021-12-21 20:56:11 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,44,133,405x267,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,405x267,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@3ec91a2d,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2021-12-21 20:56:12 [pool-3-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user Kristmascane.
2021-12-21 21:05:20 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.8.7.1 (launcher version 2.2.0) starting up, args: none
2021-12-21 21:05:22 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2021-12-21 21:05:22 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2021-12-21 21:05:22 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 1895092647.351
2021-12-21 21:05:23 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2021-12-21 21:05:23 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2021-12-21 21:05:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "inventory-setups" version "v1.12.2" commit "a801c482312c09ba6e85e599f97e9b27ace0eb07"
2021-12-21 21:05:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "door-kicker" version "1.0" commit "04dfc0e0974b28080599bb1ffdc3f7195df922d6"
2021-12-21 21:05:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "cox-special-loot-hider" version "4838f75f" commit "4838f75fb86f32b7b517b94baca94b92b7f2ed0e"
2021-12-21 21:05:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "runewatch" version "2.1.1" commit "f8616bcdb31174ae95a628ac8c1cdbd339ba754a"
2021-12-21 21:05:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "117hd" version "1.0.11" commit "d99ec13309e0794f403c1960580d447252641270"
2021-12-21 21:05:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "loot-logger" version "3.1.4" commit "f02ddd96637911ba3fd783b676ed5199d8facec9"
2021-12-21 21:05:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "fixed-mode-hide-chat" version "1.0" commit "ce4bebd044eead4b2b46433e92c96acdd45411ec"
2021-12-21 21:05:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "tob-damage-counter" version "1.1" commit "bbfa095fd86b0ca3d80f678d14e1b7595e9556c8"
2021-12-21 21:05:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "the-gauntlet" version "4e13d3eb" commit "4e13d3ebdf7da91f96c3a47856b2ac19de1e48c8"
2021-12-21 21:05:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "tempoross" version "1.2" commit "af72eacca6df48b132232cb4dd5775b225fa2e5e"
2021-12-21 21:05:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "zulrah-helper" version "1.2.1" commit "a10c7242ee25809705985883ad297e89962b9b85"
2021-12-21 21:05:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "emojiscape" version "1.6" commit "eebad1d510f80720304c0fa1812d96e5262b6b8d"
2021-12-21 21:05:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "raid-points-overlay" version "178e96a5" commit "178e96a5af1ffa883c26c8524b73b038ab15f976"
2021-12-21 21:05:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "menu-swapper-extended" version "1.8" commit "9a5a9cc3278fd552b948bfc62c2ee1a461f6fde1"
2021-12-21 21:05:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "resource-packs" version "1.4.4" commit "febc83db0fbb19172d9fa4a5d740e490cd8cd428"
2021-12-21 21:05:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "quest-helper" version "2.8.0" commit "b045eaa6a5932c229716576516e16705d3bf4928"
2021-12-21 21:05:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "bats-locator" version "890cefa0" commit "890cefa0a95a734abc15a6b1f0681276c5c78c4d"
2021-12-21 21:05:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "raid-reloader" version "415a4b71" commit "415a4b71a6f94f9f10345f5c825ab1109bc7cb07"
2021-12-21 21:05:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "theatre-of-blood-stats" version "1.3" commit "9c4493305fb6e28e283d622c674779a007c19ea3"
2021-12-21 21:05:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "banked-experience" version "2.0.9" commit "288bc92bc61e623a7466c31702bdda2488843489"
2021-12-21 21:05:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "fight-cave-waves" version "1.2" commit "51790d94159cbb85893de04d90efc5c0c20d819a"
2021-12-21 21:05:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "advanced-notifications" version "1.1.2" commit "2ebfa4f2e06218f1f7224b6987e99ea401af9363"
2021-12-21 21:05:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "shooting-stars-tracking" version "1.0" commit "f15693fec2050eee9d14e6e590e15c8410c03015"
2021-12-21 21:05:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "shortest-path" version "1.2" commit "f6073d99e00e3d06d62d6d41d506181dcee6be04"
2021-12-21 21:05:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "crab-stun-timers" version "b0e7ad22" commit "b0e7ad22a6018fed3cdcd105d6a1873a242e75e3"
2021-12-21 21:05:24 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2021-12-21 21:05:25 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 4732ms. Uptime: 6115ms
2021-12-21 21:05:25 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,22,66,405x268,invalid,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,405x268,invalid,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@abf3aed,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2021-12-21 21:05:26 [pool-3-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user Kristmascane.

**Comment by wayne-li2** [comment]
I confirmed this is still an issue on a non-M1 2019 MacBook Pro

**Comment by Adam-** [comment]
fixed in bb43d232bb594c6e062e3342fa7db1b53f594c11
