### ISSUE TITLE
Runelite AppImage won't start

### ISSUE THREAD

**Issue by cchoe1** [runelite/runelite#14611]
I'm on Debian Buster.  The app is stuck on "Connecting to update server" and doesn't budge from there.  I tried to re-download a fresh AppImage but the same thing occurs.  Eventually it errors out with the message 

`error_game_js5connect`

Here is the following trace after the client errors out:

2022-01-19 10:32:34 [main] INFO  net.runelite.launcher.Launcher - RuneLite Launcher version 2.3.0                                                         
2022-01-19 10:32:34 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to OFF                                            
2022-01-19 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of client-1.8.10.jar                                                      
2022-01-19 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of slf4j-api-1.7.25.jar                                                          
2022-01-19 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of logback-classic-1.2.9.jar                                                     
2022-01-19 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of logback-core-1.2.9.jar                                                        
2022-01-19 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jopt-simple-5.0.1.jar                                                         
2022-01-19 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of guava-23.2-jre.jar                                                            
2022-01-19 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of guice-4.1.0-no_aop.jar                                                        
2022-01-19 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of javax.inject-1.jar                                                            
2022-01-19 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of aopalliance-1.0.jar                                                                
2022-01-19 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gson-2.8.5.jar                                                                     
2022-01-19 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of substance-8.0.02.jar                                                               
2022-01-19 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of trident-1.5.00.jar                                                                  
2022-01-19 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of commons-text-1.2.jar                                                                 
2022-01-19 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of commons-lang3-3.7.jar                                                                  
2022-01-19 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of commons-csv-1.4.jar                                                           
2022-01-19 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of archive-patcher-1.0.jar                                                                  
2022-01-19 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jna-5.9.0.jar                                                                               
2022-01-19 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jna-platform-5.9.0.jar                                                             
2022-01-19 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jsr305-3.0.2.jar                                                                    
2022-01-19 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-all-2.4.0-rc-20200429.jar                                                       
2022-01-19 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-all-2.4.0-rc-20200429-natives-linux-amd64.jar                            
2022-01-19 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gluegen-rt-2.4.0-rc-20200429.jar                                                    
2022-01-19 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gluegen-rt-2.4.0-rc-20200429-natives-linux-amd64.jar                                 
2022-01-19 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jocl-1.0.jar                                                                         
2022-01-19 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of client-patch-1.8.10.jar                                                                
2022-01-19 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of http-api-1.0.0.jar                                                                        
2022-01-19 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of okhttp-3.14.9.jar                                                                           
2022-01-19 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of okio-1.17.2.jar                                                                             
2022-01-19 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of discord-1.4.jar                                                                        
2022-01-19 10:32:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of runelite-api-1.8.10-runtime.jar                                                          
2022-01-19 10:32:35 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.8.10 (launcher version 2.3.0) starting up, args: none                                                       
2022-01-19 10:32:46 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Failed to get jav_config from host "oldschool.runescape.com" (connect timed out)                               
2022-01-19 10:32:57 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Failed to get jav_config from host "oldschool144.runescape.com" (Read timed out)                               
2022-01-19 10:33:07 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Failed to get jav_config from host "oldschool154.runescape.com" (connect timed out)                                   
2022-01-19 10:33:17 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Failed to get jav_config from host "oldschool4.runescape.com" (connect timed out)                                           
2022-01-19 10:33:27 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Failed to get jav_config from host "oldschool16a.runescape.com" (connect timed out)                                         
2022-01-19 10:33:49 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Failed to get jav_config from host "oldschool42.runescape.com" (Read timed out)                                       
2022-01-19 10:33:49 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Falling back to backup client config                                                                                               
2022-01-19 10:33:49 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client                                                                                                        
2022-01-19 10:33:49 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client                                                                                                               
2022-01-19 10:33:49 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 1991215481.19                                                                                                         
2022-01-19 10:33:50 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists                                                                                                                       
2022-01-19 10:33:50 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset                                                                                                                        
2022-01-19 10:33:50 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "117hd" version "1.0.13" commit "7c6f9909a929517c6994772963971c64b2f35f96"                                                 
2022-01-19 10:33:51 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.                                                                                                                  
2022-01-19 10:33:52 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 76768ms. Uptime: 79085ms                                                                                                     
2022-01-19 10:33:52 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,873,443,811x636,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defau
ltCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,5,25,801x606,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootP
aneCheckingEnabled=true]                                                                                      
2022-01-19 10:33:52 [Client] INFO  rs117.hd.HdPlugin - Using device: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2                                                                                                                    
2022-01-19 10:33:52 [Client] INFO  rs117.hd.HdPlugin - Using driver: 4.6.0 NVIDIA 470.63.01                    
error_game_js5connect                                  
2022-01-19 10:36:02 [pool-5-thread-1] WARN  n.r.c.plugins.worldhopper.ping.Ping - error pinging                
java.net.ConnectException: Connection timed out (Connection timed out)                                         
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)                                     
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)                                
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)                         
        at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)                                  
        at java.base/java.net.SocksSocketImpl.connect(Unknown Source)                                          
        at java.base/java.net.Socket.connect(Unknown Source)                                                   
        at java.base/java.net.Socket.connect(Unknown Source)                                                   
        at net.runelite.client.plugins.worldhopper.ping.Ping.tcpPing(Ping.java:247)                            
        at net.runelite.client.plugins.worldhopper.ping.Ping.ping(Ping.java:85)                                
        at net.runelite.client.plugins.worldhopper.WorldHopperPlugin.ping(WorldHopperPlugin.java:853)          
        at net.runelite.client.plugins.worldhopper.WorldHopperPlugin.pingInitialWorlds(WorldHopperPlugin.java:770)                                                                                                            
        at net.runelite.client.util.RunnableExceptionLogger.run(RunnableExceptionLogger.java:41)               
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)                       
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)                                       
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)                                                                                                                 
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)                         
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)                        
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Hydrox6** [comment]
The game is currently down for a rollback

This is not an issue with RuneLite
