### ISSUE TITLE
RuneScape canvas not loading

### ISSUE THREAD

**Issue by samfrjn11** [runelite/runelite#14751]
When starting the RuneLite client, the RuneScape canvas is not loaded.

**Steps to reproduce the behavior:**
1. Launch client

**Environment:**
 - OS: Windows 10 21H1 19043.1586
 - RuneLite version: 1.8.13.1
 - Launcher version: 2.4.2

client.log:
```
2022-03-16 16:33:32 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.8.13.1 (launcher version 2.4.2) starting up, args: none
2022-03-16 16:33:34 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2022-03-16 16:33:34 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2022-03-16 16:33:35 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 2188984708.69
2022-03-16 16:33:36 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2022-03-16 16:33:36 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "quest-helper" version "3.0.0" commit "5dfee72a5364154cbfca08fba73678cc9dee3e74"
2022-03-16 16:33:36 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "door-kicker" version "1.0" commit "04dfc0e0974b28080599bb1ffdc3f7195df922d6"
2022-03-16 16:33:36 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "flipping-utilities" version "1.4.1" commit "8c02413fde79941b4828016bdf6001b1b71bfcaa"
2022-03-16 16:33:36 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "one-click-summer-garden" version "2.1.1" commit "5a375878b329bbed623a88b8675913a759dfa665"
2022-03-16 16:33:36 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "loot-logger" version "3.2.1" commit "9a3715104c9a0b08fd54f8a03bb474a327528dbc"
2022-03-16 16:33:36 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "ba-minigame" version "1.6" commit "31979b0f093bc15297f1ced515a4d3a1d25453f4"
2022-03-16 16:33:36 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "117hd" version "1.0.14" commit "965fe76320d329dcbb65dd19f5079c8d0fbddbff"
2022-03-16 16:33:36 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "equipment-inspector" version "1.2" commit "c0018d299bb4a3dd4ef971a72bfdc776a42f0ff8"
2022-03-16 16:33:36 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "bank-value-tracker" version "757b7b33" commit "757b7b33bdfc27ba24d57fd22a15456f75558d00"
2022-03-16 16:33:36 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "high-alc-highlight" version "82c9cc29" commit "82c9cc29d7d6ef3b4fa05a29370c1c912bf2f394"
2022-03-16 16:33:36 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "shortest-path" version "1.6" commit "42e0e6d16ca56db40749031e0f027302146616e3"
2022-03-16 16:33:36 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "time-to-level" version "1.0.2" commit "54960d5fc3e99ea9d6529c0916c426036de63719"
2022-03-16 16:33:36 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "wikisync" version "2.0" commit "8246ef597be7554010737e8c47559b23d689410f"
2022-03-16 16:33:36 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "zom-leftclick-dropper" version "1.6" commit "e21b2b56b29ed6adc0ae87938fa67672f2bf93dd"
2022-03-16 16:33:36 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "skills-tab-progress-bars" version "1.2" commit "9ea27934275a809456d7bb6ebd636009787f94f3"
2022-03-16 16:33:37 [Client] ERROR client-patch - Client error: null
java.lang.ArrayIndexOutOfBoundsException: Index 4370 out of bounds for length 4353
	at kq.ef(kq.java:155)
	at gw.dt(gw.java:46)
	at be.fk(be.java:1857)
	at client.h(client.java:952)
	at al.j(al.java:344)
	at al.run(al.java:323)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-03-16 16:33:37 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2022-03-16 16:33:37 [AWT-EventQueue-0] INFO  c.f.controller.RecipeHandler - Successfully loaded recipes
2022-03-16 16:33:39 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 6680ms. Uptime: 8938ms
2022-03-16 16:33:39 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,2513,100,1414x976,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1414x976,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@35b6d326,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
```

![image](https://user-images.githubusercontent.com/13766544/158629859-a9d64e3b-bd98-405a-85f0-2aea7bbd16d5.png)

**Comment by samfrjn11** [comment]
Apparently it was an issue on Jagex' end. 
Might be worth adding a catch if it fail to load the RuneScape client.
