### ISSUE TITLE
runelite won't open, blank screen upon opening. client error: null

### ISSUE THREAD

**Issue by naijynx** [runelite/runelite#14750]
I've tried other solutions I've read for this and I can't get anything to work.
<img width="715" alt="runelite" src="https://user-images.githubusercontent.com/101731591/158627986-b416ee84-9339-43b7-8a06-f2da452eed3d.png">

My cache log shows: 
`2022-03-16 10:09:48 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 6185ms. Uptime: 8526ms
2022-03-16 10:09:48 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,229,75,809x534,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@111f4da,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2022-03-16 10:19:56 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.8.13.1 (launcher version 2.2.0) starting up, args: none
2022-03-16 10:19:58 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2022-03-16 10:19:58 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2022-03-16 10:19:58 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 2188984708.69
2022-03-16 10:19:59 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2022-03-16 10:19:59 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2022-03-16 10:20:00 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "117hd" version "1.0.14" commit "965fe76320d329dcbb65dd19f5079c8d0fbddbff"
2022-03-16 10:20:00 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "quest-helper" version "3.0.0" commit "5dfee72a5364154cbfca08fba73678cc9dee3e74"
2022-03-16 10:20:01 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2022-03-16 10:20:01 [Client] ERROR client-patch - Client error: null
java.lang.ArrayIndexOutOfBoundsException: Index 4370 out of bounds for length 4353
	at kq.ef(kq.java:155)
	at gw.dt(gw.java:46)
	at be.fk(be.java:1857)
	at client.h(client.java:952)
	at al.j(al.java:344)
	at al.run(al.java:323)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-03-16 10:20:02 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 6201ms. Uptime: 9122ms
2022-03-16 10:20:03 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,229,75,809x534,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@a9e0a2,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2022-03-16 10:20:03 [pool-3-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user jynx.
`

**Comment by jeraziah** [comment]
I had the same issue getting mine to start and was able to fix it by removing all files from the jagexcache/oldschool/LIVE folder (backed em up just in case)

**Comment by naijynx** [comment]
> I had the same issue getting mine to start and was able to fix it by removing all files from the jagexcache/oldschool/LIVE folder (backed em up just in case)

thanks! I'll take this into consideration for the future. I disabled the login enhancements and hd plugin, it's finally loading up again.

**Comment by Adam-** [comment]
This was due to a jagex issue https://twitter.com/OldSchoolRS/status/1504108495456636929
