### ISSUE TITLE
"import loot" doubled a bunch of loot in my loot tracker

### ISSUE THREAD

**Issue by akrueger47** [runelite/runelite#14770]
**Describe the bug**
I opened my loot tracker while playing to see a suggestion at the top to import lost loot. I clicked it and it imported 70 items. I then noticed that it had just effectively doubled my loot and kc for kril/minions from the past 2 days except for my frozen key piece. When checking the runelite loots folder on my PC it still only has 1 quantity for stuff like the SoTD and shard 2 which i definitely only have 1 of.

**Screenshots**
![image](https://user-images.githubusercontent.com/101982361/159168031-9cac09bb-92de-4b4b-8775-45de3336faf6.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.8.14
 - Launcher version: 2.2.0

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

Logs from today if needed:

2022-03-20 04:58:00 [pool-3-thread-1] WARN  n.r.client.ClientSessionManager - Resetting session
java.net.SocketTimeoutException: timeout
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:678)
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:686)
	at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:154)
	at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.java:136)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at net.runelite.client.RuneLite.lambda$buildHttpClient$5(RuneLite.java:434)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at net.runelite.client.RuneLite.lambda$buildHttpClient$4(RuneLite.java:427)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
	at okhttp3.RealCall.execute(RealCall.java:81)
	at net.runelite.client.SessionClient.ping(SessionClient.java:91)
	at net.runelite.client.ClientSessionManager.ping(ClientSessionManager.java:127)
	at net.runelite.client.util.RunnableExceptionLogger.run(RunnableExceptionLogger.java:41)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-03-20 04:58:03 [pool-6-thread-1] WARN  n.r.c.plugins.worldhopper.ping.Ping - error resolving host for world ping
java.net.UnknownHostException: No such host is known (oldschool37.runescape.com)
	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(Unknown Source)
	at java.base/java.net.InetAddress.getAddressesFromNameService(Unknown Source)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName0(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName(Unknown Source)
	at java.base/java.net.InetAddress.getByName(Unknown Source)
	at net.runelite.client.plugins.worldhopper.ping.Ping.ping(Ping.java:56)
	at net.runelite.client.plugins.worldhopper.WorldHopperPlugin.ping(WorldHopperPlugin.java:853)
	at net.runelite.client.plugins.worldhopper.WorldHopperPlugin.pingNextWorld(WorldHopperPlugin.java:811)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-03-20 04:58:22 [pool-6-thread-1] WARN  n.r.c.plugins.worldhopper.ping.Ping - error resolving host for world ping
java.net.UnknownHostException: No such host is known (oldschool39.runescape.com)
	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(Unknown Source)
	at java.base/java.net.InetAddress.getAddressesFromNameService(Unknown Source)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName0(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName(Unknown Source)
	at java.base/java.net.InetAddress.getByName(Unknown Source)
	at net.runelite.client.plugins.worldhopper.ping.Ping.ping(Ping.java:56)
	at net.runelite.client.plugins.worldhopper.WorldHopperPlugin.ping(WorldHopperPlugin.java:853)
	at net.runelite.client.plugins.worldhopper.WorldHopperPlugin.pingNextWorld(WorldHopperPlugin.java:811)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-03-20 04:58:45 [pool-6-thread-1] WARN  n.r.c.plugins.worldhopper.ping.Ping - error resolving host for world ping
java.net.UnknownHostException: No such host is known (oldschool44.runescape.com)
	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(Unknown Source)
	at java.base/java.net.InetAddress.getAddressesFromNameService(Unknown Source)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName0(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName(Unknown Source)
	at java.base/java.net.InetAddress.getByName(Unknown Source)
	at net.runelite.client.plugins.worldhopper.ping.Ping.ping(Ping.java:56)
	at net.runelite.client.plugins.worldhopper.WorldHopperPlugin.ping(WorldHopperPlugin.java:853)
	at net.runelite.client.plugins.worldhopper.WorldHopperPlugin.pingNextWorld(WorldHopperPlugin.java:811)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-03-20 09:44:18 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.8.14 (launcher version 2.2.0) starting up, args: none
2022-03-20 09:44:20 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2022-03-20 09:44:20 [Preloader] WARN  net.runelite.client.rs.ClientLoader - Cached patch hash mismatches, regenerating patch
2022-03-20 09:44:21 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 2225018471.78
2022-03-20 09:44:22 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2022-03-20 09:44:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "bank-tag-layouts" version "1.4.14" commit "8f60653fe83ad614fa7f765a0dc4528b525ed9d8"
2022-03-20 09:44:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "banked-experience" version "2.1.2" commit "a0a3bf4d7a462b3a9151ebb1241e7961eb15ceab"
2022-03-20 09:44:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "quest-helper" version "3.0.0" commit "5dfee72a5364154cbfca08fba73678cc9dee3e74"
2022-03-20 09:44:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "loot-table" version "1.0.1" commit "3452f9dc16c3193f606b669e4d2489a2af56e79a"
2022-03-20 09:44:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "mahogany-homes" version "1.4" commit "a9e118c1a07df4f4bd07e259ec23b6bef5f26206"
2022-03-20 09:44:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "visual-metronome" version "1.3.7" commit "0a68a019f2d33d57287cc8640eed0ead2959807e"
2022-03-20 09:44:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "maxhitplugin" version "23d328cb" commit "23d328cb160dd471431fd88fbb8268b8f01f01a2"
2022-03-20 09:44:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "117hd" version "1.0.14.1" commit "90359faf9beb99a4a3dcf903fc53b8f8ad2acc84"
2022-03-20 09:44:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "osrs-wiki-crowdsourcing" version "1.9" commit "0869372763ed938c7c2af89cfc192ae1af82a862"
2022-03-20 09:44:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "bank-memory" version "1.2.0" commit "335a83fd6cf863b43157143d1be83c41b4aa8d88"
2022-03-20 09:44:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "plank-sack" version "1.2.1" commit "523691095058d2c6a39310a695bc88fcc5191588"
2022-03-20 09:44:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "loot-logger" version "3.2.1" commit "9a3715104c9a0b08fd54f8a03bb474a327528dbc"
2022-03-20 09:44:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "watson-clue-tracker" version "1.0.7" commit "7862ef80610a8974ef2c3f8ec1273e21cb8372e1"
2022-03-20 09:44:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "emote-clue-items" version "3.3.1" commit "e5a449e24c1c7567983e5348ae32743c9190052c"
2022-03-20 09:44:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "the-gauntlet" version "4e13d3eb" commit "4e13d3ebdf7da91f96c3a47856b2ac19de1e48c8"
2022-03-20 09:44:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "wikisync" version "2.0" commit "8246ef597be7554010737e8c47559b23d689410f"
2022-03-20 09:44:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "supplies-tracker" version "2.01" commit "ec81a6706bac83dcffa82f80c157bc1a3e866df2"
2022-03-20 09:44:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "not-empty" version "1.0" commit "bf71b54988bbac4a6ed3308e586c8e922838e612"
2022-03-20 09:44:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "combat-information" version "7a9e5e38" commit "7a9e5e38fdf69dd72a46ea8a7fab0ffd4ecbc65d"
2022-03-20 09:44:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "zulrah-helper" version "1.2.1" commit "a10c7242ee25809705985883ad297e89962b9b85"
2022-03-20 09:44:23 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "ess-pouch" version "1.3" commit "dd766b0c5cb3f9ef9c24f3ddb5f75c09b2f1318e"
2022-03-20 09:44:24 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2022-03-20 09:44:25 [AWT-EventQueue-0] INFO  dekvall.notempty.NotEmptyPlugin - Not Empty started!
2022-03-20 09:44:26 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 8601ms. Uptime: 13185ms
2022-03-20 09:44:27 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,508,307,927x588,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,927x588,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@3d3831,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2022-03-20 09:44:28 [Client] INFO  rs117.hd.HdPlugin - Using device: Radeon (TM) RX 480 Graphics
2022-03-20 09:44:28 [Client] INFO  rs117.hd.HdPlugin - Using driver: 4.6.14761 Compatibility Profile Context 21.30.23.04 30.0.13023.4001
2022-03-20 09:44:28 [Client] INFO  rs117.hd.HdPlugin - Client is 32-bit

**Comment by Adam-** [comment]
This is a side effect of both loot capturing systems running currently. The button has been there since the 9th, so any loot received since then would be duplicated in both systems. You could fix it by doing a reset all and then importing again.

**Comment by akrueger47** [comment]
That fixed it! Thank you so much!
