### ISSUE TITLE
Runelite crashes on startup

### ISSUE THREAD

**Issue by astaz001** [runelite/runelite#14850]
**Describe the bug**
Once runelite starts, between 1 minute and a few hours, my runelite will crash showing an error message.
I am unable to move or use my mouse on screen and have to close Runelite and restart.
This is the error message:

ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.IllegalArgumentException: Substance delegate used when Substance is not the current LAF

It isn't an error I have been able to produce automatically.
The last few days it has just been happening throughtout all times of the day.

I have attempted to uninstall and reinstall as well as remove the cache folder.

**Screenshots**
![RL Crash Picture](https://user-images.githubusercontent.com/103394503/162846251-671eec97-8572-47fa-99c6-32ef10be118e.PNG)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.8.16? im not sure
 - Launcher version: 1.8.16

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
What logs showed around the time of the crash:

2022-04-10 20:43:00 [Client] ERROR client-patch - Client error: null
java.lang.ArrayIndexOutOfBoundsException: Index 131 out of bounds for length 128
	at rs117.hd.ModelData.getColorForFace(ModelPusher.java:24)
	at rs117.hd.ModelPusher.getVertexDataForFace(ModelPusher.java:126)
	at rs117.hd.ModelPusher.pushModel(ModelPusher.java:97)
	at rs117.hd.HdPlugin.draw(HdPlugin.java:2478)
	at client.sa(client.java:37883)
	at gs.en(gs.java:1006)
	at gs.gt(gs.java)
	at gs.aq(gs.java:32216)
	at cx.gw(cx.java:4170)
	at cy.ib(cy.java:9709)
	at cy.ib(cy.java:9740)
	at x.in(s.java:9598)
	at client.hs(client.java:3984)
	at client.i(client.java:1089)
	at aw.w(aw.java:392)
	at aw.run(aw.java:346)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-04-10 20:43:00 [AWT-EventQueue-0] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.IllegalArgumentException: Substance delegate used when Substance is not the current LAF [component SubstanceTitlePane in window net.runelite.client.ui.ContainableFrame:'RuneLite - GroupTileman' under Metal]
	at org.pushingpixels.substance.internal.utils.SubstanceCoreUtilities.traceSubstanceApiUsage(SubstanceCoreUtilities.java:1885)
	at org.pushingpixels.substance.internal.utils.SubstanceTitlePane.paintComponent(SubstanceTitlePane.java:1099)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JLayeredPane.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent._paintImmediately(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintImmediately(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$4.run(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

**Comment by Adam-** [comment]
This is the HD plugin crashing, not a core RuneLite issue
