### ISSUE TITLE
Runelite will randomly DC and can't figure out why?

### ISSUE THREAD

**Issue by Gavatron22** [runelite/runelite#14919]
### Type

Performance

### Operating System

Windows

### OS Version

Windows 10 Home: Version 21H2

### Bug description

I'll be playing and the client will randomly disconnect until the waiting for server response message comes up on screen, then it'll come back for a few seconds where I can control my account then it'll kick me directly to OSRS login screen. Oddly enough, I've noticed with 2 clients open that the second client will have no issues while the main one is freezing up and I have no internet connection issues during this. I've tried removing all plugins, whitelisting anything Runelite in my antivirus, clearing the Runelite cache, making sure the correct 64-bit download was installed to no avail. I've also read thru troubleshooting forums on setting the properties 'target' to open with the '-mode=OFF' workaround and still have been having this issue. This started around a month and a half to two months ago and it will cause me 2-5 DC's a night; more often I've found while I am in combat. Tonight when it happened again, I logged out and saved the client log right away which I will attach. I run Windows 10 version 21H2 with a AMD Ryzen 7 2700x 8-core 3.7GHz, 16GB RAM and an NVIDIA GeForce RTX 2070 Super. Any help or advice on how to resolve this issue would be greatly appreciated as these DC's have cost me quite the amount in Death's Coffer and I'm running out of skilling to do hoping the issue would have resolved itself (wishful thinking). Thanks for your time and efforts fellow gamers.

### Logs

[client.log](https://github.com/runelite/runelite/files/8628622/client.log)

2022-05-04 23:05:40 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.8.18.5 (launcher version 2.4.2) starting up, args: none
2022-05-04 23:05:42 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2022-05-04 23:05:42 [Preloader] WARN  net.runelite.client.rs.ClientLoader - Cached patch hash mismatches, regenerating patch
2022-05-04 23:05:42 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 2272916236.124
2022-05-04 23:05:44 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2022-05-04 23:05:44 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "guardians-of-the-rift-helper" version "1.01" commit "8ead4b91869ce7b2ddd96c8188ea5c16d520d75a"
2022-05-04 23:05:44 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "117hd" version "1.0.14.1" commit "90359faf9beb99a4a3dcf903fc53b8f8ad2acc84"
2022-05-04 23:05:44 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "zom-leftclick-dropper" version "1.6" commit "a58e8acb5dad2a2b758083d839a0de83cc8c3ec2"
2022-05-04 23:05:45 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2022-05-04 23:05:46 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 6093ms. Uptime: 8873ms
2022-05-04 23:05:46 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,294,117,1053x746,layout=java.awt.BorderLayout,title=RuneLite,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1053x746,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@3e72651b,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2022-05-04 23:05:47 [pool-3-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user Gavatron.
2022-05-04 23:05:48 [Client] INFO  rs117.hd.HdPlugin - Using device: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2
2022-05-04 23:05:48 [Client] INFO  rs117.hd.HdPlugin - Using driver: 4.6.0 NVIDIA 512.59
2022-05-04 23:05:48 [Client] INFO  rs117.hd.HdPlugin - Client is 64-bit
2022-05-04 23:27:29 [Client] ERROR client-patch - Client error: 52,90,37,23,3161,12425,0,0,0,0,0,0,0,3,90,0,0,1,-128,-114,-97,90,-82,3,0,2,0,-1,0,
java.lang.RuntimeException: 
	at er.mn(er.java:42)
	at client.hp(client.java:6553)
	at client.fv(client.java:3005)
	at client.z(client.java:955)
	at ao.wp(ao.java:359)
	at ao.run(ao.java:338)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Nightfirecat** [comment]
This is better-suited as a discussion question.
