### ISSUE TITLE
CME caused by Ground Markers minimap overlay

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#15025]
### Type

Other

### Bug description

Found in the log of a `#support` user.
```
2022-05-31 22:51:34 [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.util.ConcurrentModificationException: null
    at java.base/java.util.ArrayList$Itr.checkForComodification(Unknown Source)
    at java.base/java.util.ArrayList$Itr.next(Unknown Source)
    at net.runelite.client.plugins.groundmarkers.GroundMarkerMinimapOverlay.render(GroundMarkerMinimapOverlay.java:73)
    at net.runelite.client.ui.overlay.OverlayRenderer.safeRender(OverlayRenderer.java:719)
    at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlays(OverlayRenderer.java:322)
    at net.runelite.client.ui.overlay.OverlayRenderer.renderAfterInterface(OverlayRenderer.java:236)
    at net.runelite.client.callback.Hooks.drawInterface(Hooks.java:502)
    at client.vj(client.java:35205)
    at hi.io(hi.java:10681)
    at fu.im(fu.java:10208)
    at client.ik(client.java:4417)
    at client.ar(client.java:1090)
    at aj.f(aj.java:394)
    at aj.run(aj.java:348)
    at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by Nightfirecat** [comment]
I don't recall seeing a CME for any of Ground Marker's other overlays, and they iterate `plugin.getPoints()` in the same way as this one, so I'm a little confused why only this one would have encountered it.
