### ISSUE TITLE
RuneLite Doesn't Start If Website Is Down

### ISSUE THREAD

**Issue by samcgardner** [runelite/runelite#15175]
### Type

Incorrect behavior

### OS Version

Doesn't matter, OS independent

### Bug description

Reproduction:
1. Wait for total outage of runelite.net
2. Try to start runelite

### Logs

```
java.io.IOException: Server returned HTTP response code: 500 for URL: https://static.runelite.net/bootstrap.json.sha256
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at net.runelite.launcher.Launcher.getBootstrap(Launcher.java:458)
	at net.runelite.launcher.Launcher.main(Launcher.java:266)
```

**Comment by samcgardner** [comment]
Casual suggestions, haven't read the code:
1. Don't re-download the whole bundle, just check to see if it needs updating
2. If `static.runelite.net` is unavailable, just YOLO with the old bundle

**Comment by redrails** [comment]
It would also make sense to have a redundant mirror in case runelite.net is failing i.e. s3 or or some type of CDN..?

**Comment by Adam-** [comment]
> It would also make sense to have a redundant mirror in case runelite.net is failing i.e. s3 or or some type of CDN..?

In this instance, the CDN (cloudflare) did go down - so it would have required a redundant CDN. Which I suppose is possible, but probably very costly.

**Comment by redrails** [comment]
> > It would also make sense to have a redundant mirror in case runelite.net is failing i.e. s3 or or some type of CDN..?
> 
> In this instance, the CDN (cloudflare) did go down - so it would have required a redundant CDN. Which I suppose is possible, but probably very costly.

AWS should be fairly cheap I assume, the [CloudFront free tier](https://aws.amazon.com/cloudfront/pricing/) is actually quite good and might even suit the Runelite traffic perhaps.

**Comment by LlemonDuck** [comment]
Estimates for RuneLite traffic on AWS range in the thousands of dollars per *month*. Considering how much of the broader Internet goes down when CloudFlare does, I think it's completely reasonable to see a RuneLite outage alongside everyone else in the roughly 6 hours of outage per 6 months online that CloudFlare seems to have.

**Comment by Adam-** [comment]
Our DNS is also hosted at cloudflare so if cloudflare were to go down its unclear if we would be able to reroute people to a 2nd CDN anyway
