### ISSUE TITLE
add gpu support for linux aarch64

### ISSUE THREAD

**Issue by benpoulson** [runelite/runelite#15265]
### Type

GPU

### Operating System

Linux

### OS Version

aarch64 Ubuntu 22.04 LTS

### Bug description

This exception is now occuring for me whenever I start the GPU plugin.
Guessing it's due to the recent changes involving rlawt, but beyond that I couldn't comment.

This is on a chromebook running aarch64 ubuntu 22.04 LTS.

This occurs on both the aarch64 appimage, and the universal jar.

### RuneLite version

RuneLite 1.8.25.3
Launcher version 2.4.2

### Logs

2022-07-04 00:10:07 [Client] ERROR n.r.client.plugins.gpu.GpuPlugin - Error starting GPU plugin
java.lang.RuntimeException: rlawt does not exist at linux-aarch64/librlawt.so
	at net.runelite.rlawt.AWTContext.loadNatives(AWTContext.java:86)
	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$startUp$1(GpuPlugin.java:282)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:203)
	at client.gb(client.java:60461)
	at client.ab(client.java)
	at ap.m(ap.java:338)
	at ap.run(ap.java:317)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by Adam-** [comment]
We haven't got any aarch64 builds for it, and I don't think github actions supports arm64 for building it, but we may be able to cross compile it? cc @abextm

**Comment by Adam-** [comment]
Are you sure that this used to work? Previously when we used jogl we did not build or distribute aarch64 linux natives, so I don't think it could have worked before.

**Comment by FlowOverFail** [comment]
> We haven't got any aarch64 builds for it, and I don't think github actions supports arm64 for building it, but we may be able to cross compile it? cc @abextm

Hey Adam, is there any update on this? GitHub actions should support this AFAIK. Thank you!

**Comment by Adam-** [comment]
> > We haven't got any aarch64 builds for it, and I don't think github actions supports arm64 for building it, but we may be able to cross compile it? cc @abextm
> 
> Hey Adam, is there any update on this? GitHub actions should support this AFAIK. Thank you!

Actions doesn't support aarch64. It might be possible to either cross compile, or run a container on qemu, but ultimately we don't have any aarch64 linux systems with gpus to test with. Do you have one?

**Comment by FlowOverFail** [comment]
> > > We haven't got any aarch64 builds for it, and I don't think github actions supports arm64 for building it, but we may be able to cross compile it? cc @abextm
> > 
> > 
> > Hey Adam, is there any update on this? GitHub actions should support this AFAIK. Thank you!
> 
> Actions doesn't support aarch64. It might be possible to either cross compile, or run a container on qemu, but ultimately we don't have any aarch64 linux systems with gpus to test with. Do you have one?

I appreciate the hasty response. Yes, I do have a system I can test the builds with - and I'm willing to help out here - please let me know what you'd like me to do.

**Comment by Adam-** [comment]
> > > > We haven't got any aarch64 builds for it, and I don't think github actions supports arm64 for building it, but we may be able to cross compile it? cc @abextm
> > > 
> > > 
> > > Hey Adam, is there any update on this? GitHub actions should support this AFAIK. Thank you!
> > 
> > 
> > Actions doesn't support aarch64. It might be possible to either cross compile, or run a container on qemu, but ultimately we don't have any aarch64 linux systems with gpus to test with. Do you have one?
> 
> I appreciate the hasty response. Yes, I do have a system I can test the builds with - and I'm willing to help out here - please let me know what you'd like me to do.

Get rlawt cross compiling on actions & then test that the resulting build works. I might be able to help with cross compiling some. What kind of system do you have? If it is running asahi linux that probably won't work since I don't think they have gpu drivers working yet.

**Comment by FlowOverFail** [comment]
> > > > > We haven't got any aarch64 builds for it, and I don't think github actions supports arm64 for building it, but we may be able to cross compile it? cc @abextm
> > > > 
> > > > 
> > > > Hey Adam, is there any update on this? GitHub actions should support this AFAIK. Thank you!
> > > 
> > > 
> > > Actions doesn't support aarch64. It might be possible to either cross compile, or run a container on qemu, but ultimately we don't have any aarch64 linux systems with gpus to test with. Do you have one?
> > 
> > 
> > I appreciate the hasty response. Yes, I do have a system I can test the builds with - and I'm willing to help out here - please let me know what you'd like me to do.
> 
> Get rlawt cross compiling on actions & then test that the resulting build works. I might be able to help with cross compiling some. What kind of system do you have? If it is running asahi linux that probably won't work since I don't think they have gpu drivers working yet.

Will do, any insights are appreciated. Currently running a MBP M1 16" 32GB. I'm not using Asahi linux yet, as you mentioned, due to the lack of drivers for the GPU. Right now, I can run it against an Ubuntu 20.04 LTS image through Parallels.

**Comment by mordaut97** [comment]
Hi,

might be a little of topic, but I got the GPU plugin to work under windows on arm64.

I compiled rlawt with msvc. Got lwjgl jars for windows arm64 from [gwjgl](https://www.lwjgl.org/customize). And launched client-1.9.1.jar with just the jar paths for lwjgl and rlawt changed.


```
2022-10-15 23:13:32 [Client] INFO  n.r.client.plugins.gpu.GpuPlugin - Using device: D3D12 (Qualcomm(R) Adreno(TM) 680 GPU)
2022-10-15 23:13:32 [Client] INFO  n.r.client.plugins.gpu.GpuPlugin - Using driver: 4.1 (Compatibility Profile) Mesa 22.2.0-devel (git-7cbdf9e261)
2022-10-15 23:13:32 [Client] INFO  n.r.client.plugins.gpu.GpuPlugin - disabling compute shaders because OpenGL 4.3 is not available
```

**Comment by Adam-** [comment]
It might be possible to cross compile rlawt on actions, assuming the msvc install there includes the arm64 compilers. If you wanted to try and get that working it would be a good first step.

**Comment by Mariuspersen** [comment]
Hi there, just wanted to add some information about getting gpu working for linux aarch64.
I got the gpu plugin to work by: 

1. compiling [https://github.com/runelite/rlawt](runelite/rlawt)
2. compiling lwjgl from the AUR
3. unzipping liblwjgl.so from lwjgl-natives-linux-arm64.jar
4. unzipping liblwjgl_opengl.so from lwjgl-opengl-natives-linux-arm64.jar
5. Put those in the same folder

Then you can run a script like this:
`java -Djava.library.path=<path to where unzipped files> -Drunelite.rlawtpath=<path to librlawt.so> -jar <path to RuneLite.jar`

_Important thing to note that by doing this, you actually get worse fps than without the plugin so I probably have to modify it_
_This also wont work on ubuntu since you don't have access to the AUR, I would guess just downloading lwjgl from their website and extracting the necessary files from the jars there would also work_
_I'm also not familiar with Java enough that I'm probably not doing things properly here_

**Comment by MathGeniusJodie** [comment]
I tried compiling myself and couldn't get it to work 😭 btw you can test with termux on your phone if you have no other arm device

**Comment by MikeSim1** [comment]
@Mariuspersen where did you get the `librlawt.so` file for Linux-aarch64? I extracted files from `rlawt-1.5.jar` but there is no linux-aarch64 directory. I see other aarch64 directories though so I'm confused. I managed to grab the other two files from [LWJGL's release here](https://www.lwjgl.org/browse/release/3.3.2/linux/arm64) instead of extracting manually. To be transparent I'm using Linux on an Android device via termux similar to what's mentioned in the comment from @MathGeniusJodie

**Comment by Mariuspersen** [comment]
> [@Mariuspersen](https://github.com/Mariuspersen) where did you get the `librlawt.so` file for Linux-aarch64? I extracted files from `rlawt-1.5.jar` but there is no linux-aarch64 directory. I see other aarch64 directories though so I'm confused. I managed to grab the other two files from [LWJGL's release here](https://www.lwjgl.org/browse/release/3.3.2/linux/arm64) instead of extracting manually. To be transparent I'm using Linux on an Android device via termux similar to what's mentioned in the comment from [@MathGeniusJodie](https://github.com/MathGeniusJodie)

Hi, sorry for incredibly late response, I got it from the AUR (Arch User Repositories). aarch64 and arm64 are the same thing so I think you can use the one you found

**Comment by MikeSim1** [comment]
> Hi, sorry for incredibly late response, I got it from the AUR (Arch User Repositories). aarch64 and arm64 are the same thing so I think you can use the one you found

Still trying to get this working... I've managed to get rlawt compiled for aarch64 (I think. I'm not too familiar with cmake/make but I compiled via wsl2) but when I add it to the rlawt-1.5.jar, it gets overwritten on launch. Your command line args don't seem to work (at least on Termux Android). I've tried a few other methods I found as well but nothing seems to work. Curious how you got this working in the first place now @Mariuspersen ... Quite frustrating. If it gets bundled with the app image version, why can't it just be bundled in the jar version also? Maybe there's something I'm missing there.

**Comment by Adam-** [comment]
added in ebe56b9a3b817476658981c46d7fad003daaf523
