### ISSUE TITLE
RuneLite Crashing - ERROR client-patch - Client error: null

### ISSUE THREAD

**Issue by Acronyte** [runelite/runelite#15758]
### Type

Crash or hang

### Operating System

Windows

### OS Version

Windows 10 Home Version	10.0.19044 Build 19044

### Bug description

RuneLite has been crashing often lately, often once a day or every couple of days. Unfortunately I didn't think to take a screenshot of the crash message but it mentioned Java. I updated to the latest version of Java a few days ago but it is still crashing.

It has crashed twice today, both times within an hour of launching RuneLite (I was in nightmare zone).

Excerpt from end of most recent client.log where things seem to be messing up:

```
2022-10-01 16:08:52 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 6573ms. Uptime: 8431ms
2022-10-01 16:08:52 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,-8,-8,1936x1066,invalid,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,8,36,1920x1022,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2022-10-01 16:08:52 [Client] INFO  n.r.client.plugins.gpu.GpuPlugin - Using device: NVIDIA GeForce RTX 2060/PCIe/SSE2
2022-10-01 16:08:52 [Client] INFO  n.r.client.plugins.gpu.GpuPlugin - Using driver: 4.6.0 NVIDIA 516.94
2022-10-01 16:38:02 [Client] ERROR client-patch - Client error: null
java.lang.NullPointerException: null
	at ov.fa(ov.java:11)
	at lc.p(lc.java:28)
	at gp.ax(gp.java:1179)
	at gp.um(gp.java)
	at gp.fj(gp.java:9472)
	at cz.hi(cz.java:4459)
	at bl.ju(bl.java:9883)
	at bl.ju(bl.java:9914)
	at ga.jy(ga.java:9772)
	at client.gh(client.java:4313)
	at client.as(client.java:1117)
	at ai.e(ai.java:364)
	at ai.run(ai.java:318)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### RuneLite version

RuneLite version 1.8.34.1
Oldschool revision 208
Launcher version 2.1.3

I also just started testing Runelite in safe mode to see if the problem persists, has not crashed yet in 1.5 hours of playing.

### Logs

Most Recent (Two crashes today):
[client.log](https://github.com/runelite/runelite/files/9691326/client.log)
[launcher.log](https://github.com/runelite/runelite/files/9691327/launcher.log)

Other Recent:
[jvm_crash_pid_12364.log](https://github.com/runelite/runelite/files/9691331/jvm_crash_pid_12364.log)
[client_2022-09-30.0.log](https://github.com/runelite/runelite/files/9691337/client_2022-09-30.0.log)
[launcher_2022-09-30.0.log](https://github.com/runelite/runelite/files/9691338/launcher_2022-09-30.0.log)

**Comment by Acronyte** [comment]
Running RuneLite in safe mode seems to fix the issue. Played the game for about 3 hours earlier without crashes

**Comment by Acronyte** [comment]
Hi Adam, I mentioned running RuneLite in safe mode but obviously that isn't a good long-term solution. If you know something that made you decide to close the issue, can you tell me please? The issue is still there. I'm just trying to fix my game. Thanks.

**Comment by Adam-** [comment]
If it works in safe mode, then it means the problem is with a 3rd party plugin you've installed. This is not my problem, and so the issue is closed. If you can show the problem is with core RuneLite, I will gladly reopen.
