### ISSUE TITLE
GPU plugin not working linux

### ISSUE THREAD

**Issue by allandarity** [runelite/runelite#15795]
### Type

GPU

### Operating System

Linux

### OS Version

Fedora 36

### Bug description

Trying to use the GPU plugin instant-turns off with the error. RuneLite is installed as a flatpak

GFX Card - Nvidia Geforce GTX 1070
Windowing System - Wayland & X11

```2022-10-11 09:00:38 [Client] ERROR n.r.client.plugins.gpu.GpuPlugin - Error starting GPU plugin
java.lang.RuntimeException: unable to find a fb config
        at net.runelite.rlawt.AWTContext.createGLContext(Native Method)
        at net.runelite.client.plugins.gpu.GpuPlugin.lambda$startUp$1(GpuPlugin.java:292)
        at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
        at net.runelite.client.callback.Hooks.tick(Hooks.java:209)
        at client.jh(client.java:201)
        at client.o(client.java)
        at ai.l(ai.java:338)
        at ai.run(ai.java:317)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

```
❯ lspci | egrep 'VGA|NVIDIA'
08:00.0 VGA compatible controller: NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1)
08:00.1 Audio device: NVIDIA Corporation GP104 High Definition Audio Controller (rev a1)
```
```
❯ glxinfo | grep OpenGL
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce GTX 1070/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 515.76
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6.0 NVIDIA 515.76
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 515.76
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
❯ 
❯ set | grep -e ^XDG_; lspci | grep -i -e vga -e hdmi \
| while read -r DEV_ID SKIP; do lspci -k -n -n -s ${DEV_ID}; done
XDG_CURRENT_DESKTOP=GNOME
XDG_DATA_DIRS=/home/elliott/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
XDG_MENU_PREFIX=gnome-
XDG_RUNTIME_DIR=/run/user/1000
XDG_SESSION_CLASS=user
XDG_SESSION_DESKTOP=gnome
XDG_SESSION_TYPE=wayland
08:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP104 [GeForce GTX 1070] [10de:1b81] (rev a1)
	Subsystem: ASUSTeK Computer Inc. Device [1043:8599]
	Kernel driver in use: nvidia
	Kernel modules: nouveau, nvidia_drm, nvidia```


### Screenshots or videos

_No response_

### RuneLite version

RuneLite: 1.9.1
Launcher: 2.5.0

### Logs

[client.log](https://github.com/runelite/runelite/files/9757680/client.log)
[launcher.log](https://github.com/runelite/runelite/files/9757682/launcher.log)

**Comment by fatfingers23** [comment]
I had a similar issue on Pop_Os  with the same card. I ended up using the appimage from the site, solving the issue.  Your error message is different than mine, but it still may be worth it to try. If I recall, my issue had to do with a differences in the OpenGL version the Flatpak version was using vs appimage.

**Comment by allandarity** [comment]
> I had a similar issue on Pop_Os with the same card. I ended up using the appimage from the site, solving the issue. Your error message is different than mine, but it still may be worth it to try. If I recall, my issue had to do with a differences in the OpenGL version the Flatpak version was using vs appimage.

grabbing the AppImage has actually got it working. Thanks very much

**Comment by aHooder** [comment]
You might have to update `org.freedesktop.Platform.GL.nvidia` through Flatpak after a driver update for the Flatpak to work

**Comment by allandarity** [comment]
> You might have to update `org.freedesktop.Platform.GL.nvidia` through Flatpak after a driver update for the Flatpak to work

updating that version has also got the flatpak image working.

Thanks both
