### ISSUE TITLE
Client error: null on macOS

### ISSUE THREAD

**Issue by mllrjb** [runelite/runelite#15817]
### Type

Crash or hang

### Operating System

MacOS

### OS Version

macOS 12.6 (Monterey)

### Bug description

I'm seeing a crash in safe mode:

```
2022-10-17 18:34:57 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,440,272,801x531,invalid,layout=java.awt.BorderLayout,title=RuneLite (safe mode),resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,28,801x503,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2022-10-17 18:38:37 [Client] ERROR client-patch - Client error: null
java.lang.ArrayIndexOutOfBoundsException: Index 128 out of bounds for length 128
	at gw.a(gw.java:28)
	at ak.a(ak.java:24)
	at aj.st(aj.java:54)
	at ae.u(ae.java:166)
	at client.at(client.java:1119)
	at ae.v(ae.java:389)
	at ae.run(ae.java:368)
	at java.base/java.lang.Thread.run(Unknown Source)
error_game_crash
```

### RuneLite version

RuneLite version: 1.9.1
Oldschool revision: Rev 209
Launcher version: 2.2.0

### Logs

[client.log](https://github.com/runelite/runelite/files/9805416/client.log)
[launcher.log](https://github.com/runelite/runelite/files/9805417/launcher.log)

**Comment by mllrjb** [comment]
I appear to get the same error with the official client as well, so looks like not a RuneLite issue.
