### ISSUE TITLE
Menu Entry Swapper (MES) NPE

### ISSUE THREAD

**Issue by rdutta** [runelite/runelite#15941]
### Type

Other

### Operating System

Windows

### OS Version

Win11

### Bug description

Warn message in console.

### Screenshots or videos

```
[Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
        at net.runelite.client.plugins.menuentryswapper.MenuEntrySwapperPlugin.swapMenuEntry(MenuEntrySwapperPlugin.java:1455)
        at net.runelite.client.plugins.menuentryswapper.MenuEntrySwapperPlugin.onPostMenuSort(MenuEntrySwapperPlugin.java:1531)
        at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
        at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
        at net.runelite.client.callback.Hooks.post(Hooks.java:190)
        at client.fl(client.java:43302)
        at client.ga(client.java:3518)
        at client.ad(client.java:1144)
        at ae.v(ae.java:389)
        at ae.run(ae.java:368)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

### RuneLite version

`1.9.4-SNAPSHOT`

**Comment by Adam-** [comment]
fixed in e8a65a32f1bf6c4f85dbd05fc9af54f7de897d61
