### ISSUE TITLE
RuneLite Client Crash whilst Blackjacking

### ISSUE THREAD

**Issue by HuughesRS** [runelite/runelite#16083]
### Type

Crash or hang

### Operating System

Windows

### OS Version

Windows 10, 21H2

### Bug description

Client completely froze whilst I was blackjacking

2022-12-30 09:34:14 [Client] INFO  c.f.controller.FlippingPlugin - account is an ironman, not adding it to the cache
2022-12-30 09:48:51 [AWT-EventQueue-0] INFO  c.f.controller.DataHandler - storing data
2022-12-30 09:48:51 [AWT-EventQueue-0] INFO  c.f.controller.DataHandler - account wide data changed, saving it.
2022-12-30 09:48:51 [AWT-EventQueue-0] INFO  c.f.db.TradePersister - storing trades for accountwide
2022-12-30 09:48:51 [AWT-EventQueue-0] INFO  c.f.controller.DataHandler - successfully stored account wide data
2022-12-30 09:48:51 [AWT-EventQueue-0] INFO  c.f.jobs.WikiDataFetcherJob - shut down wiki fetching job
2022-12-30 09:48:51 [AWT-EventQueue-0] INFO  c.f.jobs.SlotSenderJob - shut down slot sender job
2022-12-30 09:48:51 [pool-8-thread-1] INFO  c.f.jobs.CacheUpdaterJob - change in directory for accountwide.json with event: ENTRY_MODIFY
2022-12-30 09:48:51 [pool-8-thread-1] INFO  c.f.jobs.CacheUpdaterJob - not duplicate event, firing callbacks
2022-12-30 09:48:51 [pool-8-thread-1] INFO  c.f.jobs.CacheUpdaterJob - shutting down cache updater due to the client shutdown
2022-12-30 09:49:01 [RuneLite Shutdown] WARN  n.r.client.events.ClientShutdown - Error during shutdown: 
java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
	at net.runelite.client.events.ClientShutdown.waitForAllConsumers(ClientShutdown.java:60)
	at net.runelite.client.ui.ClientUI.lambda$shutdownClient$11(ClientUI.java:693)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-12-30 09:49:01 [RuneLite Shutdown] WARN  n.r.client.events.ClientShutdown - Timed out waiting for task completion
2022-12-30 09:49:12 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.9.6 (launcher version 2.4.5) starting up, args: none

I have updated my launcher since to 2.5.0 however with me being a HC I was wondering if anyone has any suggestions as to what is causing it to make sure this doesn't happen again. I lost my previous HCIM to a client crash at Bandos whilst using the "Twitch live loadout" plugin however I removed this last year and haven't had a client crash since.

Thanks,
HuughesRS

### Screenshots or videos

https://user-images.githubusercontent.com/101931675/210068317-d6f8e3ff-dbb9-4088-97b2-b3b604440a1a.mp4

### RuneLite version

RuneLite version 1.9.6 
Launcher version 2.4.5

### Logs
[client.log](https://github.com/runelite/runelite/files/10324633/client.log)

**Comment by Enriath** [comment]
Generally, most issues like this are to do with hub plugins, and therefore have nothing to do with RuneLite

The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.
