### ISSUE TITLE
Client randomly crashing

### ISSUE THREAD

**Issue by mjpilotto** [runelite/runelite#16098]
### Type

Crash or hang

### Operating System

Windows

### OS Version

11

### Bug description

Clinet randomly crashes

### Screenshots or videos

2023-01-02 00:34:34 [Client] ERROR client-patch - Client error: null
java.lang.ArrayIndexOutOfBoundsException: Index 16777241 out of bounds for length 40
	at ne.am(ne.java:650)
	at nv.h(nv.java:43)
	at ne.si(ne.java:509)
	at ne.s(ne.java:343)
	at ay.kv(ay.java:10597)
	at ay.kv(ay.java:10453)
	at ay.kv(ay.java:10452)
	at ay.kv(ay.java:10452)
	at ay.kv(ay.java:10452)
	at ce.ke(ce.java:10310)
	at ay.kv(ay.java:10456)
	at ay.kv(ay.java:10452)
	at ay.kv(ay.java:10452)
	at ay.kv(ay.java:10452)
	at ce.ke(ce.java:10310)
	at client.hq(client.java:4330)
	at client.ab(client.java:1126)
	at an.am(an.java:416)
	at an.run(an.java:370)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Nightfirecat** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions or support.
