### ISSUE TITLE
Runelite crashes after "Verifying"

### ISSUE THREAD

**Issue by Edvv4rdd** [runelite/runelite#16115]
### Type

Crash or hang

### Operating System

Windows

### OS Version

Win10

### Bug description

Trying to launch, first window pops and after downloading bootstrap ... verifying crashes.

I am trying to install it on win10 laptop with touchscreen, it's might a problem idk..

no gpu 
cpu-ryzen4500u

### RuneLite version

latest version of runelite and jagex launcher.
also standalone osrs works fine.

### Logs

```
2023-01-06 04:09:32 [main] INFO  net.runelite.launcher.Launcher - Verified hash of client-1.9.6.jar
2023-01-06 04:09:32 [main] INFO  net.runelite.launcher.Launcher - Verified hash of slf4j-api-1.7.25.jar
2023-01-06 04:09:32 [main] INFO  net.runelite.launcher.Launcher - Verified hash of logback-classic-1.2.9.jar
2023-01-06 04:09:32 [main] INFO  net.runelite.launcher.Launcher - Verified hash of logback-core-1.2.9.jar
2023-01-06 04:09:32 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jopt-simple-5.0.1.jar
2023-01-06 04:09:32 [main] INFO  net.runelite.launcher.Launcher - Verified hash of guava-23.2-jre.jar
2023-01-06 04:09:32 [main] INFO  net.runelite.launcher.Launcher - Verified hash of guice-4.1.0-no_aop.jar
2023-01-06 04:09:32 [main] INFO  net.runelite.launcher.Launcher - Verified hash of javax.inject-1.jar
2023-01-06 04:09:32 [main] INFO  net.runelite.launcher.Launcher - Verified hash of aopalliance-1.0.jar
2023-01-06 04:09:32 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gson-2.8.5.jar
2023-01-06 04:09:32 [main] INFO  net.runelite.launcher.Launcher - Verified hash of substance-8.0.02.jar
2023-01-06 04:09:32 [main] INFO  net.runelite.launcher.Launcher - Verified hash of trident-1.5.00.jar
2023-01-06 04:09:32 [main] INFO  net.runelite.launcher.Launcher - Verified hash of commons-text-1.2.jar
2023-01-06 04:09:32 [main] INFO  net.runelite.launcher.Launcher - Verified hash of commons-lang3-3.7.jar
2023-01-06 04:09:32 [main] INFO  net.runelite.launcher.Launcher - Verified hash of archive-patcher-applier-1.2.jar
2023-01-06 04:09:32 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jna-5.9.0.jar
2023-01-06 04:09:32 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jna-platform-5.9.0.jar
2023-01-06 04:09:32 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jsr305-3.0.2.jar
2023-01-06 04:09:32 [main] INFO  net.runelite.launcher.Launcher - Verified hash of protobuf-javalite-3.21.12.jar
2023-01-06 04:09:32 [main] INFO  net.runelite.launcher.Launcher - Verified hash of rlawt-1.3.jar
2023-01-06 04:09:32 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jocl-1.0.jar
2023-01-06 04:09:32 [main] INFO  net.runelite.launcher.Launcher - Verified hash of lwjgl-3.3.1.jar
2023-01-06 04:09:32 [main] INFO  net.runelite.launcher.Launcher - Verified hash of lwjgl-3.3.1-natives-windows.jar
2023-01-06 04:09:32 [main] INFO  net.runelite.launcher.Launcher - Verified hash of lwjgl-opengl-3.3.1.jar
2023-01-06 04:09:32 [main] INFO  net.runelite.launcher.Launcher - Verified hash of lwjgl-opengl-3.3.1-natives-windows.jar
2023-01-06 04:09:32 [main] INFO  net.runelite.launcher.Launcher - Verified hash of client-patch-1.9.6.jar
2023-01-06 04:09:32 [main] INFO  net.runelite.launcher.Launcher - Verified hash of http-api-1.1.8.jar
2023-01-06 04:09:32 [main] INFO  net.runelite.launcher.Launcher - Verified hash of okhttp-3.14.9.jar
2023-01-06 04:09:32 [main] INFO  net.runelite.launcher.Launcher - Verified hash of okio-1.17.2.jar
2023-01-06 04:09:32 [main] INFO  net.runelite.launcher.Launcher - Verified hash of discord-1.4.jar
2023-01-06 04:09:32 [main] INFO  net.runelite.launcher.Launcher - Verified hash of runelite-api-1.9.6-runtime.jar
2023-01-06 04:09:33 [RuneLite] ERROR n.r.launcher.ReflectionLauncher - Unable to launch client
java.lang.ClassNotFoundException: net.runelite.client.RuneLite
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at net.runelite.launcher.ReflectionLauncher.lambda$launch$0(ReflectionLauncher.java:58)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by Alexsuperfly** [comment]
the log makes me thing this is caused by #15301.
if you pass `--debug` when launching I suspect the log will show that

**Comment by Edvv4rdd** [comment]
> the log makes me think this is caused by #15301. if you pass `--debug` when launching I suspect the log will show that

Sounds like it will solve the problem, will try it.
Thanks!

**Comment by Adam-** [comment]
This is probably due to a launcher 2.6.0 regression, try <https://github.com/runelite/launcher/releases/download/2.6.1/RuneLiteSetup.exe>

**Comment by Edvv4rdd** [comment]
> the log makes me think this is caused by #15301. if you pass `--debug` when launching I suspect the log will show that
It solved the issue. Thanks!
