### ISSUE TITLE
ItemPricesOverlay NPE

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#16175]
### Type

Other

### Operating System

Linux

### OS Version

Linux debian 5.10.0-20-amd64

### Bug description

Found this in my client log from the other day:

```
2023-01-16 12:26:45 [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
	at net.runelite.client.plugins.itemprices.ItemPricesOverlay.render(ItemPricesOverlay.java:126)
	at net.runelite.client.ui.overlay.OverlayRenderer.safeRender(OverlayRenderer.java:735)
	at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlays(OverlayRenderer.java:328)
	at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlayLayer(OverlayRenderer.java:235)
	at net.runelite.client.callback.Hooks.drawAboveOverheads(Hooks.java:496)
	at ht.uc(ht.java:51287)
	at ht.fy(ht.java:116)
	at bj.hb(bj.java:4730)
	at ay.kv(ay.java:10421)
	at ay.kv(ay.java:10452)
	at ay.kv(ay.java:10452)
	at ay.kv(ay.java:10452)
	at ce.ke(ce.java:10310)
	at client.hq(client.java:4330)
	at client.ab(client.java:1126)
	at an.am(an.java:416)
	at an.run(an.java:370)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

[Looking at the code](https://github.com/runelite/runelite/blob/dea7e21c8939c58f1b58225a1bc8162cc928f8e4/runelite-client/src/main/java/net/runelite/client/plugins/itemprices/ItemPricesOverlay.java#L126), I'm not sure how it would have been caused and I don't remember it leading to issues, but we should look at fixing this eventually.

### RuneLite version

RuneLite version: 1.9.8-SNAPSHOT (master + various dev branches)

**Comment by SkylerPIlot** [comment]
I've had this bug before, with no ill effects on gameplay other then clogging up the client log. I'll try to replicate it and diagnose the actual cause. But we should be able to fix this by cleanly handling`if(menuEntry.getWidget().getId() == null)` yea?

**Comment by Nightfirecat** [comment]
No, adding that line would also cause an NPE. (because `menuEntry.getWidget()` is null) We should probably try to find out what case causes a `WIDGET_TARGET` menu entry to be added which wouldn't have a widget set, that seems like incorrect API behavior.
