### ISSUE TITLE
GPU plugin on FreeBSD

### ISSUE THREAD

**Issue by Limero** [runelite/runelite#16327]
### Type

GPU

### Operating System

None

### OS Version

FreeBSD 13.1

### Bug description

I've spent some time trying to get the GPU plugin to work on FreeBSD but it seems to currently be blocked by lwjgl lacking native FreeBSD support. See https://github.com/LWJGL/lwjgl3/issues/421

## rlawt

Changes are required to RuneLite's [rlawt library](https://github.com/runelite/rlawt)

I did the following for rlawt to work:
Dependencies (might be more/less than this): `pkg install libX11 mesa-libs mesa-devel`

Modify the `os.contains("nux")` switch in `AWTContext.java` to cover FreeBSD as well

Modify the CMakeLists.txt to find the libraries:
```
elseif (UNIX)
  include_directories(/usr/local/include)
  find_library(OPENGL OpenGL)
  find_library(GLX GLX)
  target_link_libraries(rlawt ${OPENGL} ${GLX})
endif ()
```

## lwjgl

For lwjgl, I attempted to just symlink the libraries

```
ln -s /usr/lib/libpthread.so /usr/lib/libpthread.so.0
ln -s /lib/libc.so.7 /lib/libc.so.6
ln -s /usr/lib/libdl.so /usr/lib/libdl.so.2
```

But it resulted in the following error when enabling the GPU plugin
```
[Client] ERROR n.r.client.plugins.gpu.GpuPlugin - Error starting GPU plugin
java.lang.UnsatisfiedLinkError: /tmp/lwjgl-rl-amd64/3.3.1-build-7/liblwjgl.so: /usr/lib/libdl.so.1: version GLIBC_2.2.5 required by /tmp/lwjgl-rl-amd64/3.3.1-build-7/liblwjgl.so not found
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2445)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2501)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2700)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2630)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at org.lwjgl.system.Library.loadSystem(Library.java:179)
	at org.lwjgl.system.Library.loadSystemFromLibraryPath(Library.java:169)
	at org.lwjgl.system.Library.loadSystem(Library.java:124)
	at org.lwjgl.system.Library.loadSystem(Library.java:63)
	at org.lwjgl.system.Library.<clinit>(Library.java:51)
	at org.lwjgl.opengl.GL.<clinit>(GL.java:80)
	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$startUp$1(GpuPlugin.java:308)
	at net.runelite.client.callback.ClientThread.invokeList(ClientThread.java:119)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:101)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:213)
	at client.kp(client.java:51836)
	at client.ax(client.java)
	at aj.d(aj.java:377)
	at aj.run(aj.java:356)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

I also attempted to replace the .so file in the linux lwjgl jar with [one built for FreeBSD](https://github.com/LWJGL/lwjgl3/issues/421#issuecomment-1445053439)

```
Unpack .jar
jar xf lwjgl-3.3.1-natives-linux.jar

Replace liblwjgl.so

Repack .jar
jar cvf lwjgl-3.3.1-natives-linux.jar META-INF linux
```

But that resulted in this error when enabling GPU plugin:
```
[Client] ERROR n.r.client.plugins.gpu.GpuPlugin - Error starting GPU plugin
java.lang.UnsatisfiedLinkError: 'long org.lwjgl.system.linux.DynamicLinkLoader.ndlopen(long, int)'
	at org.lwjgl.system.linux.DynamicLinkLoader.ndlopen(Native Method)
	at org.lwjgl.system.linux.DynamicLinkLoader.dlopen(DynamicLinkLoader.java:67)
	at org.lwjgl.system.linux.LinuxLibrary.loadLibrary(LinuxLibrary.java:30)
	at org.lwjgl.system.linux.LinuxLibrary.<init>(LinuxLibrary.java:20)
	at org.lwjgl.system.APIUtil.apiCreateLibrary(APIUtil.java:111)
	at org.lwjgl.system.Library.loadNative(Library.java:363)
	at org.lwjgl.system.Library.loadNative(Library.java:308)
	at org.lwjgl.system.Library.loadNative(Library.java:414)
	at org.lwjgl.system.Library.loadNative(Library.java:381)
	at org.lwjgl.opengl.GL.create(GL.java:101)
	at org.lwjgl.opengl.GL.<clinit>(GL.java:85)
	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$startUp$1(GpuPlugin.java:308)
	at net.runelite.client.callback.ClientThread.invokeList(ClientThread.java:119)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:101)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:213)
	at client.kp(client.java:51836)
	at client.ax(client.java)
	at aj.d(aj.java:377)
	at aj.run(aj.java:356)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### RuneLite version

RuneLite version: 1.9.11.2
Launcher version: 2.5.0

**Comment by Adam-** [comment]
As you've already identified, lwjgl doesn't support freebsd. We are unlikely to want to roll our own support outside of lwjgl due to the fact approximately noone uses any of the bsds. If lwjgl were to get proper support for it upstream though it would not be too difficult for us to add. So it is best for you to direct your efforts at trying to upstream bsd support into lwjgl.

**Comment by bdnugget** [comment]
Same problem, FreeBSD 14.0-RELEASE-p6.
I also notice hardware acceleration is turned off when starting Runelite, don't know if this is obvious Sherlock info or helpful:
```
2024-04-14 21:41:43 [main] INFO  net.runelite.launcher.Launcher - RuneLite Launcher version 2.2.0
2024-04-14 21:41:43 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to OFF
```

**Comment by Adam-** [comment]
It looks like lwjgl 3.3.4 will support freebsd https://github.com/LWJGL/lwjgl3/commit/b693e56774f55d00d23ebc2ceef81f6f4f5496ce, so this should be something we can add.
