### ISSUE TITLE
Poor AMD GPU performance with Mesa driver

### ISSUE THREAD

**Issue by deadmeu** [runelite/runelite#16354]
### Type

GPU

### Operating System

Linux

### OS Version

Arch Linux 6.2.2 - KDE Plasma 5.27.2 (Wayland)

### Bug description

My GPU is pinned at very high usage even at low framerates & window resolution.

I recently upgraded to a 7900 XT and moved from XFCE to KDE. Before moving, I tested RuneLite and saw excellent performance (easily 100+ fps with either the GPU or 117 HD plugin).

Currently I'm running the 7900 XT with the latest Mesa drivers on Wayland (under the latest version of KDE). RuneLite has been installed from Flathub. I have not yet tested compiling my own version but I'll try it out and update with the results.

With the window reduced down to its smallest size and the camera zoomed in all the way looking at the ground the performance looks roughly like this:

| FPS Limit | GPU Utilisation |
| --- | --- |
| 10 | 12.5% |
| 20 | 25% |
| 30 | 40% |
| 40 | 50% |
| 50 | 60% |
| 60 | 75% |
| 70 | 87.5% |
| 80 | 100% |

Enabling the 117  HD plugin causes the GPU Utilisation percentage to increase by about 30 points, and caps out at about 50fps.

If there's a way to profile the GPU performance of RuneLite please let me know so I can try to see what's being called under the hood.

### RuneLite version

RuneLite Version: 1.9.11.2
Launcher Version: 2.5.0

### Logs

[launcher.log](https://github.com/runelite/runelite/files/10906928/launcher.log)
[client.log](https://github.com/runelite/runelite/files/10906930/client.log)

**Comment by Espionage724** [comment]
With the built-in GPU plugin, try disabling Compute Shaders. Not sure what that option is supposed to do, but I've seen large FPS improvements on both a 6600 XT and Intel UHD 630 with turning it off and nothing seemingly looks different.

**Comment by Espionage724** [comment]
Does performance change with KDE with Xorg?

Also have you tried the AppImage of RL or running it through Java?

**Comment by Immovality** [comment]
I had a similar problem with my 6900 XT. Using progl to launch runelite solved the issue for me at the time. 

Since you're also on arch, you read through here, on what you need to install.
https://wiki.archlinux.org/title/AMDGPU_PRO

Oddly enough, with my 7900 XTX I no longer have the issue without progl.

**Comment by Immovality** [comment]
> I'd rather avoid installing any of the proprietary drivers for now as I don't think this is a driver issue. I was previously using the mesa drivers on my XFCE install and performance was great, much better compared to my previous GPU (NVIDIA GTX 1070). It seems like it must be a KDE thing (maybe something to do with KWin?)

The nice thing about the amdgpu-pro-oglp package, is that it doesn't prioritize itself over any of your drives, it just gives you the ability to launch programs under it when prefixed with progl. 

Although when I last used it, the package was known as amdgpu-pro-libgl, but they appear to be the same thing.


> So it sounds like RuneLite is working fine with your 7900 XTX? Are you also running KDE with mesa drivers or something else?

I'm running KDE 5.27.3 Wayland  on Arch Linux 6.2.8 with the mesa-git aur.

**Comment by kujan** [comment]
I have the same issue on Arch 6.2.9 with a 7900 XTX, running X. Game runs fine for most of the time and then I will get 100% GPU utilization at max core clock with frame drops until I disable "compute shaders" in the GPU plugin (and reload it). Reboot fixes issue until it comes back after some time (hours to days). No issues in other games.

**Comment by kujan** [comment]
After 2 weeks running mesa 23.0.0-3, I have been unable to reproduce the issue on my system.

**Comment by GnomeBeans** [comment]
I have the same issue I'm on endeavour 6.6.8 linux with a 6800 xt using mesa drivers. Frame rate is artificially low and gpu usage is max. I install progl and launch with that and can attain 144 vs about half that. Usage is much less as well. If anyone wants diagnostic data let me know.

**Comment by Wolfizen** [comment]
Disabling compute shaders returned performance to expected levels. I did not install AMDGPU Pro.

**Comment by Fornax96** [comment]
Is there really no fix for this issue? This is a big problem for me. I recently upgraded from a GTX 980 Ti to a RX 7900 GRE, and my FPS in game went from 100 to 5. The Compute Shaders option helps a little bit, but I'm still stuck at 20 FPS. Far from playable.

I tried a ton of other games and they all work great, RuneLite is really the only game with this problem. I also tried the Runescape client from Steam, I could not get an FPS counter to show up but it looked smooth. And I tried HDOS, I got 300 FPS at the highest graphics settings there.

How is it possible that such a powerful GPU performs so poorly in one specific game? Is RuneLite just Nvidia exclusive?

**Comment by cdfisher** [comment]
> Is there really no fix for this issue? This is a big problem for me. I recently upgraded from a GTX 980 Ti to a RX 7900 GRE, and my FPS in game went from 100 to 5. The Compute Shaders option helps a little bit, but I'm still stuck at 20 FPS. Far from playable.
> 
> I tried a ton of other games and they all work great, RuneLite is really the only game with this problem. I also tried the Runescape client from Steam, I could not get an FPS counter to show up but it looked smooth. And I tried HDOS, I got 300 FPS at the highest graphics settings there.
> 
> How is it possible that such a powerful GPU performs so poorly in one specific game? Is RuneLite just Nvidia exclusive?
> 
> If there is any way I can help please let me know. I can run debug builds or try experimental tweaks and compile the game myself. If I get annoyed enough I might even start looking for a fix myself, I have no experience with graphics programming though.

Out of curiosity, does performance improve if you have both GPU (and 117 if you use that) disabled?

**Comment by Fornax96** [comment]
> Out of curiosity, does performance improve if you have both GPU (and 117 if you use that) disabled?

With GPU disabled I get a locked 50 FPS. Everything becomes blurry though, and the render distance becomes tiny.

I also tried the 117 plugin (I normally don't have it enabled) and that resulted in even worse performance. About 4 FPS standing in the grand exchange.

**Comment by Fornax96** [comment]
I don't have any other games running. Closing firefox also does not affect performance.

I'll post my specs here for reference
![image](https://github.com/runelite/runelite/assets/1247928/38e24471-e30e-4b69-a172-a69be25baa14)

During startup runelite prints this:

```
2024-06-13 16:38:26 CEST [Client] INFO  n.r.client.plugins.gpu.GpuPlugin - Using device: AMD Radeon RX 7900 GRE (radeonsi, navi31, LLVM 17.0.6, DRM 3.57, 6.9.3-arch1-1)
2024-06-13 16:38:26 CEST [Client] INFO  n.r.client.plugins.gpu.GpuPlugin - Using driver: 4.6 (Compatibility Profile) Mesa 24.1.1-arch1.1
```

`radeontop` tells me that the GPU is barely doing anything though.

**Comment by dotaxis** [comment]
I was having poor performance using 117 HD on Arch with a 7900 XTX, but installing [amdgpu-pro-oglp](https://aur.archlinux.org/packages/amdgpu-pro-oglp/) from the AUR and then launching with `progl bolt` (I use Bolt launcher by Adamcake) downright tripled my FPS at the GE and with maxed out settings I only drop to about 70 in Prif now (was hitting lows of 20 before).

**Comment by IMRogue** [comment]
> I was having poor performance using 117 HD on Arch with a 7900 XTX, but installing [amdgpu-pro-oglp](https://aur.archlinux.org/packages/amdgpu-pro-oglp/) from the AUR and then launching with `progl bolt` (I use Bolt launcher by Adamcake) downright tripled my FPS at the GE and with maxed out settings I only drop to about 70 in Prif now (was hitting lows of 20 before).

is there a way to launch it via desktop entry instead of having to type in progl bolt everytime i wanna launch the game?

**Comment by GnomeBeans** [comment]
> > I was having poor performance using 117 HD on Arch with a 7900 XTX, but installing [amdgpu-pro-oglp](https://aur.archlinux.org/packages/amdgpu-pro-oglp/) from the AUR and then launching with `progl bolt` (I use Bolt launcher by Adamcake) downright tripled my FPS at the GE and with maxed out settings I only drop to about 70 in Prif now (was hitting lows of 20 before).
> 
> is there a way to launch it via desktop entry instead of having to type in progl bolt everytime i wanna launch the game?

create a script and run it ./script.sh

#!/bin/bash
cd /home/user/Downloads/App\ Images/
progl ./RuneLite.AppImage

**Comment by dotaxis** [comment]
> > I was having poor performance using 117 HD on Arch with a 7900 XTX, but installing [amdgpu-pro-oglp](https://aur.archlinux.org/packages/amdgpu-pro-oglp/) from the AUR and then launching with `progl bolt` (I use Bolt launcher by Adamcake) downright tripled my FPS at the GE and with maxed out settings I only drop to about 70 in Prif now (was hitting lows of 20 before).
> 
> is there a way to launch it via desktop entry instead of having to type in progl bolt everytime i wanna launch the game?

For me, I just put an executable bash script called "bolt" in `/usr/local/bin` with these contents:
```bash
#!/bin/sh
# use progl (amdgpu-pro) for bolt-launcher
# fixes 117 HD performance
echo "We are using AMDGPU PRO"
progl /usr/bin/bolt
```

My .desktop files just point to `bolt` and since on my machine `/usr/local/bin` comes before `/usr/bin`, I didn't need to make any other changes

**Comment by IMRogue** [comment]
> > > I was having poor performance using 117 HD on Arch with a 7900 XTX, but installing [amdgpu-pro-oglp](https://aur.archlinux.org/packages/amdgpu-pro-oglp/) from the AUR and then launching with `progl bolt` (I use Bolt launcher by Adamcake) downright tripled my FPS at the GE and with maxed out settings I only drop to about 70 in Prif now (was hitting lows of 20 before).
> > 
> > 
> > is there a way to launch it via desktop entry instead of having to type in progl bolt everytime i wanna launch the game?
> 
> For me, I just put an executable bash script called "bolt" in `/usr/local/bin` with these contents:
> 
> ```shell
> #!/bin/sh
> # use progl (amdgpu-pro) for bolt-launcher
> # fixes 117 HD performance
> echo "We are using AMDGPU PRO"
> progl /usr/bin/bolt
> ```
> 
> My .desktop files just point to `bolt` and since on my machine `/usr/local/bin` comes before `/usr/bin`, I didn't need to make any other changes

thanks, works great.

**Comment by KrauseKurt** [comment]
I can confirm that the issue still exists, the only workaround for now really is using [amdgpu-pro-oglp](aur.archlinux.org/packages/amdgpu-pro-oglp) or your distro equivalent, if your distro doesn't support amd pro gpu drivers you are out of luck.

**Comment by Zavarox** [comment]
Hey guys, just wanna chip in, using GPU (experimental) seems to fix all issues regarding fps. The only downside being that there are lots of graphical glitches (as expected from experimental plugin). Really hoping for a push of this to the main plugin soon.

**Comment by ASong5** [comment]
> I can confirm that the issue still exists, the only workaround for now really is using [amdgpu-pro-oglp](https://aur.archlinux.org/packages/amdgpu-pro-oglp) or your distro equivalent, if your distro doesn't support amd pro gpu drivers you are out of luck.

If anyone knows how to install amdgpu-pro-oglp on Ubuntu please let me know. I'm struggling to figure out how to install it properly.

EDIT: Disregard, managed to get the relevant oglp files on ubuntu and runelite now runs butter smooth. This is THE work-around for this issue which has plagued me for a long time. Thank you to everyone involved in figuring this out.

**Comment by DisturbingShibboleth** [comment]
Tried this today as a workaround, installed `amdgpu-pro-oglp` on arch linux (package version 24.30_2125449-1 on a Vega 64), but the gpu plugin fails to start when launched with `progl runelite` results in:
```
[Client] ERROR n.r.client.plugins.gpu.GpuPlugin - Error starting GPU plugin
java.lang.UnsatisfiedLinkError: /tmp/17582013026052843883librlawt.so: libGL.so.1: cannot enable executable stack as shared object requires: Invalid argument
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:321)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:187)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:129)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2245)
        at java.base/java.lang.Runtime.load0(Runtime.java:767)
        at java.base/java.lang.System.load(System.java:1624)
        at net.runelite.rlawt.AWTContext.loadNatives(AWTContext.java:92)
        at net.runelite.client.plugins.gpu.GpuPlugin.lambda$startUp$1(GpuPlugin.java:297)
        at net.runelite.client.callback.ClientThread.invokeList(ClientThread.java:119)
        at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:101)
        at net.runelite.client.callback.Hooks.tick(Hooks.java:229)
        at client.ab(client.java:25258)
        at client.bw(client.java)
        at bo.bv(bo.java:467)
        at bo.rn(bo.java)
        at bo.run(bo.java:61097)
        at java.base/java.lang.Thread.run(Thread.java:1447)
```
I've verified that the file in tmp that it's looking for exists with `file /tmp/2466495890954454531librlawt.so`:

`/tmp/2466495890954454531librlawt.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=c991d09a0fa1716625663b3c84779853135f40ab, not stripped`

The number before `librlawt.so` changes each time the GPU plugin is enabled, and a new file matching `/tmp/*librlawt.so` is created each time.
Has anyone else seen this behavior?

**Comment by dotaxis** [comment]
@DisturbingShibboleth `sudo execstack -c /usr/lib/amdgpu-pro/libGL.so.1`

**Comment by DisturbingShibboleth** [comment]
@dotaxis Cheers for that - I wasn't aware of `execstack` until now. Looks like something's still up though:
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fda58dceea5, pid=743882, tid=744214
#
# JRE version: OpenJDK Runtime Environment (24.0.1) (build 24.0.1)
# Java VM: OpenJDK 64-Bit Server VM (24.0.1, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [amdgpu_dri.so+0x15ceea5]  InitXThreadsIfNeeded+0x25
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h %d %F" (or dumping to /home/mokou/core.743882)
#
# An error report file with more information is saved as:
# /home/mokou/.runelite/logs/jvm_crash_pid_743882.log
[15.787s][warning][os] Loading hsdis library failed
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
```
`coredumpctl info` reveals `Module /home/mokou/.cache/JNA/temp/jna8393773388563647746.tmp (deleted) without build-id` as the message before the stacktrace.

The current state of the executable stack flags of the amdgpu-pro dir currently looks like this, but I don't know if this is the same issue:
```
- /usr/lib/amdgpu-pro/libEGL.so
- /usr/lib/amdgpu-pro/libEGL.so.1
- /usr/lib/amdgpu-pro/libGLESv1_CM.so
- /usr/lib/amdgpu-pro/libGLESv1_CM.so.1
- /usr/lib/amdgpu-pro/libGLESv2.so
- /usr/lib/amdgpu-pro/libGLESv2.so.2
- /usr/lib/amdgpu-pro/libGL.so
- /usr/lib/amdgpu-pro/libGL.so.1
X /usr/lib/amdgpu-pro/libGL.so.1.2
X /usr/lib/amdgpu-pro/libGLX_amd.so
X /usr/lib/amdgpu-pro/libGLX_amd.so.0
X /usr/lib/amdgpu-pro/libGLX_amd.so.0.0
- /usr/lib/amdgpu-pro/xorg/modules/extensions/libglx.so
```

I can provide the full dump, or the jvm_crash_pid log if those would be helpful?

**Comment by Anjato** [comment]
> [@DisturbingShibboleth](https://github.com/DisturbingShibboleth) `sudo execstack -c /usr/lib/amdgpu-pro/libGL.so.1`

this was the answer for me, thank you! For anyone else's reference, OS info below:

Kernel: 6.15.3-arch1-1
DE: Plasma 6.4.1
GPU: AMD Radeon 6800 XT

**Comment by DisturbingShibboleth** [comment]
@Anjato - you didn't hit the `[warning][os] Loading hsdis library failed` error after running `execstack`?

**Comment by Anjato** [comment]
> [@Anjato](https://github.com/Anjato) - you didn't hit the `[warning][os] Loading hsdis library failed` error after running `execstack`?

The only difference I noticed between my flags and yours is `/usr/lib/amdgpu-pro/libGL.so.1.2`

You could try running `sudo execstack -c /usr/lib/amdgpu-pro/libGL.so.1.2` to clear that flag on that one and see if that works. I didn't see what my flags were set at previously though but looking at my terminal commands history, it looks like I did run that one as well.

**Comment by DisturbingShibboleth** [comment]
@Anjato Gave that a go, but it looks like it's still crashing unfortunately. I've tried installing `java21-openjdk-hsdis` and switching java versions with `sudo archlinux-java set java21-openjdk` but no luck. Looks like it might be getting a bit further though, since I'm now getting `C  [amdgpu_dri.so+0x15ceea5]  InitXThreadsIfNeeded+0x25` as the problematic frame in the crashlog. I'll keep digging, and if I find a fix I'll add it to the thread.

**Comment by DisturbingShibboleth** [comment]
Using `amdgpu-pro-oglp-legacy` solved this for me, looks like support for my gpu was dropped from `amdgpu-pro-oglp`

**Comment by Anjato** [comment]
> Using `amdgpu-pro-oglp-legacy` solved this for me, looks like support for my gpu was dropped from `amdgpu-pro-oglp`

ahhh shoot, sorry. I should've asked which GPU you're using. I'm glad it's working for you now though! Hopefully there's a noticeable performance increase. The performance increase I've noticed is like 3x-4x in some more populated areas where I'd dip to 20fps and now it's 100-120 and seems to stabilize around 150-160 in most other areas. That's with maxed out settings on the 117 plugin

**Comment by fishermans-friend** [comment]
Been hitting this one. Spent a long time troubleshooting trying to rule things out. Runelite seems to be the only application having problems, but it also drags the rest of the system down with it when it struggles. Other, much more intensive games run fine. Looking at GPU usage, for whatever reason, it seems the way Runelite uses the GPU makes it not draw any more power, even when well below the limit. We're talking the GPU sitting at a 120W draw struggling, with 100% utilization, when it could be going up to 220W.

I tried the Ubuntu equivalent of `progl`, by attempting to install the pro drivers with `amdgpu-install`, and putting the libs in `LD_LIBRARY_PATH`, but that didn't seem to do the trick. Some things are deprecated though, so maybe I just needed an older version or something, but whatever. Didn't work for me.

What *did* work though, as @Zavarox said, is to install the `GPU (experimental)` plugin instead, and just use that instead. Now I'm easily hitting 60 fps in problem areas (Fossil Island, Civitas illa Fortnite, Prifddinas) and my GPU doesn't even break a sweat. So thanks for that.

It seems to just be way more efficient in general though, so I can't confirm you wouldn't still see the same symptoms on a less powerful GPU (something about the way Runelite uses the GPU not triggering the GPU to increase its power state), but at least the problem itself is fixed for me with this. Happy enough.

**Comment by deadmeu** [comment]
> Been hitting this one. Spent a long time troubleshooting trying to rule things out. Runelite seems to be the only application having problems, but it also drags the rest of the system down with it when it struggles. Other, much more intensive games run fine. Looking at GPU usage, for whatever reason, it seems the way Runelite uses the GPU makes it not draw any more power, even when well below the limit. We're talking the GPU sitting at a 120W draw struggling, with 100% utilization, when it could be going up to 220W.
> 
> I tried the Ubuntu equivalent of `progl`, by attempting to install the pro drivers with `amdgpu-install`, and putting the libs in `LD_LIBRARY_PATH`, but that didn't seem to do the trick. Some things are deprecated though, so maybe I just needed an older version or something, but whatever. Didn't work for me.
> 
> What _did_ work though, as [@Zavarox](https://github.com/Zavarox) said, is to install the `GPU (experimental)` plugin instead, and just use that instead. Now I'm easily hitting 60 fps in problem areas (Fossil Island, Civitas illa Fortnite, Prifddinas) and my GPU doesn't even break a sweat. So thanks for that.
> 
> It seems to just be way more efficient in general though, so I can't confirm you wouldn't still see the same symptoms on a less powerful GPU (something about the way Runelite uses the GPU not triggering the GPU to increase its power state), but at least the problem itself is fixed for me with this. Happy enough.

Thank you for mentioning the GPU (experimental) plugin. I must have missed the original comment, but I was pleasantly surprised to see my performance is rock solid (at least in the GE) using that plugin. Now I can finally play the game again 😛

**Comment by deadmeu** [comment]
With the GPU (experimental) plugin merged into the baseline GPU plugin, I no longer have any performance issues with Mesa drivers, and will close the ticket.

**Comment by tbekolay** [comment]
> With the GPU (experimental) plugin merged into the baseline GPU plugin, I no longer have any performance issues with Mesa drivers, and will close the ticket.

Thank you for this comment! The recent merge led to RuneLite crashing (and fully locking up my computer) for me, using Debian Linux and an AMD RX 6800. Realizing it was a recent merge meant I found the `GPU (legacy)` and switched to it, now everything works as it did before. Thanks RuneLite team!

**Comment by Nightfirecat** [comment]
If you're using Debian unstable, you'll have the needed driver to not crash. Otherwise, Debian testing is likely to receive the needed mesa update in the next handful of weeks. (it likely won't land in stable for quite some time)

**Comment by deadmeu** [comment]
Ugh, closed for three days before an update has tanked the performance again 😔 (I'm guessing due to either 713710e1285012f667510039a0d115777dd5d191 or 06263a8b8927dc1b045894e64f8d73f4350db946 but I'm not sure). Performance was great yesterday, but today, once I zoom out, it tanks. Curiously, my GPU usage doesn't seem to be spiking though. I might open a new ticket soon.

**Comment by cdfisher** [comment]
> Ugh, closed for three days before an update has tanked the performance again 😔 (I'm guessing due to either [713710e](https://github.com/runelite/runelite/commit/713710e1285012f667510039a0d115777dd5d191) or [06263a8](https://github.com/runelite/runelite/commit/06263a8b8927dc1b045894e64f8d73f4350db946) but I'm not sure). Performance was great yesterday, but today, once I zoom out, it tanks. Curiously, my GPU usage doesn't seem to be spiking though. I might open a new ticket soon.

We're aware of the performance regression. There were some stability issues with GPU after GPUe was moved to core, so it needed to be reverted while those issues are being addressed.

**Comment by deadmeu** [comment]
> We're aware of the performance regression. There were some stability issues with GPU after GPUe was moved to core, so it needed to be reverted while those issues are being addressed.

Very glad to hear this, thank you for letting me know.

**Comment by Adam-** [comment]
> Ugh, closed for three days before an update has tanked the performance again 😔 (I'm guessing due to either [713710e](https://github.com/runelite/runelite/commit/713710e1285012f667510039a0d115777dd5d191) or [06263a8](https://github.com/runelite/runelite/commit/06263a8b8927dc1b045894e64f8d73f4350db946) but I'm not sure). Performance was great yesterday, but today, once I zoom out, it tanks. Curiously, my GPU usage doesn't seem to be spiking though. I might open a new ticket soon.

We went back to an older branch yesterday https://github.com/runelite/runelite/tree/1.11 which doesn't have the new gpu changes, due to the update destabilizing the client. We've gone forward again to 1.12 now, but might revert it again in the future. If you want more control over what version you are running you should build from source.

**Comment by ASong5** [comment]
@deadmeu Have you tried the legacy plugin with the pro drivers since the update? I get noticeably worse performance than before despite it having been the best workaround for performance. Is this just a result of the new textures being unoptimized or is there another kind of regression affecting legacy

**Comment by dotaxis** [comment]
I think this might warrant being reopened. Before the rollback in early November, performance was fixed for me on mesa, but since the new renderer was re-released I still need to use amdgpu-pro to get good performance, and the GPU (legacy) plugin gives poor performance under both drivers.
