### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by RuneLiteissues21** [runelite/runelite#16567]
### Type

Crash or hang

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Random crash

### RuneLite version

1.9.15.3
2.1.3

### Logs

2023-05-09 15:47:12 AEST [Client] ERROR client-patch - Client error: null
java.lang.ArrayIndexOutOfBoundsException: Index -2144862125 out of bounds for length 104
	at ie.fv(ie.java:895)
	at ie.fa(ie.java)
	at ie.bg(ie.java:53110)
	at am.id(am.java:4556)
	at ao.lh(ah.java:10079)
	at ao.lh(ah.java:10110)
	at ai.lk(ah.java:9974)
	at client.im(client.java:4317)
	at client.bt(client.java:1204)
	at bm.by(bm.java:379)
	at bm.run(bm.java:333)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Nightfirecat** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions or support.
