### ISSUE TITLE
Client freezes when taking screenshots within TOA

### ISSUE THREAD

**Issue by Batthew12** [runelite/runelite#16597]
### Type

Crash or hang

### Operating System

Windows

### OS Version

Windows 11

### Bug description

Whenever I take a screenshot within the raid, my client freezes.

This has happened on three separate occasions. Twice in the wardens room, and once in the treasure room when it tried to take a screenshot of my loot.

### RuneLite version

Runelite version: 1.10.06
Launcher version: 2.1.3

### Logs

[launcher.log](https://github.com/runelite/runelite/files/11482941/launcher.log)
[client.log](https://github.com/runelite/runelite/files/11482942/client.log)

**Comment by Adam-** [comment]
This is an OOM. Pluginhub plugins typically use lots of memory, and you have 173 of them, so most likely they are pushing you over the 512mb limit. You could profile if you want, or just increase the memory via adding -Xmx to the VM arguments.

**Comment by Failed4life** [comment]
> This is an OOM. Pluginhub plugins typically use lots of memory, and you have 173 of them, so most likely they are pushing you over the 512mb limit. You could profile if you want, or just increase the memory via adding -Xmx to the VM arguments.

This seems to be a relatively common issue amongst various RS communities, due to people just downloading every and any Plugin Hub plugin they can and are not well versed enough to manually raise the JVM limit themselves. Would you consider adjusting the default amount to something like 1024mb instead of 512mb to help alleviate this issue?

**Comment by Adam-** [comment]
Maybe. Can you get a heap dump?

**Comment by Batthew12** [comment]
> > This is an OOM. Pluginhub plugins typically use lots of memory, and you have 173 of them, so most likely they are pushing you over the 512mb limit. You could profile if you want, or just increase the memory via adding -Xmx to the VM arguments.
> 
> This seems to be a relatively common issue amongst various RS communities, due to people just downloading every and any Plugin Hub plugin they can and are not well versed enough to manually raise the JVM limit themselves. Would you consider adjusting the default amount to something like 1024mb instead of 512mb to help alleviate this issue?

Yeah, I did a little looking and found out how to do that. I'm already noticing an increase in performance. That may have been my issue, thanks.

**Comment by Failed4life** [comment]
> Maybe. Can you get a heap dump?

I tried to generate one, but I get an error due to RuneLite blocking attach
`Exception in thread "main" com.sun.tools.attach.AttachNotSupportedException: The VM does not support the attach mechanism
        at jdk.attach/sun.tools.attach.HotSpotAttachProvider.testAttachable(HotSpotAttachProvider.java:153)
        at jdk.attach/sun.tools.attach.AttachProviderImpl.attachVirtualMachine(AttachProviderImpl.java:67)
        at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:207)
        at jdk.jcmd/sun.tools.jmap.JMap.executeCommandForPid(JMap.java:128)
        at jdk.jcmd/sun.tools.jmap.JMap.dump(JMap.java:208)
        at jdk.jcmd/sun.tools.jmap.JMap.main(JMap.java:114)`

**Comment by Nightfirecat** [comment]
You can use the Debug Helper hub plugin to get one

**Comment by Failed4life** [comment]
Hmm ok neat, never knew that plugin existed. I can create one, but I'm not sure it will help? As I'm not experiencing any memory crashes. My suggestion was to help the people that _are_, due to having way too many Plugin Hub plugins installed, like the user that opened this issue

**Comment by Adam-** [comment]
If you aren't getting an OOM, then a heap dump is not useful, correct.

**Comment by Failed4life** [comment]
I figured as much 🫡Perhaps something to consider though, as it seems more and more people (I've noticed) are running into memory heap issues because they just keep downloading new Plugin Hub plugins without removing the ones they never use.... like Pokemon, gotta download (catch) em all!

**Comment by mxiia** [comment]
```
java.lang.NullPointerException: null
    at net.runelite.client.plugins.interacthighlight.InteractHighlightOverlay.renderMouseover(InteractHighlightOverlay.java:119)
    at net.runelite.client.plugins.interacthighlight.InteractHighlightOverlay.render(InteractHighlightOverlay.java:71)
    at net.runelite.client.ui.overlay.OverlayRenderer.safeRender(OverlayRenderer.java:735)
    at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlays(OverlayRenderer.java:328)
    at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlayLayer(OverlayRenderer.java:235)
    at net.runelite.client.callback.Hooks.drawScene(Hooks.java:483)
    at iz.bk(iz.java:61944)
    at ir.ii(ir.java:4975)
    at gr.kp(gr.java:10660)
    at gr.kp(gr.java:10691)
    at im.ke(im.java:10555)
    at client.ie(client.java:4646)
    at client.bb(client.java:1175)
    at ba.bo(ba.java:408)
    at ba.run(ba.java:362)
    at java.base/java.lang.Thread.run(Thread.java:829)
2023-06-06 01:13:57 CDT [Client] INFO  c.weaponcharges.WeaponChargesPlugin - set charges for TUMEKENS_SHADOW to 1300 (rsprofile.Ge7K4RZI)
2023-06-06 01:20:44 CDT [Client] ERROR client-patch - Client error
java.lang.OutOfMemoryError: Java heap space
    at java.desktop/java.awt.image.DataBufferInt.<init>(DataBufferInt.java:75)
    at java.desktop/java.awt.image.Raster.createPackedRaster(Raster.java:467)
    at java.desktop/java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1032)
    at java.desktop/java.awt.image.BufferedImage.<init>(BufferedImage.java:324)
    at rs117.hd.HdPlugin.screenshot(HdPlugin.java:2202)
    at rs117.hd.HdPlugin$$Lambda$3558/0x0000000101011040.get(Unknown Source)
    at net.runelite.client.ui.DrawManager.processDrawComplete(DrawManager.java:84)
    at rs117.hd.HdPlugin.draw(HdPlugin.java:2111)
    at ba.ak(ba.java:27026)
    at ba.run(ba.java:363)
    at java.base/java.lang.Thread.run(Thread.java:829)
2023-06-06 01:21:17 CDT [main] INFO  net.runelite.client.RuneLite - RuneLite 1.10.4 (launcher version 2.6.4) starting up, args: none
2023-06-06 01:21:17 CDT [main] INFO  net.runelite.client.RuneLite - RuneLite 1.10.4 (launcher version 2.6.4) starting up, args: none
2023-06-06 01:21:17 CDT [main] INFO  net.runelite.client.RuneLite - Java VM arguments: -XX:+DisableAttachMechanism -Drunelite.launcher.blacklistedDlls=RTSSHooks.dll,RTSSHooks64.dll,NahimicOSD.dll,NahimicMSIOSD.dll,Nahimic2OSD.dll,Nahimic2DevProps.dll,k_fps32.dll,k_fps64.dll,SS2DevProps.dll,SS2OSD.dll,GTIII-OSD64-GL.dll,GTIII-OSD64-VK.dll,GTIII-OSD64.dll -Xmx512m -Xss2m -XX:CompileThreshold=1500 -Dsun.java2d.opengl=false -Drunelite.launcher.version=2.6.4 -XX:ErrorFile=/home/mxiia/.runelite/logs/jvm_crash_pid_%p.log
2023-06-06 01:21:17 CDT [main] INFO  net.runelite.client.RuneLite - Java VM arguments: -XX:+DisableAttachMechanism -Drunelite.launcher.blacklistedDlls=RTSSHooks.dll,RTSSHooks64.dll,NahimicOSD.dll,NahimicMSIOSD.dll,Nahimic2OSD.dll,Nahimic2DevProps.dll,k_fps32.dll,k_fps64.dll,SS2DevProps.dll,SS2OSD.dll,GTIII-OSD64-GL.dll,GTIII-OSD64-VK.dll,GTIII-OSD64.dll -Xmx512m -Xss2m -XX:CompileThreshold=1500 -Dsun.java2d.opengl=false -Drunelite.launcher.version=2.6.4 -XX:ErrorFile=/home/mxiia/.runelite/logs/jvm_crash_pid_%p.log
```

**Comment by mxiia** [comment]
I'm experiencing the same issue.

It's very clearly a memory leak somewhere, but I'm not sure where. I think it's in the "Tombs of Amascut" plugin and somehow this is affecting the screenshot plugin in particular

Above log is from a client crash during p3 of warden due to a defense level triggering a screenshot

I've also had at least 3 client crashes as I loot the chest - screenshot triggered - and have another ~15 raids that are missing the automatic screenshot for some reason that's likely related

**Comment by mxiia** [comment]
How can I go about helping to get to the bottom of this issue?

**Comment by Nightfirecat** [comment]
Does this behavior happen while running in safe mode?

To open in safe mode on Windows: In Command Prompt, run:
```
"%localappdata%\runelite\runelite.exe" --safe-mode
```

Or on Mac: In Terminal, run:
```
/Applications/RuneLite.app/Contents/MacOS/RuneLite --safe-mode
```

**Comment by jamolnng** [comment]
This also happens to me, this is the error I get from the console. Appears to originate from taking a screenshot, but I've also had it happen in the transition from p3 to p4 wardens which may have been due to a virtual level triggering a screenshot but I cannot be sure. The log suggests it may be 117HD related so I've opened an issue there as well https://github.com/117HD/RLHD/issues/239

```2023-09-24 22:13:23 EDT [Client] ERROR client-patch - Client error
java.lang.OutOfMemoryError: Java heap space
	at java.desktop/java.awt.image.DataBufferInt.<init>(Unknown Source)
	at java.desktop/java.awt.image.Raster.createPackedRaster(Unknown Source)
	at java.desktop/java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
	at java.desktop/java.awt.image.BufferedImage.<init>(Unknown Source)
	at rs117.hd.HdPlugin.screenshot(HdPlugin.java:2205)
	at rs117.hd.HdPlugin$$Lambda$2207/0x0000000100c9ec40.get(Unknown Source)
	at net.runelite.client.ui.DrawManager.processDrawComplete(DrawManager.java:84)
	at rs117.hd.HdPlugin.draw(HdPlugin.java:2113)
	at bb.ab(bb.java:54018)
	at bb.run(bb.java:339)
	at java.base/java.lang.Thread.run(Unknown Source)
```
