### ISSUE TITLE
Crash when teleporting to shazien

### ISSUE THREAD

**Issue by bogu88** [runelite/runelite#16826]
### Type

Crash or hang

### Operating System

Windows

### OS Version

Windows 10

### Bug description

When teleporting to Shayzien via Kharedst's memoirs (History and hearsay), runelite crashes. With the GPU plugin turned off, teleporting there works fine. I'm using a NVIDIA GeForce RTX 3060 Ti, with driver version NVIDIA 531.79

> 2023-07-22 14:36:35 CDT [Map loader] ERROR client-patch - Client error: map loading
java.lang.OutOfMemoryError: null
	at java.base/jdk.internal.misc.Unsafe.allocateMemory(Unknown Source)
	at java.base/java.nio.DirectByteBuffer.<init>(Unknown Source)
	at java.base/java.nio.ByteBuffer.allocateDirect(Unknown Source)
	at net.runelite.client.plugins.gpu.GpuIntBuffer.allocateDirect(GpuIntBuffer.java:81)
	at net.runelite.client.plugins.gpu.GpuIntBuffer.ensureCapacity(GpuIntBuffer.java:67)
	at net.runelite.client.plugins.gpu.SceneUploader.pushModel(SceneUploader.java:388)
	at net.runelite.client.plugins.gpu.SceneUploader.uploadSceneModel(SceneUploader.java:375)
	at net.runelite.client.plugins.gpu.SceneUploader.upload(SceneUploader.java:198)
	at net.runelite.client.plugins.gpu.SceneUploader.upload(SceneUploader.java:77)
	at net.runelite.client.plugins.gpu.GpuPlugin.loadScene(GpuPlugin.java:1470)
	at rl2.rx(Unknown Source)
	at rl2.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-07-22 14:36:35 CDT [Map loader] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.OutOfMemoryError: null
	at java.base/jdk.internal.misc.Unsafe.allocateMemory(Unknown Source)
	at java.base/java.nio.DirectByteBuffer.<init>(Unknown Source)
	at java.base/java.nio.ByteBuffer.allocateDirect(Unknown Source)
	at net.runelite.client.plugins.gpu.GpuIntBuffer.allocateDirect(GpuIntBuffer.java:81)
	at net.runelite.client.plugins.gpu.GpuIntBuffer.ensureCapacity(GpuIntBuffer.java:67)
	at net.runelite.client.plugins.gpu.SceneUploader.pushModel(SceneUploader.java:388)
	at net.runelite.client.plugins.gpu.SceneUploader.uploadSceneModel(SceneUploader.java:375)
	at net.runelite.client.plugins.gpu.SceneUploader.upload(SceneUploader.java:198)
	at net.runelite.client.plugins.gpu.SceneUploader.upload(SceneUploader.java:77)
	at net.runelite.client.plugins.gpu.GpuPlugin.loadScene(GpuPlugin.java:1470)
	at rl2.rx(Unknown Source)
	at rl2.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-07-22 14:36:35 CDT [Client] ERROR client-patch - Client error
java.lang.NullPointerException: null
	at net.runelite.client.plugins.gpu.GpuPlugin.swapScene(GpuPlugin.java:1489)
	at client.gl(client.java:20760)
	at ez.jx(ez.java:58644)
	at client.bw(client.java:1133)
	at bq.bd(bq.java:363)
	at bq.run(bq.java:342)
	at java.base/java.lang.Thread.run(Unknown Source)

### RuneLite version

Runelite version: 1.10.8.3
Launcher version: 2.6.4

**Comment by Felanbird** [comment]
Use the 64-bit client

**Comment by bogu88** [comment]
> Use the 64-bit client

Wow that's embarrassing, I didn't even know I was on the 32bit client. I just downloaded the 64bit client and teleporting there works now. Thanks so much!
