### ISSUE TITLE
Slayer infobox returns `Null` for target when assigned Phantom Muspah

### ISSUE THREAD

**Issue by Felanbird** [runelite/runelite#16889]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

10

### Bug description

When receiving a boss slayer task to slay the Phantom Muspah, the infobox reverts to the default Enchanted gem and the target is set to `Null`

### Screenshots or videos

![image](https://github.com/runelite/runelite/assets/41973452/220b334d-1f8f-4610-9466-5ffc268b461a)
![image](https://github.com/runelite/runelite/assets/41973452/bb0f243e-5c0d-495a-8d0a-776ba8470d14)

### RuneLite version

Tested on 1.10.9.1 and re-tested on the latest master 1.10.10-SNAPSHOT to make sure it wasn't a hub plugin.

### Logs

```
2023-08-05 16:57:43 EDT [main] INFO  net.runelite.client.RuneLite - RuneLite 1.10.10-SNAPSHOT (launcher version unknown) starting up, args: --developer-mode
2023-08-05 16:57:43 EDT [main] INFO  net.runelite.client.RuneLite - Java VM arguments: -ea -javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.3\lib\idea_rt.jar=54688:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.3\bin -Dfile.encoding=UTF-8
2023-08-05 16:57:45 EDT [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2023-08-05 16:57:45 EDT [Preloader] WARN  net.runelite.client.rs.ClientLoader - Cached patch hash mismatches, regenerating patch
2023-08-05 16:57:47 EDT [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 5764448896.216
2023-08-05 16:57:47 EDT [main] INFO  n.r.client.account.SessionManager - No session file exists
2023-08-05 16:57:47 EDT [main] INFO  n.r.client.config.ConfigManager - Profile 'actual default' (sync: false, active: true)
2023-08-05 16:57:47 EDT [main] INFO  n.r.client.config.ConfigManager - Profile '' (sync: false, active: false)
2023-08-05 16:57:47 EDT [main] INFO  n.r.client.config.ConfigManager - Profile 'for-easy-screenshot' (sync: false, active: false)
2023-08-05 16:57:47 EDT [main] INFO  n.r.client.config.ConfigManager - Using profile: actual default
2023-08-05 16:57:52 EDT [main] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2023-08-05 16:57:53 EDT [main] ERROR n.r.c.e.ExternalPluginManager - Unable to download external plugins
java.io.IOException: Non-OK response code: 404
	at net.runelite.client.externalplugins.ExternalPluginClient.downloadManifest(ExternalPluginClient.java:102)
	at net.runelite.client.externalplugins.ExternalPluginClient.downloadManifestLite(ExternalPluginClient.java:83)
	at net.runelite.client.externalplugins.ExternalPluginManager.refreshPlugins(ExternalPluginManager.java:192)
	at net.runelite.client.externalplugins.ExternalPluginManager.loadExternalPlugins(ExternalPluginManager.java:121)
	at net.runelite.client.RuneLite.start(RuneLite.java:351)
	at net.runelite.client.RuneLite.main(RuneLite.java:284)
2023-08-05 16:57:53 EDT [main] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2023-08-05 16:57:55 EDT [pool-2-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user felanbird.
2023-08-05 16:57:56 EDT [Client] ERROR n.r.client.callback.ClientThread - Exception in invoke
java.lang.NullPointerException: Cannot read the array length because "chatIcons" is null
	at net.runelite.client.game.ChatIconManager.refreshIcons(ChatIconManager.java:176)
	at net.runelite.client.callback.ClientThread.lambda$invokeLater$1(ClientThread.java:80)
	at net.runelite.client.callback.ClientThread.invokeList(ClientThread.java:119)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:101)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:217)
	at client.ce(client.java:56174)
	at client.bw(client.java)
	at bq.bd(bq.java:363)
	at bq.run(bq.java:342)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-08-05 16:57:57 EDT [main] INFO  net.runelite.client.RuneLite - Client initialization took 13987ms. Uptime: 16091ms
2023-08-05 16:58:35 EDT [Client] WARN  client-patch - Mismatch in overlaid cache archive hash for 12/909: C0218EBB7488D74689407A1A1E7C23F18E6B9C92F27BF184AA7EEE839DBEBA29 != AFE505CAB72304D58550DAD9CB244482089FFB49A4641630CEE2F483D0C224FB
2023-08-05 16:58:37 EDT [Client] WARN  client-patch - Mismatch in overlaid cache archive hash for 12/909: C0218EBB7488D74689407A1A1E7C23F18E6B9C92F27BF184AA7EEE839DBEBA29 != AFE505CAB72304D58550DAD9CB244482089FFB49A4641630CEE2F483D0C224FB
2023-08-05 16:59:46 EDT [Client] WARN  client-patch - Mismatch in overlaid cache archive hash for 12/909: C0218EBB7488D74689407A1A1E7C23F18E6B9C92F27BF184AA7EEE839DBEBA29 != AFE505CAB72304D58550DAD9CB244482089FFB49A4641630CEE2F483D0C224FB
2023-08-05 17:00:24 EDT [Client] WARN  client-patch - Mismatch in overlaid cache archive hash for 12/909: C0218EBB7488D74689407A1A1E7C23F18E6B9C92F27BF184AA7EEE839DBEBA29 != AFE505CAB72304D58550DAD9CB244482089FFB49A4641630CEE2F483D0C224FB
2023-08-05 17:01:06 EDT [Client] WARN  client-patch - Mismatch in overlaid cache archive hash for 12/909: C0218EBB7488D74689407A1A1E7C23F18E6B9C92F27BF184AA7EEE839DBEBA29 != AFE505CAB72304D58550DAD9CB244482089FFB49A4641630CEE2F483D0C224FB
```

**Comment by Adam-** [comment]
```
diff --git a/scripts/[proc,helper_slayer_current_assignment].cs2 b/scripts/[proc,helper_slayer_current_assignment].cs2
index 8a1516db..8f45f7e3 100644
--- a/scripts/[proc,helper_slayer_current_assignment].cs2
+++ b/scripts/[proc,helper_slayer_current_assignment].cs2
@@ -5,7 +5,7 @@ def_string $string1 = "";
 if (%var394 <= 0) {
        $string1 = "Need assignment";
 } else if (%var395 = 98) {
-       $string1 = enum(int, string, enum_1174, %varbit4723);
+       $string1 = struct_param(enum(int, struct, enum_5008, %varbit4723), param_1801);
 } else if (%var395 > 0) {
        $string1 = enum(int, string, enum_693, %var395);
 } else {

```
