### ISSUE TITLE
Unable to change Custom Notification .wav

### ISSUE THREAD

**Issue by Senko-cloud** [runelite/runelite#16979]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10 Build 19045

### Bug description

Went into runelite plugin settings, found custom notification options, downloaded .wav and added to root of .runelite directory;

Custom notification properly updated just fine. Removed that .wav to replace with a different .wav file. The custom notification sound remains on the old .wav sound even with that file being deleted.

Is there something I'm missing or how can I clear that initial .wav and reset the custom notification to a different sound?

Thanks,

### RuneLite version

Runelite version: 1.10.10.4
Launcher version: 2.6.7

### Logs

[client.log](https://github.com/runelite/runelite/files/12491619/client.log)
[launcher.log](https://github.com/runelite/runelite/files/12491620/launcher.log)

**Comment by Nightfirecat** [comment]
Java's sound loader is having trouble with your notification sound:

```
2023-08-31 13:49:13 HST [pool-3-thread-1] WARN  net.runelite.client.Notifier - Unable to load notification sound
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 44100.0 Hz, 24 bit, stereo, 6 bytes/frame, little-endian not supported.
	at java.desktop/com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(Unknown Source)
	at java.desktop/com.sun.media.sound.DirectAudioDevice$DirectClip.implOpen(Unknown Source)
	at java.desktop/com.sun.media.sound.AbstractDataLine.open(Unknown Source)
	at java.desktop/com.sun.media.sound.DirectAudioDevice$DirectClip.open(Unknown Source)
	at java.desktop/com.sun.media.sound.DirectAudioDevice$DirectClip.open(Unknown Source)
	at net.runelite.client.Notifier.tryLoadNotification(Notifier.java:490)
	at net.runelite.client.Notifier.playCustomSound(Notifier.java:470)
	at net.runelite.client.util.RunnableExceptionLogger.run(RunnableExceptionLogger.java:41)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Try reformatting it--I recommend using a tool such as [Tenacity](https://tenacityaudio.org/) to import it, then re-export it.

**Comment by khogeland** [comment]
What are the expected encoding options?

**Comment by YvesW** [comment]
I'd have to check the specific implementation to be sure, but generally Java likes either 8-bit or 16-bit .wav audio (**not** 24-bit or 32-bit), with sampling rates from 8 kHz to 48 kHz.
So re-encode it as 16-bit instead of 24-bit.
