### ISSUE TITLE
Auto screenshots freezing client in TOA

### ISSUE THREAD

**Issue by joshuatobler** [runelite/runelite#16998]
### Type

Crash or hang

### Operating System

Windows

### OS Version

Windows 11

### Bug description

When completing TOA runs, auto-screenshots are periodically freezing up my client. This has happened 3 times, the first two on the screenshot for a chest open and the third time right as Warden died when I got a combat achievement. Have not confirmed if this is occurring elsewhere

### RuneLite version

Runelite version: 1.10.11.1
Launcher version: 2.4.2

**Comment by Nightfirecat** [comment]
Please upload your logs.

**Comment by joshuatobler** [comment]
[client.log](https://github.com/runelite/runelite/files/12531862/client.log)
[client_2023-09-03.0.log](https://github.com/runelite/runelite/files/12531863/client_2023-09-03.0.log)
Here are my logs from today, as well as from a couple days ago when it happened as well.

**Comment by Nightfirecat** [comment]
You're running out of memory:

```
2023-09-05 17:48:00 EDT [Client] ERROR client-patch - Client error
java.lang.OutOfMemoryError: Java heap space
	at java.desktop/java.awt.image.DataBufferInt.<init>(Unknown Source)
	at java.desktop/java.awt.image.Raster.createPackedRaster(Unknown Source)
	at java.desktop/java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
	at java.desktop/java.awt.image.BufferedImage.<init>(Unknown Source)
	at net.runelite.client.plugins.gpu.GpuPlugin.screenshot(GpuPlugin.java:1443)
	at net.runelite.client.plugins.gpu.GpuPlugin$$Lambda$2968/0x4f2b8c28.get(Unknown Source)
	at net.runelite.client.ui.DrawManager.processDrawComplete(DrawManager.java:84)
	at net.runelite.client.plugins.gpu.GpuPlugin.draw(GpuPlugin.java:1350)
	at bm.ac(bm.java:59762)
	at bm.run(bm.java:382)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Either increase the client's memory limit (via something like `-Xmx1G` in the jvm options via your "RuneLite (configure)" shortcut) or uninstall some hub plugins.
