### ISSUE TITLE
java.lang.OutOfMemoryError while in kruk's dungeon

### ISSUE THREAD

**Issue by aaronenberg** [runelite/runelite#17059]
### Type

Crash or hang

### Operating System

Linux

### OS Version

Debian 11

### Bug description

walking around or hopping worlds while in kruk's dungeon

### RuneLite version

runelite 1.10.13
launcher 2.6.3

### Logs
[launcher.log](https://github.com/runelite/runelite/files/12678856/launcher.log)
[client.log](https://github.com/runelite/runelite/files/12678860/client.log)

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.runelite.client.util.ReflectUtil (file:/home/aaron/.runelite/repository2/client-1.10.13.jar) to field java.lang.reflect.Executable.declaredAnnotations
WARNING: Please consider reporting this to the maintainers of net.runelite.client.util.ReflectUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2023-09-20 20:41:08 EDT [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 6228ms. Uptime: 8572ms
2023-09-20 20:41:08 EDT [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Reset client position. Client bounds: -8x-8x2576x1416
2023-09-20 20:41:08 EDT [Client] INFO  rs117.hd.HdPlugin - Using device: NVIDIA GeForce GTX 1050/PCIe/SSE2
2023-09-20 20:41:08 EDT [Client] INFO  rs117.hd.HdPlugin - Using driver: 4.6.0 NVIDIA 470.182.03
2023-09-20 20:41:08 EDT [Client] INFO  rs117.hd.HdPlugin - Client is 64-bit

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-3-thread-1"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Map loader"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "AWT-XAWT"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-6-thread-1"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Client"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "OkHttp static.runelite.net Writer"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-5-thread-1"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Thread-13"

**Comment by Adam-** [comment]
Is your system out of physical memory? If not, run `RuneLite --configure`, add `-XX:+HeapDumpOnOutOfMemoryError` to the JVM options, start the client again and have it crash, and then run jhat/jvisualvm or some other profiler and see what it using so much memory. Or you can provide the file to us, but not through a public channel.

**Comment by aaronenberg** [comment]
Plenty of memory still. Where is the heap dump file generated?

**Comment by aaronenberg** [comment]
I found this in .xsession-errors

2023-09-20 21:03:04 EDT [Map loader] ERROR client-patch - Client error: map loading
java.lang.OutOfMemoryError: Java heap space
	at jw.ag(jw.java:1229)
	at jw.af(jw.java:30619)
	at jw.ay(jw.java)
	at jt.bv(jt.java:2042)
	at jt.sx(jt.java)
	at rl2.zg(rl2.java:35547)
	at rl2.gz(rl2.java:46843)
	at rl2.run(rl2.java:30149)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-09-20 21:03:06 EDT [Map loader] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOfRange(Unknown Source)
	at java.base/java.lang.String.<init>(Unknown Source)
	at java.base/java.util.jar.Attributes.read(Unknown Source)
	at java.base/java.util.jar.Manifest.read(Unknown Source)
	at java.base/java.util.jar.Manifest.<init>(Unknown Source)
	at java.base/java.util.jar.JarFile.getManifestFromReference(Unknown Source)
	at java.base/java.util.jar.JarFile.getManifest(Unknown Source)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader$2.getManifest(Unknown Source)
	at java.base/java.net.URLClassLoader.defineClass(Unknown Source)
	at java.base/java.net.URLClassLoader$1.run(Unknown Source)
	at java.base/java.net.URLClassLoader$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at net.runelite.client.TelemetryClient.submitError(TelemetryClient.java:142)
	at net.runelite.client.callback.Hooks.error(Hooks.java:645)
	at hk.ac(hk.java:25576)
	at rl2.du(rl2.java)
	at rl2.run(rl2.java:9103)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-09-20 21:03:06 EDT [Thread-1] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.OutOfMemoryError: Java heap space
2023-09-20 21:03:06 EDT [Client] ERROR client-patch - Client error
java.lang.NullPointerException: null
	at client.pe(client.java:56723)
	at be.ke(be.java:8781)
	at client.xv(client.java)
	at client.fq(client.java:26576)
	at je.jb(je.java:60940)
	at client.bo(client.java:1123)
	at bb.ad(bb.java:358)
	at bb.run(bb.java:335)
	at java.base/java.lang.Thread.run(Unknown Source)
error_game_crash

**Comment by Adam-** [comment]
> Plenty of memory still. Where is the heap dump file generated?

It should go either into the cwd or into ~/.runelite/logs.

**Comment by aaronenberg** [comment]
Seems to be an issue with 117hd plugin

**Comment by Adam-** [comment]
Can you provide us with a heap dump showing the issue?

**Comment by aaronenberg** [comment]
when I run `runelite --configure` it throws an error:

2023-09-20 22:03:03 [AWT-EventQueue-0] ERROR n.runelite.launcher.LauncherSettings - unable to save launcher settings!
java.nio.file.FileSystemException: /tmp/.mount_runeliSlOGNp/settings.json: Read-only file system
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixCopyFile.copyFile(Unknown Source)
	at java.base/sun.nio.fs.UnixCopyFile.move(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystemProvider.move(Unknown Source)
	at java.base/java.nio.file.Files.move(Unknown Source)
	at net.runelite.launcher.LauncherSettings.saveSettings(LauncherSettings.java:211)
	at net.runelite.launcher.ConfigurationFrame.save(ConfigurationFrame.java:228)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
2023-09-20 22:03:03 [AWT-EventQueue-0] INFO  n.r.launcher.ConfigurationFrame - Updated launcher configuration:
 debug: false
 nodiffs: false
 skip tls verification: false
 noupdates: false
 safe mode: true
 scale: system
 client arguments: none
 jvm arguments: none
 hardware acceleration mode: AUTO
 launch mode: AUTO

**Comment by Adam-** [comment]
Oh you are using the appimage? This is probably OOMing because it did not automatically get the memory increase from 512m -> 768m we changed recently. If you pass `-J -Xmx768m` it should probably be fine.  If it still crashes at `-Xmx768m` I would be interested in a heap dump, though.

**Comment by aaronenberg** [comment]
It seems as though any JVM args I specify are being ignored. The help text for mentions they only apply with `--launch-mode FORK | JVM` but when I try to set that it gets ignored and is always `REFLECT`

**Comment by Adam-** [comment]
This is very confusing because there are three different command line parsers and two of them accept two different -J arguments. `runelite -c -J -Xmx768m -- --launch-mode=REFLECT` should do it. The appimage launcher can't support fork or jvm mode because, iirc, once the main process exits the fuse mount gets unmounted, which breaks the client as it is running with it.

**Comment by aaronenberg** [comment]
That fixed it. No more crashing in Kruk's dungeon when hopping worlds or randomly while walking around

**Comment by awused** [comment]
I ran into this as well, I think even the current increased setting is not enough. I crashed several times before finding this bug, but after increasing the heap limit to 4GB (I didn't experiment with lower values) the crashes went away.
