### ISSUE TITLE
NullPointerException | Ground Items Plugin

### ISSUE THREAD

**Issue by minkeelee** [runelite/runelite#17191]
### Type

Crash or hang (on `-ea`)

### Operating System

None

### OS Version

Windows 11

### Bug description

```
- open rune pouch interface, and then click "use" on an item in inventory same tick
- "use" that clicked item on some game object
boom NPE
```

### RuneLite version

RuneLite version: 1.10.16.1
Launcher version: local

### Logs

```
2023-11-14 11:16:32 EST [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
    at net.runelite.client.plugins.grounditems.GroundItemsPlugin.onMenuOptionClicked(GroundItemsPlugin.java:686)
    at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
    at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
    at net.runelite.client.callback.Hooks.post(Hooks.java:194)
    at px.kx(px.java:11973)
    at client.ja(client.java:15636)
    at client.dn(client.java:346)
    at client.hm(client.java:3516)
    at client.bp(client.java:1161)
    at bm.dt(bm.java:394)
    at bm.gy(bm.java)
    at bm.run(bm.java:49331)
    at java.base/java.lang.Thread.run(Thread.java:829)
2023-11-14 11:16:32 EST [Client] ERROR client-patch - Client error
java.lang.AssertionError: null
    at net.runelite.client.plugins.timetracking.farming.CompostTracker.isCompostAction(CompostTracker.java:163)
    at net.runelite.client.plugins.timetracking.farming.CompostTracker.onMenuOptionClicked(CompostTracker.java:129)
    at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
    at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
    at net.runelite.client.callback.Hooks.post(Hooks.java:194)
    at px.kx(px.java:11973)
    at client.ja(client.java:15636)
    at client.dn(client.java:346)
    at client.hm(client.java:3516)
    at client.bp(client.java:1161)
    at bm.dt(bm.java:394)
    at bm.gy(bm.java)
    at bm.run(bm.java:49331)
    at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by Adam-** [comment]
fixed in f613939c4d1612e812de45ba276b5eb5e6195a62
