### ISSUE TITLE
InteractHighlightPlugin ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by CreativeTechGuy** [runelite/runelite#17439]
### Type

Other

### Operating System

Windows

### OS Version

Windows 10

### Bug description

This bug is seen randomly in the developer console when running RuneLite in IntelliJ.

I cannot determine what exactly happens in game to cause this but it seems like when it occurs, some gameobjects are unhighlightable (despite others still being highlighted on hover). Hopefully from the stack trace it should be preventable. It feels like an issue where an array is modified in another thread while being accessed.

For the Interact Highlight plugin settings, everything is enabled.

### RuneLite version

RuneLite Version:  1.10.21.1
Launcher Version: 2.6.4

### Logs

```
2024-02-01 16:05:36 PST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.ArrayIndexOutOfBoundsException: Index 106 out of bounds for length 104
	at net.runelite.client.plugins.interacthighlight.InteractHighlightPlugin.findTileObject(InteractHighlightPlugin.java:204)
	at net.runelite.client.plugins.interacthighlight.InteractHighlightOverlay.renderMouseover(InteractHighlightOverlay.java:100)
	at net.runelite.client.plugins.interacthighlight.InteractHighlightOverlay.render(InteractHighlightOverlay.java:71)
	at net.runelite.client.ui.overlay.OverlayRenderer.safeRender(OverlayRenderer.java:734)
	at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlays(OverlayRenderer.java:328)
	at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlayLayer(OverlayRenderer.java:235)
	at net.runelite.client.callback.Hooks.drawScene(Hooks.java:486)
```

**Comment by Adam-** [comment]
fixed in 3e6259640868ea831e6e0cf297a6bdf553ffd9a2
