### ISSUE TITLE
Bank Tags TabInterface NPE

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#17460]
Found in logs from the support channel on Discord:

```
2024-02-06 19:48:40 CET [Client] ERROR n.r.client.callback.ClientThread - Exception in invoke
java.lang.NullPointerException: null
	at net.runelite.client.plugins.banktags.tabs.TabInterface.resizeTabLayer(TabInterface.java:1022)
	at net.runelite.client.callback.ClientThread.lambda$invokeLater$1(ClientThread.java:80)
	at net.runelite.client.callback.ClientThread.invokeList(ClientThread.java:119)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:101)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:218)
	at client.uz(client.java:2380)
	at client.bc(client.java)
	at by.za(by.java:403)
	at by.io(by.java)
	at by.run(by.java:7195)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by Nightfirecat** [comment]
This may be fixed with efe297ede78887e4065d5842cf4a92b56aee5c46, but we don't have any known way to repro this, so can't say for certain what behavior it would exhibit now.
