### ISSUE TITLE
Ground Markers NPE

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#17461]
Found in logs from the support channel on Discord:

```
2024-02-04 01:19:32 EST [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at net.runelite.client.plugins.groundmarkers.GroundMarkerPlugin.onMenuEntryAdded(GroundMarkerPlugin.java:327)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:194)
	at client.gb(client.java:10957)
	at nc.mk(nc.java:10175)
	at oj.mx(oj.java:10157)
	at po.ms(po.java:10187)
	at jt.nj(jt.java:11713)
	at jt.nj(jt.java:11786)
	at bg.nl(bg.java:11296)
	at client.iw(client.java:3409)
	at client.bc(client.java:1182)
	at by.za(by.java:403)
	at by.io(by.java)
	at by.run(by.java:7195)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by Nightfirecat** [comment]
From a quick look at the plugin, this seems to be related to ground markers with null colors. I'll see about testing this (and coming up with a test profile) this week
