### ISSUE TITLE
Roof Removal NPE on client startup

### ISSUE THREAD

**Issue by Felanbird** [runelite/runelite#17504]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

10

### Bug description

1. Enable `Roof Removal` plugin
2. Restart the client
3. Login
4. See Roof Removal isn't working

### Screenshots or videos

![RuneLite_2024-02-17_16-59-22](https://github.com/runelite/runelite/assets/41973452/5e35e8c2-46da-4526-ac81-4045df416a63)

### RuneLite version

![image](https://github.com/runelite/runelite/assets/41973452/3cc94bc1-043e-4d36-833a-eccdbfc5bb6a)

### Logs

```
2024-02-17 17:09:37 EST [Client] ERROR n.r.client.callback.ClientThread - Exception in invoke
java.lang.NullPointerException: Cannot invoke "net.runelite.api.Scene.setRoofRemovalMode(int)" because the return value of "net.runelite.api.Client.getScene()" is null
        at net.runelite.client.plugins.roofremoval.RoofRemovalPlugin.lambda$startUp$0(RoofRemovalPlugin.java:110)
        at net.runelite.client.callback.ClientThread.lambda$invoke$0(ClientThread.java:49)
        at net.runelite.client.callback.ClientThread.invokeList(ClientThread.java:119)
        at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:101)
        at net.runelite.client.callback.Hooks.tick(Hooks.java:218)
        at client.mz(client.java:27319)
        at client.by(client.java)
        at bm.ap(bm.java:400)
        at bm.ka(bm.java)
        at bm.run(bm.java:46151)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Adam-** [comment]
fixed in fc54812af179308909c0b6b15ca6f7e08d422851
