### ISSUE TITLE
Runelite renderer messed up

### ISSUE THREAD

**Issue by elveeeeee** [runelite/runelite#17576]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Win10

### Bug description

Coming back from about 2 months break and launching my 4 clients (main + 3 alt) i noticed a strange border behaviour. The border, including the title bar are:

1) Too thin, as if one or two pixel width is missing both vertically and horizontally.
2) Produces side artifacts (with respect to the outer border) when resizing, either manually or via script
3) Fixes the artifacts when minimizing/maximizing, but not the overall trimmed size of the client (it remains too thin)

I'm using ahk for autoresize clients nicely. Coming back from my break i can no longer do that properly with this rather trivial script of mine. The screen resolution is 1920  X 1080; resizng 4 clients to 4 corners, each client being 960 X 540 in size, which used to fill the screen nicely, now leaves the gaps between clients (point 1) and of course the artifacts (point 2) which are shown in the images attached (pre and post minimizing/maximizing)

i found this gem in the client.log:

2024-03-14 02:29:28 CET [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at net.runelite.client.plugins.lowmemory.LowMemoryPlugin.onBeforeRender(LowMemoryPlugin.java:118)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.frame(Hooks.java:268)
	at client.bl(client.java:45610)
	at client.bn(client.java)
	at bm.bo(bm.java:430)
	at bm.ji(bm.java)
	at bm.run(bm.java:65016)
	at java.base/java.lang.Thread.run(Unknown Source)

i don't have time to dig into the code myself, but im seeing a NPE and 'render' in the method name, maybe this is whats causing it?

regards,

Elve.

### Screenshots or videos

![broken](https://github.com/runelite/runelite/assets/158539876/8233c65a-420d-43a8-b74f-b0528c9db2eb)
![very_broken](https://github.com/runelite/runelite/assets/158539876/f1e3f700-9ee9-426a-9bc8-b01b91ec81f4)

### RuneLite version

runelite version 1.10.24
oldschool version : Rev 220
launcher version: 2.6.10

### Logs

[client.log](https://github.com/runelite/runelite/files/14595775/client.log)
[launcher.log](https://github.com/runelite/runelite/files/14595777/launcher.log)

**Comment by rdutta** [comment]
I also get this error on client launch. It doesn't happen every time.

```java
2024-04-18 22:26:54 MDT [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
        at net.runelite.client.plugins.lowmemory.LowMemoryPlugin.onBeforeRender(LowMemoryPlugin.java:118)
        at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
        at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
        at net.runelite.client.callback.Hooks.frame(Hooks.java:267)
        at client.sw(client.java:61160)
        at client.bs(client.java)
        at bx.am(bx.java:410)
        at bx.eq(bx.java)
        at bx.run(bx.java:65091)
        at java.base/java.lang.Thread.run(Thread.java:829)
```
