### ISSUE TITLE
OpponentInfoOverlay plugin NPE

### ISSUE THREAD

**Issue by rdutta** [runelite/runelite#17644]
### Type

Incorrect behavior

### Operating System

Windows

### Bug description

```java
2024-03-27 15:45:16 MDT [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
        at net.runelite.client.plugins.opponentinfo.OpponentInfoOverlay.hasHpHud(OpponentInfoOverlay.java:232)
        at net.runelite.client.plugins.opponentinfo.OpponentInfoOverlay.render(OpponentInfoOverlay.java:143)
        at net.runelite.client.ui.overlay.OverlayRenderer.safeRender(OverlayRenderer.java:734)
        at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlays(OverlayRenderer.java:328)
        at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlayLayer(OverlayRenderer.java:235)
        at net.runelite.client.callback.Hooks.drawAboveOverheads(Hooks.java:513)
        at je.nj(je.java:30437)
        at je.aw(je.java:122)
        at kp.ix(kp.java:4943)
        at aa.le(aa.java:10786)
        at aa.le(aa.java:10817)
        at aa.le(aa.java:10817)
        at aa.le(aa.java:10817)
        at et.lp(et.java:10681)
        at client.mr(client.java:4660)
        at client.bs(client.java:1204)
        at bx.am(bx.java:410)
        at bx.xy(bx.java)
        at bx.run(bx.java:26455)
        at java.base/java.lang.Thread.run(Thread.java:829)
2024-03-27 15:46:20 MDT [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
2024-03-27 15:56:06 MDT [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - following log message logged 1000 times
```

Occurred at either Tombs of Amascut or the Easter event.

### RuneLite version

1.10.27-SNAPSHOT

**Comment by Adam-** [comment]
fixed in d8cb13bd9710b42f99f56b2c470965d7a0dd3baa
