### ISSUE TITLE
Runelite party plugin does not ping when using assigned key

### ISSUE THREAD

**Issue by jack-hughes** [runelite/runelite#17785]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

I've enabled the party plugin:

<img width="184" alt="image" src="https://github.com/runelite/runelite/assets/4501812/5a0f1ff4-913d-4bf1-b0d3-115c0f51716b">

When in a party solo or alone, I can't ping, regardless of what hotkey the ping is bound to. 

Some log lines that look suspect:

```
2024-04-23 20:32:46 BST [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.ArrayIndexOutOfBoundsException: Index 13 out of bounds for length 13
	at net.runelite.api.coords.WorldPoint.fromLocalInstance(WorldPoint.java:269)
	at net.runelite.api.coords.WorldPoint.fromLocalInstance(WorldPoint.java:229)
	at net.runelite.client.plugins.objectindicators.ObjectIndicatorsPlugin.checkObjectPoints(ObjectIndicatorsPlugin.java:469)
	at net.runelite.client.plugins.objectindicators.ObjectIndicatorsPlugin.onGameObjectSpawned(ObjectIndicatorsPlugin.java:168)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:204)
	at jp.ax(jp.java:46582)
	at jp.as(jp.java:269)
	at mi.av(mi.java:1186)
	at cv.kg(cv.java:40222)
	at hx.kh(hx.java:8655)
	at client.et(client.java:3388)
	at client.bh(client.java:1167)
	at bx.aa(bx.java:380)
	at bx.gx(bx.java)
	at bx.run(bx.java:23164)
	at java.base/java.lang.Thread.run(Unknown Source)
2024-04-23 21:34:04 BST [OkHttp https://api.runelite.net/...] WARN  net.runelite.client.party.WSClient - Error in websocket: null
java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(Unknown Source)
	at java.base/java.net.SocketInputStream.read(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(Unknown Source)
	at okio.Okio$2.read(Okio.java:140)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	at okio.RealBufferedSource.request(RealBufferedSource.java:72)
	at okio.RealBufferedSource.require(RealBufferedSource.java:65)
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:78)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:117)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:273)
	at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:209)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### RuneLite version

Runelite Version: 1.10.27.2
Launcher Version: 2.6.7

### Logs

[client.log](https://github.com/runelite/runelite/files/15083707/client.log)
[launcher.log](https://github.com/runelite/runelite/files/15083708/launcher.log)

**Comment by YvesW** [comment]
Have you read the description of pings or the ping hotkey?

**Comment by jack-hughes** [comment]
@YvesW no, recently came back to this plugin after not using for a long time. Was this always the case? I could have sworn it used to be on key press. Oh well, problem solved, thanks!

**Comment by YvesW** [comment]
Yup, AFAIK it's always been the case! We had quite a bit of #support traffic because people didn't know that it worked that way though, so I added it to the config descriptions semi-recently in https://github.com/runelite/runelite/commit/41da18ac1381b044b7e1bb3c5c07d871b38d25b0 It's reduced party ping related support traffic quite a bit in my experience, but hasn't removed it completely.
