### ISSUE TITLE
GPU plugin suddenly stopped working

### ISSUE THREAD

**Issue by patrickmurray18** [runelite/runelite#17832]
### Type

GPU

### Operating System

Windows

### OS Version

Windows 10

### Bug description

I just noticed that the GPU plugin (which had been working) now is permanently disabled. Whenever I try to re-enable the plugin it just switches off again. This started happening recently, possibly just a day ago. I have made no changes to the runelite client in this time.

I have tried re-installing runelite but this didn't help.

In the logs, there is this error:
```
2024-05-12 08:34:20 AEST [Client] ERROR n.r.client.plugins.gpu.GpuPlugin - Error starting GPU plugin
java.lang.RuntimeException: net.runelite.client.plugins.gpu.ShaderException: Out of resource error.

	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$startUp$1(GpuPlugin.java:384)
	at net.runelite.client.callback.ClientThread.invokeList(ClientThread.java:119)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:101)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:228)
	at client.rc(client.java:21537)
	at client.bh(client.java)
	at bx.gc(bx.java:380)
	at bx.aj(bx.java)
	at bx.run(bx.java:65044)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: net.runelite.client.plugins.gpu.ShaderException: Out of resource error.

	at net.runelite.client.plugins.gpu.Shader.compile(Shader.java:94)
	at net.runelite.client.plugins.gpu.GpuPlugin.initProgram(GpuPlugin.java:597)
	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$startUp$1(GpuPlugin.java:380)
	... 9 common frames omitted
```

### RuneLite version

RuneLite version: 1.10.29
Launcher version: 2.7.1

### Logs

[client.log](https://github.com/runelite/runelite/files/15284489/client.log)

**Comment by Felanbird** [comment]
These logs say you don't have a GPU, are you on a laptop that might not be plugged in?

**Comment by patrickmurray18** [comment]
@Felanbird Yes it's a laptop. Plugging it in (To the power? Is that a thing with GPUs?) does not make a difference. The GPU is working for all other applications and I have not made any changes to any GPU settings.

**Comment by Adam-** [comment]
Some recent changes have caused some newer versions of the Intel HD Graphics drivers to no longer work. I've heard downgrading to version 15.40.42.5063 from https://www.intel.com/content/www/us/en/download/18369/28662/intel-graphics-driver-for-windows-15-40.html fixes it.

**Comment by patrickmurray18** [comment]
@Adam- Yep my video card is an Intel HD Graphics 5500, thanks. Is there any intention to fix this on RuneLite's side?

**Comment by scott-parkhill** [comment]
So, I had RuneLite installed via snap, and this experience just emphasizes why I never install anything from these "convenience" installers. Basically, it seems that snap's sandboxing was preventing RuneLite from seeing the updated openGL drivers (that's my suspicion, at least). This was confirmed by downloading the AppImage from the RuneLite website, which immediately ran with the GPU just fine. I've had RuneLite installed via snap for *years* without issue, but it suddenly decided to break, so idk.

To be clear, I do not have flatpak installed, so the above solutions did not apply. Here are steps to fix this issue for anyone going forward. This saves your current plugins and settings.

```
# This command creates these directories if they don't already exist.
mkdir -p ~/.local/share/icons ~/.local/share/applications

# Copy desktop file, icon, and settings out of the snap folder.
cp /snap/runelite/current/meta/gui/runelite.png ~/.local/share/icons
cp /snap/runelite/current/meta/gui/runelite.desktop ~/.local/share/applications
cp -r  ~/snap/runelite/common/.runelite ~/.runelite

# This command assumes you've already downloaded the correct AppImage for your system from the RuneLite website.
# Move the app image into our installation directory.
mv ~/Downloads/RuneLite.AppImage ~/.local/share

# Make the AppImage executable.
chmod +x ~/.local/share/RuneLite.AppImage

# This part rewrites the .desktop file so that it points to the new locations for the AppImage and icons.
sed -i -e "s|^Exec=.*$|Exec=$HOME/.local/share/RuneLite.AppImage|" -e 's|^Icon=.*$|Icon=runelite|' ~/.local/share/applications/runelite.desktop

# This makes the AppImage icon the RuneLite icon.
echo "StartupWMClass=net-runelite-launcher-Launcher" >> `/.local/share/applications/runelite.desktop

# Delete the old snap.
snap remove runelite

# Make the .desktop executable and findable.
chmod +x ~/.local/share/applications/runelite.desktop
gio set ~/.local/share/applications/runelite.desktop metadata::trusted true
desktop-file-validate ~/.local/share/applications/runelite.desktop
update-desktop-database ~/.local/share/applications
```
