### ISSUE TITLE
NPC Aggression Timer doesn't appear in RuneLite plugins

### ISSUE THREAD

**Issue by freebiesoft** [runelite/runelite#17914]
### Type

Incorrect behavior

### Operating System

Linux

### OS Version

Ubuntu 23.10

### Bug description

You can see in the red box that the NPC aggression timer plugin exists, but when I search for it in plugins, it's not there. I can't see it from standard browser without using search filter either.

![image](https://github.com/runelite/runelite/assets/28921401/38889139-d179-43b8-b5e0-a10415f74e23)

### RuneLite version

RuneLite ver: 1.10.31.2
Launcher ver: 2.6.13

I'm using Snap on ubuntu

### Logs

let me know if you want logs

**Comment by Adam-** [comment]
This is probably this:
```
Caused by: java.lang.NullPointerException: null
    at net.runelite.api.Client.getBaseX(Client.java:2237)
    at net.runelite.client.plugins.npcunaggroarea.NpcAggroAreaPlugin.calculateLinesToDisplay(NpcAggroAreaPlugin.java:209)
    at net.runelite.client.plugins.npcunaggroarea.NpcAggroAreaPlugin.checkAreaNpcs(NpcAggroAreaPlugin.java:316)
    at net.runelite.client.plugins.npcunaggroarea.NpcAggroAreaPlugin.recheckActive(NpcAggroAreaPlugin.java:322)
    at net.runelite.client.plugins.npcunaggroarea.NpcAggroAreaPlugin.startUp(NpcAggroAreaPlugin.java:152)
    at net.runelite.client.plugins.PluginManager.startPlugin(PluginManager.java:438)
```

which is fixed by 97ec3ac57da8112ea4961030afb94a1c2c5156e1
