### ISSUE TITLE
LowMemoryPlugin Client getScene Null Pointer Exception

### ISSUE THREAD

**Issue by rdutta** [runelite/runelite#17924]
### Type

Incorrect behavior

### Operating System

Windows

### Bug description

```
2024-06-04 11:26:59 MDT [main] INFO  net.runelite.client.RuneLite - RuneLite 1.10.32-SNAPSHOT (launcher version unknown) starting up, args: --developer-mode
2024-06-04 11:26:59 MDT [main] INFO  net.runelite.client.RuneLite - Java VM arguments: -ea -Drunelite.pluginhub.version=1.10.31
2024-06-04 11:27:02 MDT [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2024-06-04 11:27:02 MDT [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2024-06-04 11:27:02 MDT [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 9359544463.156
2024-06-04 11:27:03 MDT [main] INFO  client-patch - read 5 credentials from disk
2024-06-04 11:27:03 MDT [main] INFO  n.r.client.config.ConfigManager - Profile 'default' (sync: true, active: true, id: 0)
2024-06-04 11:27:03 MDT [main] INFO  n.r.client.config.ConfigManager - Profile '$rsprofile' is up to date
2024-06-04 11:27:03 MDT [main] INFO  n.r.client.config.ConfigManager - Using profile: default (0)
2024-06-04 11:27:03 MDT [main] INFO  n.r.client.config.ConfigManager - Profile 'default' is up to date
2024-06-04 11:27:03 MDT [main] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2024-06-04 11:27:04 MDT [main] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "inventory-setups" jar "d7WqbRSPI7xyAg3TgEMppaHO7EQ9hYw3LeKJWzC1Hmc"
2024-06-04 11:27:04 MDT [main] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "bank-tag-layouts" jar "GxKz4qQJMIwUAMcIVT2b1WzVQ8xBNDpHKvuNyGN2fVE"
2024-06-04 11:27:04 MDT [main] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "ticktracker" jar "-uu_7mS8DvMpjW4Na1S2o6U8ZCIakTwzPFiJ_8sSZj0"
2024-06-04 11:27:04 MDT [main] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "customizable-xp-drops" jar "-EgEKNPw0FWPakBoCUhWIlv_kVIAM9A3hlIj331Hn4w"
2024-06-04 11:27:04 MDT [main] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2024-06-04 11:27:04 MDT [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
        at net.runelite.api.Client.getScene(Client.java:2115)
        at net.runelite.client.plugins.lowmemory.LowMemoryPlugin.onBeforeRender(LowMemoryPlugin.java:117)
        at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
        at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
        at net.runelite.client.callback.Hooks.frame(Hooks.java:265)
        at client.ej(client.java:41505)
        at client.br(client.java)
        at be.bl(be.java:401)
        at be.ag(be.java)
        at be.run(be.java:13119)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

#17576 possibly related

Sometimes the exception does not occur, in which case logging into the game, then logging out, closing the client, and then relaunching the jar will cause it to occur.

### RuneLite version

1.10.32-SNAPSHOT

**Comment by rdutta** [comment]
ab35ef41512e7f3db4617ab55a476cbe8e1ff812 added a nullcheck to `client.getScene` but there also should be one at `net.runelite.client.plugins.lowmemory.LowMemoryPlugin.onBeforeRender(LowMemoryPlugin.java:117)`

**Comment by Felanbird** [comment]
```
2024-11-03 17:31:37 EST [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: Cannot invoke "net.runelite.api.Scene.setMinLevel(int)" because the return value of "net.runelite.api.Client.getScene()" is null
	at net.runelite.client.plugins.lowmemory.LowMemoryPlugin.onBeforeRender(LowMemoryPlugin.java:118)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.frame(Hooks.java:265)
	at client.km(client.java:20016)
	at client.by(client.java)
	at bz.bx(bz.java:424)
	at bz.zp(bz.java)
	at bz.run(bz.java:19738)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
