### ISSUE TITLE
GPU Plugin Stopped Working on Linux

### ISSUE THREAD

**Issue by CiaranSanders** [runelite/runelite#17997]
### Type

GPU

### Operating System

Linux

### OS Version

Ubuntu 22.04

### Bug description

The GPU plugin will now automatically turn itself off when attempting to turn it on. Up until recently, about 4-5 days ago maybe, the GPU plugin was working perfectly fine. I have an NVIDIA RTX 3070 Ti graphics card, which is running OpenGl version 4.6. According to the FAQ for the GPU plugin, I believe I should meet the requirements for usage.

I am also using the Bolt launcher to run runelite on linux, [https://github.com/Adamcake/Bolt](https://github.com/Adamcake/Bolt)

### RuneLite version

Runelite version: 1.10.33.1
Launcher version: 2.7.1

### Logs

```2024-07-01 08:32:25 MDT [AWT-EventQueue-0] DEBUG n.r.client.config.ConfigManager - Setting configuration value for runelite.gpuplugin to true
2024-07-01 08:32:25 MDT [AWT-EventQueue-0] DEBUG n.r.client.plugins.PluginManager - Plugin GpuPlugin is now running
2024-07-01 08:32:25 MDT [AWT-EventQueue-0] DEBUG n.runelite.client.eventbus.EventBus - Registering class net.runelite.client.events.ConfigChanged - EventBus.Subscriber(object=net.runelite.client.plugins.gpu.GpuPlugin@1491344a, method=public void net.runelite.client.plugins.gpu.GpuPlugin.onConfigChanged(net.runelite.client.events.ConfigChanged), priority=0.0, lambda=net.runelite.client.plugins.gpu.GpuPlugin$$Lambda$2463/0x00007c67c09e58c8@7a6f0e0a)
2024-07-01 08:32:25 MDT [AWT-EventQueue-0] DEBUG n.runelite.client.eventbus.EventBus - Registering class net.runelite.api.events.GameStateChanged - EventBus.Subscriber(object=net.runelite.client.plugins.gpu.GpuPlugin@1491344a, method=public void net.runelite.client.plugins.gpu.GpuPlugin.onGameStateChanged(net.runelite.api.events.GameStateChanged), priority=0.0, lambda=net.runelite.client.plugins.gpu.GpuPlugin$$Lambda$2464/0x00007c67c09e5b00@594493a1)
2024-07-01 08:32:25 MDT [Client] ERROR n.r.client.plugins.gpu.GpuPlugin - Error starting GPU plugin
java.lang.RuntimeException: unable to find a fb config
	at net.runelite.rlawt.AWTContext.createGLContext(Native Method)
	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$startUp$1(GpuPlugin.java:310)
	at net.runelite.client.callback.ClientThread.invokeList(ClientThread.java:119)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:101)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:226)
	at client.xg(client.java:35810)
	at client.bw(client.java)
	at bs.ar(bs.java:388)
	at bs.ke(bs.java)
	at bs.run(bs.java:4092)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-07-01 08:32:25 MDT [AWT-EventQueue-0] DEBUG n.r.client.config.ConfigManager - Setting configuration value for runelite.gpuplugin to false
2024-07-01 08:32:25 MDT [AWT-EventQueue-0] DEBUG n.r.client.plugins.PluginManager - Plugin GpuPlugin is now stopped
2024-07-01 08:32:25 MDT [Client] DEBUG n.runelite.client.eventbus.EventBus - Registering class net.runelite.client.events.ConfigChanged - EventBus.Subscriber(object=net.runelite.client.plugins.gpu.GpuPlugin@1491344a, method=public void net.runelite.client.plugins.gpu.GpuPlugin.onConfigChanged(net.runelite.client.events.ConfigChanged), priority=0.0, lambda=net.runelite.client.plugins.gpu.GpuPlugin$$Lambda$2465/0x00007c67c09e5d38@541ab460)
2024-07-01 08:32:25 MDT [Client] DEBUG n.runelite.client.eventbus.EventBus - Registering class net.runelite.api.events.GameStateChanged - EventBus.Subscriber(object=net.runelite.client.plugins.gpu.GpuPlugin@1491344a, method=public void net.runelite.client.plugins.gpu.GpuPlugin.onGameStateChanged(net.runelite.api.events.GameStateChanged), priority=0.0, lambda=net.runelite.client.plugins.gpu.GpuPlugin$$Lambda$2466/0x00007c67c0782000@750a574f)
2024-07-01 08:32:25 MDT [Client] DEBUG net.runelite.client.callback.Hooks - Graphics reset!```

**Comment by Adam-** [comment]
This means RuneLite is unable to find a framebuffer config from glXChooseFBConfig(). It is likely due to a change in your system and not a RuneLite bug.

**Comment by CiaranSanders** [comment]
Ah I see, thank you for the response! I was struggling trying to find online what an fb config file was. Without much context or knowledge of OpenGl/Runelite and all this it was hard for me to troubleshoot. 

After a bunch more troubleshooting of random things, I finally realized I hadn't tried simply updating Bolt launcher... and yeah after doing so the gpu plugin is working. Thank you again for your help!
