### ISSUE TITLE
[Crowdsourcing] NPE on Fight Caves NPC chat after relog

### ISSUE THREAD

**Issue by tylerwgrass** [runelite/runelite#18111]
### Type

Other

### Operating System

None

### Bug description

After logging in again in the middle of the fight caves, received a NPE for the dialog from the NPC `TzHaar-Mej-Jal` with the chat `You're on your own now JalYt, prepare to fight for your life!`

Trace:
```
java.lang.NullPointerException: null
	at java.base/java.util.regex.Pattern.<init>(Pattern.java:1427)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1069)
	at java.base/java.lang.String.replaceAll(String.java:2126)
	at net.runelite.client.plugins.crowdsourcing.dialogue.CrowdsourcingDialogue.sanitize(CrowdsourcingDialogue.java:57)
	at net.runelite.client.plugins.crowdsourcing.dialogue.CrowdsourcingDialogue.onChatMessage(CrowdsourcingDialogue.java:142)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
```

### RuneLite version

Runelite version: 1.10.35
Launcher version: 2.7.1

**Comment by Nightfirecat** [comment]
fyi @leejt @andmcadams
