### ISSUE TITLE
Can't launch Runelite with --configure flag on macOS

### ISSUE THREAD

**Issue by shi-vy** [runelite/runelite#18253]
### Type

Crash or hang

### Operating System

MacOS

### OS Version

Sonoma 14.6.1

### Bug description

On macOS I'm trying to follow this [documentation](https://github.com/runelite/runelite/wiki/Using-Jagex-Accounts) which states to run Runelite like so:

 `/Applications/RuneLite.app/Contents/MacOS/RuneLite --configure`
 
 When I do this, I get this crash

```java
2024-09-10 19:45:39 [RuneLite] ERROR n.r.launcher.ReflectionLauncher - Unable to launch client
java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.runelite.launcher.ReflectionLauncher$1.run(ReflectionLauncher.java:63)
Caused by: joptsimple.UnrecognizedOptionException: configure is not a recognized option
	at joptsimple.OptionException.unrecognizedOption(OptionException.java:108)
	at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:510)
	at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56)
	at joptsimple.OptionParser.parse(OptionParser.java:396)
	at net.runelite.client.RuneLite.main(RuneLite.java:204)
	... 5 common frames omitted
``` 

It seems as if this `--configure` flag isn't actually working on macOS.

### RuneLite version

RuneLite version: 1.10.36.3
Launcher version: 2.5.0

**Comment by cwjoshuak** [comment]
Step 1 says: Make sure your RuneLite launcher is version 2.6.3 or newer

Download and install the updated RuneLite launcher from the website. You don't need to uninstall your current version. You will not lose any settings or plugins. Then try it again.
