### ISSUE TITLE
Frequent java.io.IOException following various runelite.client.game errors

### ISSUE THREAD

**Issue by keywok** [runelite/runelite#18271]
### Type

Other

### Operating System

Windows

### OS Version

Windows 11

### Bug description

I have posted a bit in the support channel of the RuneLite discord however the suggestions that have been provided haven't resolved the issue so thought posting everything in one place here might be more helpful rather than a long chain of replies over the course of multiple days.

I first noticed the various errors and warning when I was trying to troubleshoot another issue which has since been resolved however I haven't had any luck on stopping the errors and IOExceptions. 

As far as I can tell everytime there is an IOException it is immediately preceeded by either `[pool-3-thread-1] WARN  net.runelite.client.game.ItemManager - error loading prices!` or `[pool-3-thread-1] WARN  n.runelite.client.game.WorldService - Error looking up worlds` and then a series of either `failed to delete` or `failed to rename` various `okhttp` cache files.

The steps I have currently gone through to try and resolve this issue are:
1. Removed RuneLite via Windows Installed Apps
2. Deleted the .runelite folder within default install location
3. Downloaded latest launcher version from the RuneLite site
4. Installed as normal *(Installer was **not** ran as Administrator)*
5. Launched RuneLite via the Jagex launcher
6. Logged into my RuneLite account
7. Both of the CloudSync'd profiles appeared, these being `Main` and `Alt`
8. Swapped to the `Main` profile that is CloudSync'd
9. Deleted the `default` profile that was created via the Profiles tab and also within the `profiles2` directory
10. Logged in and set the `Main` and `Alt` profiles to be default to the specific accounts one at a time closing client after each
11. Disabled CloudSync for both `Main` and `Alt` profiles 
12. Restored both my custom notification sound as well as resource pack into the `.runelite` directory
13. Restored the contents of the `screenshots` directory and setup only this directory to be sync'd with my Google Drive
14. Imported and renamed the additional two profiles, `Lavas` and `Spec Alt`, that weren't originally CloudSync'd from exports I made before this
15. Logged into the `Spec Alt` account and set profile to be default before closing client
16. Logged into the `Main` account and exported all 4 profiles as a backup
17. Launched all 3 accounts and logged in
18. Repeated all the above for my laptop
19. Checked all directory and user permissions for the C: drive where I have RuneLite installed to make sure that everything has full access

If there is anymore information that I can give or steps I can try to resolve this then I am happy to try them and upload whatever might help. I know that they are just warnings however the fact its happening multiple times a day and always preceeded by a warning makes me think something isn't working correctly especially as the errors are originating from either `n.runelite.client.game.WorldService` or `net.runelite.client.game.ItemManager`.

Sorry for the wall of text and thank you in advance!

### Screenshots or videos

**C: Drive Permissions**
![image](https://github.com/user-attachments/assets/4375899c-8afd-4462-b8cd-545114378df7)

**.runelite Directory Permissions**
![image](https://github.com/user-attachments/assets/a56f059a-39ae-4959-9ac3-818c575026d9)

### RuneLite version

RuneLite Version: 1.10.37
Launcher Version: 2.7.2

*I am aware that late this afternoon a new version was pushed to fix the new KC commify issues that came up but haven't had time to see if that fixes my issue and don't see why it would affect this specific one*

### Logs

[client.log](https://github.com/user-attachments/files/16999677/client.log)
[launcher.log](https://github.com/user-attachments/files/16999688/launcher.log)

**Comment by keywok** [comment]
It seems that the `java.io.IOExceptions` aren't just limited to the `okhttp` directory as the following came up today while playing affecting the `profiles2` directory when trying to rename a `.tmp` file.
```
2024-09-14 10:45:24 BST [pool-3-thread-1] ERROR n.r.c.util.RunnableExceptionLogger - Uncaught exception in runnable net.runelite.client.config.ConfigManager$$Lambda$239/0x000000010048a440@7a90cf02
java.nio.file.AccessDeniedException: C:\Users\XXXXX\.runelite\profiles2\runelite_profiles16668187788758453107.tmp -> C:\Users\XXXXX\.runelite\profiles2\profiles.json
	at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileCopy.move(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source)
	at java.base/java.nio.file.Files.move(Unknown Source)
	at net.runelite.client.config.ProfileManager$Lock.close(ProfileManager.java:125)
	at net.runelite.client.config.ConfigManager.sendConfig(ConfigManager.java:1364)
	at net.runelite.client.util.RunnableExceptionLogger.run(RunnableExceptionLogger.java:41)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
I have attached the full `client.log` below:
[client.log](https://github.com/user-attachments/files/17002297/client.log)

**Comment by cdfisher** [comment]
> It seems that the `java.io.IOExceptions` aren't just limited to the `okhttp` directory as the following came up today while playing affecting the `profiles2` directory when trying to rename a `.tmp` file.
> 
> ```
> 2024-09-14 10:45:24 BST [pool-3-thread-1] ERROR n.r.c.util.RunnableExceptionLogger - Uncaught exception in runnable net.runelite.client.config.ConfigManager$$Lambda$239/0x000000010048a440@7a90cf02
> java.nio.file.AccessDeniedException: C:\Users\XXXXX\.runelite\profiles2\runelite_profiles16668187788758453107.tmp -> C:\Users\XXXXX\.runelite\profiles2\profiles.json
> 	at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
> 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
> 	at java.base/sun.nio.fs.WindowsFileCopy.move(Unknown Source)
> 	at java.base/sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source)
> 	at java.base/java.nio.file.Files.move(Unknown Source)
> 	at net.runelite.client.config.ProfileManager$Lock.close(ProfileManager.java:125)
> 	at net.runelite.client.config.ConfigManager.sendConfig(ConfigManager.java:1364)
> 	at net.runelite.client.util.RunnableExceptionLogger.run(RunnableExceptionLogger.java:41)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
> 	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
> 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.base/java.lang.Thread.run(Unknown Source)
> ```
> 
> I have attached the full `client.log` below: [client.log](https://github.com/user-attachments/files/17002297/client.log)

Can you share what the Windows properties window looks like for your profiles2 folder and for that tmp file?

**Comment by keywok** [comment]
Security Settings for the `profiles2` directory:
![image](https://github.com/user-attachments/assets/40fdf72d-9563-4b33-a0c1-40cd7f79d3a1)

Security Settings for the `runelite_profiles16668187788758453107.tmp` file:
![image](https://github.com/user-attachments/assets/b3995872-460b-4617-9354-5a3d32d2e616)

**Comment by keywok** [comment]
Just bumping this with the `client.log` from the last last two days with less but still getting the same `java.io.IOExceptions` for the `okhttp` directory.

[client.log](https://github.com/user-attachments/files/17046425/client.log)

**Comment by keywok** [comment]
Following a conversation with duralith yesterday in the Discord they suggested the following which I have done and has had no change in me seeing the errors.

- Closed all 3 clients
- Restarted my PC
- Redownloaded and installed RuneLite
- Ran the standalone client once as admin
- Restarted my PC again

Updated Logs:
[client.log](https://github.com/user-attachments/files/17089456/client.log)
[launcher.log](https://github.com/user-attachments/files/17089454/launcher.log)

**Comment by keywok** [comment]
As mentioned in another issue I raised [here](https://github.com/runelite/runelite/issues/18299) I am also having profiles  being dropped randomly and almost daily at this point. The only way to get them to re-appear is to re-open all of my clients which is getting extremely frustrating. I have inclued more information in the linked issue but have put the logs below from today.

Logs:
[client.log](https://github.com/user-attachments/files/17099275/client.log)

The last thing I have tried was to do a complete clean install of RuneLite by deleting both the `.runelite` directory and removing RuneLite from my PC by uninstalling it, redownloading the installer, installing it onto a different drive to the default and then running the standalone client as admin once until it hits the login screen. This last step was a suggestion from `duralith`. 

Logs from the above:
[client.log](https://github.com/user-attachments/files/17099406/client.log)
[launcher.log](https://github.com/user-attachments/files/17099382/launcher.log)

**Comment by keywok** [comment]
Decided to check my logs on my laptop that only has ever had two clients open and am seeing the same errors as I am on my main PC so it seems its not limited to just one computer. the only thing thats the same between the two devices is the use of a Microsoft account instead of a local one but I've used this for years at this point.

Logs from laptop:
[client.log](https://github.com/user-attachments/files/17128164/client.log)
[launcher.log](https://github.com/user-attachments/files/17128171/launcher.log)
[client_2024-09-17.0.log](https://github.com/user-attachments/files/17128165/client_2024-09-17.0.log)
[launcher_2024-09-16.0.log](https://github.com/user-attachments/files/17128170/launcher_2024-09-16.0.log)

**Comment by keywok** [comment]
I have now checked on a completely fresh install of windows on a third computer and am still seeing the same errors and behaviour when having 3 clients open and leaving them open across multiple days with putting the computer to sleep overnight.

Logs:
[client.log](https://github.com/user-attachments/files/17256848/client.log)
[launcher.log](https://github.com/user-attachments/files/17256850/launcher.log)

**Comment by keywok** [comment]
Been a while and did some more troubleshooting and I think I have figured out the cause of the issues. If you leave multiple clients open and put the PC to sleep you will start to get the ioExceptions for both https cache and profile files. 

For the last week or so I have been closing all clients each night or before putting the PC to sleep and not had a single instance of the errors however the single time I did leave a client open and put the PC to sleep the next day I got the errors again.

Kinda annoying having to relaunch clients every single morning especially as I use 3 but is what it is I guess.
