### ISSUE TITLE
Can't toggle GPU plugin on

### ISSUE THREAD

**Issue by noelpilled** [runelite/runelite#18566]
### Type

GPU

### Operating System

Linux

### OS Version

Guix System / Linux 6.11.9

### Bug description

Running sway & flatpak runelite, toggling gpu or 117 on results in an error in logs & the plugin immediately turning back off.
I believe this is a Sway issue, setting up hyprland right now to test it out.

Turning off compute shaders didn't fix
_JAVA_AWT_WM_NONREPARENTING=1 doesn't fix (separate bug, also doesn't fix the client not stretching to fill the window)

### RuneLite version

Runelite version: 1.10.44
Launcer version: 2.7.2

### Logs

[logs.log](https://github.com/user-attachments/files/17931337/logs.log)
[glxinfo.txt](https://github.com/user-attachments/files/17931370/glxinfo.txt)

**Comment by puzzler995** [comment]
I'm having the same issue, on Fedora with Cinnamon on X11
Stack trace in the logs:
2024-11-27 12:00:33 EST [Client] ERROR n.r.client.plugins.gpu.GpuPlugin - Error starting GPU plugin
java.lang.RuntimeException: unable to find a fb config
	at net.runelite.rlawt.AWTContext.createGLContext(Native Method)
	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$startUp$1(GpuPlugin.java:312)
	at net.runelite.client.callback.ClientThread.invokeList(ClientThread.java:119)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:101)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:226)
	at client.ke(client.java:19485)
	at client.bu(client.java)
	at bo.am(bo.java:391)
	at bo.iz(bo.java)
	at bo.run(bo.java:9213)
	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by lithream** [comment]
What about an X11-based one like i3?
