### ISSUE TITLE
Can't Enable GPU Plugin

### ISSUE THREAD

**Issue by AliceWilliamson** [runelite/runelite#18582]
### Type

GPU

### Operating System

Linux

### OS Version

Linux 6.11.10-2-MANJARO

### Bug description

When attempting to enable the GPU plugin, the slider flicks on and then back off instantly.

Error is: 
2024-12-04 00:21:36 MST [Client] ERROR n.r.client.plugins.gpu.GpuPlugin - Error starting GPU plugin
java.lang.RuntimeException: unable to find a fb config
	at net.runelite.rlawt.AWTContext.createGLContext(Native Method)
	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$startUp$1(GpuPlugin.java:312)
	at net.runelite.client.callback.ClientThread.invokeList(ClientThread.java:119)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:101)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:226)
	at client.ke(client.java:19485)
	at client.bu(client.java)
	at bo.am(bo.java:391)
	at bo.iz(bo.java)
	at bo.run(bo.java:9213)
	at java.base/java.lang.Thread.run(Thread.java:1583)

### RuneLite version

Runelite version: 1.10.45
Launcher version 1.10.45

### Logs

[client.log](https://github.com/user-attachments/files/18004044/client.log)
[launcher.log](https://github.com/user-attachments/files/18004045/launcher.log)

**Comment by Nightfirecat** [comment]
What is the output of `glxinfo -B`?

**Comment by AliceWilliamson** [comment]
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 6144 MB
    Total available memory: 6144 MB
    Currently available dedicated video memory: 5241 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 565.57.01
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6.0 NVIDIA 565.57.01
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)

OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 565.57.01
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

**Comment by StrikeForceZero** [comment]
@AliceWilliamson did you get it working?

Im also now having this issue after a recent arch system update. similar glxinfo -B output.

the error log for the 117HD plugin seems to have more hints

```
2024-12-17 19:38:21 EST [Client] ERROR rs117.hd.HdPlugin - Error while starting 117HD
java.lang.RuntimeException: unable to find a fb config
        at net.runelite.rlawt.AWTContext.createGLContext(Native Method)
        at rs117.hd.HdPlugin.lambda$startUp$1(HdPlugin.java:518)
        at net.runelite.client.callback.ClientThread.invokeList(ClientThread.java:119)
        at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:101)
        at net.runelite.client.callback.Hooks.tick(Hooks.java:226)
        at client.gj(client.java:30423)
        at client.bu(client.java)
        at bo.qn(bo.java:391)
        at bo.on(bo.java)
        at bo.run(bo.java:60039)
        at java.base/java.lang.Thread.run(Thread.java:840)
2024-12-17 19:38:22 EST [Client] ERROR n.r.client.callback.ClientThread - Exception in invoke
java.lang.ExceptionInInitializerError: null
        at org.lwjgl.opengl.GL$ICDStatic.get(GL.java:722)
        at org.lwjgl.opengl.GL.getICD(GL.java:689)
        at org.lwjgl.opengl.GL15C.glDeleteQueries(GL15C.java:1288)
        at rs117.hd.overlays.FrameTimer.lambda$destroy$2(FrameTimer.java:52)
        at net.runelite.client.callback.ClientThread.lambda$invokeLater$1(ClientThread.java:80)
        at net.runelite.client.callback.ClientThread.invokeList(ClientThread.java:119)
        at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:101)
        at net.runelite.client.callback.Hooks.tick(Hooks.java:226)
        at client.gj(client.java:30423)
        at client.bu(client.java)
        at bo.qn(bo.java:391)
        at bo.on(bo.java)
        at bo.run(bo.java:60039)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.IllegalStateException: No GLCapabilities instance has been set
        at org.lwjgl.opengl.GL$ICDStatic$WriteOnce.<clinit>(GL.java:732)
        ... 14 common frames omitted
2024-12-17 19:38:22 EST [Client] ERROR n.r.client.callback.ClientThread - Exception in invoke
java.lang.NoClassDefFoundError: Could not initialize class org.lwjgl.opengl.GL$ICDStatic$WriteOnce
        at org.lwjgl.opengl.GL$ICDStatic.get(GL.java:722)
        at org.lwjgl.opengl.GL.getICD(GL.java:689)
        at org.lwjgl.opengl.GL15C.glDeleteQueries(GL15C.java:1288)
        at rs117.hd.overlays.FrameTimer.lambda$destroy$2(FrameTimer.java:52)
        at net.runelite.client.callback.ClientThread.lambda$invokeLater$1(ClientThread.java:80)
        at net.runelite.client.callback.ClientThread.invokeList(ClientThread.java:119)
        at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:101)
        at net.runelite.client.callback.Hooks.tick(Hooks.java:226)
        at client.gj(client.java:30423)
        at client.bu(client.java)
        at bo.qn(bo.java:391)
        at bo.on(bo.java)
        at bo.run(bo.java:60039)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalStateException: No GLCapabilities instance has been set [in thread "Client"]
        at org.lwjgl.opengl.GL$ICDStatic$WriteOnce.<clinit>(GL.java:732)
        ... 14 common frames omitted
```

tried downgrading my jdk just in case but that doesn't seem to make a difference.

**Comment by abextm** [comment]
Which wm / wayland compositor do you use?

**Comment by StrikeForceZero** [comment]
I just figured it out for my specific issue thanks to [this discord comment](https://discord.com/channels/301497432909414422/442492468307427330/1296978078907502634)

`flatpak update` fixed it for me. I had no idea flatpak had its own set of drivers

**Comment by AliceWilliamson** [comment]
> I just figured it out for my specific issue thanks to [this discord comment](https://discord.com/channels/301497432909414422/442492468307427330/1296978078907502634)
> 
> `flatpak update` fixed it for me. I had no idea flatpak had its own set of drivers

I actually just came here to post this. This worked for me as well.

**Comment by JellyMyst** [comment]
> I just figured it out for my specific issue thanks to [this discord comment](https://discord.com/channels/301497432909414422/442492468307427330/1296978078907502634)
> 
> `flatpak update` fixed it for me. I had no idea flatpak had its own set of drivers

It might be useful to copy across why this is the solution. I came across this, and the solution worked, but I'm unclear on exactly why, and I don't know what server that link points to.

**Comment by LlemonDuck** [comment]
It's a link to a discord comment in the runelite server. Here's the contents, they're not much extra help:

> Im getting this error when trying to turn on the GPU plugin. im on Linux, nixOS. started happening after I updated my nvidia drivers. Tried updating the drivers again (nvidia 555.58.02) but issue persisted. I saw in the log as well that it was trying to load the old driver still. any way to force it to try and use new driver version?
 ERROR n.r.client.plugins.gpu.GpuPlugin - Error starting GPU plugin
java.lang.RuntimeException: unable to find a fb config
        at net.runelite.rlawt.AWTContext.createGLContext(Native Method) [...]

> edit: I fixed it, it was an issue with the jagexlauncher flatpak needing to have nvidia driver updated as well

**Comment by abextm** [comment]
you have to `flatpak update` because the userland opengl driver installed into the flatpak has to match the kernel driver outside of the flatpak

**Comment by JellyMyst** [comment]
Many thanks to you both. I figured it was something like that, but I wasn't sure.
