### ISSUE TITLE
SlayerPlugin NullPointerException

### ISSUE THREAD

**Issue by Foulwerp** [runelite/runelite#2295]
Got a new assignment, received spiritual creatures, console kept giving me this error.
```
2018-05-03 08:57:51 [Thread-5] WARN  net.runelite.client.RuneLiteModule - uncaught exception in event subscriber
java.lang.NullPointerException: null
	at net.runelite.client.plugins.slayer.SlayerPlugin.buildTargetsToHighlight(SlayerPlugin.java:431)
	at net.runelite.client.plugins.slayer.SlayerPlugin.onGameTick(SlayerPlugin.java:237)
	at sun.reflect.GeneratedMethodAccessor153.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:119)
	at client.ak(client.java)
	at bz.x(bz.java:366)
	at bz.copy$run(bz.java:320)
	at bz.run(bz.java:60)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Adam-** [comment]
Fixed in #4199
