### ISSUE TITLE
Can't run rs-client from Main

### ISSUE THREAD

**Issue by Wonderlus** [runelite/runelite#232]
**runescape-client/src/test/java/Main**
```
Exception in thread "Thread-6" java.lang.IllegalMonitorStateException
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at RSSocket.run(RSSocket.java:167)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Adam-** [comment]
Sorry about that. It looks like fernflower was not liking the control flow deobfuscator reordering the blocks in the protected range, and was generating an empty expression for the synchronized{} block [here](https://github.com/runelite/runelite/blob/master/runescape-client/src/main/java/RSSocket.java#L136). I removed the exception CFG stuff since it has been causing problems lately and I don't think the blocks inside of methods with exceptions are actually obfuscated anyway.
