### ISSUE TITLE
Can't click sometimes after clicking stat search box

### ISSUE THREAD

**Issue by vikke1234** [runelite/runelite#2680]
I just clicked it and then it stopped working, then the UI was completely unresponsive
``
2018-05-13 10:01:17 [pool-2-thread-1] WARN  n.r.client.ClientSessionManager - Resetting session
java.io.IOException: Unsuccessful ping
    at net.runelite.http.api.session.SessionClient.ping(SessionClient.java:81)
    at net.runelite.client.ClientSessionManager.ping(ClientSessionManager.java:105)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
2018-05-13 18:55:13 [main] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2018-05-13 18:55:15 [main] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2018-05-13 18:55:16 [main] INFO  n.r.client.account.SessionManager - No session file exists
2018-05-13 21:04:29 [main] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2018-05-13 21:04:30 [main] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2018-05-13 21:04:31 [main] INFO  n.r.client.account.SessionManager - No session file exists
``

**Comment by deathbeam** [comment]
This bug contains like no information and I never saw it reported outside of this issue, so maybe it is not even valid anymore. Closing as invalid, reopen if bug persists + include more information about the bug
