### ISSUE TITLE
Examine plugin - Out of bounds exception

### ISSUE THREAD

**Issue by deathbeam** [runelite/runelite#294]
Occurring randomly, or at least I do not found reason why is it happening. Probably just needs some array bounds check.

The exception is occurring for ids: 507, 508, 509, 510, 511, 487, 510, 511, 312, 276 (probably also few more). Here is example output: 

```
[Thread-7] WARN net.runelite.client.RuneliteModule - uncaught exception in event subscriber
java.lang.ArrayIndexOutOfBoundsException: 507
        at net.runelite.client.plugins.examine.ExaminePlugin.findExamineItem(ExaminePlugin.java:266)
        at net.runelite.client.plugins.examine.ExaminePlugin.onChatMessage(ExaminePlugin.java:214)
        at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
        at com.google.common.eventbus.EventBus.post(EventBus.java:217)
        at net.runelite.client.callback.Hooks.addChatMessage(Hooks.java:240)
        at ag.e(ag.java)
        at p.w(p.java)
        at client.gs(client.java)
        at client.ev(client.java)
        at client.aq(client.java)
        at be.p(be.java)
        at be.run(be.java)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by UniquePassive** [comment]
This happens when you have requested an examine and then closed the bank interface.

``widget.getDynamicChildren()`` will return an empty array, ``new Widget[0]``, because the bank interface is missing its children when it is closed.
