### ISSUE TITLE
Slayer plugin throws a NullPointerException

### ISSUE THREAD

**Issue by SomeoneWithAnInternetConnection** [runelite/runelite#296]
I'm not 100% sure what the reason for this NPE is, but I think it was probably the result of getting slayer XP without having detected a task, since I hadn't yet done anything slayer-y while using runelite. The exception happened just as I finished the Varrock museum natural history quiz miniquest (which awards 1000 Slayer XP). I did have an active slayer assignment (0/88 moss giants).

Here's the stacktrace, along with some related logs before and after:
```
[Thread-7] DEBUG net.runelite.client.callback.Hooks - Chat message type SERVER: You have gained 1000xp in Slayer and Hunter.
[Thread-7] DEBUG net.runelite.client.plugins.examine.ExaminePlugin - Got examine without a pending examine?
[Thread-7] DEBUG net.runelite.client.config.ConfigManager - Setting configuration value for slayer.amount to -1
[pool-1-thread-1] DEBUG net.runelite.http.api.config.ConfigClient - Built URI: https://api.runelite.net/runelite-1.2.11-SNAPSHOT/config/slayer.amount
[Thread-7] DEBUG net.runelite.client.config.ConfigManager - Setting configuration value for slayer.taskName to 
[Thread-7] DEBUG net.runelite.client.config.ConfigManager - Setting configuration value for slayer.points to 0
[Thread-7] DEBUG net.runelite.client.config.ConfigManager - Setting configuration value for slayer.streak to 0
[Thread-7] WARN net.runelite.client.RuneliteModule - uncaught exception in event subscriber
java.lang.NullPointerException
	at net.runelite.client.plugins.slayer.SlayerPlugin.killedOne(SlayerPlugin.java:268)
	at net.runelite.client.plugins.slayer.SlayerPlugin.onExperienceChanged(SlayerPlugin.java:257)
	at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.runelite.client.callback.Hooks.callHook(Hooks.java:136)
	at client.gs(client.java)
	at client.ev(client.java)
	at client.aq(client.java)
	at be.p(be.java)
	at be.run(be.java)
	at java.lang.Thread.run(Thread.java:748)
[Thread-7] DEBUG net.runelite.client.plugins.xpglobes.XpGlobesOverlay - Loading skill icon from /skill_icons/slayer.png
[Thread-7] DEBUG net.runelite.client.plugins.xpglobes.XpGlobesOverlay - Loading skill icon from /skill_icons/hunter.png
[pool-1-thread-1] DEBUG net.runelite.http.api.config.ConfigClient - Set configuration value 'slayer.amount' to '-1'
[pool-1-thread-1] DEBUG net.runelite.http.api.config.ConfigClient - Built URI: https://api.runelite.net/runelite-1.2.11-SNAPSHOT/config/slayer.taskName
[pool-1-thread-1] DEBUG net.runelite.http.api.config.ConfigClient - Set configuration value 'slayer.taskName' to ''
[pool-1-thread-1] DEBUG net.runelite.http.api.config.ConfigClient - Built URI: https://api.runelite.net/runelite-1.2.11-SNAPSHOT/config/slayer.points
[pool-1-thread-1] DEBUG net.runelite.http.api.config.ConfigClient - Set configuration value 'slayer.points' to '0'
[pool-1-thread-1] DEBUG net.runelite.http.api.config.ConfigClient - Built URI: https://api.runelite.net/runelite-1.2.11-SNAPSHOT/config/slayer.streak
[pool-1-thread-1] DEBUG net.runelite.http.api.config.ConfigClient - Set configuration value 'slayer.streak' to '0'
```

**Comment by UniquePassive** [comment]
This seems to happen when you receive Slayer experience, and the plugin thinks you have killed a monster, but the plugin has not recorded you as having an active task (by either receiving the "You're assigned to kill ...." message or by having the task saved in your Slayer config).

We can either just add a check to see if we are on a task in the onExperienceChanged callback, or add some code to verify that you have killed your assigned mob when you receive the experience. The latter is probably not so easy to implement, and the former still has slip-throughs when you're on a task and receive non-task experience.

**Comment by Sethtroll** [comment]
I believe this was fixed in https://github.com/runelite/runelite/commit/d3173c118189aa60630433001620d81966571bd8

**Comment by Adam-** [comment]
Reopen if this is still a problem.
