### ISSUE TITLE
Runelite locks /dev/snd

### ISSUE THREAD

**Issue by BartWillems** [runelite/runelite#3525]
When I start Runelite before any other application, it locks my sound devices.
Because of this, I can't play youtube videos, vlc can't output sound, ...

I always have to make sure that either Firefox or vlc is started first.

**Comment by BartWillems** [comment]
I use Arch btw

**Comment by deathbeam** [comment]
Are you sure you have pulseaudio set-up correctly?

**Comment by BartWillems** [comment]
My pulseaudio is indeed set-up correctly. 

Recently I read some old arch forum entry about someone with the same issue. It was because some sun library tries to put a lock on the device in stead of talking to the sound server. I would link it, but I can't find it anymore...

Here is another link to someone who has the same issue, but in 2010:
https://ubuntuforums.org/archive/index.php/t-1445507.html

**Comment by AverageHumanoid** [comment]
I've also experienced this with Arch Linux but not with Ubuntu.

**Comment by BartWillems** [comment]
I solved this by installing "pulseaudio-alsa".

**(Please do not close this as it's still a bug)**

The problem was that runelite directly communicates with Alsa, thus locking it.
Pulseaudio-alsa makes acts like an alsa wrapper, so that miss-behaving programs(like runelite in this case) can't connect to alsa, but pass to pulseaudio.

**Comment by jachymb** [comment]
I am having the same problem on Arch.

**Comment by hur** [comment]
Having the same problem on Pop!_OS. Can't find `pulseaudio-alsa` in Ubuntu repositories.

**Comment by brainard52** [comment]
I may be experiencing the same thing when running the snap inside Fedora 31. I'm running the default sound configs. The behaviour I'm seeing is that pulseaudio crashes, but ALSA seems to continue working. I can tell that ALSA is working because Runescape audio keeps playing. Oddly, the notifications by the client do not continue playing.

**Comment by brainard52** [comment]
As a workaround for people who are experiencing this, please take a look at `man padsp`. It's not a permanent fix because the issue is allegedly not with Runelite or OSRS and is something that should be reported to system maintainers.

**Comment by HirschBerge** [comment]
Workaround is using BT headset for other audio. This just seems to hijack only speakers and audio jack

**Comment by abextm** [comment]
install `pulseaudio-alsa`

**Comment by HirschBerge** [comment]
> install `pulseaudio-alsa`

Already installed. Does not impact the bug

**Comment by abextm** [comment]
then your pulseadio is configured wrong or you have hit a different odd jvm behavior.

**Comment by HirschBerge** [comment]
Nothing seems wrong with pulseaudio. Installed runelite through the AUR, it's deps are messed up btw. Could be causing some of the issue as I had to install some things manually.

**Comment by abextm** [comment]
Try the appimage from runelite.net, we don't support the aur version

**Comment by brainard52** [comment]
Could also just try the jar. Once the jar is in ~/Downloads, you can use this to install a Desktop file to show up in most desktop managers
https://github.com/brainard52/RuneLite-Jar-Installer

**Comment by dipshit** [comment]
I encountered this issue on Pop!_OS with openjdk-14. Installing alsa or pulseaudio-utils did not fix the issue. Running the AppImage yielded no sound, while running the AppImage with `padsp` yielded sound, but locked all devices.

The workaround for me was to use snap to install & run runelite.
1. `sudo apt update && sudo apt install snapd`
1. `sudo snap install runelite`
1. Launch runelite with `snap run runelite`

**Comment by dginovker** [comment]
This is gonna sound stupid, but for anyone else with this issue, make sure the audio is playing out of the right device.

**Comment by fuzxi** [comment]
If anyone is having this issue and uses pipewire in place of pulseaudio, I can confirm that `pipewire-alsa` fixes this.

**Comment by edisionnano** [comment]
Uninstalling droidcam made sound work for me

**Comment by TheGreatestJannet** [comment]
@fuzxi is pipewire-alsa still working for you? For me I get lots of crackle whenever runelite is open

**Comment by fuzxi** [comment]
@TheGreatestJannet Yes, it still works fine for me. No audio issues. Currently using version 1:0.3.35-1 of pipewire and pipewire-alsa.

**Comment by hankjordan** [comment]
For those of you with `pipewire` but installing `pipewire-alsa` did not resolve the issue, installing `wireplumber` and uninstalling `pulseaudio-alsa` resolved the issue for me.

**Comment by sangoku116** [comment]
> For those of you with `pipewire` but installing `pipewire-alsa` did not resolve the issue, installing `wireplumber` and uninstalling `pulseaudio-alsa` resolved the issue for me.

I do have ```wireplumber``` installed and do not have ```pulseaudio-alsa``` installed. Yet still no sound.

**Comment by Lindenk** [comment]
Weird. I was having this issue as well with almost exactly the set up above. I uninstalled pulseaudio-alsa and now I'm no longer having the issue. This is with using `pipewire-media-session` instead of `wireplumber`

**Comment by hankjordan** [comment]
Okay, I've managed to fix this issue on the device that was still having an issue.

I believe Runelite Flatpak's version of Java is outdated.

Installing Runelite from AUR and updating JRE to <code>openjdk 18.0.1.1</code> resolves my sound issue entirely.

**Comment by sangoku116** [comment]
> Okay, I've managed to fix this issue on the device that was still having an issue.
> 
> I believe Runelite Flatpak's version of Java is outdated.
> 
> Installing Runelite from AUR and updating JRE to `openjdk 18.0.1.1` resolves my sound issue entirely.

Just tried this and no luck on my end. Runelite is the only application unable to output any sounds despite trying out everything that was mentioned as working in this post.

**Comment by hankjordan** [comment]
@sangoku116 Please tell me the result from running <code>java --version</code>. If you are on Arch, please also show me the output of <code>archlinux-java get</code>.

**Comment by sangoku116** [comment]
> @sangoku116 Please tell me the result from running `java --version`. If you are on Arch/Manjaro, please also show me the output of `archlinux-java get`.
```java --version```
```
openjdk 18.0.1.1 2022-04-22
OpenJDK Runtime Environment (build 18.0.1.1+2)
OpenJDK 64-Bit Server VM (build 18.0.1.1+2, mixed mode)
```

```archlinux-java get```
`java-18-openjdk`

**Comment by hankjordan** [comment]
@sangoku116 Well, hmm. Are you certain Runelite is running with the updated version of Java?

<code>XXXX-XX-XX XX:XX:XX [main] INFO  net.runelite.launcher.JvmLauncher - Running [/usr/lib/jvm/**java-18-openjdk**/bin/java ...</code> should appear somewhere in your runelite log.

If it is running with the updated version it may be related to installed packages. Note, contrary to my earlier post I am not running **Wireplumber** on this device. Here are mine:

```
alsa-card-profiles 1:0.3.51-1
alsa-firmware 1.2.4-2
alsa-lib 1.2.6.1-1
alsa-oss 1.1.8-4
alsa-plugins 1:1.2.6-3
alsa-topology-conf 1.2.5.1-1
alsa-ucm-conf 1.2.6.3-1
alsa-utils 1.2.6-1
java-runtime-common 3-3
jre-openjdk 18.0.1.u10-1
jre-openjdk-headless 18.0.1.u10-1
pipewire 1:0.3.51-1
pipewire-alsa 1:0.3.51-1
pipewire-jack 1:0.3.51-1
pipewire-media-session 1:0.4.1-1
pipewire-pulse 1:0.3.51-1
pipewire-v4l2 1:0.3.51-1
polkit 0.120-5
realtime-privileges 4-1
rtkit 0.13-1
runelite 1:2.4.2-1
sof-firmware 2.1.1-1
```

**Comment by sangoku116** [comment]
Yup I get: ```2022-05-23 21:01:16 [main] INFO  net.runelite.launcher.JvmLauncher - Running [/usr/lib/jvm/java-18-openjdk/bin/java``` . I tried with both ```wireplumber``` and ```pipewire-media-session```. 

```
alsa-card-profiles 1:0.3.51-1
alsa-firmware 1.2.4-2
alsa-lib 1.2.6.1-1
alsa-oss 1.1.8-4
alsa-plugins 1:1.2.6-3
alsa-topology-conf 1.2.5.1-1
alsa-ucm-conf 1.2.6.3-1
alsa-utils 1.2.6-1
lib32-alsa-lib 1.2.6.1-1
lib32-alsa-oss 1.1.8-3
lib32-alsa-plugins 1.2.6-1
pipewire-alsa 1:0.3.51-1
zita-alsa-pcmi 0.4.0-1
lib32-pipewire 1:0.3.51-1
lib32-pipewire-jack 1:0.3.51-1
pipewire 1:0.3.51-1
pipewire-alsa 1:0.3.51-1
pipewire-jack 1:0.3.51-1
pipewire-pulse 1:0.3.51-1
wireplumber 0.4.10-3
runelite 1:2.4.2-1
```

**Comment by hankjordan** [comment]
@sangoku116 In your audio mixer, do you see <code>ALSA plug-in [java]</code> or <code>PipeWire ALSA [java]</code>?

**Comment by sangoku116** [comment]
> @sangoku116 In your audio mixer, do you see `ALSA plug-in [java]` or `PipeWire ALSA [java]`?

None of these appear.

**Comment by hankjordan** [comment]
> > @sangoku116 In your audio mixer, do you see `ALSA plug-in [java]` or `PipeWire ALSA [java]`?
> 
> None of these appear.

These may be two separate issues. I was having intermittent audio, with music cutting in and out but sound effects working (mostly) fine. I missed the part that your audio isn't working **at all**.

The only thing that I can think of is that somehow Pulseaudio hasn't been uninstalled completely. Maybe look for installed Pulse packages with <code>pacman -Q | grep pulse</code>. Having <code>pulseaudio-alsa</code> installed presented similar issues for me, and it isn't removed by installing <code>pipewire</code>. That's the only other thing I think it could be.

**Comment by sangoku116** [comment]
These are the only ones I havE: ```
lib32-libpulse 15.0-2
libpulse 15.0-4
pipewire-pulse 1:0.3.51-1
pulseaudio-ctl 1.70-1
xfce4-pulseaudio-plugin 0.4.3-2
```

**Comment by hankjordan** [comment]
Last try,

Do you have <code>realtime-privileges</code> installed?

If not, please install it and make sure your current user is a member of the group <code>realtime</code>.

Then I'd completely restart your device and try to launch Runelite again.

**Comment by sangoku116** [comment]
> Last try,
> 
> Do you have `realtime-privileges` installed?
> 
> If not, please install it and make sure your current user is a member of the group `realtime`.
> 
> Then I'd completely restart your device and try to launch Runelite again.

I do not what does that package do?

**Comment by hankjordan** [comment]
> > Last try,
> > Do you have `realtime-privileges` installed?
> > If not, please install it and make sure your current user is a member of the group `realtime`.
> > Then I'd completely restart your device and try to launch Runelite again.
> 
> I do not what does that package do?

My best guess is that it allows your user to interact with the realtime audio process. I don't know for sure if it will resolve the issue but it is mentioned on [the Arch wiki PipeWire troubleshooting guide](https://wiki.archlinux.org/title/PipeWire#Troubleshooting) and I've got it installed on both working devices.

I don't know what flavor of Arch you are running but if you're on Manjaro you may also try installing the following packages:
```
manjaro-alsa
manjaro-pipewire
```

**Comment by sangoku116** [comment]
> > > Last try,
> > > Do you have `realtime-privileges` installed?
> > > If not, please install it and make sure your current user is a member of the group `realtime`.
> > > Then I'd completely restart your device and try to launch Runelite again.
> > 
> > 
> > I do not what does that package do?
> 
> My best guess is that it allows your user to interact with the realtime audio process. I don't know for sure if it will resolve the issue but it is mentioned on [the Arch wiki PipeWire troubleshooting guide](https://wiki.archlinux.org/title/PipeWire#Troubleshooting) and I've got it installed on both working devices.
> 
> I don't know what flavor of Arch you are running but if you're on Manjaro you may also try installing the following packages:
> 
> ```
> manjaro-alsa
> manjaro-pipewire
> ```

I installed it and tried does not work for me. I am on arch not manjaro.

**Comment by hankjordan** [comment]
> > > > Last try,
> > > > Do you have `realtime-privileges` installed?
> > > > If not, please install it and make sure your current user is a member of the group `realtime`.
> > > > Then I'd completely restart your device and try to launch Runelite again.
> > > 
> > > 
> > > I do not what does that package do?
> > 
> > 
> > My best guess is that it allows your user to interact with the realtime audio process. I don't know for sure if it will resolve the issue but it is mentioned on [the Arch wiki PipeWire troubleshooting guide](https://wiki.archlinux.org/title/PipeWire#Troubleshooting) and I've got it installed on both working devices.
> > I don't know what flavor of Arch you are running but if you're on Manjaro you may also try installing the following packages:
> > ```
> > manjaro-alsa
> > manjaro-pipewire
> > ```
> 
> I installed it and tried does not work for me. I am on arch not manjaro.

Well I'm all out of ideas, sorry :(

**Comment by sangoku116** [comment]
> > > > > Last try,
> > > > > Do you have `realtime-privileges` installed?
> > > > > If not, please install it and make sure your current user is a member of the group `realtime`.
> > > > > Then I'd completely restart your device and try to launch Runelite again.
> > > > 
> > > > 
> > > > I do not what does that package do?
> > > 
> > > 
> > > My best guess is that it allows your user to interact with the realtime audio process. I don't know for sure if it will resolve the issue but it is mentioned on [the Arch wiki PipeWire troubleshooting guide](https://wiki.archlinux.org/title/PipeWire#Troubleshooting) and I've got it installed on both working devices.
> > > I don't know what flavor of Arch you are running but if you're on Manjaro you may also try installing the following packages:
> > > ```
> > > manjaro-alsa
> > > manjaro-pipewire
> > > ```
> > 
> > 
> > I installed it and tried does not work for me. I am on arch not manjaro.
> 
> Well I'm all out of ideas, sorry :(

Thank you for your help, I appreciate it! I don't think I will ever get to hear the runescape audio again since the issue is marked as wontfix.

**Comment by DoctorAmerica** [comment]
> using openjdk-11 `java -jar RuneLite.jar --configure` then in the JVM arguments section I put these four lines:
> 
> ```
> -Djavax.sound.sampled.Clip=com.sun.media.sound.DirectAudioDeviceProvider
> -Djavax.sound.sampled.Port=com.sun.media.sound.PortMixerProvider
> -Djavax.sound.sampled.SourceDataLine=com.sun.media.sound.DirectAudioDeviceProvider
> -Djavax.sound.sampled.TargetDataLine=com.sun.media.sound.DirectAudioDeviceProvider
> ```

I'm not sure what else I need to do here, but this gave me progress in that I now get this error instead:
```
2024-04-04 17:04:55 EDT [Client] ERROR client-patch - Error initializing sound engine. Audio will be unavailable.
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 22050.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian not supported.
        at java.desktop/com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:503)
        at java.desktop/com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:119)
        at java.desktop/com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:387)
        at ae.ah(ae.java:31)
        at ae.ah(ae.java:37)
        at hj.hf(hj.java:1557)
        at client.bh(client.java:1144)
        at bx.aa(bx.java:380)
        at bx.he(bx.java)
        at bx.run(bx.java:13052)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by guydols** [comment]
I had this problem too but **fixed** it and maybe it will help some of you.

I started Runelite for a terminal so I could see some more output.
There I saw it was complaining about a specific line of `/etc/pulseaudio/client.conf` saying `Unknown lvalue 'resample-method' in section 'n/a'`.
I could not remember ever editing that file, I removed the settings it was complaining about, it was 3 in total.
After restarting PulseAudio (`pulseaudio -k && pulseaudio -D` , or just reboot) Runelite sound worked again.

If this does not help you at all maybe the output you see from the terminal would put you on the right track.

**Comment by albinahlback** [comment]
I too get this issue, but I get no error message (to my knowledge) related to audio in the terminal.

**Comment by Eelinki** [comment]
I had the same issue with pipewire, turns out I did not have pipewire-alsa installed. So make sure you have the ALSA client installed if you are using pipewire.

**Comment by funnykeyboardsymbols** [comment]
> I had the same issue with pipewire, turns out I did not have pipewire-alsa installed. So make sure you have the ALSA client installed if you are using pipewire.

This solved it for me as well. Running Kubuntu 25.04 and the version of Runelite from the Lutris Jagex launcher package.

**Comment by MikeDriel** [comment]
I'm on CachyOS (arch) and I've tried everything I could find on this topic, but every time I launch RuneLite, it creates a lot of ALSA connections. And i've only seen this behaviour on RuneLite so far. Official launcher seems to work fine.

<img width="547" height="512" alt="Image" src="https://github.com/user-attachments/assets/beb0143f-002e-4c95-9555-57ea7c22fd2c" />

My installed pipewire packages:
<img width="707" height="522" alt="Image" src="https://github.com/user-attachments/assets/544ae6dd-9bc7-46be-986b-a2f7b6d59f6c" />

I'm fairly confident that PipeWire is correctly installed with all the necessary plugins. The only workaround that has somewhat helped is an extra command I have to run each time I start RuneLite. But it's not ideal.

I've created an alias for it:

`alias fixaudio='systemctl --user restart wireplumber pipewire pipewire-pulse'`

From what I can tell, running this cleans up the audio entries, leaving only one device. It also resolves the issue where the folder gets locked. As before i do this commands like `$ pactl info` also cease to function. So after the command i can open other applications, like my browser, and audio continues to work.

<img width="547" height="512" alt="Image" src="https://github.com/user-attachments/assets/c31b739d-c467-4fc3-a3ec-0aee62144760" />

I don't seem to grasp why it works as intended by restarting pipewire after launching RuneLite. Anyone got an idea?

**Comment by MikeDriel** [comment]
For anyone that it might help in the future. Turns out that this plugin was the culprit for me.  

<img width="241" height="406" alt="Image" src="https://github.com/user-attachments/assets/0583c430-48f3-4549-b7cc-a71a13d84382" />
