### ISSUE TITLE
Error building RuneLite from source - missing class rs2asmBaseListener 

### ISSUE THREAD

**Issue by Isometries** [runelite/runelite#3652]
I've followed the guide on the wiki but keep running across the problem:

```
Information:java: Errors occurred while compiling module 'cache'
Information:javac 1.8.0_171 was used to compile java sources
Information:6/6/18 2:41 AM - Compilation completed with 19 errors and 0 warnings in 3s 7ms
/home/ultralord/IdeaProjects/runelite/cache/src/main/java/net/runelite/cache/script/assembler/LabelVisitor.java
Error:(32, 35) java: cannot find symbol
  symbol: class rs2asmBaseListener
Error:(40, 49) java: package rs2asmParser does not exist
Error:(46, 44) java: package rs2asmParser does not exist
/home/ultralord/IdeaProjects/runelite/cache/src/main/java/net/runelite/cache/script/assembler/Assembler.java
Error:(31, 56) java: package net.runelite.cache.script.assembler.rs2asmParser does not exist
/home/ultralord/IdeaProjects/runelite/cache/src/main/java/net/runelite/cache/script/assembler/ScriptWriter.java
Error:(38, 35) java: cannot find symbol
  symbol: class rs2asmBaseListener
Error:(63, 47) java: package rs2asmParser does not exist
Error:(70, 54) java: package rs2asmParser does not exist
Error:(77, 57) java: package rs2asmParser does not exist
Error:(84, 52) java: package rs2asmParser does not exist
Error:(91, 55) java: package rs2asmParser does not exist
Error:(98, 49) java: package rs2asmParser does not exist
Error:(104, 50) java: package rs2asmParser does not exist
Error:(119, 50) java: package rs2asmParser does not exist
Error:(140, 50) java: package rs2asmParser does not exist
Error:(148, 54) java: package rs2asmParser does not exist
Error:(156, 52) java: package rs2asmParser does not exist
Error:(170, 52) java: package rs2asmParser does not exist
Error:(182, 48) java: package rs2asmParser does not exist
Error:(197, 50) java: package rs2asmParser does not exist
```

After ignoring the cache class (exclude form compile), I'm still ending up with a problem when running the compiled program:

```
2018-06-06 03:41:27 [main] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2018-06-06 03:41:28 [main] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2018-06-06 03:41:28 [Thread-4] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.ExceptionInInitializerError: null
	at ir.s(ir.java:55)
	at ks.n(ks.java:205)
	at bh.s(bh.java:33)
	at kv.z(kv.java:37)
	at aw.fd(aw.java:1366)
	at client.at(client.java:815)
	at aj.ab(aj.java:401)
	at aj.copy$run(aj.java:380)
	at aj.run(aj.java:60)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at net.runelite.api.overlay.OverlayIndex.<clinit>(OverlayIndex.java:46)
	... 10 common frames omitted
	Suppressed: java.lang.NullPointerException: null
		at java.io.FilterInputStream.close(FilterInputStream.java:181)
		at net.runelite.api.overlay.OverlayIndex.<clinit>(OverlayIndex.java:50)
		... 10 common frames omitted
2018-06-06 03:41:28 [main] INFO  n.r.client.account.SessionManager - No session file exists
```

I've seen other people on the discord have this problem as well, but no one has offered a solution.

**Comment by SoyChai** [comment]
Are you using a fresh clone of the official runelite repository? The guide on the wiki still works for me when creating a new project.

**Comment by Isometries** [comment]
Yes, I cloned it myself using `git clone`, and then set up maven as the guide said. I've tried deleting it and doing it fresh, but still get the same problem.

**Comment by sawyerclever** [comment]
You are most likely editing the default maven configuration and then clicking build. A lot of packages are downloaded after running the project. In IntelliJ, click 'Edit Configurations'. From there, do not expand the dropdown 'defaults' menu, instead, click the '+' in the configuration interface. Then continue following the process defined within the wiki. Then instead of building, use the 'Run' option which will allow you to get the missing files/directories. After this, the errors should be resolved.

**Comment by ahuangJM** [comment]
@sawyerclever solution worked for me. Thank you

**Comment by santi95** [comment]
Thanks @sawyerclever!
