### ISSUE TITLE
Xp globes can't handle levels over 126

### ISSUE THREAD

**Issue by Dreyri** [runelite/runelite#373]
When one has xp over lvl126 the following exception gets thrown

```
[Thread-8] WARN net.runelite.client.RuneLiteModule - uncaught exception in event subscriber
java.lang.IllegalArgumentException: 127 is not a valid level
	at net.runelite.api.Experience.getXpForLevel(Experience.java:53)
	at net.runelite.client.plugins.xpglobes.XpGlobesPlugin.onExperienceChanged(XpGlobesPlugin.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.runelite.client.callback.Hooks.callHook(Hooks.java:136)
	at client.gs(client.java)
	at client.ev(client.java)
	at client.aq(client.java)
	at be.p(be.java)
	at be.run(be.java)
	at java.lang.Thread.run(Thread.java:748)
```
either you could display next level at 200m or completely remove the next level part of the tooltip as there is no virtual level after 126.

**Comment by Adam-** [comment]
Fixed in 59afd6a7223df66bec8b27ec46da1a39f443131c
