### ISSUE TITLE
GroundItemPlugin Crashing Client

### ISSUE THREAD

**Issue by bolinkd** [runelite/runelite#3751]
| Question    | Answer
| ------------| ---------------
| Java Version | 1.8
| Operating System | Windows

Downloaded the most recent version of the client from master to run with my new pr.
Was at the GE when my Client Crashed.

<details>
 <summary>stack trace</summary>
 
 ```
java.lang.AbstractMethodError: Method jt.isTradeable()Z is abstract
	at jt.isTradeable(jt.java)
	at net.runelite.client.plugins.grounditems.GroundItemsPlugin.buildGroundItem(GroundItemsPlugin.java:310)
	at net.runelite.client.plugins.grounditems.GroundItemsPlugin.checkItems(GroundItemsPlugin.java:278)
	at net.runelite.client.plugins.grounditems.GroundItemsOverlay.render(GroundItemsOverlay.java:106)
	at net.runelite.client.ui.overlay.OverlayRenderer.safeRender(OverlayRenderer.java:572)
	at net.runelite.client.ui.overlay.OverlayRenderer.render(OverlayRenderer.java:349)
	at net.runelite.client.callback.Hooks.drawRegion(Hooks.java:337)
	at dm.aq(dm.java:62)
 ```
</details>

**Comment by bolinkd** [comment]
Nvm, it was an issue with maven build being out of date. Has been resolved
