### ISSUE TITLE
Runelite client causes screen to go black, flicker, and sleep

### ISSUE THREAD

**Issue by DevonRyder** [runelite/runelite#3979]
**Java Version**: OpenJDK 1.8.0_172
**Operating System**: Arch Linux

I have two screens on my system that are enabled, one via HDMI, and another via displayport. When the Runelite client is running on any screen it causes my main displayport screen to go black, sometimes coming back on and off periodically, and sometimes causing the display to completely enter sleep mode. Closing runelite fully immediately brings the display back. This happens whether or not I'm in fixed or resizable mode, or the client is fullscreen. Hardware acceleration is already disabled.

I am running a hybrid graphics/optimus laptop using bumblebee, but the issue persists whether I am running runelite normally, or via the Nvidia dGPU with Primusrun.

My latest log from `~/.runelite/logs/application.log`

`2018-06-23 11:37:59 [main] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2018-06-23 11:37:59 [main] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2018-06-23 11:38:00 [OkHttp https://api.runelite.net/...] INFO  net.runelite.client.account.WSClient - Websocket okhttp3.internal.ws.RealWebSocket@5245bea1 opened
2018-06-23 13:43:17 [pool-2-thread-1] WARN  n.r.client.ClientSessionManager - Resetting session
java.net.SocketTimeoutException: timeout
	at okio.Okio$4.newTimeoutException(Okio.java:227)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:284)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:240)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:344)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:216)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at net.runelite.http.api.session.SessionClient.ping(SessionClient.java:77)
	at net.runelite.client.ClientSessionManager.ping(ClientSessionManager.java:105)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:204)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.Okio$2.read(Okio.java:138)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:236)
	... 28 common frames omitted
2018-06-23 13:44:45 [main] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2018-06-23 13:44:46 [main] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2018-06-23 13:44:46 [OkHttp https://api.runelite.net/...] INFO  net.runelite.client.account.WSClient - Websocket okhttp3.internal.ws.RealWebSocket@6024fafb opened
2018-06-23 13:54:34 [main] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2018-06-23 13:54:35 [main] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2018-06-23 13:54:36 [OkHttp https://api.runelite.net/...] INFO  net.runelite.client.account.WSClient - Websocket okhttp3.internal.ws.RealWebSocket@43c8c97d opened`

**Comment by deathbeam** [comment]
What if you try this: https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by DevonRyder** [comment]
@deathbeam It happened while I was using Konduit as well, but I don't know the proper upstream to report to. This issue only started about a month ago.

**Comment by dekvall** [comment]
No additional information has been provided for more than a year so I am closing this. If the problem persists feel free to reopen the issue.

**Comment by najushua** [comment]
I have been having a similar issue with Runelite. 

I have a 2k monitor ran through display port and a 43in TV through HDMI
refocusing on the game after having another window selected (discord, a word document, or chrome) my monitor will go black for a few seconds in the exact same manner when you load into a fullscreen game before runelite appears on my screen. 

Only the Monitor connected through display port goes dark the TV displays as normal. 

I have both cables plugged into the 1070Ti GPU
