### ISSUE TITLE
Launcher fails to start, not on the FAQ

### ISSUE THREAD

**Issue by Vladthewarrior** [runelite/runelite#4272]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/issues)

| Question    | Answer
| ------------| ---------------
| Java Version | 8
| Operating System | Windows 10/64 Bit

<details>
 <summary>stack trace</summary>
 
 ```
2018-07-11 17:40:30 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to DIRECTDRAW
2018-07-11 17:40:39 [main] ERROR net.runelite.launcher.Launcher - unable to download artifacts
java.io.IOException: Server returned HTTP response code: 503 for URL: http://mvn.runelite.net/org/apache/commons/commons-text/1.2/commons-text-1.2.jar
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at net.runelite.launcher.Launcher.download(Launcher.java:323)
	at net.runelite.launcher.Launcher.main(Launcher.java:186)
2018-07-11 17:44:35 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to OFF
2018-07-11 17:44:36 [main] ERROR net.runelite.launcher.Launcher - unable to download artifacts
java.io.IOException: Server returned HTTP response code: 503 for URL: http://mvn.runelite.net/org/apache/commons/commons-text/1.2/commons-text-1.2.jar
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at net.runelite.launcher.Launcher.download(Launcher.java:323)
	at net.runelite.launcher.Launcher.main(Launcher.java:186)
2018-07-11 17:47:04 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to OFF
2018-07-11 17:47:05 [main] ERROR net.runelite.launcher.Launcher - unable to download artifacts
java.io.IOException: Server returned HTTP response code: 503 for URL: http://mvn.runelite.net/org/apache/commons/commons-text/1.2/commons-text-1.2.jar
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at net.runelite.launcher.Launcher.download(Launcher.java:323)
	at net.runelite.launcher.Launcher.main(Launcher.java:186)
 ```
</details>

**Comment by tr33s** [comment]
Blocked by firewall?

**Comment by Vladthewarrior** [comment]
Not the firewall. I have it disabled when attempting to run it and have runelite added under exemptions in case I missed something disabling it.

**Comment by Adam-** [comment]
Is this still happening? Those urls look reachable to me from here. What if you open http://mvn.runelite.net/org/apache/commons/commons-text/1.2/commons-text-1.2.jar in a browser?

**Comment by Vladthewarrior** [comment]
That fixed it, client opened right up after I opened it in a browser. Thank you!
