### ISSUE TITLE
building Runlite - java.lang.ExceptionInInitializerError: null

### ISSUE THREAD

**Issue by jordeguevara** [runelite/runelite#4314]
| Operating System: MacOS

I am using IntelliJ to build my project, I followed all the steps in the guide up to where it prompts  you to run runlite.main(). I assume it is because OSRS got updated but I don't know where to go from here. Any help would be appreciated!

The error I get:

java.lang.ExceptionInInitializerError: null
	at net.runelite.http.api.updatecheck.UpdateCheckClient.isOutdated(UpdateCheckClient.java:45)
	at net.runelite.client.ClientLoader.loadRs(ClientLoader.java:42)
	at net.runelite.client.RuneLite.start(RuneLite.java:213)
	at net.runelite.client.RuneLite.main(RuneLite.java:207)
Caused by: java.lang.RuntimeException: Version string has not been substituted; Re-run maven
	at net.runelite.http.api.RuneLiteAPI.<clinit>(RuneLiteAPI.java:63)

<details>
 <summary>stack trace</summary>
 
 ```
  %paste your stack trace here%
 ```
</details>

**Comment by Alexsuperfly** [comment]
The error literally says Re-run maven. Do that

**Comment by jordeguevara** [comment]
Thanks! silly me🤷‍♀️
