### ISSUE TITLE
Client loads but nothing happens

### ISSUE THREAD

**Issue by akutis4pres** [runelite/runelite#4454]
**Describe the bug**
When I click on the launcher on my desktop a load bar comes up and loads the client but as soon as it gets to 100% it disappears and nothing happens after. 

**To Reproduce**
1. Double click on launcher

**Expected behavior**
I expected OSRS to load.

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.4.8.1
 - Launcher version: Current launcher download on runelite.net

**Additional context**
There are two logs in the runelite logs. One is Launcher and the other is Launcher_2018-07-22.0

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client check if anything here helps first, and also follow instructions there to find any Exceptions/ERRORs in logs.

**Comment by akutis4pres** [comment]
I checked out the artifacts section but i'm still getting  "ERROR net.runelite.launcher.Launcher - unable to download artifacts
java.net.SocketException: Connection reset"

in my logs.

**Comment by akutis4pres** [comment]
Tested the method 1 and method 2 are coming up with the same results having that error in the launcher log.

**Comment by akutis4pres** [comment]
Am I able to get any help on this issue? I'd love to use this client!

**Comment by deathbeam** [comment]
Do you have the full log?

**Comment by akutis4pres** [comment]
2018-07-23 00:03:52 [main] ERROR net.runelite.launcher.Launcher - unable to download artifacts
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.MeteredStream.read(MeteredStream.java:134)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3393)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3386)
	at net.runelite.launcher.Launcher.download(Launcher.java:329)
	at net.runelite.launcher.Launcher.main(Launcher.java:186)
2018-07-23 00:08:20 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to DIRECTDRAW
2018-07-23 00:08:39 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to DIRECTDRAW
2018-07-23 00:13:04 [main] ERROR net.runelite.launcher.Launcher - unable to download artifacts
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.MeteredStream.read(MeteredStream.java:134)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3393)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3386)
	at net.runelite.launcher.Launcher.download(Launcher.java:329)
	at net.runelite.launcher.Launcher.main(Launcher.java:186)
2018-07-23 00:13:31 [main] ERROR net.runelite.launcher.Launcher - unable to download artifacts
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.MeteredStream.read(MeteredStream.java:134)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3393)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3386)
	at net.runelite.launcher.Launcher.download(Launcher.java:329)
	at net.runelite.launcher.Launcher.main(Launcher.java:186)
2018-07-23 00:30:05 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to OFF
2018-07-23 00:36:24 [main] ERROR net.runelite.launcher.Launcher - unable to download artifacts
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.MeteredStream.read(MeteredStream.java:134)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3393)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3386)
	at net.runelite.launcher.Launcher.download(Launcher.java:329)
	at net.runelite.launcher.Launcher.main(Launcher.java:186)
2018-07-23 00:44:50 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to DIRECTDRAW
2018-07-23 00:50:20 [main] ERROR net.runelite.launcher.Launcher - unable to download artifacts
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.MeteredStream.read(MeteredStream.java:134)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3393)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3386)
	at net.runelite.launcher.Launcher.download(Launcher.java:329)
	at net.runelite.launcher.Launcher.main(Launcher.java:186)
2018-07-23 00:56:20 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to OFF
2018-07-23 01:03:52 [main] ERROR net.runelite.launcher.Launcher - unable to download artifacts
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.MeteredStream.read(MeteredStream.java:134)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3393)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3386)
	at net.runelite.launcher.Launcher.download(Launcher.java:329)
	at net.runelite.launcher.Launcher.main(Launcher.java:186)
2018-07-23 01:11:16 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to OFF
2018-07-23 01:16:36 [main] ERROR net.runelite.launcher.Launcher - unable to download artifacts
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.MeteredStream.read(MeteredStream.java:134)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3393)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3386)
	at net.runelite.launcher.Launcher.download(Launcher.java:329)
	at net.runelite.launcher.Launcher.main(Launcher.java:186)
2018-07-23 01:18:54 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to OFF
2018-07-23 01:22:20 [main] ERROR net.runelite.launcher.Launcher - unable to download artifacts
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.MeteredStream.read(MeteredStream.java:134)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3393)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3386)
	at net.runelite.launcher.Launcher.download(Launcher.java:329)
	at net.runelite.launcher.Launcher.main(Launcher.java:186)
2018-07-23 01:28:10 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to DIRECTDRAW
2018-07-23 01:34:32 [main] ERROR net.runelite.launcher.Launcher - unable to download artifacts
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.MeteredStream.read(MeteredStream.java:134)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3393)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3386)
	at net.runelite.launcher.Launcher.download(Launcher.java:329)
	at net.runelite.launcher.Launcher.main(Launcher.java:186)
2018-07-23 01:35:18 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to DIRECTDRAW
2018-07-23 01:39:53 [main] ERROR net.runelite.launcher.Launcher - unable to download artifacts
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.MeteredStream.read(MeteredStream.java:134)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3393)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3386)
	at net.runelite.launcher.Launcher.download(Launcher.java:329)
	at net.runelite.launcher.Launcher.main(Launcher.java:186)
2018-07-23 01:40:23 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to DIRECTDRAW
2018-07-23 01:43:42 [main] ERROR net.runelite.launcher.Launcher - unable to download artifacts
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.MeteredStream.read(MeteredStream.java:134)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3393)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3386)
	at net.runelite.launcher.Launcher.download(Launcher.java:329)
	at net.runelite.launcher.Launcher.main(Launcher.java:186)
2018-07-23 02:33:19 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to OFF
2018-07-23 02:36:00 [main] ERROR net.runelite.launcher.Launcher - unable to download artifacts
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.MeteredStream.read(MeteredStream.java:134)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3393)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3386)
	at net.runelite.launcher.Launcher.download(Launcher.java:329)
	at net.runelite.launcher.Launcher.main(Launcher.java:186)

**Comment by Gamer1120** [comment]
Is your firewall blocking access to some websites maybe?

**Comment by akutis4pres** [comment]
Not that i'm aware of. That's never been an issue before.
