### ISSUE TITLE
"Players" DevTool throwing errors

### ISSUE THREAD

**Issue by MagicfTail** [runelite/runelite#4582]
When turned on, it throws the following error every frame, but everything seems to be working

`[Thread-2] WARN  net.runelite.client.callback.Hooks - Error during overlay rendering
java.lang.ArrayIndexOutOfBoundsException: null`

**Comment by MagicfTail** [comment]
`WARN  net.runelite.client.callback.Hooks - Error during overlay rendering
java.lang.ArrayIndexOutOfBoundsException: 159
	at net.runelite.api.Perspective.getTileHeight(Perspective.java:254)
	at net.runelite.api.Perspective.worldToCanvas(Perspective.java:103)
	at net.runelite.api.Perspective.worldToCanvas(Perspective.java:86)
	at bp.getPolygons(bp.java:132)
	at net.runelite.client.plugins.devtools.DevToolsOverlay.renderPlayerWireframe(DevToolsOverlay.java:506)
	at net.runelite.client.plugins.devtools.DevToolsOverlay.renderPlayers(DevToolsOverlay.java:159)
	at net.runelite.client.plugins.devtools.DevToolsOverlay.render(DevToolsOverlay.java:110)
	at net.runelite.client.ui.overlay.OverlayRenderer.safeRender(OverlayRenderer.java:385)
	at net.runelite.client.ui.overlay.OverlayRenderer.render(OverlayRenderer.java:170)
	at net.runelite.client.callback.Hooks.draw(Hooks.java:290)
	at ae.k(ae.java:49)
	at ae.s(ae.java:39)
	at client.aq(client.java:959)
	at ap.an(ap.java:436)
	at ap.copy$run(ap.java:390)
	at ap.run(ap.java:68)
	at java.base/java.lang.Thread.run(Thread.java:844)`

**Comment by Abextm** [comment]
This is caused by an out of date injected client
