### ISSUE TITLE
Report button plugin not working

### ISSUE THREAD

**Issue by Twiglet1022** [runelite/runelite#4748]
**Describe the bug**
As of the latest update the report button plugin no longer works. The report button just says "Report", no timer is displayed.

**To Reproduce**
1. Turn on the "Report button" plugin
2. Set it to any option other than "Off"

**Expected behavior**
The text of the report button should be replaced with the selected timer/clock.

**Screenshots**
https://i.imgur.com/VVA06X3.png

**Environment (please complete the following information):**
 - OS: Windows 10 Home
 - RuneLite version: 1.4.10.2
 - Launcher version: Unknown

**Additional context**
Here's the most recent log file:

2018-08-04 09:38:43 [OkHttp https://api.runelite.net/...] INFO  net.runelite.client.account.WSClient - Websocket okhttp3.internal.ws.RealWebSocket@2b2fd305 opened
2018-08-04 09:38:48 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1258x1040,invalid,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1258x1040,invalid,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@433cad2d,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2018-08-04 17:31:40 [OkHttp https://api.runelite.net/...] WARN  net.runelite.client.account.WSClient - Error in websocket
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at sun.security.ssl.InputRecord.readFully(Unknown Source)
	at sun.security.ssl.InputRecord.read(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
	at sun.security.ssl.AppInputStream.read(Unknown Source)
	at okio.Okio$2.read(Okio.java:138)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:236)
	at okio.RealBufferedSource.request(RealBufferedSource.java:66)
	at okio.RealBufferedSource.require(RealBufferedSource.java:59)
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:72)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:262)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:201)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2018-08-04 17:31:40 [pool-2-thread-1] WARN  n.r.client.ClientSessionManager - Resetting session
java.io.IOException: Unsuccessful ping
	at net.runelite.http.api.session.SessionClient.ping(SessionClient.java:81)
	at net.runelite.client.ClientSessionManager.ping(ClientSessionManager.java:105)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2018-08-04 17:32:10 [OkHttp https://api.runelite.net/...] INFO  net.runelite.client.account.WSClient - Websocket okhttp3.internal.ws.RealWebSocket@477ae51e opened
2018-08-05 09:07:48 [OkHttp https://api.runelite.net/...] INFO  net.runelite.client.account.WSClient - Websocket okhttp3.internal.ws.RealWebSocket@4f343706 opened
2018-08-05 09:07:52 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,809x1040,invalid,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x1040,invalid,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@14395b14,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2018-08-05 12:10:29 [OkHttp https://api.runelite.net/...] WARN  net.runelite.client.account.WSClient - Error in websocket
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at sun.security.ssl.InputRecord.readFully(Unknown Source)
	at sun.security.ssl.InputRecord.read(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
	at sun.security.ssl.AppInputStream.read(Unknown Source)
	at okio.Okio$2.read(Okio.java:138)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:236)
	at okio.RealBufferedSource.request(RealBufferedSource.java:66)
	at okio.RealBufferedSource.require(RealBufferedSource.java:59)
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:72)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:262)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:201)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2018-08-05 12:10:30 [pool-2-thread-1] WARN  n.r.client.ClientSessionManager - Resetting session
java.io.IOException: Unsuccessful ping
	at net.runelite.http.api.session.SessionClient.ping(SessionClient.java:81)
	at net.runelite.client.ClientSessionManager.ping(ClientSessionManager.java:105)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2018-08-05 12:11:00 [OkHttp https://api.runelite.net/...] INFO  net.runelite.client.account.WSClient - Websocket okhttp3.internal.ws.RealWebSocket@52daeb88 opened
2018-08-05 22:11:25 [OkHttp https://api.runelite.net/...] INFO  net.runelite.client.account.WSClient - Websocket okhttp3.internal.ws.RealWebSocket@482f1153 opened
2018-08-05 22:11:29 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1419x1040,invalid,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1419x1040,invalid,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@6c1019c4,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2018-08-05 22:11:32 [pool-2-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready.
2018-08-06 07:56:49 [OkHttp https://api.runelite.net/...] INFO  net.runelite.client.account.WSClient - Websocket okhttp3.internal.ws.RealWebSocket@223af94b opened
2018-08-06 07:56:54 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1591x1040,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1591x1040,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@7e6249a2,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2018-08-06 19:28:25 [OkHttp https://api.runelite.net/...] INFO  net.runelite.client.account.WSClient - Websocket okhttp3.internal.ws.RealWebSocket@7aed2128 opened
2018-08-06 19:28:28 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1591x1040,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1591x1040,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@61aa71a4,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2018-08-06 20:54:22 [OkHttp https://api.runelite.net/...] INFO  net.runelite.client.account.WSClient - Websocket okhttp3.internal.ws.RealWebSocket@561c4046 opened
2018-08-06 20:54:24 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1591x1040,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1591x1040,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@5d595a39,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2018-08-06 21:09:50 [OkHttp https://api.runelite.net/...] INFO  net.runelite.client.account.WSClient - Websocket okhttp3.internal.ws.RealWebSocket@561c4046 opened
2018-08-06 21:09:51 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1478x1040,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1478x1040,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@757f5dbf,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2018-08-06 21:09:54 [pool-2-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready.

**Comment by devLotto** [comment]
Fixed with #4740
