### ISSUE TITLE
Client simply wouldn't run suddenly

### ISSUE THREAD

**Issue by mjglqw** [runelite/runelite#5040]
Client simply won't run. No errors(GUI), no loading screens, etc.

 - OS: Ubuntu 18.04
 - RuneLite version: Couldn't find out as it won't open. Not sure how to check via cmd.

No logs for some reason. Here's the error on cmd though, via java -jar

```
2018-08-21 18:38:50 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to OPENGL
Exception in thread "main" java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
	at java.desktop/java.awt.Toolkit.newAWTError(Toolkit.java:472)
	at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Toolkit.java:488)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1608)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.desktop/java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:532)
	at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:613)
	at java.desktop/sun.swing.SwingUtilities2.getSystemMnemonicKeyMask(SwingUtilities2.java:2143)
	at java.desktop/javax.swing.plaf.basic.BasicLookAndFeel.initComponentDefaults(BasicLookAndFeel.java:1096)
	at java.desktop/javax.swing.plaf.metal.MetalLookAndFeel.initComponentDefaults(MetalLookAndFeel.java:440)
	at java.desktop/javax.swing.plaf.basic.BasicLookAndFeel.getDefaults(BasicLookAndFeel.java:150)
	at java.desktop/javax.swing.plaf.metal.MetalLookAndFeel.getDefaults(MetalLookAndFeel.java:1560)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:587)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:628)
	at net.runelite.launcher.Launcher.main(Launcher.java:156)
Caused by: java.lang.ClassNotFoundException: org.GNOME.Accessibility.AtkWrapper
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:374)
	at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Toolkit.java:485)
	... 19 more


```

**Comment by sluppo** [comment]
I am also facing the same issue on Ubuntu 18.04 with the same exception in terminal.

**Comment by rstabler** [comment]
Yup - JAVA broken on my 18.04 too. 
Removing openjdk11 brings back some java programmes........

**Comment by bekemaydin** [comment]
Same problem and same results on terminal here. 
Ubuntu 18.04

$ java --version
openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.1)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.1, mixed mode)

Also osbuddy is not working too.

**Comment by Adam-** [comment]
Deleting `https://github.com/runelite/launcher/releases/download/1.6.0/RuneLite.jar` on Ubuntu 18 seems to fix it for me.

**Comment by DevonRyder** [comment]
Any idea on the reasoning @Adam- ? Did something change with a java update?

**Comment by mjglqw** [comment]
@Adam- that worked. thanks!

**Comment by bekemaydin** [comment]
I set the oracle java 8 as default with 
$ sudo apt install oracle-java8-set-default
and that worked for me now.

**Comment by deathbeam** [comment]
Looks like this is nothing we can solve. Added relevant section to the troubleshooting page here: https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client#client-not-launching-on-linux and closing this issue.

**Comment by Adam-** [comment]
If we want to track this, it would be better under runelite/launcher.

**Comment by Farcrada** [comment]
You can run: `sudo update-alternatives --config java` and select a previous Java version (8 is preferred) (`sudo apt-get install openjdk-8-jre` to install Java 8 if it isn't already.)

If you need the other version again, running this command doesn't add an incredible delay to the process.
