### ISSUE TITLE
Tiled display on Linux unless playing in stretched fixed mode

### ISSUE THREAD

**Issue by TaxoRubio** [runelite/runelite#5156]
**Describe the bug**
The game screen only draws a square at the top left of the screen and repeats it over and over again. Interactions can be made, but the screen is not properly drawn.

**To Reproduce**
1. Open Runelite.jar
2. Set Stretched Fixed Mode off
3. ???
4. Profit 

**Expected behavior**
The screen should draw normally, not just the top left square.

**Screenshots**
![](http://i.imgur.com/9uMuTLR.png)
The only settings the game will run in.
![](http://i.imgur.com/c5kmItA.png)
The tiled display. As you can see, the mouse is pointing at the fixed mode button, so only the final screen drawing is affected. 

**Environment (please complete the following information):**
 - OS: Linux Mint 19 Tara running Xfce 4.12.3 (Gtk 2.24.31) desktop
 - RuneLite version: 1.4.14
 - Launcher version: 1.6.0

**Additional context**
Application.log:
```
2018-08-27 13:09:11 [main] INFO  n.r.client.account.SessionManager - No session file exists
2018-08-27 13:09:11 [main] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2018-08-27 13:09:16 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,279,117,809x534,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@4f0d0a9e,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2018-08-27 13:09:16 [main] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2018-08-27 13:09:18 [main] INFO  net.runelite.client.RuneLite - Client initialization took 9431ms. Uptime: 9866ms
2018-08-27 13:09:28 [Thread-4] WARN  n.r.client.callback.ClientThread - Exception in invoke
java.lang.NullPointerException: null
	at net.runelite.client.game.SpriteManager.getSprite(SpriteManager.java:75)
	at net.runelite.client.game.SpriteManager.lambda$getSpriteAsync$0(SpriteManager.java:92)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:149)
	at client.methodDraw(client.java:1132)
	at client.an(client.java)
	at am.ah(am.java:392)
	at am.run(am.java:346)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration
