### ISSUE TITLE
Lookup never fails when looking up a player that doesn't exist

### ISSUE THREAD

**Issue by MagicfTail** [runelite/runelite#5513]
Returns the following error:
`2018-09-16 03:12:06 [pool-2-thread-1] WARN  n.r.c.util.RunnableExceptionLogger - Uncaught exception in runnable net.runelite.client.plugins.hiscore.HiscorePanel$$Lambda$387/1265071771@734e6b1f
java.lang.IllegalArgumentException: null
	at net.runelite.http.api.hiscore.HiscoreClient.lookupUsername(HiscoreClient.java:95)
	at net.runelite.http.api.hiscore.HiscoreClient.lookup(HiscoreClient.java:47)
	at net.runelite.http.api.hiscore.HiscoreClient.lookup(HiscoreClient.java:42)
	at net.runelite.client.plugins.hiscore.HiscorePanel.lookup(HiscorePanel.java:383)
	at net.runelite.client.util.RunnableExceptionLogger.run(RunnableExceptionLogger.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by MagicfTail** [comment]
The same thing happens if you try to lookup the "Ironman Hiscores" for a player that isn't an ironman, except with no error
