### ISSUE TITLE
Uncaught NumberFormatException in SlayerPlugin when being assigned boss task

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#5848]
```
2018-10-06 00:42:32 [Thread-7] WARN  net.runelite.client.RuneLiteModule - uncaught exception in event subscriber
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.parseInt(Integer.java:615)
	at net.runelite.client.plugins.slayer.SlayerPlugin.onGameTick(SlayerPlugin.java:272)
	at sun.reflect.GeneratedMethodAccessor132.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:143)
	at client.methodDraw(client.java:1200)
	at client.am(client.java)
	at ai.ax(ai.java:414)
	at ai.run(ai.java:368)
	at java.lang.Thread.run(Thread.java:748)
```

This was after receiving a Barrows Brothers task. Unfortunately, I skipped past the assignment dialog so I don't know what the exact text for the assignment was.

**Comment by Nightfirecat** [comment]
Apparently the barrows brother task assignment is matched by `NPC_ASSIGN_MESSAGE`, which is usually reserved for non-boss tasks.

```
NPC_ASSIGN_MESSAGE = Pattern.compile(".*Your new task is to kill\\s*(\\d*) (.*)\\.");
```

**Comment by Nightfirecat** [comment]
@deathbeam I feel like one of your PRs fixed this issue?

**Comment by deathbeam** [comment]
Hmm probably, we can close it and reopen if it still occurs

**Comment by Nightfirecat** [comment]
This isn't fixed on master; I got the same error when getting a Commander Zilyana task:

```
2018-12-07 12:01:50 [Thread-7] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.parseInt(Integer.java:615)
	at net.runelite.client.plugins.slayer.SlayerPlugin.onGameTick(SlayerPlugin.java:285)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:72)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:218)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:146)
	at client.methodDraw(client.java:1249)
	at client.ar(client.java)
	at ah.o(ah.java:356)
	at ah.run(ah.java:310)
	at java.lang.Thread.run(Thread.java:748)
```

![untitled](https://user-images.githubusercontent.com/2199511/49670115-72376100-fa5b-11e8-875e-e5db520638af.png)

**Comment by Nightfirecat** [comment]
I remembered to actually slow down and get a screenshot of the text this time around. Same error as my most recent comment.

![2019-01-16_17-15-44](https://user-images.githubusercontent.com/2199511/51302971-dcb0c900-1a2b-11e9-90c1-52760530b291.png)

**Comment by Nightfirecat** [comment]
I've done a number of boss tasks and gained several million slayer experience since the last comment here, and not encountered this error again. It's possible this is specific to barrows tasks, but I don't know about whether that's actually the case, and haven't gotten another one of those to verify since, so I'm closing this for the time being.
