### ISSUE TITLE
Unable to start client using OpenJDK 11, SSLHandshakeException

### ISSUE THREAD

**Issue by KingEdwardV** [runelite/runelite#6221]
**Describe the bug**
Using Ubuntu 16.04, and after having installed OpenJDK 11, the latest version, RuneLite.jar no longer starts due to a 'SSLHandshakeException'. RuneLite previously started using OpenJDK 8.

**To Reproduce**
- install OpenJDK 11 for Ubuntu 16.04
- run the command: java -jar RuneLite.jar

```
ubuntu@terminal:~$ java -jar RuneLite.jar 
2018-10-27 20:31:11 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to OPENGL
2018-10-27 20:31:12 [main] ERROR net.runelite.launcher.Launcher - error fetching bootstrap
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:128)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:312)
	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:270)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:181)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:877)
	at java.base/sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:810)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:383)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245)
	at net.runelite.launcher.Launcher.getBootstrap(Launcher.java:265)
	at net.runelite.launcher.Launcher.main(Launcher.java:168)

```

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04
 - RuneLite version: 1.6.1

**Comment by deathbeam** [comment]
Did you tried the troubleshooting guide? https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client#problems-with-accessing-api

**Comment by KingEdwardV** [comment]
Thank you for the suggestion, unfortunately it didn't fix my issues.

I fixed this by reverting to OpenJDK 8. 

If anyone else is having this issue, and wants to revert, the following command line will prompt you choose your default Java version:

`sudo update-alternatives --config java`

**Comment by deathbeam** [comment]
Well looks like this is not RuneLite-related issue then, and so closing.

**Comment by AHeavner** [comment]
Why is this labeled invalid? There's nothing wrong with OpenJDK-11. Using OpenJDK-8 is a work-around.

**Comment by AHeavner** [comment]
Are you sure about that?

**Comment by Abextm** [comment]
yes, your install of jdk11 is missing certs probably

**Comment by douglasg14b** [comment]
Also having this issue.

@deathbeam  Why doesn't runelite provide java version info in the FAQ to avoid this if there isn't JDK11 support?

**Comment by deathbeam** [comment]
Feel free to add it, but it works flawlessly on JDK 8, so your installation is probably just incorrect

**Comment by nt4cats** [comment]
This problem was resolved for me when OpenJDK updated to `openjdk version "11.0.2" 2019-01-15`.
