### ISSUE TITLE
 n.r.client.plugins.PluginManager - Unable to start plugin StretchedModePlugin. 

### ISSUE THREAD

**Issue by formatme** [runelite/runelite#6286]
[main] WARN  n.r.client.plugins.PluginManager - Unable to start plugin StretchedModePlugin. {}
net.runelite.client.plugins.PluginInstantiationException: java.lang.reflect.InvocationTargetException
	at net.runelite.client.plugins.PluginManager.startPlugin(PluginManager.java:342)
	at net.runelite.client.plugins.PluginManager.startCorePlugins(PluginManager.java:207)
	at net.runelite.client.RuneLite.start(RuneLite.java:295)
	at net.runelite.client.RuneLite.main(RuneLite.java:221)
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1349)
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1324)
	at javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1353)
	at net.runelite.client.plugins.PluginManager.startPlugin(PluginManager.java:314)
	... 3 common frames omitted
Caused by: java.lang.AbstractMethodError: Method client.setScalingFactor(I)V is abstract
	at client.setScalingFactor(client.java)
	at net.runelite.client.plugins.stretchedmode.StretchedModePlugin.updateConfig(StretchedModePlugin.java:116)
	at net.runelite.client.plugins.stretchedmode.StretchedModePlugin.startUp(StretchedModePlugin.java:76)
	at net.runelite.client.plugins.PluginManager.lambda$startPlugin$3(PluginManager.java:318)
	at java.awt.event.InvocationEvent.dispatch$$$capture(InvocationEvent.java:301)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2018-10-31 19:34:27 [main] INFO  net.runelite.client.RuneLite - Client initialization took 7469ms. Uptime: 8034ms

**Comment by deathbeam** [comment]
This was already solved, builds were broken
