### ISSUE TITLE
Agility plugin crash

### ISSUE THREAD

**Issue by Abextm** [runelite/runelite#647]
Got this when teleporting to the gnome stronghold. On a branch based on `b43bef40`

```
Exception in thread "Thread-6" java.lang.AssertionError
	at net.runelite.api.model.Jarvis.convexHull(Jarvis.java:82)
	at net.runelite.api.Perspective.getAABB(Perspective.java:674)
	at net.runelite.api.Perspective.getClickbox(Perspective.java:509)
	at dn.getClickbox(dn.java)
	at net.runelite.client.plugins.agilityplugin.AgilityOverlay.lambda$render$0(AgilityOverlay.java:66)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at net.runelite.client.plugins.agilityplugin.AgilityOverlay.render(AgilityOverlay.java:61)
	at net.runelite.client.ui.overlay.OverlayRenderer.safeRender(OverlayRenderer.java:298)
	at net.runelite.client.ui.overlay.OverlayRenderer.lambda$render$4(OverlayRenderer.java:257)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.runelite.client.ui.overlay.OverlayRenderer.render(OverlayRenderer.java:225)
	at net.runelite.client.callback.Hooks.drawRegion(Hooks.java:131)
	at ec.ay(ec.java)
	at m.ih(i.java)
	at fi.ix(fi.java)
	at client.ge(client.java)
	at client.ah(client.java)
	at bt.ax(bt.java)
	at bt.run(bt.java)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by deathbeam** [comment]
Is this still happening? Also, this does not happen without the assertions enabled, and it still seems to work fine, so probably the assertion is wrong?

**Comment by Abextm** [comment]
I haven't had it happen again, but I think we should still  figure out why
it happened.

**Comment by devLotto** [comment]
This happens if the list passed to Jarvis.convexHull(...) only consists of nulls, as "next" is always null. This happens when all worldToCanvas calls in Perspective#getAABB(...) return null. That in turn happens if y is less than 50 in worldToCanvas.

Our worldToCanvas isn't as refactored, so let's use https://github.com/Wingman/wingman/blob/master/src/main/java/com/wingman/defaultplugins/devutils/game/world/Perspective.java#L133 as reference. transformedZ (y in our case) is the distance between the camera and the point in 3D space, as illustrated by https://en.wikipedia.org/wiki/3D_projection#Diagram.

So from what I could gather from that, if getAABB is being called on 3D points that are very close to the camera, "next" is always null, which causes the assertion to fail. I'm not exactly sure why is less than 50, but it seems to happen some in Ardougne.
