### ISSUE TITLE
Remember Tag Tab ArrayOutOfBounds exception

### ISSUE THREAD

**Issue by Alexsuperfly** [runelite/runelite#6563]
When opening the bank to a remembered Tag Tab hundreds of ArrayIndexOutOfBoundsExceptions are thrown.

```
2018-11-18 11:51:56 [Thread-5] WARN  net.runelite.client.RuneLiteModule - uncaught exception in event subscriber
java.lang.ArrayIndexOutOfBoundsException: null
2018-11-18 11:51:56 [Thread-5] WARN  net.runelite.client.RuneLiteModule - uncaught exception in event subscriber
java.lang.ArrayIndexOutOfBoundsException: -1
	at net.runelite.client.plugins.banktags.BankTagsPlugin.onScriptCallbackEvent(BankTagsPlugin.java:184)
	at sun.reflect.GeneratedMethodAccessor78.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.runelite.client.callback.Hooks.post(Hooks.java:128)
	at gr.au(gr.java:833)
	at o.jl(o.java:11251)
	at client.gz(client.java:5724)
	at client.fk(client.java:2780)
	at client.ad(client.java:1216)
	at ah.ac(ah.java:338)
	at ah.run(ah.java:317)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Adam-** [comment]
This is due to the eventbus deferring the event until later (outside of the vm)
