### ISSUE TITLE
Launcher crashing at 0% (Arch Linux)

### ISSUE THREAD

**Issue by hshackle** [runelite/runelite#7044]
When running runelite, the launcher crashes at 0%. This seems similar to the SSL exception problem as mentioned in the FAQ, except the listed workaround does not work on Arch Linux. Using the current AUR version (says 1.6.1-1).

The log is included below:

`2018-12-21 11:02:34 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to OPENGL
2018-12-21 11:02:36 [main] ERROR net.runelite.launcher.Launcher - error fetching bootstrap
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:128)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:308)
	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:279)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:181)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245)
	at net.runelite.launcher.Launcher.getBootstrap(Launcher.java:265)
	at net.runelite.launcher.Launcher.main(Launcher.java:168)`

This was ran on a mostly-new installation of Arch Linux, with only Java 11 downloaded. Installing various other versions of Java don't seem to fix this. I'm not sure whether it's more appropriate to post this here or somewhere more Arch-related, but thought I'd post it here in case the bug is actually unrelated to Arch.

**Comment by ruany** [comment]
Try using the launch option: `-Djdk.tls.client.protocols=TLSv1.2` (before the `-jar` option)
