### ISSUE TITLE
Game freezes when using GPU

### ISSUE THREAD

**Issue by meaud** [runelite/runelite#7181]
**Describe the bug**
The game will freeze randomly after enabling GPU, usually just a few minutes after. The runelite client is still responsive, but not the game.

-I have tried disabling HW acceleration
-I have tried using the all platforms version
-Clean install of latest driver
-tried all fixes in the GPU FAQ

**To Reproduce**
1. Enable GPU plugin, any combination of settings

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.6
 - Launcher version: 1.6
 - geforce gtx 780
 - 8gb Ram
 - i5 4670

**Additional context**
Log:
2019-01-04 14:14:46 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2019-01-04 14:14:46 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-01-04 14:14:47 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1920x1040,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@1656653,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-01-04 14:14:47 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-01-04 14:14:49 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 9291ms. Uptime: 11682ms
2019-01-04 14:18:54 [Thread-7] ERROR net.runelite.client.RuneLite - Game crash
com.jogamp.opengl.GLException: GL-Error 0x505 while creating mutable storage for target 0x8892 -> buffer 5 of size 144864 with data java.nio.DirectIntBufferU[pos=0 lim=36216 cap=8388608]
	at jogamp.opengl.GLBufferObjectTracker.createBufferStorage(GLBufferObjectTracker.java:176)
	at jogamp.opengl.gl4.GL4bcImpl.glBufferData(GL4bcImpl.java:40258)
	at net.runelite.client.plugins.gpu.GpuPlugin.draw(GpuPlugin.java:874)
	at ah.onPost(ah.java:84)
	at ah.p(ah.java)
	at ah.run(ah.java:311)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Alexsuperfly** [comment]
are you sure the gpu plugin is running off your dedicated card.  A 505 error is a GL_OUT_OF_MEMORY error and your 780 should definitely have enough.

**Comment by meaud** [comment]
> 
> 
> are you sure the gpu plugin is running off your dedicated card. A 505 error is a GL_OUT_OF_MEMORY error and your 780 should definitely have enough.

![capture](https://user-images.githubusercontent.com/46364881/50675396-9b86e500-1039-11e9-8afd-41e74c075175.PNG)

I am pretty sure?

**Comment by gypsyvoiidz** [comment]
Was this ever patched or a fixed ? I am getting a very similar problem on a RTX 2060.

**Comment by xgalpin** [comment]
dude i been getting this for months and no one can help, i pray this gets fixed

**Comment by gypsyvoiidz** [comment]
Sorry to hear it man..... I am still getting it too.. spent hours trying to fix it :(

**Comment by xgalpin** [comment]
geforce gtx 1660 too, it worked when i first got the comp then after a month it stopped

**Comment by meaud** [comment]
This stopped happening to me after I switched from HDMI to display port cable. Although I'm not sure if that actually had anything to do with it

**Comment by gpbollen** [comment]
I had exactly this problem when I got a new second monitor a couple of days ago. It does not seem to be a RuneLite specific issue, though.

> 
> 
> This stopped happening to me after I switched from HDMI to display port cable. Although I'm not sure if that actually had anything to do with it

This solution worked for me as well.

**Comment by MESLewis** [comment]
Reopen this issue if the problem persists in the current RuneLite release.
