### ISSUE TITLE
client instantly closes

### ISSUE THREAD

**Issue by 3duz** [runelite/runelite#7347]
every time i try to open runelite it instantly closes and i tried reinstalling runelite and java. i also tried every other solution i found in github but none of those helped

all i have in logs is this message

2019-01-13 21:39:37 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to DIRECTDRAW
2019-01-13 21:39:38 [main] ERROR net.runelite.launcher.Launcher - error fetching bootstrap
java.io.IOException: Server returned HTTP response code: 403 for URL: http://static.runelite.net/bootstrap.json
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at net.runelite.launcher.Launcher.getBootstrap(Launcher.java:264)
	at net.runelite.launcher.Launcher.main(Launcher.java:168)

also osbuddy doesn't let me login on my account or just as guest idk if that is connected to this problem somehow.

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client 403 means access denied, nothing that we can do about it
