### ISSUE TITLE
Status bars throwing ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Joshwat** [runelite/runelite#7357]
**Describe the bug**
The game randomly disconnects and/or loses connection.

**To Reproduce**
Just play the game, no specific action needed.

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.7
 - Launcher version: 1.6.0

**Additional context**
2019-01-14 15:09:29 [Thread-7] WARN  net.runelite.client.callback.Hooks - Error during overlay rendering
java.lang.ArrayIndexOutOfBoundsException: -1
	at net.runelite.client.plugins.statusbars.StatusBarsOverlay.render(StatusBarsOverlay.java:186)
	at net.runelite.client.ui.overlay.OverlayRenderer.safeRender(OverlayRenderer.java:399)
	at net.runelite.client.ui.overlay.OverlayRenderer.render(OverlayRenderer.java:180)
	at net.runelite.client.callback.Hooks.drawAfterWidgets(Hooks.java:435)
	at client.gd(client.java:4512)
	at client.ar(client.java:1575)
	at ah.o(ah.java:356)
	at ah.run(ah.java:310)
	at java.lang.Thread.run(Thread.java:748)
2019-01-14 15:10:32 [Thread-7] WARN  net.runelite.client.callback.Hooks - Error during overlay rendering
java.lang.ArrayIndexOutOfBoundsException: null
2019-01-14 15:11:01 [Thread-7] WARN  net.runelite.client.callback.Hooks - Error during overlay rendering
java.lang.ArrayIndexOutOfBoundsException: null

![bug1](https://user-images.githubusercontent.com/39422750/51134649-ef05e980-1816-11e9-8445-ad6990205318.png)
![bug2](https://user-images.githubusercontent.com/39422750/51134648-ef05e980-1816-11e9-86bd-5146466c8aae.png)

**Comment by Defragler** [comment]
Taking a look at this

**Comment by Adam-** [comment]
I already have this fixed actually I just forgot about it and didn't push it.

**Comment by Adam-** [comment]
Fixed in e97c5ba517fcd9cf9c89546123de8c773899fbd0
