### ISSUE TITLE
GLException when closing client

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#7492]
When closing latest master's RuneLite:

<details><summary>Expand to see logs</summary>
<pre><code>GLDrawableFactory.shutdownAll 2 instances, on thread NativeWindowFactory_ShutdownHook
GLDrawableFactory.shutdownAll[1/2]:  jogamp.opengl.windows.wgl.WindowsWGLDrawableFactory
DisplayGamma: Reset
WindowsWGLDrawableFactory.shutdown
SharedResourceRunner.stop() - NativeWindowFactory_ShutdownHook
SharedResourceRunner.run(): RELEASE START - Thread-5-SharedResourceRunner
Shutdown Shared:
Device  : WindowsGraphicsDevice[type .windows, connection decon, unitID 0, handle 0x0, owner false, NullToolkitLock[obj 0x1b3cb867]]
Screen  : DefaultGraphicsScreen[WindowsGraphicsDevice[type .windows, connection decon, unitID 0, handle 0x0, owner false, NullToolkitLock[obj 0x1b3cb867]], idx 0]
Drawable: WindowsOnscreenWGLDrawable[Realized true,
	Factory   jogamp.opengl.windows.wgl.WindowsWGLDrawableFactory@146e92ae,
	Handle    0x0,
	Surface   GDISurface[ displayHandle 0x0
, surfaceHandle 0x0
, size 64x64
, UOB[ OWNS_SURFACE | WINDOW_INVISIBLE ]
, WindowsWGLGraphicsConfiguration[DefaultGraphicsScreen[WindowsGraphicsDevice[type .windows, connection decon, unitID 0, handle 0x0, owner false, NullToolkitLock[obj 0x1b3cb867]], idx 0], pfdID 7, ARB-Choosen false,
	requested GLCaps[rgba 8/8/8/0, opaque, accum-rgba 0/0/0/0, dp/st/ms 16/0/0, dbl, mono  , hw, GLProfile[GL2/GL2.sw], on-scr[.]],
	chosen    GLCaps[wgl vid 7 gdi: rgba 8/8/8/0, opaque, accum-rgba 16/16/16/16, dp/st/ms 24/0/0, dbl, mono  , hw, GLProfile[GL2/GL2.sw], on-scr[.]]]
, surfaceLock <4743842d, 121d5383>[count 0, qsz 0, owner <NULL>]
, GDIDummyUpstreamSurfaceHook[pixel 64x64]
, upstreamSurface false ]]
CTX     : WindowsWGLContext [Version 4.6 (Compat profile, arb, compat[ES2, ES3, ES31, ES32], FBO, hardware) - 4.6.0 NVIDIA 417.35 [GL 4.6.0, vendor 417.35.0 (NVIDIA 417.35)], options 0x7c03, this 0x1ef06554, handle 0x30001, isShared false, jogamp.opengl.gl4.GL4bcImpl@67948f26,
	 quirks: [NoDoubleBufferedBitmap, NoSurfacelessCtx],
	Drawable: WindowsOnscreenWGLDrawable[Realized true,
	Factory   jogamp.opengl.windows.wgl.WindowsWGLDrawableFactory@146e92ae,
	Handle    0x0,
	Surface   GDISurface[ displayHandle 0x0
, surfaceHandle 0x0
, size 64x64
, UOB[ OWNS_SURFACE | WINDOW_INVISIBLE ]
, WindowsWGLGraphicsConfiguration[DefaultGraphicsScreen[WindowsGraphicsDevice[type .windows, connection decon, unitID 0, handle 0x0, owner false, NullToolkitLock[obj 0x1b3cb867]], idx 0], pfdID 7, ARB-Choosen false,
	requested GLCaps[rgba 8/8/8/0, opaque, accum-rgba 0/0/0/0, dp/st/ms 16/0/0, dbl, mono  , hw, GLProfile[GL2/GL2.sw], on-scr[.]],
	chosen    GLCaps[wgl vid 7 gdi: rgba 8/8/8/0, opaque, accum-rgba 16/16/16/16, dp/st/ms 24/0/0, dbl, mono  , hw, GLProfile[GL2/GL2.sw], on-scr[.]]]
, surfaceLock <4743842d, 121d5383>[count 0, qsz 0, owner <NULL>]
, GDIDummyUpstreamSurfaceHook[pixel 64x64]
, upstreamSurface false ]]] 
Thread-5-SharedResourceRunner: GLContextImpl.destroy.0: obj 0x1ef06554, ctx 0x30001, isShared false, surf true 0x0, <4c0a7a2a, 4b8f5c84>[count 0, qsz 0, owner <NULL>]
Thread-5-SharedResourceRunner: GLContext.resetStates(isInit false)
Thread-5-SharedResourceRunner: GLContextImpl.destroy.X: obj 0x1ef06554, ctx 0x0, isShared false, surf true 0x3d0115d7, <4c0a7a2a, 4b8f5c84>[count 0, qsz 0, owner <NULL>]
Thread-5-SharedResourceRunner: setRealized: drawable WindowsOnscreenWGLDrawable, surface GDISurface, isProxySurface true: true -> false
    [2]: jogamp.opengl.GLDrawableImpl.setRealized(GLDrawableImpl.java:176)
    [3]: jogamp.opengl.windows.wgl.WindowsWGLDrawableFactory$SharedResourceImplementation.releaseSharedResource(WindowsWGLDrawableFactory.java:393)
    [4]: jogamp.opengl.SharedResourceRunner.releaseSharedResources(SharedResourceRunner.java:403)
    [5]: jogamp.opengl.SharedResourceRunner.run(SharedResourceRunner.java:385)
    [6]: java.lang.Thread.run(Thread.java:748)
SharedResourceRunner.run(): RELEASE END - Thread-5-SharedResourceRunner
GLDrawableFactory.shutdownAll[2/2]:  jogamp.opengl.egl.EGLDrawableFactory
DisplayGamma: Reset
EGLDrawableFactory.shutdown
EGLDisplayUtil.EGLDisplays: Shutdown (open: 0)
    [2]: jogamp.opengl.egl.EGLDisplayUtil.shutdown(EGLDisplayUtil.java:166)
    [3]: jogamp.opengl.egl.EGLDrawableFactory.shutdownImpl(EGLDrawableFactory.java:400)
    [4]: com.jogamp.opengl.GLDrawableFactory.shutdown0(GLDrawableFactory.java:215)
    [5]: com.jogamp.opengl.GLDrawableFactory.access$000(GLDrawableFactory.java:97)
    [6]: com.jogamp.opengl.GLDrawableFactory$1.run(GLDrawableFactory.java:125)
    [7]: com.jogamp.nativewindow.NativeWindowFactory.shutdown(NativeWindowFactory.java:272)
    [8]: com.jogamp.nativewindow.NativeWindowFactory$2$1.run(NativeWindowFactory.java:190)
    [9]: java.lang.Thread.run(Thread.java:748)
GLDrawableFactory.shutdownAll.X on thread NativeWindowFactory_ShutdownHook
2019-01-21 16:36:14 [Thread-5] ERROR net.runelite.client.RuneLite - Game crash
com.jogamp.opengl.GLException: Error swapping buffers
	at jogamp.opengl.windows.wgl.WindowsWGLDrawable.swapBuffersImpl(WindowsWGLDrawable.java:93)
	at jogamp.opengl.GLDrawableImpl.swapBuffers(GLDrawableImpl.java:88)
	at net.runelite.client.plugins.gpu.GpuPlugin.draw(GpuPlugin.java:1119)
	at ah.onPost(ah.java:84)
	at ah.p(ah.java)
	at ah.run(ah.java:311)
	at java.lang.Thread.run(Thread.java:748)
error_game_crash</code></pre></details>

**Comment by Nightfirecat** [comment]
This appears to have been introduced in 01fbcde008964d54d3156bf126bb9be6a7031d8f

**Comment by deathbeam** [comment]
Hmm I guess this happens only on windows. Unfortunately I guess I can't use the windowClosed hook then.
