### ISSUE TITLE
Client Launch issue

### ISSUE THREAD

**Issue by ummzicle** [runelite/runelite#7499]
Can't seem to launch the client suddenly. Client stuck at 8% loading always. Even reinstalled and nothing happened.

Here is the event log.

2019-01-22 21:35:29 [main] INFO  net.runelite.launcher.Launcher - Verified signature of net.runelite:client:jar:1.5.8
2019-01-22 21:43:37 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to DIRECTDRAW
2019-01-22 21:52:16 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to DIRECTDRAW
2019-01-22 22:37:24 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to DIRECTDRAW
2019-01-22 22:38:10 [main] ERROR net.runelite.launcher.Launcher - error fetching bootstrap
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:706)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at net.runelite.launcher.Launcher.getBootstrap(Launcher.java:264)
	at net.runelite.launcher.Launcher.main(Launcher.java:168)
2019-01-22 22:39:07 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to DIRECTDRAW
2019-01-22 22:44:06 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to DIRECTDRAW
2019-01-22 22:47:30 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to DIRECTDRAW
2019-01-22 22:54:22 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to DIRECTDRAW
2019-01-22 22:57:59 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to DIRECTDRAW
2019-01-22 23:01:08 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to DIRECTDRAW
2019-01-22 23:07:07 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to DIRECTDRAW
2019-01-22 23:09:18 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to DIRECTDRAW
2019-01-22 23:12:53 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to DIRECTDRAW

**Comment by deathbeam** [comment]
It looks like you cant access internet, that is not something we can affect
