### ISSUE TITLE
NPC Indicator Error during overlay rendering NullPointerException

### ISSUE THREAD

**Issue by ralpha** [runelite/runelite#7501]
**Describe the bug**
Using NPC Indicators and Changing Highlight Color triggers a game crash.
"Error during overlay rendering
java.lang.NullPointerException: null"

**To Reproduce**
1. Go to NPC Indictors
2. Click on the Highlight Color (to change it)
3. This opens a window
4. Error occurs (changing color, might trigger it)

**Expected behavior**
To not make the game crash.

**Environment (please complete the following information):**
 - OS: Linux (mint) 
 - Java: OpenJDK 10.0.2
 - RuneLite version: 1.5.9
 - Launcher version: 1.6.1

**Additional context**
This message repeats for about 40 time:
```
2019-01-22 18:14:52 [Thread-2] WARN  net.runelite.client.callback.Hooks - Error during overlay rendering
java.lang.NullPointerException: null
	at net.runelite.client.ui.overlay.components.ProgressPieComponent.render(ProgressPieComponent.java:54)
	at net.runelite.client.plugins.hunter.TrapOverlay.drawTimerOnTrap(TrapOverlay.java:153)
	at net.runelite.client.plugins.hunter.TrapOverlay.drawTraps(TrapOverlay.java:108)
	at net.runelite.client.plugins.hunter.TrapOverlay.render(TrapOverlay.java:74)
	at net.runelite.client.ui.overlay.OverlayRenderer.safeRender(OverlayRenderer.java:399)
	at net.runelite.client.ui.overlay.OverlayRenderer.render(OverlayRenderer.java:180)
	at net.runelite.client.callback.Hooks.drawScene(Hooks.java:394)
	at de.ay(de.java:295)
	at ag.go(ag.java:4859)
	at cq.io(cq.java:9620)
	at am.iq(am.java:9509)
	at client.gd(client.java:4510)
	at client.ar(client.java:1575)
	at ah.o(ah.java:356)
	at ah.run(ah.java:310)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by Adam-** [comment]
In what way is this making the game crash?

**Comment by ralpha** [comment]
The game will have a drop in fps (but keeps running), clicking in-game does nothing (no response), high CPU usage, RuneLite interface will stop responding. Closing window does nothing. I have to kill the process and restart it. 
This happens often when changing settings in RuneLite interface, all part of interface.
Error's like this occur inconsistent, always when changing settings in RuneLite, not always on same parts of interface.

(Having a quick look trough my RuneLine log files, not many errors there, might overwrite the files on restarting RuneLite on same day.)
Only found this error in log files (that is different form above error):
```
2019-01-22 22:48:49 [Thread-2] WARN  net.runelite.client.callback.Hooks - error during main loop tasks
java.util.ConcurrentModificationException: null
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:937)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:891)
	at net.runelite.client.ui.overlay.infobox.InfoBoxManager.cull(InfoBoxManager.java:103)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:173)
	at client.methodDraw(client.java:1264)
	at client.ar(client.java)
	at ah.o(ah.java:356)
	at ah.run(ah.java:310)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by Adam-** [comment]
Do you have any idea what causes the CME in the infobox manager?

**Comment by ralpha** [comment]
I think it was checking/unchecking a checkbox in the 'Impling' settings-page.
I reproduced the bug (game freeze) when unchecking it (a min ago), but did not get any message in error log.
(after restarting game I can check/uncheck it again without any bugs, so might only happen after playing for some time. Same is true for other (similar) bugs.)
