### ISSUE TITLE
NPE is SpriteManager#getSprite on clan icon manager startup and on screenshot

### ISSUE THREAD

**Issue by deathbeam** [runelite/runelite#7600]
```
2019-01-28 11:46:14 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2019-01-28 11:46:16 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-01-28 11:46:19 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,247,117,809x534,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@bfd2cb1,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-01-28 11:46:19 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-01-28 11:46:22 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 11478ms. Uptime: 25311ms
2019-01-28 11:46:33 [Thread-7] WARN  n.r.client.callback.ClientThread - Exception in invoke
java.lang.NullPointerException: null
	at net.runelite.client.game.SpriteManager.getSprite(SpriteManager.java:75)
	at net.runelite.client.game.SpriteManager.lambda$getSpriteAsync$0(SpriteManager.java:92)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:156)
	at client.methodDraw(client.java:1265)
	at client.ar(client.java)
	at ah.o(ah.java:356)
	at ah.run(ah.java:310)
	at java.lang.Thread.run(Thread.java:748)
2019-01-28 11:47:10 [Thread-7] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at net.runelite.client.game.SpriteManager.getSprite(SpriteManager.java:75)
	at net.runelite.client.game.ClanManager.loadClanChatIcons(ClanManager.java:155)
	at net.runelite.client.game.ClanManager.onGameStateChanged(ClanManager.java:136)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:72)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:218)
	at net.runelite.client.callback.Hooks.post(Hooks.java:130)
	at client.gameStateChanged(client.java:933)
	at h.ek(h.java:1700)
	at client.ae(client.java:1527)
	at ah.u(ah.java:330)
	at ah.run(ah.java:309)
	at java.lang.Thread.run(Thread.java:748)
2019-01-28 11:47:10 [Thread-7] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at net.runelite.client.game.SpriteManager.getSprite(SpriteManager.java:75)
	at net.runelite.client.plugins.screenshot.ScreenshotPlugin.onGameStateChanged(ScreenshotPlugin.java:254)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:72)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:218)
	at net.runelite.client.callback.Hooks.post(Hooks.java:130)
	at client.gameStateChanged(client.java:933)
	at h.ek(h.java:1700)
	at client.ae(client.java:1527)
	at ah.u(ah.java:330)
	at ah.run(ah.java:309)
	at java.lang.Thread.run(Thread.java:748)
2019-01-28 11:52:24 [Thread-7] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at net.runelite.client.game.SpriteManager.getSprite(SpriteManager.java:75)
	at net.runelite.client.game.ClanManager.loadClanChatIcons(ClanManager.java:155)
	at net.runelite.client.game.ClanManager.onGameStateChanged(ClanManager.java:136)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:72)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:218)
	at net.runelite.client.callback.Hooks.post(Hooks.java:130)
	at client.gameStateChanged(client.java:933)
	at h.ek(h.java:1700)
	at client.ae(client.java:1527)
	at ah.u(ah.java:330)
	at ah.run(ah.java:309)
	at java.lang.Thread.run(Thread.java:748)
2019-01-28 11:52:41 [Thread-7] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at net.runelite.client.game.SpriteManager.getSprite(SpriteManager.java:75)
	at net.runelite.client.game.ClanManager.loadClanChatIcons(ClanManager.java:155)
	at net.runelite.client.game.ClanManager.onGameStateChanged(ClanManager.java:136)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:72)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:218)
	at net.runelite.client.callback.Hooks.post(Hooks.java:130)
	at client.gameStateChanged(client.java:933)
	at h.ek(h.java:1700)
	at client.ae(client.java:1527)
	at ah.u(ah.java:330)
	at ah.run(ah.java:309)
	at java.lang.Thread.run(Thread.java:748)
2019-01-28 11:54:56 [Thread-7] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at net.runelite.client.game.SpriteManager.getSprite(SpriteManager.java:75)
	at net.runelite.client.game.ClanManager.loadClanChatIcons(ClanManager.java:155)
	at net.runelite.client.game.ClanManager.onGameStateChanged(ClanManager.java:136)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:72)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:218)
	at net.runelite.client.callback.Hooks.post(Hooks.java:130)
	at client.gameStateChanged(client.java:933)
	at h.ek(h.java:1700)
	at client.ae(client.java:1527)
	at ah.u(ah.java:330)
	at ah.run(ah.java:309)
	at java.lang.Thread.run(Thread.java:748)
2019-01-28 11:57:33 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2019-01-28 11:57:34 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-01-28 11:57:37 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1303x768,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@5329c08a,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-01-28 11:57:37 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-01-28 11:57:40 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 11234ms. Uptime: 13644ms
2019-01-28 12:04:51 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2019-01-28 12:04:56 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-01-28 12:05:00 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1303x768,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@3ff542bb,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-01-28 12:05:00 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-01-28 12:05:09 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 26347ms. Uptime: 33279ms
2019-01-28 12:08:17 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2019-01-28 12:08:19 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-01-28 12:08:23 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1303x768,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@41296f53,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-01-28 12:08:23 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-01-28 12:08:28 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 17285ms. Uptime: 21014ms
2019-01-28 12:13:43 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2019-01-28 12:13:46 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-01-28 12:13:48 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1303x768,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@c940673,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-01-28 12:13:48 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-01-28 12:13:52 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 13075ms. Uptime: 15875ms
2019-01-28 12:33:21 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2019-01-28 12:33:24 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-01-28 12:33:26 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1303x768,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@228ea513,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-01-28 12:33:26 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-01-28 12:33:30 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 13519ms. Uptime: 16023ms
2019-01-28 12:35:59 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2019-01-28 12:35:59 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-01-28 12:36:03 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1303x768,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@5f7f2d1a,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-01-28 12:36:03 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-01-28 12:36:09 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 14316ms. Uptime: 16681ms
2019-01-28 12:37:58 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2019-01-28 12:37:59 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-01-28 12:38:01 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1303x768,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@18b80c94,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-01-28 12:38:01 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-01-28 12:38:05 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 11381ms. Uptime: 13683ms
2019-01-28 12:42:33 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2019-01-28 12:42:36 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-01-28 12:42:38 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1303x768,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@6cc74f99,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-01-28 12:42:38 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-01-28 12:42:41 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 13528ms. Uptime: 16050ms
```

**Comment by Abextm** [comment]
I guess this happens when you don't have a full cache?

**Comment by deathbeam** [comment]
Can we do anything about this? I guess it will work fine after first the sprites are loaded, e.g after first restart as we use common ones that are loaded for base interfaces (based on what Abex was saying they are loaded on demang).

**Comment by Abextm** [comment]
there are a couple of options for dealing with this.
1) make getSprite nullable and make all of the client's deal with that
2) block loading until the sprites we need are loaded. This would require a central place with a list of all needed sprites, it couldn't wait for plugins to be loaded

We cannot make getSprite block because it would deadlock unless it started ticking the client until download was complete, which seems bad.

There is a bit more bug here, getSpriteAsync should be able to deal with this without changing its api.

**Comment by Joshua-F** [comment]
This is still an issue when loading cc icons into mod_icons.

```
java.lang.NullPointerException: null
	at net.runelite.client.util.ImageUtil.resizeCanvas(ImageUtil.java:206)
	at net.runelite.client.game.ClanManager.clanChatImageFromSprite(ClanManager.java:167)
	at net.runelite.client.game.ClanManager.loadClanChatIcons(ClanManager.java:151)
	at net.runelite.client.game.ClanManager.onGameStateChanged(ClanManager.java:132)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:72)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:218)
	at net.runelite.client.callback.Hooks.post(Hooks.java:136)
	at client.lg(client.java:31874)
	at ba.ec(ba.java:1781)
	at client.au(client.java:1614)
	at ba.p(ba.java:393)
	at ba.run(ba.java:372)
	at java.lang.Thread.run(Thread.java:748)```
