### ISSUE TITLE
6x4 grid of login screens

### ISSUE THREAD

**Issue by Aschwins** [runelite/runelite#7617]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
When starting Runelite, instead of the login screen showing up. A 6 x 4 grid of log in screens shows up.

**To Reproduce**
1. Start Runelite

**Expected behavior**

**Screenshots**

![screenshot from 2019-01-29 22-28-06](https://user-images.githubusercontent.com/35034721/51942326-15cb3f00-2417-11e9-8315-431bddc12423.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - RuneLite version: 1.5.9
 - Launcher version: 1.6.1

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

```
2019-01-29 22:20:10 [main] INFO  n.r.client.account.SessionManager - No session file exists
2019-01-29 22:20:11 [main] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-01-29 22:20:13 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,312,130,809x534,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@3bda69b1,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-01-29 22:20:13 [main] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-01-29 22:20:16 [main] INFO  net.runelite.client.RuneLite - Client initialization took 9729ms. Uptime: 10448ms
2019-01-29 22:20:25 [Thread-3] WARN  n.r.client.callback.ClientThread - Exception in invoke
java.lang.NullPointerException: null
	at net.runelite.client.game.SpriteManager.getSprite(SpriteManager.java:75)
	at net.runelite.client.game.SpriteManager.lambda$getSpriteAsync$0(SpriteManager.java:92)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:156)
	at client.methodDraw(client.java:1265)
	at client.ar(client.java)
	at ah.o(ah.java:356)
	at ah.run(ah.java:310)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-01-29 22:24:01 [main] INFO  n.r.client.account.SessionManager - No session file exists
2019-01-29 22:24:01 [main] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-01-29 22:24:03 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,115,99,809x534,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@7e9ccfe4,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-01-29 22:24:03 [main] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-01-29 22:24:06 [main] INFO  net.runelite.client.RuneLite - Client initialization took 8357ms. Uptime: 9071ms
2019-01-29 22:27:58 [AWT-EventQueue-0] INFO  n.r.c.p.screenshot.ScreenshotPlugin - Login screenshot prevented
2019-01-29 22:28:01 [AWT-EventQueue-0] INFO  n.r.c.p.screenshot.ScreenshotPlugin - Login screenshot prevented
2019-01-29 22:31:30 [main] INFO  n.r.client.account.SessionManager - No session file exists
2019-01-29 22:31:31 [main] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-01-29 22:31:33 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,67,27,1299x741,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@1425f911,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-01-29 22:31:33 [main] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-01-29 22:31:37 [main] INFO  net.runelite.client.RuneLite - Client initialization took 9310ms. Uptime: 10061ms
2019-01-29 22:36:35 [main] INFO  n.r.client.account.SessionManager - No session file exists
2019-01-29 22:36:36 [main] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-01-29 22:36:38 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,67,27,1299x741,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@7e9ccfe4,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-01-29 22:36:38 [main] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-01-29 22:36:41 [main] INFO  net.runelite.client.RuneLite - Client initialization took 9043ms. Uptime: 9747ms
2019-01-29 22:37:32 [main] INFO  n.r.client.account.SessionManager - No session file exists
2019-01-29 22:37:32 [main] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-01-29 22:37:34 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,67,27,1299x741,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@26d05e2e,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-01-29 22:37:34 [main] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-01-29 22:37:37 [main] INFO  net.runelite.client.RuneLite - Client initialization took 8117ms. Uptime: 8785ms
```

**Comment by raiyni** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by Nightfirecat** [comment]
Graphical artifacts? Try disabling hardware acceleration: https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration
