### ISSUE TITLE
How to know if hardware acceleration is turned off?

### ISSUE THREAD

**Issue by zanderb21** [runelite/runelite#7685]
How to know if hardware acceleration is turned off?

How to disable hardware acceleration in custom client?

When I try it gives this error 

Exception in thread "main" joptsimple.UnrecognizedOptionException: mode is not a recognized option
        at joptsimple.OptionException.unrecognizedOption(OptionException.java:108)
        at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:510)
        at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56)
        at joptsimple.OptionParser.parse(OptionParser.java:396)
        at net.runelite.client.RuneLite.main(RuneLite.java:174)

**Comment by deathbeam** [comment]
You are entering the argument wrong. Simply follow the wiki page.
