### ISSUE TITLE
Runelite does not launch stuck at 0% Logfile: "Error loading RS"

### ISSUE THREAD

**Issue by Lorentary** [runelite/runelite#7758]
Runelite shortly flashes the 0% box and then disappears - and then nothing. Sometimes it works to just spam-click the shortcut to Runelite for a minute or so - sometimes not

I'm not really into coding and bug-fixing, but it seems from the log file that the error is in loading RuneScape itself. The problem has persisted for months now and reinstalling / erasing .runelite is not working.

Using: Windows 10 x64 with Runelite 64-bit

Below are my two log files

client.log
```
2019-02-08 08:10:18 [RuneLite] ERROR net.runelite.client.rs.ClientLoader - Error loading RS!
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at okio.Okio$2.read(Okio.java:138)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:236)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:344)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:216)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at net.runelite.http.api.RuneLiteAPI$1.intercept(RuneLiteAPI.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at net.runelite.client.rs.ClientLoader.load(ClientLoader.java:91)
	at net.runelite.client.RuneLiteModule.provideApplet(RuneLiteModule.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.inject.internal.ProviderMethod$ReflectionProviderMethod.doProvision(ProviderMethod.java:292)
	at com.google.inject.internal.ProviderMethod$Factory.provision(ProviderMethod.java:401)
	at com.google.inject.internal.ProviderMethod$Factory.get(ProviderMethod.java:376)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:54)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:132)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:120)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
	at net.runelite.client.RuneLite.main(RuneLite.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.runelite.launcher.ReflectionLauncher$1.run(ReflectionLauncher.java:64)
```

launcher.log
```
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of client-1.5.11.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of slf4j-api-1.7.25.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of logback-classic-1.2.3.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of logback-core-1.2.3.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jopt-simple-5.0.1.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of guava-23.2-jre.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jsr305-1.3.9.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of error_prone_annotations-2.0.18.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of j2objc-annotations-1.1.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of animal-sniffer-annotations-1.14.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of guice-4.1.0-no_aop.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of javax.inject-1.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of aopalliance-1.0.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gson-2.8.5.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of substance-8.0.02.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of trident-1.5.00.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of commons-text-1.2.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of commons-lang3-3.7.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-all-2.3.2.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-all-2.3.2-natives-windows-amd64.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-all-2.3.2-natives-windows-i586.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-all-2.3.2-natives-linux-amd64.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-all-2.3.2-natives-linux-i586.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gluegen-rt-2.3.2.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gluegen-rt-2.3.2-natives-windows-amd64.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gluegen-rt-2.3.2-natives-windows-i586.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gluegen-rt-2.3.2-natives-linux-amd64.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gluegen-rt-2.3.2-natives-linux-i586.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jbsdiff-1.0.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of commons-compress-1.5.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jna-4.5.1.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jna-platform-4.5.1.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of runelite-api-1.5.11.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of runescape-api-1.5.11.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of client-patch-1.5.11.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of http-api-1.5.11.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of okhttp-3.7.0.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of okio-1.12.0.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of commons-csv-1.4.jar
2019-02-08 08:12:46 [main] INFO  net.runelite.launcher.Launcher - Verified hash of discord-1.1.jar
```

**Comment by deathbeam** [comment]
That looks like you cant connect to OSRS, nothing we can do about that really

**Comment by BaphionOSRS** [comment]
I was having this same issue with an Asus laptop that came with windows edge 10, I couldn't run .jar files. It lead me a Java update, and I am hoping it works, I will let you know if it corrects the problem.

**Comment by BaphionOSRS** [comment]
Download Java for Windows
Recommended Version 8 Update 201 (filesize: 1.87 MB)
Release date January 15, 2019

**Comment by Lorentary** [comment]
Java was updated to the newest version (and computer restarted for good measure) before i wrote this
