### ISSUE TITLE
Game crash when opening World Map (NullPointerException)

### ISSUE THREAD

**Issue by deathbeam** [runelite/runelite#7759]
```
019-02-08 10:15:08 [Thread-7] ERROR net.runelite.client.RuneLite - Game crash
java.lang.NullPointerException: null
    at gl.aj(gl.java:248)
    at k.g(k.java:24)
    at aj.bt(aj.java:17)
    at ae.g(ae.java:53)
    at lg.o(lg.java:395)
    at cq.io(cq.java:9636)
    at cq.io(cq.java:9648)
    at cq.io(cq.java:9648)
    at cq.io(cq.java:9648)
    at cq.io(cq.java:9648)
    at cq.io(cq.java:9648)
    at am.iq(am.java:9509)
    at cq.io(cq.java:9652)
    at cq.io(cq.java:9648)
    at am.iq(am.java:9509)
    at client.gd(client.java:4510)
    at client.ar(client.java:1575)
    at ah.o(ah.java:356)
    at ah.run(ah.java:310)
    at java.lang.Thread.run(Thread.java:748)
2019-02-08 10:15:45 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2019-02-08 10:15:50 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-02-08 10:15:52 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,1147,546,809x534,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@142f68cd,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-02-08 10:15:52 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-02-08 10:15:53 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 12245ms. Uptime: 29297ms
2019-02-08 10:15:54 [pool-5-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user <redacted>.
2019-02-08 10:16:03 [Thread-7] WARN  n.r.client.callback.ClientThread - Exception in invoke
java.lang.NullPointerException: null
    at net.runelite.client.game.SpriteManager.getSprite(SpriteManager.java:75)
    at net.runelite.client.game.SpriteManager.lambda$getSpriteAsync$0(SpriteManager.java:92)
    at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
    at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:156)
    at client.methodDraw(client.java:1279)
    at client.ar(client.java)
    at ah.o(ah.java:356)
    at ah.run(ah.java:310)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by deathbeam** [comment]
Looks like this comes from `Buffer.readString()` from `loadMapData` method. No idea why.

**Comment by deathbeam** [comment]
This is probably outdated, reopen if it still occurs
