### ISSUE TITLE
Game crash on logout (division by zero)

### ISSUE THREAD

**Issue by deathbeam** [runelite/runelite#7760]
```
2019-02-08 00:32:47 [Thread-3] ERROR net.runelite.client.RuneLite - Game crash
java.lang.ArithmeticException: / by zero
  at km.az(km.java:2395)
  at ee.e(ee.java:414)
  at client.copy$runScript(client.java:345)
  at client.r(client.java:135)
  at bz.g(bz.java:96)
  at client.fn(client.java:3641)
  at client.ae(client.java:1552)
  at ah.u(ah.java:330)
  at ah.run(ah.java:309)
  at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by deathbeam** [comment]
For anyone looking at this in future, this comes from `SCALE` OpCode I think:

```
         class70.intStack[++class60.intStackSize - 1] = (int)(var9 * var13 / var11);
```

Maybe zoom plugin?

**Comment by joshuaRMS** [comment]
Any idea on how to reproduce this crash?

**Comment by deathbeam** [comment]
No idea, its possible that the user meant logout from runelite and not from game, so maybe it broke while plugin config was being changed

**Comment by abextm** [comment]
This can't crash the client anymore, and seems stale
