### ISSUE TITLE
Runelite won't open - "unable to download artifacts" 

### ISSUE THREAD

**Issue by gamergui** [runelite/runelite#7873]
2019-02-15 18:40:10 [main] ERROR net.runelite.launcher.Launcher - unable to download artifacts
java.io.IOException: Data error (cyclic redundancy check)
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:233)
	at com.google.common.io.ByteStreams.copy(ByteStreams.java:106)
	at com.google.common.io.ByteSource.copyTo(ByteSource.java:246)
	at com.google.common.io.ByteSource.hash(ByteSource.java:326)
	at net.runelite.launcher.Launcher.hash(Launcher.java:367)
	at net.runelite.launcher.Launcher.download(Launcher.java:305)
	at net.runelite.launcher.Launcher.main(Launcher.java:186)

I tried opening it on multiple different networks. Never had an issue until last night, my laptop died and I had to run CHKDSK. I repaired the drive, but RuneLite won't open now. I've tried everything from the FAQ, even disabling hardware acceleration didn't work. RuneLite load shows 0%, after a few seconds it disappears. Usually it won't run at all if I am not connected to the internet, but this has never happened. Seems like it's ever since the update.

**Comment by gamergui** [comment]
re installed it onto my desktop instead of the usual location - now it's running ?

**Comment by deathbeam** [comment]
Opened issue for this here: https://github.com/runelite/launcher/issues/53
