### ISSUE TITLE
PM Target Cycling when only talking to one person

### ISSUE THREAD

**Issue by Beagon** [runelite/runelite#7936]
**Describe the bug**
What I've noticed is that when I use tab to respond to a person when I only have 1 private chat open after a while tab just doesn't seem to function at all anymore. Once I turn PM Target Cycling off everything works again.

**To Reproduce**
1. Get a PM
2. Press tab a few times.
3. No window appears to pm the person back

**Expected behavior**
A window should pop up where I can pm a person back.

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.13-Snapshot
 - Launcher version: 1.6.2

**Additional context**
```
2019-02-19 22:11:19 [AWT-EventQueue-0] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.NoSuchFieldError: PRIVATE_MESSAGE
	at net.runelite.client.plugins.chathistory.ChatHistoryPlugin.keyPressed(ChatHistoryPlugin.java:202)
	at net.runelite.client.input.KeyManager.processKeyPressed(KeyManager.java:54)
	at net.runelite.client.callback.Hooks.keyPressed(Hooks.java:269)
	at aa.keyPressed(aa.java:58)
	at java.desktop/java.awt.Component.processKeyEvent(Component.java:6590)
	at java.desktop/java.awt.Component.processEvent(Component.java:6409)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1950)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:871)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1140)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1010)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:836)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Comment by Beagon** [comment]
Sidenote: This could also be because I'm hopping around worlds. If that's the case it has something to do with the VarBit not being loaded when entering a world again.

**Comment by Abextm** [comment]
this looks like you have not built the client correctly

**Comment by Beagon** [comment]
> 
> 
> this looks like you have not built the client correctly
You're right. I see what I did wrong. Sorry.
