### ISSUE TITLE
Prayer boost indicator breaks other indicators

### ISSUE THREAD

**Issue by haakonrp** [runelite/runelite#7964]
Just updated to latest client release, and the prayer boost indicator just overwrites the slayer infobox and breaks the other indicators so they can't move and sometimes are misplaced.

**Comment by haakonrp** [comment]
Nvm, probably this commit https://github.com/runelite/runelite/commit/06d4adc5e432513177011e30a1c6c353e49e12b9?

**Comment by haakonrp** [comment]
**Error msg:**
`2019-02-21 15:58:55 [Thread-5] DEBUG n.r.c.u.o.infobox.InfoBoxManager - Adding InfoBox net.runelite.client.plugins.prayer.PrayerCounter@57375860
2019-02-21 15:58:55 [Thread-5] WARN  net.runelite.client.callback.Hooks - Error during overlay rendering
java.lang.NullPointerException: null
	at sun.font.FontDesignMetrics.stringWidth(FontDesignMetrics.java:472)
	at net.runelite.client.ui.overlay.components.InfoBoxComponent.render(InfoBoxComponent.java:92)
	at net.runelite.client.ui.overlay.components.PanelComponent.render(PanelComponent.java:125)
	at net.runelite.client.ui.overlay.infobox.InfoBoxOverlay.render(InfoBoxOverlay.java:115)
	at net.runelite.client.ui.overlay.OverlayRenderer.safeRender(OverlayRenderer.java:461)
	at net.runelite.client.ui.overlay.OverlayRenderer.render(OverlayRenderer.java:262)
	at net.runelite.client.callback.Hooks.drawAboveOverheads(Hooks.java:415)
	at dg.checkTextures(dg.java:56)
	at dg.m(dg.java:116)
	at ag.go(ag.java:4967)
	at cq.io(cq.java:9620)
	at am.iq(am.java:9509)
	at client.gd(client.java:4510)
	at client.ar(client.java:1575)
	at ah.o(ah.java:356)
	at ah.run(ah.java:310)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by haakonrp** [comment]
That fixed it :)

**Comment by xanderqixter** [comment]
I'm having a bit of trouble understanding if this is the same issue I am running into, but when using any prayer that causes an infobox, it overrides my slayer task infobox no longer showing task information anywhere on screen. a bit of a pain when at dust devils and nechryeals.

**Comment by deathbeam** [comment]
restart your client
