### ISSUE TITLE
ChatCommandsPlugin: "!price" without an item name throws an exception

### ISSUE THREAD

**Issue by deathbeam** [runelite/runelite#8047]
I was randomly standing around while somebody in public chat wrote `!Price` and it threw an error:

```
2019-02-28 23:36:37 [Thread-3] DEBUG net.runelite.client.RuneLite - Chat message type PUBLIC: !Price
2019-02-28 23:36:37 [Thread-3] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.base/java.lang.String.substring(String.java:1841)
	at net.runelite.client.plugins.chatcommands.ChatCommandsPlugin.itemPriceLookup(ChatCommandsPlugin.java:578)
```

Moved from https://github.com/runelite/runelite.net/issues/216

**Comment by tchar989** [comment]
This would be a very simple fix [here](http://tinyurl.com/y35vq5nk).

Change the following:
`		if (!config.price())
		{
			return;
		}
`

To:
		if (!config.price() || message.length() == 0)
		{
			return;
		}

I don't currently have time to push this code change but that's the solution if someone wants to take a crack at it. This bug isn't really of high impact, but it does bloat the logs unnecessarily and we should try to prevent that wherever possible.

**Comment by Hydrox6** [comment]
That wouldn't work @tchar989, since the message is always at the very least `!price`

**Comment by tchar989** [comment]
@Hydrox6 I see, I also see there's already a pull request that fixes this bug awaiting a revision over a checkstyle error. Once that gets pushed this issue should be resolved.

**Comment by chivesrs** [comment]
This should also be done for other chat commands (and `!task` which is in the slayer plugin).

Here's the stack trace for `!task`:
```
java.lang.NullPointerException: null
	at net.runelite.client.plugins.slayer.SlayerPlugin.taskLookup(SlayerPlugin.java:757)
	at net.runelite.client.chat.ChatCommandManager.lambda$onChatMessage$0(ChatCommandManager.java:123)
	at net.runelite.client.util.RunnableExceptionLogger.run(RunnableExceptionLogger.java:41)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

and two related to `!kc` and `!kc zulrah`
```
2019-03-05 18:38:28 [Thread-4] DEBUG net.runelite.client.RuneLite - Chat message type PUBLIC: !Kc
2019-03-05 18:38:28 [pool-2-thread-1] WARN  n.r.c.util.RunnableExceptionLogger - Uncaught exception in runnable net.runelite.client.chat.ChatCommandManager$$Lambda$922/1331964404@23e0a9a4
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1931)
	at net.runelite.client.plugins.chatcommands.ChatCommandsPlugin.killCountLookup(ChatCommandsPlugin.java:370)
	at net.runelite.client.chat.ChatCommandManager.lambda$onChatMessage$0(ChatCommandManager.java:123)
	at net.runelite.client.util.RunnableExceptionLogger.run(RunnableExceptionLogger.java:41)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-03-05 18:38:30 [Thread-4] DEBUG net.runelite.client.RuneLite - Chat message type PUBLIC: !Kc zulrah
2019-03-05 18:38:30 [pool-2-thread-1] DEBUG n.r.c.p.c.ChatCommandsPlugin - unable to lookup killcount
java.io.IOException: Unable to look up killcount!
	at net.runelite.http.api.chat.ChatClient.getKc(ChatClient.java:77)
	at net.runelite.client.plugins.chatcommands.ChatCommandsPlugin.killCountLookup(ChatCommandsPlugin.java:387)
	at net.runelite.client.chat.ChatCommandManager.lambda$onChatMessage$0(ChatCommandManager.java:123)
	at net.runelite.client.util.RunnableExceptionLogger.run(RunnableExceptionLogger.java:41)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I'll look into resolving these. There's no user visible impact, but it does clutter the logs, which isn't ideal.

**Comment by Nightfirecat** [comment]
The `!kc zulrah` message is expected. I have #5327 open to send user-facing feedback so it's not a silent failure.
