### ISSUE TITLE
Can't start runelite

### ISSUE THREAD

**Issue by CircledRed** [runelite/runelite#8069]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Cant start runelite

**To Reproduce**
1.Click
2. doesnt work

**Environment (please complete the following information):**
Windows 10

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

2019-03-02 14:10:03 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to DIRECTDRAW
2019-03-02 14:10:03 [main] ERROR net.runelite.launcher.Launcher - error fetching bootstrap
java.io.IOException: Server returned HTTP response code: 403 for URL: http://static.runelite.net/bootstrap.json
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at net.runelite.launcher.Launcher.getBootstrap(Launcher.java:264)
	at net.runelite.launcher.Launcher.main(Launcher.java:168)

**Comment by deathbeam** [comment]
Cloudflare issue, use VPN to start runelite

**Comment by CircledRed** [comment]
Could you please let me know how to properly fix it?

**Comment by deathbeam** [comment]
Cloudflare issue, use VPN to start runelite

**Comment by CircledRed** [comment]
Could you please let me know how to properly fix it?

**Comment by CircledRed** [comment]
I dont have a VPN, it worked fine earlier today.

**Comment by deathbeam** [comment]
Cloudflare issue, use VPN to start runelite
