### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by zfrye06** [runelite/runelite#8083]
There seems to be an issue in OverlayIndex.java when trying to load "/runelite/index". There doesn't appear to be a file with that name/location, so I'm getting a NullPointerException. I am using the most updated version of the repo.

2019-03-03 03:09:46 [Thread-5] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.ExceptionInInitializerError: null
	at iu.e(iu.java:71)
	at iu.j(iu.java:184)
	at kt.g(kt.java:20)
	at cl.fw(cl.java:1915)
	at client.ae(client.java:886)
	at ah.u(ah.java:330)
	at ah.run(ah.java:309)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: null
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at net.runelite.api.overlay.OverlayIndex.<clinit>(OverlayIndex.java:46)
	... 8 common frames omitted
	Suppressed: java.lang.NullPointerException: null
		at java.io.FilterInputStream.close(FilterInputStream.java:181)
		at net.runelite.api.overlay.OverlayIndex.<clinit>(OverlayIndex.java:50)
		... 8 common frames omitted

Log:
[client.log](https://github.com/runelite/runelite/files/2923035/client.log)

**Comment by deathbeam** [comment]
```
[12:20] deathbeam: !linkerror
[12:20] BOTRuneLite: 1) Make sure your branch is up to date with master. See !sync
2) Run maven with -U. Typically your arguments will look like clean install -DskipTests -U
3) In IntelliJ: Maven Projects > Reimport all maven projects
```
