### ISSUE TITLE
game_crash when clicking world map

### ISSUE THREAD

**Issue by deathbeam** [runelite/runelite#8142]
Apparently the guy clicked on clue and then world map and this happened

```
2019-03-07 11:20:15 [Thread-7] ERROR net.runelite.client.RuneLite - Game crash: null
java.lang.NullPointerException: null
    at gc.u(gc.java:187)
    at ao.by(ao.java:18)
    at al.n(al.java:55)
    at lj.s(lj.java:405)
    at ki.ix(ki.java:9111)
    at ki.ix(ki.java:9123)
    at ki.ix(ki.java:9123)
    at ki.ix(ki.java:9123)
    at ki.ix(ki.java:9123)
    at ki.ix(ki.java:9123)
    at ax.ia(ax.java:8984)
    at ki.ix(ki.java:9127)
    at ki.ix(ki.java:9123)
    at ki.ix(ki.java:9123)
    at ax.ia(ax.java:8984)
    at client.gv(client.java:4052)
    at client.ak(client.java:1402)
    at bf.ag(bf.java:397)
    at bf.run(bf.java:351)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by Abextm** [comment]
Does this still happen?

**Comment by deathbeam** [comment]
I am pretty sure we did not changed anything in regards to this so it should still be an issue. I was never able to reproduce it but I got it from logs of someone on release.

**Comment by Abextm** [comment]
Does this still happen?

**Comment by sniznads** [comment]
happens to me alot when I use my macbook

**Comment by deathbeam** [comment]
This is probably outdated, reopen if it still occurs
