### ISSUE TITLE
NullPointerException when running project in intelliJ IDEA

### ISSUE THREAD

**Issue by PalyonRS** [runelite/runelite#8242]
Operating System: macOS Mojave

I added like 2 lines of code for testing purposes, followed  all the instructions in the guide for building the project, and then the client froze before it could finish loading and I got this error:

Error in LSRegisterURL: -10811
2019-03-17 15:00:55 [Thread-2] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.ExceptionInInitializerError: null
	at ij.l(ij.java:71)
	at ij.d(ij.java:193)
	at ls.n(ls.java:20)
	at av.fn(av.java:1797)
	at client.an(client.java:1063)
	at bf.ai(bf.java:371)
	at bf.run(bf.java:350)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.NullPointerException: null
	at java.base/java.io.DataInputStream.readInt(DataInputStream.java:392)
	at net.runelite.api.overlay.OverlayIndex.<clinit>(OverlayIndex.java:46)
	... 8 common frames omitted
	Suppressed: java.lang.NullPointerException: null
		at java.base/java.io.FilterInputStream.close(FilterInputStream.java:180)
		at net.runelite.api.overlay.OverlayIndex.<clinit>(OverlayIndex.java:50)
		... 8 common frames omitted
2019-03-17 15:00:56 [main] INFO  net.runelite.client.RuneLite - Client initialization took 9113ms. Uptime: 9721ms

Any help would be much appreciated!

**Comment by rhoiyds** [comment]
Remove your two added lines and then try re-doing the mvn clean install -DskipTests step
I think I recall something similar and this helped me. (I was too impatient during the testing phase of the mvn build and cut the process short, thinking it had stalled)

**Comment by deathbeam** [comment]
Use Discord if you are having trouble with building
