### ISSUE TITLE
Startup Error:  "Expected ..... for client-1..17.1 but got...." and "Unable to verify artifacts"

### ISSUE THREAD

**Issue by daves28** [runelite/runelite#8317]
Hello. Runelite fails to start the client after loading. The logs contain the following messages:

```
2019-03-26 08:52:30 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to DIRECTDRAW
2019-03-26 08:52:34 [main] WARN  net.runelite.launcher.Launcher - Expected b9949a0c08b8fc8a604bd1a27142bbc8c552e28fde76fd596bc9f3243f5393a7 for client-1.5.17.1.jar but got 76e77188abf48e7a33fb365c0ffef0afa87a01f0700579b0289ac0ddddd5038c
2019-03-26 08:52:34 [main] ERROR net.runelite.launcher.Launcher - Unable to verify artifacts
net.runelite.launcher.VerificationException: Expected b9949a0c08b8fc8a604bd1a27142bbc8c552e28fde76fd596bc9f3243f5393a7 for client-1.5.17.1.jar but got 76e77188abf48e7a33fb365c0ffef0afa87a01f0700579b0289ac0ddddd5038c
	at net.runelite.launcher.Launcher.verifyJarHashes(Launcher.java:357)
	at net.runelite.launcher.Launcher.main(Launcher.java:203)

```
Any ideas?

Thank you.

**Comment by Adam-** [comment]
This usually means your internet connection is broke. `#support`on Discord is the best place for support.
