### ISSUE TITLE
`GLIBCXX_3.4.21' not found

### ISSUE THREAD

**Issue by AoiYui** [runelite/runelite#9015]
I recently installed steamOS (debian 8.1 based) and attempted to run the both the appimage and .jar versions through the terminal

when i ran the appimage i got the following error

> desktop@steamos:~$ '/home/desktop/Desktop/RuneLite.AppImage' 
> /home/desktop/Desktop/RuneLite.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/desktop/Desktop/RuneLite.AppImage)

when I ran the .jar i got the following error

> desktop@steamos:~$ java -jar '/home/desktop/Desktop/RuneLite.jar'
> Exception in thread "main" java.lang.UnsupportedClassVersionError: net/runelite/launcher/Launcher : Unsupported major.minor version 52.0
> 	at java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:808)
> 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
> 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
> 	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:430)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:323)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
> 	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

how do i fix this the only installers for GLIBCXX_3.4.21 i could find were [here](https://pkgs.org/download/libstdc++.so.6(GLIBCXX_3.4.21)(64bit)) and none of those match up with my version I don't know much about linux as i literally installed ths morning but i think all the distros in the list are heavily dated.

I know this is a difficult request but I'd really appreciate the help.

**Comment by jplsek** [comment]
The AppImage error comes from the binary being created on a system with a newer version of GLIBC. There isn't really anything you can do to fix that. That's up to the RuneLite maintainers to compile the AppImage with an older version of GLIBC.

As for the jar issue, that's probably because you tried to run it with Java 7 instead of Java 8(+). If you run `java -version`, it will probably say something like `1.7`. You can install Java 8 on Debian 8, but I don't think it's in the default repos. There seems to be several guides on how to install Java 8 on Debian 8. (Either Oracle Java or OpenJDK Java is fine.)

**Comment by ile6695** [comment]
This is an old issue, but it's the only match when searching glibcxx.
It seems the maintainers have moved to  `GLIBCXX_3.4.32`, which makes even the latest debian release (12 Bookworm) outdated.
[Launcher 2.7.2](https://github.com/runelite/launcher/releases/tag/2.7.2) AppImage still works for Bookworm if anyone else has the same issue I had.

**Comment by luanmm** [comment]
There is a real need of building it in newer GCC versions? I'm using a distro based on Ubuntu 22 and just can't use AppImage.

@Adam- could you explain why [this commit](https://github.com/runelite/launcher/commit/a2c45b2fcb21995195bfa651ae18da1ce4108d95) was needed?

Seems to me that this is what broken support for a lot of Linux versions... and, in this case, updating the build container OS do not seems to have any positive impacts. In the contrary... the more outdated build container (or GCC version, at least), the better.

Hope we can revert it so I can run RuneLite (natively). 

Thanks in advance for the attention! And congratz for all the great work done here!

**Comment by Adam-** [comment]
> There is a real need of building it in newer GCC versions? I'm using a distro based on Ubuntu 22 and just can't use AppImage.
> 
> [@Adam-](https://github.com/Adam-) could you explain why [this commit](https://github.com/runelite/launcher/commit/a2c45b2fcb21995195bfa651ae18da1ce4108d95) was needed?
> 
> Seems to me that this is what broken support for a lot of Linux versions... and, in this case, updating the build container OS do not seems to have any positive impacts. In the contrary... the more outdated build container (or GCC version, at least), the better.
> 
> Hope we can revert it so I can run RuneLite (natively).
> 
> Thanks in advance for the attention! And congratz for all the great work done here!

~~I think that the glibc requirement comes from appimagetool and not the image the ci uses.~~ Evidently this isn't accurate.

I think this must be from changing the launcher CI to use ubuntu 24.04 https://github.com/runelite/launcher/commit/a2c45b2fcb21995195bfa651ae18da1ce4108d95. You could try using launcher 2.7.3?

**Comment by luanmm** [comment]
Tested 2.7.3 and it works here.

I think the thing with AppImage is this: the output is compiled linked (not statically) to the GCC version available in the build machine, so, if it is newer than runtime machine, the package just can't run because of missing features/libs.

I don't know if the Ubuntu upgrade in Github Actions was done "to keep things updated" or have another reason, but IMHO it should be reverted to increase the number of supported machines - as some people, like me, but without technical background, could just download the latest version from the website and give up to use the client (as AppImage is still the simpler way to run it, when it works ^^).

**Comment by abextm** [comment]
it was updated because [github doesn't provide 20.04 runners any more](https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/)

**Comment by luanmm** [comment]
@abextm 😢 

Perhaps a solution to this is to [force the building machine use older GCC versions](https://stackoverflow.com/a/66177164), then?

**Comment by jplsek** [comment]
I haven't been involved in appimage packaging for a few years now, so my assumptions might be incorrect, but it looks like there's at least two options to look into for the feasibility of this. Assuming musl libc would work in place of glibc, then using [type2-runtime](https://github.com/AppImage/type2-runtime) or [go-appimage](https://github.com/probonopd/go-appimage) instead might work.

**Comment by Adam-** [comment]
> I haven't been involved in appimage packaging for a few years now, so my assumptions might be incorrect, but it looks like there's at least two options to look into for the feasibility of this. Assuming musl libc would work in place of glibc, then using [type2-runtime](https://github.com/AppImage/type2-runtime) or [go-appimage](https://github.com/probonopd/go-appimage) instead might work.

We are using type2-runtime - the binary that is using the newer glibc version is the RuneLite binary itself (which the appimage unpacks and runs) and not the appimage.

**Comment by luanmm** [comment]
But the main problem is still the same: linking against new versions of GCC.

[Here](https://docs.appimage.org/reference/best-practices.html#binaries-compiled-on-old-enough-base-system) are some guidance about this subject. But I'm not sure yet what is the best practice in this case. The easiest would be building in a container with an older Linux version - but this seems no to be possible in Github Actions anymore, as stated by @abextm. The oldest Linux available is 22.04 (for me its good, as I use Pop OS 22.04, but not for people using older machines).

**Comment by Adam-** [comment]
IMO if you want to use an older system you should just use an older launcher - we support launchers back to 2.0.0 which was built in 2019.

**Comment by luanmm** [comment]
> IMO if you want to use an older system you should just use an older launcher - we support launchers back to 2.0.0 which was built in 2019.

If they are supported, I agree. But it is not too clear that older versions are supported, neither if they work. At first, I didn't even know that RuneLite had a "launcher" separated from the client itself (discovered that yesterday, but needed to check the project repositories). Because of this, I think that some people will not have enough knowledge to just figure it all out.

If I have time to work on this, maybe I submit a PR.

Thank you everyone for all the attention! Best regards.

**Comment by Adam-** [comment]
We've released a new appimage built on ubuntu 20 which should fix this for you.

**Comment by luanmm** [comment]
Wow, thank you very much, @Adam-! It worked great!
