### ISSUE TITLE
Can't open RuneLite. A Java Exception has occured.

### ISSUE THREAD

**Issue by dmafioly** [runelite/runelite#9436]
Hey guys, I can't open runelite. When I double click it, it doesn't even open. I tried running as admin, reinstalling, rebooting, opening the .jar file in the directory. Nothing seems to work. When I open the .jar file the error "A Java Exceprtion has occured" and nothing else happens:

Then trying to open the java file from CMD using  java -jar RuneLite.jar this appears:

Failed to auto configure default logger context
Reported exception:
ch.qos.logback.core.joran.spi.JoranException: Could not open URL [jar:file:/C:/Users/Daniele!/AppData/Local/RuneLite/RuneLite.jar!/logback.xml].
        at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:57)
        at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
        at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
        at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
        at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
        at net.runelite.launcher.Launcher.<clinit>(Launcher.java:68)
Caused by: java.io.FileNotFoundException: C:\Users\Daniele (The system cannot find the file specified)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.jar.JarFile.<init>(Unknown Source)
        at java.util.jar.JarFile.<init>(Unknown Source)
        at sun.net.www.protocol.jar.URLJarFile.<init>(Unknown Source)
        at sun.net.www.protocol.jar.URLJarFile.getJarFile(Unknown Source)
        at sun.net.www.protocol.jar.JarFileFactory.get(Unknown Source)
        at sun.net.www.protocol.jar.JarURLConnection.connect(Unknown Source)
        at sun.net.www.protocol.jar.JarURLConnection.getInputStream(Unknown Source)
        at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:52)
        ... 10 more
22:59:55,779 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
22:59:55,779 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
22:59:55,779 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/C:/Users/Daniele!/AppData/Local/RuneLite/RuneLite.jar!/logback.xml]
22:59:55,787 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@fb509a - URL [jar:file:/C:/Users/Daniele!/AppData/Local/RuneLite/RuneLite.jar!/logback.xml] is not of type file
22:59:55,788 |-ERROR in ch.qos.logback.classic.joran.JoranConfigurator@ffa5d - Could not open URL [jar:file:/C:/Users/Daniele!/AppData/Local/RuneLite/RuneLite.jar!/logback.xml]. java.io.FileNotFoundException: C:\Users\Daniele (The system cannot find the file specified)
        at java.io.FileNotFoundException: C:\Users\Daniele (The system cannot find the file specified)
        at      at java.util.zip.ZipFile.open(Native Method)
        at      at java.util.zip.ZipFile.<init>(Unknown Source)
        at      at java.util.zip.ZipFile.<init>(Unknown Source)
        at      at java.util.jar.JarFile.<init>(Unknown Source)
        at      at java.util.jar.JarFile.<init>(Unknown Source)
        at      at sun.net.www.protocol.jar.URLJarFile.<init>(Unknown Source)
        at      at sun.net.www.protocol.jar.URLJarFile.getJarFile(Unknown Source)
        at      at sun.net.www.protocol.jar.JarFileFactory.get(Unknown Source)
        at      at sun.net.www.protocol.jar.JarURLConnection.connect(Unknown Source)
        at      at sun.net.www.protocol.jar.JarURLConnection.getInputStream(Unknown Source)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:52)
        at      at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
        at      at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
        at      at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
        at      at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
        at      at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
        at      at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
        at      at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
        at      at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
        at      at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
        at      at net.runelite.launcher.Launcher.<clinit>(Launcher.java:68)

Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.NullPointerException
        at java.util.Properties$LineReader.readLine(Unknown Source)
        at java.util.Properties.load0(Unknown Source)
        at java.util.Properties.load(Unknown Source)
        at net.runelite.launcher.LauncherProperties.<init>(LauncherProperties.java:44)
        at net.runelite.launcher.Launcher.<clinit>(Launcher.java:77)

**Comment by dekvall** [comment]
I believe it has to do with the exclamation mark in your username. Now, the client looks for `AppData/..` inside of the jar, which doesn't exist. I will look into it, try removing it for now and please tell me if it works.

**Comment by dmafioly** [comment]
> I believe it has to do with the exclamation mark in your username. Now, the client looks for `AppData/..` inside of the jar, which doesn't exist. I will look into it, try removing it for now and please tell me if it works.

I'll try that once I get home in 12 hours and tell you if it works. Thank you!

**Comment by dmafioly** [comment]
> I believe it has to do with the exclamation mark in your username. Now, the client looks for `AppData/..` inside of the jar, which doesn't exist. I will look into it, try removing it for now and please tell me if it works.

I'll try that tomorrow since I won't be able to access my computer today. I'll let you know if it works. Thank you!

**Comment by Adam-** [comment]
This is due to the `!` in your `%userhome%`. Jar URLs use `!` to specify entries in jar files, see https://docs.oracle.com/javase/7/docs/api/java/net/JarURLConnection.html

**Comment by dmafioly** [comment]
Thank you guys.
