### ISSUE TITLE
Client crashing once while loading (Arch Linux)

### ISSUE THREAD

**Issue by JimmyTheRustler** [runelite/runelite#9517]
Since Song of the Elves released after I updated my Client it seems to get just before the login point and then crashes. I've tried using osbuddy and that client seems to work just fine. I am using a dell XPS 13 9434 running arch. I've tried to do some research and I think it might be a connection issue? If anyone has any insight on what might be the issue it would be greatly appreciated! Below is what comes from my log file.

2019-07-28 00:41:34 [main] INFO  net.runelite.client.rs.ClientLoader - client-patch 259011122.206
2019-07-28 00:41:36 [main] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-07-28 00:41:39 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1920x1044,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultClose>
2019-07-28 00:41:39 [main] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-07-28 00:41:45 [main] INFO  net.runelite.client.RuneLite - Client initialization took 17338ms. Uptime: 18162ms
2019-07-28 00:41:58 [main] INFO  net.runelite.client.rs.ClientLoader - client-patch 259011122.206
2019-07-28 00:42:01 [main] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-07-28 00:42:03 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1920x1044,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultClose>
2019-07-28 00:42:03 [main] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-07-28 00:42:20 [main] INFO  net.runelite.client.rs.ClientLoader - client-patch 259011122.206
2019-07-28 00:42:23 [main] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-07-28 00:42:25 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1920x1044,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultClose>
2019-07-28 00:42:25 [main] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
**2019-07-28 14:14:06 [main] ERROR net.runelite.client.rs.ClientLoader - Error loading RS!
java.net.UnknownHostException: oldschool.runescape.com: Temporary failure in name resolution**
        at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
        at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1515)
        at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298)
        at okhttp3.Dns$1.lookup(Dns.java:39)
        at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:170)
        at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:136)
        at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:81)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:171)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92

**Comment by nateisonfire** [comment]
Just out of curiosity, how are you running RL on arch? Are you using this:

https://aur.archlinux.org/packages/runelite/

**Comment by JimmyTheRustler** [comment]
@nateisonfire yeah I'm using that aur repo, I was able to get the client to launch if I quickly logged out of the runelite client (not runescape), and when I try to log back into runelite it crashes again. Do you think the repo isn't fully up to date?

**Comment by Nightfirecat** [comment]
[From Adam's comment](https://github.com/runelite/runelite/issues/9562#issuecomment-517947933):

> The AUR version is not something we officially maintain or support. Does the Linux version on [runelite.net](https://runelite.net) work?

**Comment by MESLewis** [comment]
Reopen this issue if the problem persists in the latest release of RuneLite.
