### ISSUE TITLE
Receiver class client does not define or inherit an implementation of runScript

### ISSUE THREAD

**Issue by dekvall** [runelite/runelite#9646]
**Describe the bug**
When logging in with the WorldMapPlugin enabled I encounter the error 
```
2019-08-13 00:35:01 [Client] WARN  n.r.client.callback.ClientThread - Exception in invoke
java.lang.AbstractMethodError: Receiver class client does not define or inherit an implementation of the resolved method 'abstract void runScript(java.lang.Object[])' of interface net.runelite.api.Client.
	at net.runelite.api.Quest.getState(Quest.java:203)
	at net.runelite.client.plugins.worldmap.WorldMapPlugin.createQuestStartPoint(WorldMapPlugin.java:338)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at net.runelite.client.plugins.worldmap.WorldMapPlugin.lambda$updateQuestStartPointIcons$10(WorldMapPlugin.java:325)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:187)
	at m.gp(b.java:64039)
	at client.ag(client.java)
	at bz.cx(bz.java:390)
	at bz.run(bz.java:344)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

If i try to add a new bank tag i encounter 
```
2019-08-13 00:36:36 [Client] WARN  n.r.client.callback.ClientThread - Exception in invoke
java.lang.AbstractMethodError: Receiver class client does not define or inherit an implementation of the resolved method 'abstract void runScript(java.lang.Object[])' of interface net.runelite.api.Client.
	at net.runelite.client.game.chatbox.ChatboxPanelManager.unsafeOpenInput(ChatboxPanelManager.java:104)
	at net.runelite.client.game.chatbox.ChatboxPanelManager.lambda$openInput$1(ChatboxPanelManager.java:138)
	at net.runelite.client.callback.ClientThread.lambda$invokeLater$1(ClientThread.java:79)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:187)
	at m.gp(b.java:64039)
	at client.ag(client.java)
	at bz.cx(bz.java:390)
	at bz.run(bz.java:344)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
**Environment (please complete the following information):**
 - OS: Ubuntu 19.04
 - RuneLite version: master as of 98fc599e15bcdc49b5dbabbe4d4cdcbab97b71ee
 - Launcher version: null

**Comment by dekvall** [comment]
Time made it work, idk I probably did something dumb.
