### ISSUE TITLE
Issue when starting runelite-1.5.31-SNAPSHOT.war with Tomcat

### ISSUE THREAD

**Issue by Christopher-Stolfa** [runelite/runelite#9656]
This is my first time dabbling with Tomcat and i'm using Windows which has caused exponential pain to set up anything server related haha. Anyways I got up to the part on the "Running-the-Runelite-HTTP-API-Service" guide where I select runelite-1.5.31-SNAPSHOT.war but when I start it up I get two errors in which I cannot figure out how to solve (in the screenshot below). I'm not sure what I could be doing different due to a lack of experience with the software i'm using and i'm not sure what kind of questions I should be asking to approach this issue. This is also my first time setting up development environments on windows, normally I use a Mac for these kind of things but there's reasons.

I'm stoked to get into some runelite development and would appreciate any help, thank you!

![Screenshot_120](https://user-images.githubusercontent.com/31984576/63054078-2c1b8280-beb1-11e9-8e09-578c9eff5883.png)

LOGS: 
stdout: [tomcat7-stdout.2019-08-14.log](https://github.com/runelite/runelite/files/3503568/tomcat7-stdout.2019-08-14.log)
stderr: [tomcat7-stderr.2019-08-14.log](https://github.com/runelite/runelite/files/3503570/tomcat7-stderr.2019-08-14.log)

**Comment by TheStonedTurtle** [comment]
Go look at the actual log files for the server, if you used the default install location they should be located in `C:\Program Files\Apache Software Foundation\Tomcat 7.0\logs`. IIRC stdout should be it.

**Comment by Chribtoper** [comment]
> Go look at the actual log files for the server, if you used the default install location they should be located in `C:\Program Files\Apache Software Foundation\Tomcat 7.0\logs`. IIRC stdout should be it.

Gotcha, i'm gonna look through it. In the meantime I just clipped the logfile to the post.

**Comment by Chribtoper** [comment]
Hmm I might be having java runetime environment issues perhaps

**Comment by deathbeam** [comment]
https://github.com/deathbeam/runelite-ansible try this, and just run http-service from IntelliJ and connect it to stack. Our HTTP service guide is extremely outdated at this point

**Comment by Chribtoper** [comment]
> https://github.com/deathbeam/runelite-ansible try this, and just run http-service from IntelliJ and connect it to stack. Our HTTP service guide is extremely outdated at this point

Thanks so much man, i'm gonna get on it soon.

**Comment by shuhaowu** [comment]
runelite-ansible as above doesn't have tomcat anymore as [this commit](https://github.com/deathbeam/runelite-ansible/commit/5e965b9344cea795e52b999e4dce5f62765378a9#diff-2f78c4e27feaf25ffb33d97e8ff7e7a6) says to run the .war files directly via the IDE. If you're running this stuff without a development IDE, how else can we run the http-service?

**Comment by shuhaowu** [comment]
As I see there's no logs from this, the detailed logs is as follows:

```
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [net.runelite.http.service.SpringBootWebApplication]; nested exception is java.lang.IllegalStateException: Failed to introspect annotated methods on class net.runelite.http.service.SpringBootWebApplication
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:181) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:308) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:228) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:270) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:93) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:525) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) ~[spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) ~[spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
        at org.springframework.boot.web.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:151) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
        at org.springframework.boot.web.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:131) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
        at org.springframework.boot.web.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:86) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
        at net.runelite.http.service.SpringBootWebApplication.onStartup(SpringBootWebApplication.java:212) [classes/:na]
        at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:169) [spring-web-4.3.10.RELEASE.jar:4.3.10.RELEASE]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5253) [tomcat8-catalina-8.0.32.jar:8.0.32]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147) [tomcat8-catalina-8.0.32.jar:8.0.32]
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) [tomcat8-catalina-8.0.32.jar:8.0.32]
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) [tomcat8-catalina-8.0.32.jar:8.0.32]
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717) [tomcat8-catalina-8.0.32.jar:8.0.32]
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:939) [tomcat8-catalina-8.0.32.jar:8.0.32]
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1812) [tomcat8-catalina-8.0.32.jar:8.0.32]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
Caused by: java.lang.IllegalStateException: Failed to introspect annotated methods on class net.runelite.http.service.SpringBootWebApplication
        at org.springframework.core.type.StandardAnnotationMetadata.getAnnotatedMethods(StandardAnnotationMetadata.java:163) ~[spring-core-4.3.10.RELEASE.jar:4.3.10.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassParser.retrieveBeanMethodMetadata(ConfigurationClassParser.java:380) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:314) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:245) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:198) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:167) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
        ... 27 common frames omitted
Caused by: java.lang.NoClassDefFoundError: com/mongodb/client/MongoClient
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[na:1.8.0_191]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[na:1.8.0_191]
        at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[na:1.8.0_191]
        at org.springframework.core.type.StandardAnnotationMetadata.getAnnotatedMethods(StandardAnnotationMetadata.java:152) ~[spring-core-4.3.10.RELEASE.jar:4.3.10.RELEASE]
        ... 32 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.mongodb.client.MongoClient
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1309) ~[tomcat8-catalina-8.0.32.jar:8.0.32]
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1143) ~[tomcat8-catalina-8.0.32.jar:8.0.32]
        ... 36 common frames omitted

```

The likely culprit are these two commits: c6e24b832d2656e7bb80f0f442e79c7eeafc9eb4 and 277a3ccd35e55a3010c18bdb9c97d819418f3e06

**Comment by shuhaowu** [comment]
The situation can be fixed if mongo-java-driver is downloaded from [maven](https://repo1.maven.org/maven2/org/mongodb/mongo-java-driver/3.10.2/) as a jar. 

This jar can be placed in the tomcat8 shared lib (?) directory. For me, this is `/usr/share/tomcat8/common/`

Then, the following snippets must be added to context.xml (for me, at `/etc/tomcat8/context.xml`):

```
<Resource name="mongodb/runelite"
          auth="Container"
          type="com.mongodb.client.MongoClient"
          closeMethod="close"
          factory="com.mongodb.client.MongoClientFactory"
          singleton="true"
          connectionString="mongodb://localhost"/>
```

After that, tomcat8 should start. However, this seems like a relatively cumbersome procedure. How does runelite's official server install the mongo driver to its server?

**Comment by deathbeam** [comment]
@shuhaowu Without tomcat, you can just run the .war directly (with java -jar).

**Comment by Chribtoper** [comment]
IntelliJ is my IDE. I had to write batch scripts to start and restart the server because tomcat is really finicky on windows for whatever reason. I’ll test your solution when I wake up thanks for the response!

**Comment by shuhaowu** [comment]
Running it directly still would require the .jar for mongo tho, right?

**Comment by deathbeam** [comment]
Not sure, maybe. But I think spring boot plugin should package it

**Comment by deathbeam** [comment]
And if not, we should fix that

**Comment by Adam-** [comment]
The war has to be deployable onto a container with jndi provided mongo+mysql, so we cannot really package it in due to the classes conflicting I believe.

**Comment by deathbeam** [comment]
We can probably add property for this then? Maaybe. <provided>${property}</provided> should work, right?

**Comment by Adam-** [comment]
They are already `provided` dependencies.

**Comment by deathbeam** [comment]
yes, and we can add property to not make them provided (and by default they would be), if it works

**Comment by LlemonDuck** [comment]
http-api project now lives in runelite/api.runelite.net, feel free to open a new issue there if this persists
