### ISSUE TITLE
Error starting GPU plugin after updating to 1.5.31 (Ubuntu)

### ISSUE THREAD

**Issue by sergkr** [runelite/runelite#9681]
**Describe the bug**
GPU plugin fails to start when launching RuneLite after the latest release. There is an error log entry in `client.log` (see below). Once the client is launched, enabling the GPU plugin works fine, but the next time the client is launched, the plugin is disabled again. Not sure if this affects other platforms, but I am seeing the issue on Ubuntu 18.04.3 LTS.

**To Reproduce**
1. Launch RuneLite

**Expected behavior**
GPU plugin should successfully initialize on startup.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS
 - RuneLite version: 1.5.31.1
 - Launcher version: 1.6.2

**Additional context**
Here are the contents of `client.log`:

```
2019-08-17 07:26:39 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 273267602.227
2019-08-17 07:26:40 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-08-17 07:26:41 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-08-17 07:26:42 [Client] ERROR n.r.client.plugins.gpu.GpuPlugin - Error starting GPU plugin
com.jogamp.opengl.GLException: GLDrawableImpl.setRealized(true): Surface not ready (lockSurface)
        at jogamp.opengl.GLDrawableImpl.setRealized(GLDrawableImpl.java:184)
        at net.runelite.client.plugins.gpu.GpuPlugin.lambda$startUp$0(GpuPlugin.java:266)
        at net.runelite.client.callback.ClientThread.lambda$invoke$0(ClientThread.java:48)
        at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
        at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:187)
        at client.je(client.java:15125)
        at client.ag(client.java)
        at bz.fu(bz.java:390)
        at bz.run(bz.java:344)
        at java.lang.Thread.run(Thread.java:748)
2019-08-17 07:26:43 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 7985ms. Uptime: 11154ms
2019-08-17 07:26:44 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,589,286,809x534,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@1db80409,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
```

And `launcher.log` (though doesn't look like there's anything relevant here):

```
2019-08-17 07:26:33 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to OFF
2019-08-17 07:26:34 [main] WARN  net.runelite.launcher.PackrConfig - error updating packr vm args!
java.io.FileNotFoundException: /tmp/.mount_runelikM9xJf/config.json (Read-only file system)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at net.runelite.launcher.PackrConfig.updateLauncherArgs(PackrConfig.java:75)
        at net.runelite.launcher.Launcher.main(Launcher.java:178)
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of client-1.5.31.1.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of slf4j-api-1.7.25.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of logback-classic-1.2.3.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of logback-core-1.2.3.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jopt-simple-5.0.1.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of guava-23.2-jre.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jsr305-1.3.9.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of error_prone_annotations-2.0.18.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of j2objc-annotations-1.1.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of animal-sniffer-annotations-1.14.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of guice-4.1.0-no_aop.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of javax.inject-1.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of aopalliance-1.0.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gson-2.8.5.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of substance-8.0.02.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of trident-1.5.00.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of commons-text-1.2.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of commons-lang3-3.7.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-all-2.3.2.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-all-2.3.2-natives-windows-amd64.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-all-2.3.2-natives-windows-i586.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-all-2.3.2-natives-linux-amd64.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-all-2.3.2-natives-linux-i586.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gluegen-rt-2.3.2.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gluegen-rt-2.3.2-natives-windows-amd64.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gluegen-rt-2.3.2-natives-windows-i586.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gluegen-rt-2.3.2-natives-linux-amd64.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gluegen-rt-2.3.2-natives-linux-i586.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jbsdiff-1.0.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of commons-compress-1.5.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jna-4.5.1.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jna-platform-4.5.1.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of runelite-api-1.5.31.1.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of client-patch-1.5.31.1.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of http-api-1.5.31.1.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of okhttp-3.7.0.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of okio-1.12.0.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of commons-csv-1.4.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of discord-1.1.jar
```

As a side note, I noticed the fan on my PC running much louder after the recent update. I don't have a benchmark comparison since this was never an issue previously, but after the update I checked my GPU temps and they're hovering around the max that is recommended (85°C). This happens even when I'm just smithing bars in Varrock - not an especially graphics-intensive activity, I would imagine. Turning the GPU plugin off returns the temps back to normal.

**Comment by jolty1** [comment]
Same here, fixed it changing settings.properties. Using the AppImage it doesn't seem to write the gpu setting to the config properly.

~/.runelite/settings.properties

runelite.gpuplugin=true

**Comment by sergkr** [comment]
Just adding some more info, since the behavior I'm seeing now is a bit different than what I saw earlier. Now, if the GPU plugin was enabled when I close RuneLite, then next time I launch, it gets stuck somewhere on the main game loading screen (at a different point each time). I'm seeing some additional info in the logs too. The only way to get the client to launch now is to disable the GPU plugin (while it's stuck at the loading screen), then restart the client.

Here is `client.log`:

```
2019-08-18 08:00:17 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 273267602.227
2019-08-18 08:00:18 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-08-18 08:00:19 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-08-18 08:00:21 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 8184ms. Uptime: 11344ms
2019-08-18 08:00:22 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,589,286,809x534,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@1db80409,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-08-18 08:00:23 [Client] WARN  n.r.client.plugins.gpu.GpuPlugin - Canvas invalidated!
2019-08-18 08:00:23 [Client] ERROR net.runelite.client.RuneLite - Game crash: null
com.jogamp.opengl.GLException: Surface not ready to lock: X11OnscreenGLXDrawable[Realized true,
        Factory   jogamp.opengl.x11.glx.X11GLXDrawableFactory@23d0d2fb,
        Handle    0x4200056,
        Surface   JAWTWindow[0x1fe258bf][JVM version: 1.8.0_202 (1.8.0 update 202)
JAWT version: 0x10004, CA_LAYER: false, isLayeredSurface false, bounds [ 0 / 0  1817 x 1030 ], insets [ l 0, r 0 - t 0, b 0 - 0x0], pixelScale 1.0x1.0, shallUseOffscreenLayer false, isOffscreenLayerSurface false, attachedSurfaceLayer 0x0, windowHandle 0x4200056, surfaceHandle 0x4200056, bounds [ 0 / 0  1817 x 1030 ], insets [ l 0, r 0 - t 0, b 0 - 0x0], window [0/0 1817x1030], pixels[scale 1.0, 1.0 -> 1817x1030], visible true, lockedExt false,
        config AWTGraphicsConfiguration[AWTGraphicsScreen[AWTGraphicsDevice[type .awt, connection :0.0, unitID 0, awtDevice X11GraphicsDevice[screen=0], handle 0x0], idx 0],
        chosen    GLCaps[glx vid 0x27, fbc 0x10d: rgba 8/8/8/0, opaque, accum-rgba 16/16/16/16, dp/st/ms 24/0/0, dbl, mono  , hw, GLProfile[GL4/GL4.hw], on-scr[.]],
        requested GLCaps[rgba 8/8/8/0, opaque, accum-rgba 0/0/0/0, dp/st/ms 16/0/0, dbl, mono  , hw, GLProfile[GL4/GL4.hw], on-scr[.]],
        X11GraphicsConfig[dev=X11GraphicsDevice[screen=0],vis=0x27],
        encapsulated X11GLXGraphicsConfiguration[X11GraphicsScreen[X11GraphicsDevice[type .x11, connection :0, unitID 0, handle 0x7f504c7f22b0, owner true, JAWTToolkitLock[obj 0x4626f079, isOwner false, <5d4b2e82, 782978da>[count 0, qsz 0, owner <NULL>]]], idx 0], visualID 0x27, fbConfigID 0x10d,
        requested GLCaps[rgba 8/8/8/0, opaque, accum-rgba 0/0/0/0, dp/st/ms 16/0/0, dbl, mono  , hw, GLProfile[GL4/GL4.hw], on-scr[.]],
        chosen    GLCaps[glx vid 0x27, fbc 0x10d: rgba 8/8/8/0, opaque, accum-rgba 16/16/16/16, dp/st/ms 24/0/0, dbl, mono  , hw, GLProfile[GL4/GL4.hw], on-scr[.]]]],
        awtComponent am[canvas0,0,0,1817x1030,invalid],
        surfaceLock <7503e0c0, 4d76321>[count 0, qsz 0, owner <NULL>]]]
        at jogamp.opengl.GLContextImpl.destroy(GLContextImpl.java:454)
        at net.runelite.client.plugins.gpu.GpuPlugin.lambda$shutDown$1(GpuPlugin.java:396)
        at net.runelite.client.callback.ClientThread.lambda$invoke$0(ClientThread.java:48)
        at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:61)
        at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:46)
        at net.runelite.client.plugins.gpu.GpuPlugin.shutDown(GpuPlugin.java:350)
        at net.runelite.client.plugins.gpu.GpuPlugin.draw(GpuPlugin.java:792)
        at bz.tx(bz.java:20545)
        at bz.xb(bz.java)
        at bz.run(bz.java:345)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by doorknob60** [comment]
I can confirm the issue on Ubuntu 19.04 with the AppImage. Game crashes while loading, then I need to disable GPU, restart Runelite, then I can re-enable GPU and it works.

**Comment by MP2E** [comment]
This happens on Red Hat Enterprise Linux 8 with the NVIDIA binary driver and OpenJDK 8 as well, the workaround described above to disable GPU plugin then re-enable after the game starts works
