### ISSUE TITLE
[Ubuntu 19.04] Runelite failing to launch

### ISSUE THREAD

**Issue by Mantas4682** [runelite/runelite#9682]
Hello,

Runelite is downloaded through Flatpak. I've tried disabling hardware acceleration, which is about the only solution I've found, though I realize it has nothing to do with the issue. Apologies if this has already been documented.

Here's what launcher.log says:
`2019-08-17 15:46:53 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to OFF
2019-08-17 15:46:54 [main] ERROR net.runelite.launcher.Launcher - unable to download artifacts
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at java.base/sun.security.ssl.Alerts.getSSLException(Alerts.java:198)
	at java.base/sun.security.ssl.Alerts.getSSLException(Alerts.java:159)
	at java.base/sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2046)
	at java.base/sun.security.ssl.SSLSocketImpl.processInputRecord(SSLSocketImpl.java:1207)
	at java.base/sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1074)
	at java.base/sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at java.base/sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1402)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1429)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245)
	at net.runelite.launcher.Launcher.download(Launcher.java:323)
	at net.runelite.launcher.Launcher.main(Launcher.java:186)
2019-08-17 15:47:05 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to OFF
2019-08-17 15:47:07 [main] ERROR net.runelite.launcher.Launcher - unable to download artifacts
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at java.base/sun.security.ssl.Alerts.getSSLException(Alerts.java:198)
	at java.base/sun.security.ssl.Alerts.getSSLException(Alerts.java:159)
	at java.base/sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2046)
	at java.base/sun.security.ssl.SSLSocketImpl.processInputRecord(SSLSocketImpl.java:1207)
	at java.base/sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1074)
	at java.base/sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at java.base/sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1402)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1429)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245)
	at net.runelite.launcher.Launcher.download(Launcher.java:323)
	at net.runelite.launcher.Launcher.main(Launcher.java:186)`

Cheers.

**Comment by Adam-** [comment]
Try using the appimage from https://runelite.net

**Comment by Mantas4682** [comment]
The appimage does work, though that removes the whole point of me trying to install it, as I can't easily access the file. I always have to navigate through the file manager to said folder.

Searching for "runelite" always gives me an error:
`Invalid url: '/home/mantas/RuneLite.AppImage'
given, exiting
no ':' in the uri`

**Comment by ollieatkinson** [comment]
Create a Launcher and point it to the app image

![image](https://user-images.githubusercontent.com/1382565/63216168-5a0afc00-c129-11e9-9e09-28a7c5fddcd7.png)

![image](https://user-images.githubusercontent.com/1382565/63216162-495a8600-c129-11e9-952d-86a5f5cacd57.png)

![image](https://user-images.githubusercontent.com/1382565/63216159-39db3d00-c129-11e9-911e-bbdd635118e6.png)

**Comment by deathbeam** [comment]
The Flatpak distribution is 3rd party and not managed by us, so we don't support it. If it works with our actual distribution, then there is no reason to keep this issue open, so closing
