### ISSUE TITLE
Crash to desktop when uploading screenshot

### ISSUE THREAD

**Issue by MESLewis** [runelite/runelite#9773]
```
2019-08-29 08:17:50 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 283108390.241
2019-08-29 08:17:52 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-08-29 08:17:52 [RuneLite] WARN  n.r.client.config.ConfigManager - Unable to unmarshal screenshot.uploadScreenshot 
java.lang.IllegalArgumentException: No enum constant net.runelite.client.plugins.screenshot.UploadStyle.true
	at java.base/java.lang.Enum.valueOf(Unknown Source)
	at net.runelite.client.config.ConfigManager.stringToObject(ConfigManager.java:585)
	at net.runelite.client.config.ConfigManager.getConfiguration(ConfigManager.java:376)
	at net.runelite.client.config.ConfigManager.setDefaultConfiguration(ConfigManager.java:512)
	at net.runelite.client.plugins.PluginManager.loadDefaultPluginConfiguration(PluginManager.java:192)
	at net.runelite.client.RuneLite.start(RuneLite.java:291)
	at net.runelite.client.RuneLite.main(RuneLite.java:241)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.runelite.launcher.ReflectionLauncher$1.run(ReflectionLauncher.java:64)
```

Didn't even take a screenshot that I know of.

**Comment by Adam-** [comment]
The client has logic to convert the config key on startup, which should have changed the value

**Comment by MESLewis** [comment]
Just had another crash to desktop. No logs in .runelite/logs have been written to though.

**Comment by Chasesc** [comment]
I had this same issue (occurring on startup). I fixed it by removing the settings file. For me, that was located at `~/.runelite/settings.properties`

**Comment by Nightfirecat** [comment]
For anyone still encountering this bug, [please reach out to one of the project's admins or contributors on Discord](https://runelite.net/discord) to share some of your configuration file contents. Per Adam's comment, this is likely fixed for any future users already, so I am closing this issue.
