### ISSUE TITLE
Runelite won't launch

### ISSUE THREAD

**Issue by Stormmcmichael94** [runelite/runelite#9798]
all the that's in my log is this
2019-09-03 00:07:04 [main] ERROR net.runelite.launcher.Launcher - Failure during startup
java.lang.UnsatisfiedLinkError: C:\Users\Aarons Customer\AppData\Local\RuneLite\jre\bin\javaaccessbridge.dll: Can't find dependent libraries
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(Unknown Source)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.base/java.lang.System.loadLibrary(Unknown Source)
	at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge$3.run(Unknown Source)
	at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge$3.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge.<clinit>(Unknown Source)
	at jdk.accessibility/com.sun.java.accessibility.internal.ProviderImpl.activate(Unknown Source)
	at java.desktop/java.awt.Toolkit.lambda$loadAssistiveTechnologies$0(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.Toolkit.loadAssistiveTechnologies(Unknown Source)
	at java.desktop/java.awt.Toolkit.getDefaultToolkit(Unknown Source)
	at java.desktop/java.awt.EventQueue.invokeAndWait(Unknown Source)
	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(Unknown Source)
	at net.runelite.launcher.SplashScreen.init(SplashScreen.java:161)
	at net.runelite.launcher.Launcher.main(Launcher.java:128)

I've tried uninstalling and reinstalling java and visual c++ multiple times and can't seem to fix the issue, i'm running windows 10.
Edit: also have tried both 32 Bit client, 64 bit client, and client for all system as well. I'm stumped I know it's some sort of Java exception more then likely but how to fix it I have no clue lol.

**Comment by Adam-** [comment]
The installer should be prompting you to install the redistributables. If not, they are https://download.microsoft.com/download/2/E/6/2E61CFA4-993B-4DD4-91DA-3737CD5CD6E3/vcredist_x86.exe and https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe for 32bit/64bit respectively.

**Comment by Nightfirecat** [comment]
Closing due to inactivity. If following Adam's comment did not address this issue, please comment here again and we will re-open this issue.
