### ISSUE TITLE
runelite client wont open/fatal error starting runelite

### ISSUE THREAD

**Issue by KillerHippo13** [runelite/runelite#9816]
<details><summary>client.log</summary><pre><code>2019-09-04 12:50:42 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Failed to get jav_config from host "null" (Invalid or missing jav_config)
2019-09-04 12:50:42 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Failed to get jav_config from host "oldschool115.runescape.com" (Invalid or missing jav_config)
2019-09-04 12:50:43 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Failed to get jav_config from host "oldschool218.runescape.com" (Invalid or missing jav_config)
2019-09-04 12:50:43 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Failed to get jav_config from host "oldschool146.runescape.com" (Invalid or missing jav_config)
2019-09-04 12:50:43 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Failed to get jav_config from host "oldschool45.runescape.com" (Invalid or missing jav_config)
2019-09-04 12:50:43 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Failed to get jav_config from host "oldschool33a.runescape.com" (Invalid or missing jav_config)
2019-09-04 12:50:43 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Failed to get jav_config from host "oldschool152.runescape.com" (Invalid or missing jav_config)
2019-09-04 12:50:43 [Preloader] ERROR net.runelite.client.rs.ClientLoader - Error loading RS!
java.io.IOException: Invalid or missing jav_config
	at net.runelite.client.rs.ClientLoader.doLoad(ClientLoader.java:117)
	at net.runelite.client.rs.ClientLoader.get(ClientLoader.java:84)
	at net.runelite.client.RuneLite.lambda$main$1(RuneLite.java:213)
	at java.base/java.lang.Thread.run(Unknown Source)
2019-09-04 12:50:43 [Preloader] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.RuntimeException: java.io.IOException: Invalid or missing jav_config
	at net.runelite.client.rs.ClientLoader.get(ClientLoader.java:89)
	at net.runelite.client.RuneLite.lambda$main$1(RuneLite.java:213)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Invalid or missing jav_config
	at net.runelite.client.rs.ClientLoader.doLoad(ClientLoader.java:117)
	at net.runelite.client.rs.ClientLoader.get(ClientLoader.java:84)
	... 2 common frames omitted
2019-09-04 12:50:43 [RuneLite] WARN  net.runelite.client.RuneLite - Failure during startup
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1\) Error in custom provider, java.lang.RuntimeException: java.io.IOException: Invalid or missing jav_config
  at net.runelite.client.RuneLiteModule.provideApplet(Unknown Source)
  at net.runelite.client.RuneLiteModule.provideApplet(Unknown Source)
  while locating java.applet.Applet
    for the 4th parameter of net.runelite.client.ui.ClientUI.<init>(Unknown Source)
  at net.runelite.client.ui.ClientUI.class(Unknown Source)
  while locating net.runelite.client.ui.ClientUI
    for field at net.runelite.client.RuneLite.clientUI(Unknown Source)
  at net.runelite.client.RuneLite.class(Unknown Source)
  while locating net.runelite.client.RuneLite
Caused by: java.lang.RuntimeException: java.io.IOException: Invalid or missing jav_config
	at net.runelite.client.rs.ClientLoader.get(ClientLoader.java:89)
	at net.runelite.client.rs.ClientLoader.get(ClientLoader.java:66)
	at net.runelite.client.RuneLiteModule.provideApplet(RuneLiteModule.java:98)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.inject.internal.ProviderMethod$ReflectionProviderMethod.doProvision(ProviderMethod.java:292)
	at com.google.inject.internal.ProviderMethod$Factory.provision(ProviderMethod.java:401)
	at com.google.inject.internal.ProviderMethod$Factory.get(ProviderMethod.java:376)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:54)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:132)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:120)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
	at net.runelite.client.RuneLite.main(RuneLite.java:241)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.runelite.launcher.ReflectionLauncher$1.run(ReflectionLauncher.java:64)
Caused by: java.io.IOException: Invalid or missing jav_config
	at net.runelite.client.rs.ClientLoader.doLoad(ClientLoader.java:117)
	at net.runelite.client.rs.ClientLoader.get(ClientLoader.java:84)
	at net.runelite.client.RuneLite.lambda$main$1(RuneLite.java:213)
	at java.base/java.lang.Thread.run(Unknown Source)</code></pre></details>

**Comment by KillerHippo13** [comment]
I think i figured out what was causing it at least for me. I think it was caused by the restriction on wifi, due to me trying to open it at my school. It worked just fine at my house.
Possible fix- check the internet and if there are any restrictions set up on it.
